stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "44efe9a5efd7783298caa6b8c4dce555a3f01eea"
},
"details": {
"image": {
"imageId": "sha256:a5c74bed8c0f22efe0c4267d03a7d338fdbd1235d7f5c976c13096750426f0db",
"tag": "2022.03.17.00.40.20.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "926a9fb346f1b5ab63070b5288660121a481acb1"
}
},
}
}
```
=> chore(cd): update fiat-armory version to 2022.03.17.00.40.20.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:6213a9fb31d63a3333beef0ac4b8431c89cb3e8f25fcd6c1ae1798c74de6b6d4",
"tag": "2022.03.17.00.41.15.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "8e0c49961209eee90ceddde5bf465911c261f9aa"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.03.17.00.41.15.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:b20913335eabf47351fddc6e6c482676148f71c68f9d3a614da08d6d5929c18a",
"tag": "2022.03.17.00.40.15.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "88c44710211d05fb1c5fce3f96dafd76748e1e91"
}
},
}
}
```
=> chore(cd): update orca-armory version to 2022.03.17.00.40.15.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:97517609cb63cb945d5cf162e9cf1d453c04fad72689dd5b08f9a5bbcfac1f08",
"tag": "2022.03.17.00.42.20.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "2ad862864655afa32e63d32db7db0246edc6ea2b"
}
},
}
}
```
=> chore(cd): update igor-armory version to 2022.03.17.00.42.20.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:37d0d5d8538a791c9020571c2dde179cf3343e262c277633cb82327a9f9e77c5",
"tag": "2022.03.17.00.40.25.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "5d4f6d28fc7f5422b364d4be518bc168ac960082"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.03.17.00.40.25.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:37678c37aa803c7f3624a9b95600a82e948441bff25124d2b3b9a2d074308335",
"tag": "2022.03.17.00.42.15.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "3bd1bb5f2877c5b4df8a7c128f4ac9fbafb2227d"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.03.17.00.42.15.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:cf09677d71e1586392f63a5997ee469d46c04d864ba1cb9c5cd59fbfcce16b0d",
"tag": "2022.03.17.00.42.25.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "654b83c9a075712595de7273cecb03668924e257"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.03.17.00.42.25.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "37f136c789ace6d5f4ae9e58fc9d5847aeabbbeb"
},
"details": {
"image": {
"imageId": "sha256:bdcf1f18cebb54245d63641605e8d4adc2f8759bf057fe08695591d18c7d8f35",
"tag": "2022.03.17.04.46.09.release-2.25.x"
},
"vcs": {
"repo": {
},
"sha": "1d9d723fffc390c35accbca877e436ce1f28428d"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.03.17.04.46.09.release-2.25.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:7712bd6a5db078583df09a1f5de1c34310df0cfc1b26cd30eafb3113e419d0b5",
"tag": "2022.03.17.07.34.41.release-2.25.x"
},
"vcs": {
"repo": {
},
"sha": "31c31d513c1899f7b7dfb742d4dd28a6ed7cc10c"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.03.17.07.34.41.release-2.25.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:b542351f0efda6e417d72cd12d9179df8604d2ee21ad6ad1387a82615184aa24",
"tag": "2022.03.17.07.40.12.release-2.25.x"
},
"vcs": {
"repo": {
},
"sha": "6e42deadec84c723c0f4b3bf40d14ee9fb17f6ec"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.03.17.07.40.12.release-2.25.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f089465776be82f3f865925d75f5ec71ba478ab2"
},
"details": {
"image": {
"imageId": "sha256:68a9886feb80df470efa449094a3516f5c62d1e27f62a0a5c098da0ad34e0ec3",
"tag": "2022.03.17.07.49.30.release-2.25.x"
},
"vcs": {
"repo": {
},
"sha": "7e874ca312c441e4c1f8c2dc3e721698f801669c"
}
},
}
}
```
=> chore(cd): update kayenta-armory version to 2022.03.17.07.49.30.release-2.25.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:6774de811801aeb9f72d3728d076b8f1049e84da1f7ad7ccbe053f885e27a3ff",
"tag": "2022.03.17.09.09.54.release-2.25.x"
},
"vcs": {
"repo": {
},
"sha": "ce0b6657e8658ba8f3d760ae1a791ffbd3f8425a"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.03.17.09.09.54.release-2.25.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:7d77c9186d7b5d60e766e56d04c92b6a41095be1eacf3d9bdd78fd35e6ca9745",
"tag": "2022.03.17.09.09.50.release-2.26.x"
},
"vcs": {
"repo": {
},
"sha": "df08490c4e12feae6fb1860ce37a6f3b05cf9834"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.03.17.09.09.50.release-2.26.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:e7f89ead7d159eb6f30bd51299008f98f0863eea96a4864c4ae9e2e74c11a395",
"tag": "2022.03.17.09.09.46.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "19385f47391a54823402a682a759fb0a913fd2bd"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.03.17.09.09.46.release-2.27.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:00654eb77418e5299c3aeeaa78c6fe9b01e7b86731affe96ed73acbe961f1be8",
"tag": "2022.03.17.09.32.06.release-2.26.x"
},
"vcs": {
"repo": {
},
"sha": "c29b4d7f00c89d4c74953ae465cd2c71cb75ad9a"
}
},
}
}
```
=> chore(cd): update terraformer version to 2022.03.17.09.32.06.release-2.26.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:a76d25ba71acadec6fda2e606c6c98d04b67fa5a104d425e4f44864aacb1c843",
"tag": "2022.03.17.09.30.55.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "842c8f521bcb715a1569049fa1efed8879baaaec"
}
},
}
}
```
=> chore(cd): update terraformer version to 2022.03.17.09.30.55.release-2.27.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:9c7b75df887b123092d6fe9defe5353fe3f9a5298738025ec663dd94807e13a9",
"tag": "2022.03.17.18.46.48.release-2.26.x"
},
"vcs": {
"repo": {
},
"sha": "d4dff2fa7750a572659b905f9a1fc5030d10706a"
}
},
}
}
```
=> chore(cd): update deck-armory version to 2022.03.17.18.46.48.release-2.26.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:b7078114834b140e5883b4efbbcfd98db72ebb06170101d4c196978400962ceb",
"tag": "2022.03.17.18.45.23.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "6da861c96ef96fa8320889668ad57b600ea53a0b"
}
},
}
}
```
=> chore(cd): update deck-armory version to 2022.03.17.18.45.23.release-2.27.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:e3b790001ce50c87e5d7f13916dcf13ae4735b10aec92a732cff547011ad2198",
"tag": "2022.03.17.19.00.30.release-2.25.x"
},
"vcs": {
"repo": {
},
"sha": "fdde5bd8fe35581eb9abbb507ebc3ee62ea12a8f"
}
},
}
}
```
=> chore(cd): update deck-armory version to 2022.03.17.19.00.30.release-2.25.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:a987d3e66fe80f6f3fcf02e6874928e1ffe8e92383be3c7f56ee172efa4f81e1",
"tag": "2022.03.17.19.31.32.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "9895b83d6f5856a039233c77586582c791db4876"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.03.17.19.31.32.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:137647000c68d3a6ca57e9c8ad7f823ed51a4631b9567c7c5447ffa39c36a87c",
"tag": "2022.03.17.19.30.11.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "93cd6081f76dfa8dd3b18c8956b6978dbcdee836"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.03.17.19.30.11.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:5a08f0fe22d035f7252f6b2a32c23068993257a566ad04ae862e168976f4502f",
"tag": "2022.03.17.19.35.13.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "29564d884403dbedbefffba9d8523a2ced4983ac"
}
},
}
}
```
=> chore(cd): update orca-armory version to 2022.03.17.19.35.13.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:10bb081f332d93f166c40084fc3aa9e6364be1110ab23a8fe3cd234d429b9e4f",
"tag": "2022.03.17.19.41.01.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "bdfcae8aeedf9c3c5096a35ed4667324ff3d873e"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.03.17.19.41.01.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:f5991fdc34c95de78782106fd24d1ef47338aa86fc27723f1038f1930117508d",
"tag": "2022.03.17.20.14.53.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "438658ac6d1d2cd70923fe76486f2e17234e8825"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.03.17.20.14.53.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:14ddf8b01a200b660881c03b1743e691ec88da79975efa4d9ef3a33904e1c7d4",
"tag": "2022.03.17.19.32.28.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "c71adb5508a609df5ef5c12eee6eb1ea035d31c4"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.03.17.19.32.28.release-2.27.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:75ae98087d49bd9d21bc94ba3d341d2a86c9b6d43e2f22f3d8fc7db7eb642887",
"tag": "2022.03.11.01.48.50.release-2.26.x"
},
"vcs": {
"repo": {
},
"sha": "eafa560eaf8c6fce56656dbe0774266ebc96b5b2"
}
},
}
}
```
=> chore(cd): update igor-armory version to 2022.03.11.01.48.50.release-2.26.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:94e26ba9e07885a99d80cd9426b14ad7927030d195d2a66b7c4e461eac9b6feb",
"tag": "2022.03.17.09.33.00.release-2.25.x"
},
"vcs": {
"repo": {
},
"sha": "6b396cc9c51c396231d75f2f28899dd3ec8c6844"
}
},
}
}
```
=> chore(cd): update terraformer version to 2022.03.17.09.33.00.release-2.25.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:ccf41cc09ff57b0bdc76fb31b407d7e9d613658dde2c7b16849b13e24e4adfd4",
"tag": "2022.03.17.19.29.59.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "f11df55a9398f4efbc641e85afde34fdccbed3a2"
}
},
}
}
```
=> chore(cd): update igor-armory version to 2022.03.17.19.29.59.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "aea00fab3be93848adde89f06ef8f44a57c35468"
},
"details": {
"image": {
"imageId": "sha256:3e69c5ae589de4d937f7d336c27926f2e946348adbd0ae7d54a5ee55b747e9aa",
"tag": "2022.03.17.23.26.12.release-2.26.x"
},
"vcs": {
"repo": {
},
"sha": "67ad6aba719223720e1a4e8999a85471ba3963a1"
}
},
}
}
```
=> chore(cd): update deck-armory version to 2022.03.17.23.26.12.release-2.26.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "6b7cafe88b0d0aa004fdb60cfa9dd247ba7af391"
},
"details": {
"image": {
"imageId": "sha256:6fa5db0a184d0a0e42e47e028fa2a66ba9471cf99692b6a9ce660b804dbca11b",
"tag": "2022.03.17.23.30.53.release-2.25.x"
},
"vcs": {
"repo": {
},
"sha": "509a6a3d0dc87754ce53a4e7072f5101f5f90fbd"
}
},
}
}
```
=> chore(cd): update deck-armory version to 2022.03.17.23.30.53.release-2.25.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f6b2d8577f9a3120321af9ca9297769fe51288b3"
},
"details": {
"image": {
"imageId": "sha256:055be5d9aeee363fb53ebb32c8dbe377be6e52561261aafb4ab2908f22b6be83",
"tag": "2022.03.18.17.21.26.release-2.25.x"
},
"vcs": {
"repo": {
},
"sha": "56c9f6e90c9dc2181208f76576b2a20b6a5aa38a"
}
},
}
}
```
=> chore(cd): update fiat-armory version to 2022.03.18.17.21.26.release-2.25.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b03c87e6fcbc08c518e46ccd192fd225091a9329"
},
"details": {
"image": {
"imageId": "sha256:9c058bb54f5ea57a43f7249901da8c2bd09777d833db48c998fdb17d51871561",
"tag": "2022.03.21.16.08.03.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "ff45de5fd8465a9047c04c823de5c8610f5eb4de"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.03.21.16.08.03.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5807198e8fd2a6f5f9cf59409c2687b4a4f388b6"
},
"details": {
"image": {
"imageId": "sha256:bd64b6ee1a3168803782e87d8814b77275d43b8b7e73612585f222172a047152",
"tag": "2022.03.21.19.00.03.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "0cf17b35a938f66049a0e511199310b2196c5344"
}
},
}
}
```
=> chore(cd): update igor-armory version to 2022.03.21.19.00.03.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b1b5b8730aa29d49272a887e6440641fd212cd9a"
},
"details": {
"image": {
"imageId": "sha256:40a1392c143918bda84a55a42266ad0f814f58fd4e57ef7abff5f7da5ad529b0",
"tag": "2022.03.21.19.02.59.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "24e3abaa8dfcfc388950607f12567cd2d0e6bb94"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.03.21.19.02.59.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f0c1db6bd87e197b5a7230d26081833276793320"
},
"details": {
"image": {
"imageId": "sha256:7a0131995a7b861ad64dce8503ef8356b9b3eff9067aef3a978b420c64c2d1e0",
"tag": "2022.03.21.23.37.11.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "e6cae79cd53c2a1bb696db29cbed9ab268b46613"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.03.21.23.37.11.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0aab97cd1e88f1359a1f7f947154c77065eafd37"
},
"details": {
"image": {
"imageId": "sha256:eef602d7e8a3155222e2185b62ad13affadc25c96cd6f8fb794d54ed3c365008",
"tag": "2022.03.21.23.36.17.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "daf883e2d1f572df0dddc7452366d81f291f2b36"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.03.21.23.36.17.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "044ddee2642213eb36b0eab98e0628c76d8c7ace"
},
"details": {
"image": {
"imageId": "sha256:a50d35b49c13b01bae33697fd5633f4b1184e82db9071bb7d68e7c07a98808a6",
"tag": "2022.03.21.23.36.13.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "411c7020f603826c439c05ba528af22ea60759a4"
}
},
}
}
```
=> chore(cd): update fiat-armory version to 2022.03.21.23.36.13.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0c5f1bdbb474a90091201ccb1db01dd1c376339b"
},
"details": {
"image": {
"imageId": "sha256:23f6c5064317475302d0884cf2b56d578728db12e63ca69ec34f627e88b0e41e",
"tag": "2022.03.21.23.37.53.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "0ba6c07c3f7ac5a4eaff1a3e4d13d334c90a2341"
}
},
}
}
```
=> chore(cd): update igor-armory version to 2022.03.21.23.37.53.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9882c3d303ae03e73ded305d57c118896e18aa9a"
},
"details": {
"image": {
"imageId": "sha256:9111bf302d35633a467f5cd7f3ace9218a4e53229672993a45b0c0e41e5610f5",
"tag": "2022.03.21.23.40.32.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "f12518df92f4922d2b75c7c9ee14f7d489da2680"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.03.21.23.40.32.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "aa6d25fb7c4d90a43220f021e290e4d54341dd35"
},
"details": {
"image": {
"imageId": "sha256:1d4ac7e9d937289301af1a6603fb087f56913a63626e6b01fab03c53917fedb4",
"tag": "2022.03.21.23.58.58.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "a4ecbb3f5909fc27031f83e9e6bc5eb0bd48e412"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.03.21.23.58.58.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b725a6fb8d6d57770a7666f16754392fed99bac2"
},
"details": {
"image": {
"imageId": "sha256:53ab7acf0d68cf99b764dc948300542c9227c9ff61ae8e24c6bf72d8e8c36e72",
"tag": "2022.03.22.23.14.23.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "1a8a461d4f65c4ab3adb449f45c66c788aea3ca6"
}
},
}
}
```
=> chore(cd): update deck-armory version to 2022.03.22.23.14.23.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0c1ba16d8db65ed1a26c7dcc2723ca5228b8f313"
},
"details": {
"image": {
"imageId": "sha256:0052a774df1f3cd80e99b13c1ef543c34b7d4a65af42845142f6897974edbb96",
"tag": "2022.03.22.23.29.53.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "b165ac297f639bf935ab4ed0cef8e4a4e44e7dca"
}
},
}
}
```
=> chore(cd): update deck-armory version to 2022.03.22.23.29.53.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "159c875584e5fb4850e8ed831ae00297cb0a70ae"
},
"details": {
"image": {
"imageId": "sha256:7eaac9b9b326065883bfc7a88eba147fb2536ad6008e5e01b4c88ef0bd23c5c0",
"tag": "2022.03.21.16.07.57.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "965db29c51700ea1bac3aa0f080fa7538e390acd"
}
},
}
}
```
=> chore(cd): update orca-armory version to 2022.03.21.16.07.57.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "2e2f1f13360784ebf781cc31f51210565398647d"
},
"details": {
"image": {
"imageId": "sha256:af86d5d0fabbc1dc22b2212696deb1c68e95bc051b5872c58115d9a4ec171670",
"tag": "2022.03.21.18.58.38.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "0f0798aca2763853efd40f40b7a29bd877ed2808"
}
},
}
}
```
=> chore(cd): update orca-armory version to 2022.03.21.18.58.38.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "eb42eafdf21a36b44ff6c374817a88a298b5ebf1"
},
"details": {
"image": {
"imageId": "sha256:2c31795895757469caee2340fcea7db6b91e92a2c8f245369e546c4998191cfe",
"tag": "2022.03.23.19.36.08.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "b778ded2dacfaf51c7634aeda2191f0752c53148"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.03.23.19.36.08.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "eb42eafdf21a36b44ff6c374817a88a298b5ebf1"
},
"details": {
"image": {
"imageId": "sha256:8620cba347e6e2240a16bd503c0495baad22be16ec902a9a2f3cab2bb7fce6ff",
"tag": "2022.03.23.20.39.36.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "3c3fffda543a818ab6f2ab385783adb4c58c7aaa"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.03.23.20.39.36.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:b3790b3c8e2d745743358fb0fc3e044681d1ba7eead04faa9d598b42a3b831f4",
"tag": "2022.03.23.20.39.31.release-2.25.x"
},
"vcs": {
"repo": {
},
"sha": "40cfa8aea76490f18dc326f814f5b56261e4f11b"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.03.23.20.39.31.release-2.25.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:b70a6a1860da6d73389f06625eb409ba424267c9ef3433706ad80553d023019a",
"tag": "2022.03.23.20.39.26.release-2.26.x"
},
"vcs": {
"repo": {
},
"sha": "44fe75a4cb9070d5bbe1d07fe3d6ff0f6e680e76"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.03.23.20.39.26.release-2.26.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "187edbbf5c63c75b168e4061fcfa0458b05fa379"
},
"details": {
"image": {
"imageId": "sha256:3eb83c0a9b05b515ab291c635d117b812530d3e68854ec72b62ca78a1eb73d58",
"tag": "2022.03.23.23.24.53.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "e1207937e2987406ba6d9f07b9c1bf683f57e3da"
}
},
}
}
```
=> chore(cd): update deck-armory version to 2022.03.23.23.24.53.release-2.27.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:f09162caa40d11a1395c4af52542878c1f48638d27c6220a58090ef27dad62d9",
"tag": "2022.04.01.22.32.22.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "81da136cd140e84851714752adb9ae10bb0f1536"
}
},
}
}
```
=> chore(cd): update fiat-armory version to 2022.04.01.22.32.22.release-2.27.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:89eba3716c1b9bee5d4ffa54255f14992a02f88c758a2ca7a8ad9926172e8a1b",
"tag": "2022.04.01.22.56.49.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "e26b2c10bccf5a82473482efda2fc710430b803a"
}
},
}
}
```
=> chore(cd): update fiat-armory version to 2022.04.01.22.56.49.release-2.27.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:8ce1ccd812b7eb689a62eeb665415c0ccc819ce1279d116ffde9e20e68de7ba5",
"tag": "2022.04.01.23.22.04.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "fb2e8546e10ec6f99ca65508e6507430f98ca7ec"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.04.01.23.22.04.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7f94af6d8507f72e86a284b7a3fda3e61ca5d327"
},
"details": {
"image": {
"imageId": "sha256:94a126a666318fa68dbc2d7edc6266b32e74c116e7f802e873fbc7e5f78cfedb",
"tag": "2022.04.01.23.28.57.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "ea9bb4a7c20fd81050e4fe38e3ed708de66d3f7f"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.04.01.23.28.57.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "131e25f0102ce60cc6552fa38417a8074d47138a"
},
"details": {
"image": {
"imageId": "sha256:b94bf71e1400462341e91f2ad8e4701bd26b3141c19bdb61f03f6409a2cc9c20",
"tag": "2022.04.01.23.28.43.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "1b1b6702403f31c010ea7f2cc2d8a37f311ac439"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.04.01.23.28.43.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "db183763708e67720372b34dba87e4d713b0663c"
},
"details": {
"image": {
"imageId": "sha256:ec096f8a9431d74c9db9ee38bde70f9a5911864e4f481f9452c5494e958ee596",
"tag": "2022.04.01.23.39.30.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "19ba7b6af918d90ad97ee8633ec1f898ea02f155"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.01.23.39.30.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b539e13644b390df5b63dff30be32d2cdd1dc5f5"
},
"details": {
"image": {
"imageId": "sha256:aaa6489d8b8b9c7452566441621439078e9566e93ae2b2f7de9e9bc6c30d85d1",
"tag": "2022.04.01.23.45.10.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "5d9d7a4776230a2b2b3571ded6086f33644a209b"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.04.01.23.45.10.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c0448b70b1d03e2c120261a58f4f61e29dd4147c"
},
"details": {
"image": {
"imageId": "sha256:dffa6218d930b58fb6bf5956df122c61f9f7bc4feca9ff39d36658d06e44b9bb",
"tag": "2022.04.01.23.49.46.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "4f652eaaf59ac34def265022176f5d2c2ed4e344"
}
},
}
}
```
=> chore(cd): update igor-armory version to 2022.04.01.23.49.46.release-2.27.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:672cddd114158bb0d5f9cead0c4f86cffa44a4f7a62a805bf3365bffbd8f1395",
"tag": "2022.04.01.23.52.59.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "04ca6ca6f66a466fb4e66f8bf23f12135e3de4a2"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.04.01.23.52.59.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "63ada85fa0b81e91476743c8b85da119e5439137"
},
"details": {
"image": {
"imageId": "sha256:b99af174ae81ce6c3d1681cf65794f27227973f0f15736a69b2a6e6ef7a61bf3",
"tag": "2022.04.01.23.57.59.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "42f4bbeb9bb226bf738c0882320f879d22a272c4"
}
},
}
}
```
=> chore(cd): update orca-armory version to 2022.04.01.23.57.59.release-2.27.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:0a40182b5d5717115db02d1541f411ca8215c08415a013a7d9484019246d77b4",
"tag": "2022.04.02.00.09.14.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "006ed54db3f9ea3b775cd955ecd60503a748fb2c"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.04.02.00.09.14.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "746b7d3965d93aed3aaa5e36c4b13e9ea479d3c4"
},
"details": {
"image": {
"imageId": "sha256:d686c4c73e4f3eb9d60acd0f3470c7fc9dbba631832b9dd723f0e378c1bb4be7",
"tag": "2022.04.02.00.10.25.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "283908aac8d67edc6942cd12c59709add4a076a6"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.02.00.10.25.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "cbd9f141ffbd4c9cb1dc5b57c908376a7cbac8da"
},
"details": {
"image": {
"imageId": "sha256:fa28a1671349daf546d1a00495e71528d2141516d03101df72b2c9fd0f2ca803",
"tag": "2022.04.02.02.55.47.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "015174b95930462dff99f799f90f1845bc36b60d"
}
},
}
}
```
=> chore(cd): update orca-armory version to 2022.04.02.02.55.47.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d17a4467233b85255db8929387f155f1615b74b7"
},
"details": {
"image": {
"imageId": "sha256:0ab05599fe167b8e1f0fc4188c002b04a986ed6802ecc7fe035454dbdefffc8a",
"tag": "2022.04.02.03.10.37.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "94c9f9ff6fa163fae8967ee51a36e01c3cd306d4"
}
},
}
}
```
=> chore(cd): update igor-armory version to 2022.04.02.03.10.37.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4a0337879936d8a77eeed0ef2b7c881ba605f6ed"
},
"details": {
"image": {
"imageId": "sha256:a6f2b648cb51b058bbd50d55d2ab451b08e7beeab1cd5cd883fc12c8c9f12367",
"tag": "2022.04.02.22.13.59.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "edf0b1e4fa38708ddba526747f3f3c0d506b2ffa"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.02.22.13.59.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7fbae17b319979b06221789e34f9c354ad782695"
},
"details": {
"image": {
"imageId": "sha256:47aa78c06356ae68dcec50d64babe738c23645543892b0533de7fd3977b27fc5",
"tag": "2022.04.02.22.19.50.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "86f359fe3a3d0f8876c551c6236a586351e8db85"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.04.02.22.19.50.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b4e1db9641b68dad506e9b9a10a49d7c17c58b51"
},
"details": {
"image": {
"imageId": "sha256:2d7d611c9dd21fa72b333a6cc4893e723c1dbaed69304bb2da342fcf41f430dd",
"tag": "2022.04.02.22.40.33.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "7d730bba59e7b6636e8c322945f4933b4eeeb6f0"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.02.22.40.33.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "bddc0e2b73dfb1abcce08fc95a13df6def9350cc"
},
"details": {
"image": {
"imageId": "sha256:176094c84b6e0c7778c2ae0dfc0ac75042b1b74102076c2abe3beb6d14ceaca5",
"tag": "2022.04.04.17.11.03.release-2.25.x"
},
"vcs": {
"repo": {
},
"sha": "33b60a3d7d9e038b4cac59f256dfb1cdcd6dfc4c"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.04.17.11.03.release-2.25.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "cbd9f141ffbd4c9cb1dc5b57c908376a7cbac8da"
},
"details": {
"image": {
"imageId": "sha256:a7d519daff8e7ecd6100d405ab5f5e120743ef5fba3aa6c02a6213fc5bbff2aa",
"tag": "2022.04.07.18.16.06.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "ea996bac1fea906a2a4b764e7ea147777db92dc6"
}
},
}
}
```
=> chore(cd): update orca-armory version to 2022.04.07.18.16.06.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7fbae17b319979b06221789e34f9c354ad782695"
},
"details": {
"image": {
"imageId": "sha256:bfe4de76ab25e8ed3a483251371daca19be1c32697920cc29e448fbfa06a34d2",
"tag": "2022.04.07.20.10.53.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "3501964fda14592680f9e6d0ceb8515f9224edb1"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.04.07.20.10.53.release-2.27.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:ae9461d6bc175ccec6e2e94f9ffa8f50caa735fafd3d7e0d60d3c8d5d309c8c6",
"tag": "2022.04.08.05.45.38.release-2.26.x"
},
"vcs": {
"repo": {
},
"sha": "1b459f3f0bbc60f8d1b81ac211317616ee380abb"
}
},
}
}
```
=> chore(cd): update kayenta-armory version to 2022.04.08.05.45.38.release-2.26.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:468ccfb9d9e6f60b2d4aa21ef9b93bb73e3f0c1a0940c04a479b794e46ecdc97",
"tag": "2022.01.25.21.22.55.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "403640bc88ad42cc55105bff773408d5f845e49c"
}
},
}
}
```
=> chore(cd): update dinghy version to 2022.01.25.21.22.55.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "033f8768e76fc443f97f6ba8cbe7237a990c4129"
},
"details": {
"image": {
"imageId": "sha256:e080b23a854ee4135d964109d96f4d88a2fc04ed596416ae5642f38898d0752f",
"tag": "2022.04.04.17.17.42.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "5094f98634be982623dd96e959238c6e26fc8d1f"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.04.17.17.42.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1c7614c9479f089d966378e4f1ae9c7aa14502bf"
},
"details": {
"image": {
"imageId": "sha256:84e8ddea1477b943f63d3e4200c225de242e6c9d8c663369d3b022837bb3e70e",
"tag": "2022.03.24.09.08.14.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "fc550ba9099e491e50b94de431c5571dfdc6fc7e"
}
},
}
}
```
=> chore(cd): update deck-armory version to 2022.03.24.09.08.14.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4457080862bf665e8a7094ccfeaa792906c81f82"
},
"details": {
"image": {
"imageId": "sha256:fe000e1b8b1d90ab7ab629cbd1d6a5d25d19d6cd5af8ea5c4f652cbcee0d80c2",
"tag": "2022.04.09.01.01.55.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "72c785a8b869c9f34c00b2f34e71745ac4f8bd5c"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.09.01.01.55.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5d8789f8d9a0287f11d73c5abdc63d32af3721fc"
},
"details": {
"image": {
"imageId": "sha256:0af0f816c9391ec28a6fc7e733e4d3d72d49f046a625f7dfc1cb14c126a51c8c",
"tag": "2022.04.09.03.15.10.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "72d3733d662a0f62fcf3102a71a02fa1439f6bf1"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.09.03.15.10.release-2.28.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:a12b607779d04cecf5d7d07a76ba58ee91e7d5c55dc4160cdb238ca760fecfcc",
"tag": "2021.12.08.16.32.05.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "a9eacb43c1edd0cb2159ec038eecf246d6147f25"
}
},
}
}
```
=> chore(cd): update terraformer version to 2021.12.08.16.32.05.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "854d708bc8e46f6c3eb5f80582ead9ed4d3f30eb"
},
"details": {
"image": {
"imageId": "sha256:9d51f4e77d3ac3f3ec401e0e79666dc3941f6e0066ded039e3a1758fb208fd52",
"tag": "2022.04.12.03.18.21.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "7b6097c32d22603c546a65c78a28db32a607ccff"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.12.03.18.21.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5d8789f8d9a0287f11d73c5abdc63d32af3721fc"
},
"details": {
"image": {
"imageId": "sha256:5decf0bca884ad021dcf9ddace5b1ec47159225ee449b6a9ded2376be183831c",
"tag": "2022.04.12.16.01.42.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "27da2fca595ca0825662ab4f3c94e73de3491e98"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.12.16.01.42.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:d585c69c961e52999c674769085d167c637ef0853ee14e517da271c36c5a77ef",
"tag": "2022.04.12.16.32.56.release-2.26.x"
},
"vcs": {
"repo": {
},
"sha": "bfa2194f3b76f8b41de4def07228b71a13a4059a"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.12.16.32.56.release-2.26.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "854d708bc8e46f6c3eb5f80582ead9ed4d3f30eb"
},
"details": {
"image": {
"imageId": "sha256:8edf80ce6b4e5db56bb094004b88a90c7ac6d4a76fcf6188b1f03d1fc882197b",
"tag": "2022.04.14.16.29.15.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "6f368ae012b596015845b4bd05312955f8f67158"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.14.16.29.15.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:db2d65626d9617c12ec02d5bd3bdc773e85a0eab0186437adb43234fcdf80486",
"tag": "2022.04.14.16.28.58.release-2.26.x"
},
"vcs": {
"repo": {
},
"sha": "169736dd1e757fb067f11c673f887c7096caab0a"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.14.16.28.58.release-2.26.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:70b619bd1199651b2dd72b42a4a002544c4032a8709631f630d1131733d07dd6",
"tag": "2022.04.14.18.47.56.release-2.26.x"
},
"vcs": {
"repo": {
},
"sha": "c30bb0089de2f5b6eecdc26d32c2abe7617af29c"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.14.18.47.56.release-2.26.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "854d708bc8e46f6c3eb5f80582ead9ed4d3f30eb"
},
"details": {
"image": {
"imageId": "sha256:bff1bafe5b2893d2d0386de4bd610574e36cd74c1a09d60e62b4bd8605ae00e6",
"tag": "2022.04.14.21.02.59.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "fc09609ea215323fb41cab71e3ecf696d06404ef"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.14.21.02.59.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "074198ae910104c93026ffd65eb50b1106cb1431"
},
"details": {
"image": {
"imageId": "sha256:ac383ed074df1d2f3fc9a14ee84e3f45fb59f74dca1e3d62fa0f0dc80963cf63",
"tag": "2022.04.01.15.50.46.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "06f25d3966952226e8ec90084bc29da3602602d9"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.04.01.15.50.46.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "074198ae910104c93026ffd65eb50b1106cb1431"
},
"details": {
"image": {
"imageId": "sha256:f32afd7bcd7dd6f7eb05df49331ba4b16e1732034bfb38bc0042352ef9b8fead",
"tag": "2022.04.26.00.30.50.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "b2a9b91702994c5bec2e3a9763095da72fcee7f0"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.04.26.00.30.50.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5d8789f8d9a0287f11d73c5abdc63d32af3721fc"
},
"details": {
"image": {
"imageId": "sha256:c8ec8efaf01f2146efe1c78107027dbe7b0bf942af38a67ab0c500c1a3e2020a",
"tag": "2022.04.26.00.29.23.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "52b177759f821678ded376951a654721fee635b1"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.26.00.29.23.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "975fdbb57a5353c725db04dc743317646425fff6"
},
"details": {
"image": {
"imageId": "sha256:f97f54f90ccea666dd0cf92578d4b00a55ae415d0e6f0c85161f1418dcd3d425",
"tag": "2022.04.26.15.35.50.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "8eada0fc4aa167bb7d69ed23bcebbe78a766b7bb"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.26.15.35.50.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d3eba02bb4faa0654f862ca03373d1f87c3bac30"
},
"details": {
"image": {
"imageId": "sha256:ccfe92e2fa0cd6a02a01dccda7d065f5901f0858b9b05b3e7786bdc93b55c60d",
"tag": "2022.04.26.16.10.29.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "691d0701836f5122b94ec8e1da5ccd7e6bdba6cc"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.26.16.10.29.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c4da2ea7471b5391c90a3d2e9aa1f0267d1f55c4"
},
"details": {
"image": {
"imageId": "sha256:eabf45e8f3c0c0b85c0f245b89eba747abf2c3b2e418a9bd2460db96b4d4c861",
"tag": "2022.04.26.16.35.09.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "f5c8db83fa373bf768c3bf03b3b912ba10b0075a"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.04.26.16.35.09.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "99b6551677e8ee0688c18f8a4b440164af3aebaa"
},
"details": {
"image": {
"imageId": "sha256:3b4fae4cb2345c3b8d6dd180378e96d69278f01888d014f9dc5ba996b5ae9ff2",
"tag": "2022.04.26.17.12.50.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "8c9d3e89206bd809ff4568f421b0278e3b5787d7"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.04.26.17.12.50.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9b7886145d1258d8132a42adf64b57337f7dc0bb"
},
"details": {
"image": {
"imageId": "sha256:bae4e2a74ec680e8dad59d49894fe4b25b039a8fadfb9113b96ce0c210dd5ca8",
"tag": "2022.04.26.17.15.34.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "01f19e9c4cd1d0fc008e5dd740bebcade32ac8af"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.04.26.17.15.34.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d17a4467233b85255db8929387f155f1615b74b7"
},
"details": {
"image": {
"imageId": "sha256:c8c83dc7ca0bf7a000f0350075b7a9d68e5e468a0d442a64442a95a3a01fb94f",
"tag": "2022.04.26.17.19.15.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "1dbf04071495d186f7dbc534ed8c01e68950d29e"
}
},
}
}
```
=> chore(cd): update igor-armory version to 2022.04.26.17.19.15.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "2089ee02b8d26159c8c6b79d939a6748ed0e1f0b"
},
"details": {
"image": {
"imageId": "sha256:0ace5e54e9470d9bff7374546ad49dc3f4c11f0582f6676210ac2429920f2ec7",
"tag": "2022.04.26.18.35.53.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "a296680859bae35d405e84fc526a5f91904c8853"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.04.26.18.35.53.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "fed26a58d23a15946d73b5f23ffcd494eb9f3b6d"
},
"details": {
"image": {
"imageId": "sha256:758da2a74878ccf4ad592a011bd18df41f17a12d6a2099a89b2cfa2199968266",
"tag": "2022.04.26.21.22.04.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "2d59687dd10716649e35308350d655ecbc9ece14"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.04.26.21.22.04.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f612dd30ad6a7b491e0a9678e780d6982c3f3236"
},
"details": {
"image": {
"imageId": "sha256:84f8c10f4d51c9bb0123d610cec6ceeb50c2311433a516cdb8129cc61b598ee7",
"tag": "2022.04.26.21.20.32.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "be4cf639005d48251f189ec8f520773e74eb80c8"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.04.26.21.20.32.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "975fdbb57a5353c725db04dc743317646425fff6"
},
"details": {
"image": {
"imageId": "sha256:ac46033f5a3fe97f450ab732e63ed6d2578af0f17fa04bfdd831c2794412a512",
"tag": "2022.04.26.21.37.57.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "6b717a17d201f456a4b4699991e66a6d2bf2572e"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.26.21.37.57.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "dba199e7cb2eb1d28192efda6e51b1685b8a3ecf"
},
"details": {
"image": {
"imageId": "sha256:be6be3830a1ed4e2f5e6505cf421b102b1acdd4661ac9a37e732894e04a4d4a4",
"tag": "2022.04.26.21.36.23.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "b139b70d9e376c85c2c3e159b59d17de4b57b10e"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.04.26.21.36.23.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "2a2a7abb7d905a186faed58b6235efe2854500a9"
},
"details": {
"image": {
"imageId": "sha256:595445dfd674c4f13eb88163d46c1a23c907561a3fee9e24df69f31e084c6bbf",
"tag": "2022.04.26.21.43.12.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "e18acb93b29b58cf27d15e0cbd2cbff38969938c"
}
},
}
}
```
=> chore(cd): update orca-armory version to 2022.04.26.21.43.12.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "260578adfe38a504da2bf7e7a1b5a74a75559f0b"
},
"details": {
"image": {
"imageId": "sha256:f081d3532759c697d21b3ccd12054369aaa296812f9fbc108bdfbfea1f434dcd",
"tag": "2022.04.26.21.55.34.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "d574051e8541cd5b0f80f0927f5d5631d29355d5"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.04.26.21.55.34.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "2cbfb86ae84987f8b3456fbb5f278a7a1114aeda"
},
"details": {
"image": {
"imageId": "sha256:323bc17caeb18f568fc07b0411b9ec634c076661fa443dcbefca424d1a2b87ef",
"tag": "2022.04.27.00.27.37.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "78e9f230f7604b4180da9facfb12379ed43a43c2"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.04.27.00.27.37.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:16b41c6908cca03a276d830246ce2b37e5b96c159621279877a7eb07ce1277af",
"tag": "2022.04.27.03.37.39.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "469ea3e1a1bf2adfa7303aed5d5c4e75d63e81b4"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.04.27.03.37.39.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1256d50daded7459a54133b41eacb313d54fa7f4"
},
"details": {
"image": {
"imageId": "sha256:98c9373cc9a1ed27f5a0dcd26212ea607c5f3a32b8a447f85792f96faa4b7dde",
"tag": "2022.04.27.03.37.44.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "83405e3fc7725e65619eafdbcbb499a14754fc2b"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.04.27.03.37.44.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "2445666ca79174f5a721c3d463c78b9a30987a28"
},
"details": {
"image": {
"imageId": "sha256:fc7b54f428d1fc04d3f7b141e5ef773ed863b4ea3d5b89d0ad0bf1f6b21f17ea",
"tag": "2022.04.27.04.09.53.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "c0cdf2b0956533e6214567f958a9ed4155b4e9f1"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.27.04.09.53.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "6ca647a0269b1c8e28bb2e0b27f3eea8a0459efd"
},
"details": {
"image": {
"imageId": "sha256:f0d5409c95e7592f2df72adb4c2facdac02becd413b21cf605704da30ea2515d",
"tag": "2022.04.27.04.09.57.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "549a23a10b96ddec8229319de17d1353aa0a8f03"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.27.04.09.57.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9f6b4dce228d35d0a54d56d79c17424eec04704b"
},
"details": {
"image": {
"imageId": "sha256:576c9881b273fdddb0d5b6a7c0e2acdfe9c71c66ddc5ac622d4f692f976e165a",
"tag": "2022.04.27.04.22.58.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "cc69c0b320aefa63215703df4f4801acabbb1d53"
}
},
}
}
```
=> chore(cd): update deck-armory version to 2022.04.27.04.22.58.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "52a8f5204dc12b693b8eac5ff6126759c119684a"
},
"details": {
"image": {
"imageId": "sha256:b726c8c97c61a78715a1152430130cf16fe15bbcf91809d4345352e7e8a45478",
"tag": "2022.04.27.04.25.34.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "6597515e93bc46657d72111e04e0dccfa3d18227"
}
},
}
}
```
=> chore(cd): update fiat-armory version to 2022.04.27.04.25.34.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "2cbfb86ae84987f8b3456fbb5f278a7a1114aeda"
},
"details": {
"image": {
"imageId": "sha256:458b9a507e207b3b8d8753dd7c359688410fc9ddac9ca9f4b73ee8294c4b151f",
"tag": "2022.04.27.04.56.18.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "fa6fa41607e5dae90a8b9a1b280214099e193f7a"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.04.27.04.56.18.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "48f722afe278cea6dc051a9d6197f90d66d817d7"
},
"details": {
"image": {
"imageId": "sha256:1c1f4c499ca3c1ca96d200b1fdc93e17d2c3c4a315a9d3f3ce853a91ab2df4af",
"tag": "2022.04.27.05.05.21.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "3decc54666598b2ad206e640066f4268061e350a"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.04.27.05.05.21.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "6a42b629c72c32c094a06e4757658b9418135bc7"
},
"details": {
"image": {
"imageId": "sha256:6f9730bde6b6a7543a4fb3b8cb3cee66fb20d325dd25104ac7085f7ff0cec828",
"tag": "2022.04.27.04.59.09.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "824b6c3cbaeea32df6c2a83e70287168587fb951"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.04.27.04.59.09.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "59b8723dd9ad46b13eede1bf84711f0dd2bf1b3d"
},
"details": {
"image": {
"imageId": "sha256:a3f4c7c7e0bab2731f6e74573c7ffde0a333d5a29cb3b4772f4f312613a73236",
"tag": "2022.04.27.05.18.15.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "02fb456d1d9cdd0d04461d972b839ec64870276e"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.04.27.05.18.15.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "ef6eadebd58988fb049832c695dbfcfdd388ea74"
},
"details": {
"image": {
"imageId": "sha256:5942dc504d5d3139f1aa86b58c76ff1e2562f29fb69e35063b463963d5011065",
"tag": "2022.04.27.05.33.51.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "5529365d88eac22923a54d08ba4b073a277ff66b"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.04.27.05.33.51.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e82d299e721d69c1f587393683f21c2affbaf17c"
},
"details": {
"image": {
"imageId": "sha256:ee1001a6a8209257f1caab602027c1a727fc99e35eb82140efad00df55a562e4",
"tag": "2022.04.27.05.33.34.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "76bc52f2761661c9913c9fdb3fa8a13ae47d87d9"
}
},
}
}
```
=> chore(cd): update igor-armory version to 2022.04.27.05.33.34.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:a0c8e76014656123589da8731d724efe504d4e4c34cbc7389dcb9b86c895d96d",
"tag": "2022.04.27.05.45.11.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "21ba5b1f0d8f7e42cad40fe19dfb58cccf71a02f"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.27.05.45.11.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c2972d12c297263391ca917fde5b5b9c1452e382"
},
"details": {
"image": {
"imageId": "sha256:b261a74930318b96b93ab4e46061bc1384166355f9376a9209d46eee23fac5fe",
"tag": "2022.04.27.05.44.01.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "2d66cb9252236e6f9ebc8c486c038b0b01dcaa60"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.04.27.05.44.01.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d695313e120d80ddd379f04f449a40befc031173"
},
"details": {
"image": {
"imageId": "sha256:2fc96f2860dde819bf15930e81795b8b298e50d86470bd05ea5da9ed6bec0afa",
"tag": "2022.04.27.05.45.17.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "efc2244af80153e2e8c7cf30ad0da95d3c0e00b7"
}
},
}
}
```
=> chore(cd): update igor-armory version to 2022.04.27.05.45.17.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "17fec14f84c520ef6b393fa81fe0ce1414e4942e"
},
"details": {
"image": {
"imageId": "sha256:14998d0c3ac84bccd194f3a4fd79861581ee9c7d7e48f3220cdef21fbd67c55f",
"tag": "2022.04.27.05.48.50.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "924e80f11e9c7bbcf01c1b818152a50af91721e9"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.27.05.48.50.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "ac31f337cd0845d10c1474dc8a8cc8df6fdd8862"
},
"details": {
"image": {
"imageId": "sha256:482b793abe1e653de3f831354fbd9f26b0d7f6703a2452c73c3013db8eb47ed2",
"tag": "2022.04.27.05.58.47.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "8f08391eade3decfedec5707fc6dc62fd4d4aea9"
}
},
}
}
```
=> chore(cd): update orca-armory version to 2022.04.27.05.58.47.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7145e8a3eff67ba022bd45bdeb29425eddf62e7c"
},
"details": {
"image": {
"imageId": "sha256:ef7f5ecf04b40387af43ab88b1b3a8d782bc535b0b65d04f073f2818e5a7cbbb",
"tag": "2022.04.27.06.17.06.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "37fa411ca94db108fcd765c600f9f8230c32c829"
}
},
}
}
```
=> chore(cd): update orca-armory version to 2022.04.27.06.17.06.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:609b8ec086f2ab58df6abdefa005cd0777ca528c71a8dfcbb30b2faa7a569d43",
"tag": "2022.04.27.22.42.51.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "2a0c69a15b421bacede459e4f4468ffc30af58b9"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.04.27.22.42.51.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:7edfee125e44ad2f5355be1f3adb3c5633837125abc02a7eca8fa60b18d31110",
"tag": "2022.04.27.22.50.19.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "c9b3b5e7fa06469fed77ccdb7abee77886264f26"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.27.22.50.19.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:e9cd87095fc27ec6e37b5399d597dce43dbd49f5e50159a2c7dcdf4597769781",
"tag": "2022.04.27.23.17.56.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "f872e07b57baf2c43a19218f70dbfdd9862a475d"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.27.23.17.56.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d7fcb25c7fcf1f7e73b6f49cb65cc775250bd642"
},
"details": {
"image": {
"imageId": "sha256:865599c5442543bd30695fea515f5425311929436a94489216a09d791eed0f2c",
"tag": "2022.04.28.16.50.08.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "7c10887526400192ffb24f0fbb7499b47bd1f5b9"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.04.28.16.50.08.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d7fcb25c7fcf1f7e73b6f49cb65cc775250bd642"
},
"details": {
"image": {
"imageId": "sha256:9a29f614efca51020c968440064f3c4b082eb1200be20413200aeac9611d2821",
"tag": "2022.04.28.17.04.51.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "0e6849e1174645a8da78cd02196488e3beb2236d"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.04.28.17.04.51.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:b08191e54f39c366c8c3e8cd83714070dc00da65a72c24e59933724d3d9ec625",
"tag": "2022.04.28.19.56.25.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "4092cd60bc02207b67a14ae0bbdcf660310475f2"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.04.28.19.56.25.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:954d6bb86eb90a2f6e3c4f377c6c6d80a15fcd63e93480cb7bd9dbf12c073cce",
"tag": "2022.04.28.20.14.17.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "42bbb9d68fa7d338781fe93e7e5b2e792f09eb84"
}
},
}
}
```
=> chore(cd): update orca-armory version to 2022.04.28.20.14.17.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:ba9840c9ea382981ad45b242833d87e344bd82c0ecba7c8503a440805de18078",
"tag": "2022.04.29.16.35.27.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "dbb1fbe0bc4b9039b887cf6e2d34ee3316ef0e64"
}
},
}
}
```
=> chore(cd): update fiat-armory version to 2022.04.29.16.35.27.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1256d50daded7459a54133b41eacb313d54fa7f4"
},
"details": {
"image": {
"imageId": "sha256:2a396e3aa1ea8a20bf593ce04cee41058313d2a1e0de7b56da80ef6ce24874a2",
"tag": "2022.04.29.17.19.52.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "7e740f0e66e8a8fe877e0fb06b69e05d4596bf8d"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.04.29.17.19.52.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:d5c4a8bd6fefc03b818f3fefa5e7e44ea5479869510d8d01405937c3227718ea",
"tag": "2022.04.29.17.26.17.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "09098dfa90f88adbc44528d85d71bb0c73b980b4"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.04.29.17.26.17.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:60f0e1b6f4fcd4bc635ba5ce74905f055dc0bbe3614e51e8ba3c6c273703c6e7",
"tag": "2022.04.29.17.57.29.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "a9ddffe690ef3f6d73b695673ef88cafe631743f"
}
},
}
}
```
=> chore(cd): update fiat-armory version to 2022.04.29.17.57.29.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:fd9bf1d95de2b5705354625c234be1cb025a3f64dfb42c8d8ef39ced9025aec7",
"tag": "2022.04.29.17.57.41.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "59e19546faa877655b9e11690eedc51e1cded17e"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.04.29.17.57.41.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:5f7da96652cc1022ed6c98500e284d74136f8002e9f2dfb86cfadefc980a95d6",
"tag": "2022.04.29.17.56.13.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "e5231b8542a2b5be70951f3dcd4f27aef527dd83"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.04.29.17.56.13.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:875e0411d37a3dd0e281877119f0125d71c2a550e236a846eda26bf7e59daea6",
"tag": "2022.04.29.18.01.45.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "da71af78518c927978e6bf8e27da6e10d27d672a"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.04.29.18.01.45.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:281eb370325eeb4d1765796919393897fd12d12ad5c7f48b41dd71a4176c6a14",
"tag": "2022.04.29.17.58.01.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "759f273203bb67e785c68ae26555ea55f4975fb9"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.04.29.17.58.01.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:924393a8e0bd6a3b859bcb089f95594e942f1a31d5b1f2efd7d8a6298f1f718e",
"tag": "2022.05.02.22.07.42.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "b9aa28ce70b3da80268659a195ad968a217debfa"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.05.02.22.07.42.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:d0780e4affc70a78379a86c75a9db5cc41a12dd7b853d8e5b2acd84980c038c8",
"tag": "2022.05.02.22.15.52.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "5d146a61327665d4c47e8f5c4c51d449627a707d"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.05.02.22.15.52.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:c3ae876d85bc51d1317cfcaaba8961a921f091c7b6e01e316846d4a1b8be8309",
"tag": "2022.05.02.22.15.58.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "0449e2f4c812d2622c16fb7f441835411d474f8a"
}
},
}
}
```
=> chore(cd): update orca-armory version to 2022.05.02.22.15.58.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:508884ef66466cf6dc6706a4a9c55f1865b20bafc0a912026bdac0bdf0e22674",
"tag": "2022.05.02.22.12.34.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "b179e79c40bc1242d58be7900e5595287e4515de"
}
},
}
}
```
=> chore(cd): update fiat-armory version to 2022.05.02.22.12.34.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0c2da717d35964d50a9aa6322522a5c57002fa73"
},
"details": {
"image": {
"imageId": "sha256:20d12e15c9344e1e6393308c74089950c8a7e3b4a3d56d881c25b21961eddc38",
"tag": "2022.05.02.22.26.38.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "830b9ed090139e3d30725f56d8b8fe266528a1bf"
}
},
}
}
```
=> chore(cd): update igor-armory version to 2022.05.02.22.26.38.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9cf7854cd672e89a02797d8796316277fc197a7d"
},
"details": {
"image": {
"imageId": "sha256:6c65f8781ab3622efedc5d9697fde84fdd2ee95b6320939bb42cf1d66a9b8804",
"tag": "2022.05.02.22.21.42.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "c4f4a453150a5c9748d7225739ce30d919df02cc"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.05.02.22.21.42.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7c3979e7e36e5936c7036d39702b1d3c0589a872"
},
"details": {
"image": {
"imageId": "sha256:ce6544f6ebd689dbd876bcfed70649bff06ff8f6e62647d0332a80bb776206f4",
"tag": "2022.05.02.22.36.47.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "5cdfab6cbab3bbd748500d8058737e95d0a75f0f"
}
},
}
}
```
=> chore(cd): update igor-armory version to 2022.05.02.22.36.47.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:c6951de9473962ea8e2f36c55c1b27ed43a9b3bbf6edee1b3895fa0abee3dd0c",
"tag": "2022.05.02.22.12.40.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "76cba3c7cea547e9fc5935dab6cac12d83ac7f36"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.05.02.22.12.40.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c36b9051afa0de2bd1321790c442db27122cd75f"
},
"details": {
"image": {
"imageId": "sha256:50628d1bb86b983c5729174a6e3a7aa7b84087792597ca85d82667f47e6dc84a",
"tag": "2022.04.27.05.36.06.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "d33ba2c96d34e35ad063ce089fe465097c1c9ec8"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.04.27.05.36.06.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:891f86b0279051cd1fefc8353c7424aa796e2b45490bd5e898d48debdb8d6945",
"tag": "2022.05.05.17.52.40.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "dfb92ed1271ffeda96bc9fdd4b2870364aefc99d"
}
},
}
}
```
=> chore(cd): update orca-armory version to 2022.05.05.17.52.40.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d76525aea1c3619da154032d24c0aef1fbf36994"
},
"details": {
"image": {
"imageId": "sha256:959e102587f64aa8863a9b4d18e5964c7b217bda0025bf2146c4597f8ecad8c0",
"tag": "2022.05.05.18.34.01.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "d286b012b5e51c3d825d467dd73a795d23463575"
}
},
}
}
```
=> chore(cd): update kayenta-armory version to 2022.05.05.18.34.01.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d76525aea1c3619da154032d24c0aef1fbf36994"
},
"details": {
"image": {
"imageId": "sha256:ffc1a00f38792eef663328b9b599b39bd27e8acb65d1dcb794a960798dcfcd87",
"tag": "2022.05.05.19.44.15.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "9f710ad8df2eaf871f104586b58d4938296e59de"
}
},
}
}
```
=> chore(cd): update kayenta-armory version to 2022.05.05.19.44.15.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "12be87dc853c47d6f91594931d2c1501676aab73"
},
"details": {
"image": {
"imageId": "sha256:aa448df5e9f79db018bbac6a38b068a36fce773652ab250e6b3040f7f565d84f",
"tag": "2022.05.05.20.14.45.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "c1eccc94074fb289bfa07b6337c9fd2595a45c47"
}
},
}
}
```
=> chore(cd): update kayenta-armory version to 2022.05.05.20.14.45.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "85a1eb391ab1c2f053f8bff5dd14d38d9e8a4e26"
},
"details": {
"image": {
"imageId": "sha256:9191bef7fba2dfc034be95c8d5541113e9c2044b5ec3e656db325e063035eb19",
"tag": "2022.05.05.23.27.52.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "40a5361b6a809f44e5b50841818edaa40dd04f79"
}
},
}
}
```
=> chore(cd): update kayenta-armory version to 2022.05.05.23.27.52.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "85a1eb391ab1c2f053f8bff5dd14d38d9e8a4e26"
},
"details": {
"image": {
"imageId": "sha256:ac4bd8d2bf6e9d2c4612a8bc7131a66ffb5e0699ea3836aecaddb25d41aa1e40",
"tag": "2022.05.06.00.09.19.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "1e2237a01de8216325d86bb2fcdb869ab15be5d2"
}
},
}
}
```
=> chore(cd): update kayenta-armory version to 2022.05.06.00.09.19.release-2.27.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:4f8ebad17690ad8669d175ebca13fdd842a3e8982f132d43c4525251c197f340",
"tag": "2022.05.06.22.38.47.release-2.26.x"
},
"vcs": {
"repo": {
},
"sha": "a63964f2518893bd936448937c9cf6a955771f63"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.05.06.22.38.47.release-2.26.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:c82aee5fd9e681d7e37a909f7c58244bb8ab1e52975df31a4b887b88d5a7e63c",
"tag": "2022.05.09.21.43.08.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "97ea226de97509838a0216cea2b1643bcb568188"
}
},
}
}
```
=> chore(cd): update terraformer version to 2022.05.09.21.43.08.release-2.27.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:8f4f5116ce84cea71f34f9df4411fa1e2fefdaf5871b0550de60333b9faa1498",
"tag": "2022.05.09.21.43.02.release-2.26.x"
},
"vcs": {
"repo": {
},
"sha": "5996b35ab6a6f088fb903e6395a4b9d4d6bf6a6d"
}
},
}
}
```
=> chore(cd): update terraformer version to 2022.05.09.21.43.02.release-2.26.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:9f02ed126cb0b32a5d4597c33d81966e9b1384e3a882d7ec7964bac7f8ce6479",
"tag": "2022.05.09.22.11.36.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "47163cb8a5d4c72aeca2c9de13f1f25b22028b68"
}
},
}
}
```
=> chore(cd): update terraformer version to 2022.05.09.22.11.36.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:878d22dde7c8edee4817a64d643d92b45ff8307a4d0c6390408b99fa230e6c39",
"tag": "2022.05.11.17.19.43.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "d49d6289e66897f00e6a62f065310ee3fe090f77"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.05.11.17.19.43.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:81e99ccfc816f504b4741ffcfb5b406efe5c2c4339dc4136a7abb3c1d2707cf7",
"tag": "2022.05.11.17.27.50.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "cabe7b17a0794213f3b41d0713f3e0163ae719d7"
}
},
}
}
```
=> chore(cd): update fiat-armory version to 2022.05.11.17.27.50.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7c3979e7e36e5936c7036d39702b1d3c0589a872"
},
"details": {
"image": {
"imageId": "sha256:3b045f7f2a229525565a4bb2ee2b0aba7ad742858201d18010acfb2f2cc557c5",
"tag": "2022.05.11.17.57.10.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "3765fe7f5e051b08e2e00c2d99ef9f5e9d87bcfd"
}
},
}
}
```
=> chore(cd): update igor-armory version to 2022.05.11.17.57.10.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "12be87dc853c47d6f91594931d2c1501676aab73"
},
"details": {
"image": {
"imageId": "sha256:c41ca53a17a963c100ed8cdc5a641d190655e1261f625d9e62ec22054bc54648",
"tag": "2022.05.11.18.01.59.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "098bdb638e825225cd44138e4b9c5fa9e8dbd7c2"
}
},
}
}
```
=> chore(cd): update kayenta-armory version to 2022.05.11.18.01.59.release-2.28.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:343ba72231a41c7d410f24baa35ebc42dbc87b1ee955e36d2a51c38a4a6c0eaf",
"tag": "2022.05.11.20.03.13.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "a1e4e43748ce11e8de85f7d29dfba21d12152d68"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.05.11.20.03.13.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a06ae3c6f92b79ca922fe9e6a53902fdf921af7e"
},
"details": {
"image": {
"imageId": "sha256:9cdf9258c09abcf1283c041462a5a9bb8989e864e12c9ccedfcdeb7532b52841",
"tag": "2022.05.18.17.00.41.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "6312b579acaa141f6f677cabedacf1f04869bd82"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.05.18.17.00.41.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "79531aee41b14b657644161c062cec92f51df39a"
},
"details": {
"image": {
"imageId": "sha256:e13b693f93bfe5226be90c85143ce788011e5e064debc862d1c6a7ce3e1ed1f8",
"tag": "2022.05.18.17.33.16.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "d8b26f4c4a92ff7db77472a51cbbc9bf9a7d23a6"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.05.18.17.33.16.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:e4545cf02ec2a4601812f17405b03b7f1f2cf36862cdcf1966065c749db926e0",
"tag": "2022.05.18.18.09.00.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "16feb09310155bd0d18e18033d399d1d64411ef3"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.05.18.18.09.00.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7c3979e7e36e5936c7036d39702b1d3c0589a872"
},
"details": {
"image": {
"imageId": "sha256:9a31a3dfd2558416a41cb0959240f53c1e0b150ee125713613e004157fd97457",
"tag": "2022.05.18.20.57.02.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "5ea6da54f840ecaffa72d62386d9efd7bb54e0fe"
}
},
}
}
```
=> chore(cd): update igor-armory version to 2022.05.18.20.57.02.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "79531aee41b14b657644161c062cec92f51df39a"
},
"details": {
"image": {
"imageId": "sha256:3824f97efe41c575c5fbf3c51fb46d00ff4464c9c8c17005c0d49aaeaa977e65",
"tag": "2022.05.18.20.55.16.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "473f34b0c776ff56e443c1db4244f2aa9257aa91"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.05.18.20.55.16.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:d90a0ad93b323721e3a9a3a735675e993fda217e81f38b2af25246d9fb7cbe58",
"tag": "2022.05.18.20.56.57.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "6748c08dc6b2329724076684a66b11ae7f3dce76"
}
},
}
}
```
=> chore(cd): update fiat-armory version to 2022.05.18.20.56.57.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:2b83a64577896371246ce68c97323c8c3f632b4bda0f66112383bc11c8b86acb",
"tag": "2022.05.18.20.57.13.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "877733807a0661adef388e9ad45f79506428e2fe"
}
},
}
}
```
=> chore(cd): update orca-armory version to 2022.05.18.20.57.13.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:459457b70de9b3d7458c8c5066a32972203470d2c6ba5ddce7c3fad06f7b7bc2",
"tag": "2022.05.18.20.59.42.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "07620baf7b0460f0ab42562fc21b847f771c0dcd"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.05.18.20.59.42.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:f1c56706c17b3521239424d66aa3e1f6675001373efcc3477429ae2e1dfca123",
"tag": "2022.05.18.20.57.08.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "07633630b58c15b5145cc00af08528f0b2b0607f"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.05.18.20.57.08.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9cf7854cd672e89a02797d8796316277fc197a7d"
},
"details": {
"image": {
"imageId": "sha256:ffabd934bf7eaaedfe5716f0ff3bded2eb64b83a05e317bb068ae002e29f45e5",
"tag": "2022.05.18.20.57.18.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "f818ac4ce606e4b4f74f3cada4f4bc173a949b50"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.05.18.20.57.18.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:c69f270836c0ee9b82f4f7444bfdde25856e3ee890dc20b8f6b3be9f41ad16aa",
"tag": "2022.05.18.20.57.43.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "d0761570b845d9dbda0f117ff6f56d78ac203cfb"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.05.18.20.57.43.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "12be87dc853c47d6f91594931d2c1501676aab73"
},
"details": {
"image": {
"imageId": "sha256:7f9d667e7a353e6406442fdbc6392eebeeb46aa2ee0a8b63f6300810191221e0",
"tag": "2022.05.18.21.13.15.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "ebc7a92d06ed18b93233a6c887fe9acfd85ccc8c"
}
},
}
}
```
=> chore(cd): update kayenta-armory version to 2022.05.18.21.13.15.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:449773eb2d71bd91f3c41cf8767eb7cc18bf4382113438d0566ae91c0683177c",
"tag": "2022.05.18.21.53.35.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "8bf193b7b47ba22d6443336ea45773fa546d66f7"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.05.18.21.53.35.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0f94933969e57c13423b088cc17cae628f5e3d22"
},
"details": {
"image": {
"imageId": "sha256:3cdfd9e87c688bf7c02761a9bfd2ac5abf8872c931bb0c012156e69d36efe7a7",
"tag": "2022.05.19.23.50.25.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "fd23bb31094d533ed8f1c3ee26930d352e0de4b9"
}
},
}
}
```
=> chore(cd): update fiat-armory version to 2022.05.19.23.50.25.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:c1c5df9e9d42148cf1c783d74ed5ae8c2a48ac98be043e7e21388d72b7e58234",
"tag": "2022.05.20.19.37.45.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "8878e069687bfd229bd00907ede66dfe1b73d2e0"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.05.20.19.37.45.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:002527a18af4db4ab0f69537d4825024fbf494afafb9a541ffd62a784232d744",
"tag": "2022.05.20.19.48.50.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "488477dd85edfc6206337bb31f76892e641d1803"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.05.20.19.48.50.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "33f8653e7d3bbab4f7385f60ff4de36d880561aa"
},
"details": {
"image": {
"imageId": "sha256:504cc065491151d15eafadeb4ef9de748065ce5d4f134c54648b64b354faa736",
"tag": "2022.05.20.23.15.25.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "9aca7990e68cc8022a55af31db7df1d04e02de4c"
}
},
}
}
```
=> chore(cd): update fiat-armory version to 2022.05.20.23.15.25.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "17fec14f84c520ef6b393fa81fe0ce1414e4942e"
},
"details": {
"image": {
"imageId": "sha256:14f5d6a16819a4288f917c363f8a8c7f545c16d84420694649c7e4ac675e7971",
"tag": "2022.05.23.21.05.31.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "d34d34d6e21c6e9a4fbc1a42884836696400b33a"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.05.23.21.05.31.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:bb4ae750592260eb6ed84094e081f6764c7fc9114dfe539b66b9e5c1f8dac19d",
"tag": "2022.05.23.21.05.50.release-2.26.x"
},
"vcs": {
"repo": {
},
"sha": "9d0983d2f987e4f2c25fa794b8cc3ce15b8c83ee"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.05.23.21.05.50.release-2.26.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e25048cade6843746fd28386c9223ada649f8f7d"
},
"details": {
"image": {
"imageId": "sha256:5139ecb873b449d9d42f9bfd9bd6d5f3a0f4e5f48888634be69ab4526fde085e",
"tag": "2022.05.23.21.14.31.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "ff7c2f1f7fc427344d8d39aafb45962d8e118c8f"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.05.23.21.14.31.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0f94933969e57c13423b088cc17cae628f5e3d22"
},
"details": {
"image": {
"imageId": "sha256:8640de6ae08cf82524bdac02420446899dbab595d0888e494277a562cb0507e6",
"tag": "2022.05.24.08.20.34.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "e6133161f465172dc3071df9216323c67f281c45"
}
},
}
}
```
=> chore(cd): update fiat-armory version to 2022.05.24.08.20.34.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:8103e7a5d3cffa5674f927b86649d9c29c361e875688ad2c0a5bc0dfdef936ae",
"tag": "2022.05.24.08.25.18.release-2.26.x"
},
"vcs": {
"repo": {
},
"sha": "8e36b152a9d8ff9eef152ae381ec311804dcb919"
}
},
}
}
```
=> chore(cd): update fiat-armory version to 2022.05.24.08.25.18.release-2.26.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1660a69403841a868100f6859b3fd494ab611f13"
},
"details": {
"image": {
"imageId": "sha256:6b3e0447f06eac7d0e35f710b1a7ff3fc580c7301e71bb8514e392e5ab9a2eae",
"tag": "2022.05.24.10.12.51.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "ac414551dc5044e9d6661827a30885eb9d364468"
}
},
}
}
```
=> chore(cd): update deck-armory version to 2022.05.24.10.12.51.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1cf66a05e1064ca6e3970a22dd8ee35698028449"
},
"details": {
"image": {
"imageId": "sha256:53f4a4fdde6580a7b46f335f9591e9c0e8199f9278e79ca2f1f5688d500d1117",
"tag": "2022.06.03.23.04.44.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "188d76cfbc65dd5da1d7de9e7813a8d107945066"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.06.03.23.04.44.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "349cd1c3a3b0797285bc28ac41787d650e10c478"
},
"details": {
"image": {
"imageId": "sha256:c82738a5e6ceb9e305127ad785b16028fcd3a47ba93fe1933e94cea1fd4ddb40",
"tag": "2022.06.06.18.17.57.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "fb3d82a10893e234e2988450e28d53924a4bb2a3"
}
},
}
}
```
=> chore(cd): update deck-armory version to 2022.06.06.18.17.57.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:a3068434b5efe7d3b6faf69d2be054dcb71a444711f1cbcb64409b8403fdb5a1",
"tag": "2022.06.07.15.27.43.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "0e15acb4f229f88830bd7b2afbd9d9fe249e6502"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.06.07.15.27.43.release-2.28.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:02297526ca9dba9c60a7a4ca7f5384811e916f31bd2f0b72fdd239da760f8183",
"tag": "2022.06.07.18.44.09.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "242708d1942db1329a3c688c91def8c4caef763d"
}
},
}
}
```
=> chore(cd): update terraformer version to 2022.06.07.18.44.09.release-2.28.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:dc775734fc49b81cd036a080b074b6d16c6c4224cce089dc089a0e63b50a3c54",
"tag": "2022.06.07.19.26.36.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "d48f30874895dae37f214e4b4a8900cb44c721e0"
}
},
}
}
```
=> chore(cd): update terraformer version to 2022.06.07.19.26.36.release-2.28.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:d17f23cf806906604d4a9f81c95d5918cb18639bbb451b6c795d13982f25d0de",
"tag": "2022.06.07.21.57.31.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "ff2c760d3128a504f57698e3c01d30d9499fe5e7"
}
},
}
}
```
=> chore(cd): update terraformer version to 2022.06.07.21.57.31.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:9de502c7928671eaba896952f56274a9feb9da0dd18a04413d6b52d829018afc",
"tag": "2022.06.07.22.41.23.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "472e2dd8a37e85403b1c934d194d0c4862d97a96"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.06.07.22.41.23.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "349cd1c3a3b0797285bc28ac41787d650e10c478"
},
"details": {
"image": {
"imageId": "sha256:c9450caaf4c134ebab3548f03a40e275a8879c33f153fde4c2d193a05cda253d",
"tag": "2022.06.08.17.10.52.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "693348595c771625ac4bdc5224921b5882578d79"
}
},
}
}
```
=> chore(cd): update deck-armory version to 2022.06.08.17.10.52.release-2.28.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:f3dfa4d12130f0444cabe110e5c865384f4dc4937ea108a532db7ed53fc03fb2",
"tag": "2022.06.08.17.19.37.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "cc5d52a61e95aa2f8eef88915f5aec8d6d6ac001"
}
},
}
}
```
=> chore(cd): update terraformer version to 2022.06.08.17.19.37.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9f6b4dce228d35d0a54d56d79c17424eec04704b"
},
"details": {
"image": {
"imageId": "sha256:25ba3c90c190127021b273c73ccc8373b7663f354d99326858148fb3b7fb4fd6",
"tag": "2022.06.14.17.39.13.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "aff6b09daf760af3f86bc194cb0945c44fcd5b4f"
}
},
}
}
```
=> chore(cd): update deck-armory version to 2022.06.14.17.39.13.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0417e97fb2baea07bdff3acf3b40aa2008a9c30f"
},
"details": {
"image": {
"imageId": "sha256:2da0eb2b853470eba9e5e49b09be96835406411d1ecfddc585930b6951480648",
"tag": "2022.06.14.17.54.03.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "d0a4c0b534877e8b38d9dc03c2dc4a683c289a64"
}
},
}
}
```
=> chore(cd): update deck-armory version to 2022.06.14.17.54.03.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "2cbecd73b1e214f7738e0251d191b30a9588f7ea"
},
"details": {
"image": {
"imageId": "sha256:0c331ed36bb94b1ea92960e391d8a8555b400eafba1dbfebbd2abb5fc3fcc5e3",
"tag": "2022.06.14.19.47.58.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "e8c9c4ef055315d1271e1805241c08fbe2629725"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.06.14.19.47.58.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c2972d12c297263391ca917fde5b5b9c1452e382"
},
"details": {
"image": {
"imageId": "sha256:54775b7dc6bb484dd6dc127b2b65a2024737b81b9ee8d5512aaabc8d9b780a98",
"tag": "2022.06.15.17.51.55.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "3575251530883797df41742f766b467611645159"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.06.15.17.51.55.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9cf7854cd672e89a02797d8796316277fc197a7d"
},
"details": {
"image": {
"imageId": "sha256:8b52343aa203dff789caef5ae8236012a762c46636899a8f072c71015e167cc7",
"tag": "2022.06.24.22.45.18.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "ce9e9eea6aad61957643fd6ced6b52102773a90a"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.06.24.22.45.18.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c2972d12c297263391ca917fde5b5b9c1452e382"
},
"details": {
"image": {
"imageId": "sha256:27abe39c8f632b15fb1beb658f6b31c2c77907e588e14e89d7f91489002d50e4",
"tag": "2022.07.01.23.35.10.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "4af6a46ce17161cad9c3264df2f4030f2d3f3ee0"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.07.01.23.35.10.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:685098d5310198c6037461f65d4c665902bfc8e42aa81d82213e2bbed934d151",
"tag": "2022.07.01.23.28.17.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "938dccc232f849bae4446376579a39755267904b"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.07.01.23.28.17.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "bfd8e75bfeacfc1409f9814decd7af2b7432a223"
},
"details": {
"image": {
"imageId": "sha256:c3172fc5afd668d03bd95d206162001366c8672178afdff3f929a34d554d80f0",
"tag": "2022.07.05.21.12.24.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "9b0cf4b69531092914811f5ded0cf34aefa8c5d6"
}
},
}
}
```
=> chore(cd): update deck-armory version to 2022.07.05.21.12.24.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b1a4dda2428f779564fdd4de1bdcbe226a736c80"
},
"details": {
"image": {
"imageId": "sha256:57cf00ab2b29bc9547467a2e62caf16fa2be0f48ae914ca3fe2432a3b292eddf",
"tag": "2022.07.06.00.14.57.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "4bdd7850e874672bdc1f8cc360c08b7e9497b4ff"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.07.06.00.14.57.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "364bc4d64e87cc2494839632a0ddcfd98ae89da1"
},
"details": {
"image": {
"imageId": "sha256:020777d72afd3240c7b01e71ae1c9202742ffb38c83d1f14402c731ea3527965",
"tag": "2022.07.07.00.07.26.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "cba7fd84457fd2dc97fe10ac62acd6c467a88031"
}
},
}
}
```
=> chore(cd): update deck-armory version to 2022.07.07.00.07.26.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b6a79b07787241b0a48d693695bcdf640621f1a6"
},
"details": {
"image": {
"imageId": "sha256:aa947c5f64c3ada263a72c2acc63aa07aaea3809990d06b82aef2f14cde994bf",
"tag": "2022.07.07.19.09.25.release-2.26.x"
},
"vcs": {
"repo": {
},
"sha": "60c1212dc7b1328b6c8a41bdaca7c5435065c65a"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.07.07.19.09.25.release-2.26.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f7448fe9c68e950a63c1cc2d2019d857d3fc135c"
},
"details": {
"image": {
"imageId": "sha256:3d28b7e4ea7529bb336c20b3c2be214c8816fd6ec611744c0bcd5212e30bdc13",
"tag": "2022.07.07.23.53.38.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "db67e93c1cf470ed0c36258096bc116bc4edc6e1"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.07.07.23.53.38.release-2.28.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:41fd13c65e6f31cd68671852a620d69ed3559daad78280b2428c9cdb180cf591",
"tag": "2022.07.08.15.31.16.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "62cb8fcdb89b30da5c9060bda912d40ca56a167f"
}
},
}
}
```
=> chore(cd): update kayenta-armory version to 2022.07.08.15.31.16.release-2.27.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:f7f9bcf2e49a4c962db1c915ead704498f302e3e6cdd10dcd823eb45fae3f075",
"tag": "2022.07.08.15.30.30.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "e9399998f26517271acda3c083a6c4c0f2d38fa2"
}
},
}
}
```
=> chore(cd): update igor-armory version to 2022.07.08.15.30.30.release-2.27.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:1e6b941de1998cf0d3770c6bebbda7f3892eea3361a1477fc8840b7a737526b1",
"tag": "2022.07.08.15.31.25.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "7bfe2c300432c865f10f07985d81decb58b1ee48"
}
},
}
}
```
=> chore(cd): update kayenta-armory version to 2022.07.08.15.31.25.release-2.28.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:f91b908d10ba1d10387b63b2d97bf49fb55a7615a3785551cbfd97da5d1141f9",
"tag": "2022.07.08.15.30.35.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "c10937f0110f81bd2f17dfea79bfbf01f53598a5"
}
},
}
}
```
=> chore(cd): update igor-armory version to 2022.07.08.15.30.35.release-2.28.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:cf0a5679493ca4b9cf04fecba4ae1e6689aa6ae827593d2684d34c62b468aa1f",
"tag": "2022.07.08.15.30.43.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "1bc61a77916acf5bf7b13041005e730bdac8cd8e"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.07.08.15.30.43.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:94899b60fe01a6ca384f95ea8e4640dc71ff572c5165cbe5f3ac635c8e600a38",
"tag": "2022.07.08.15.35.58.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "30ca83945081107105b9186461730988fabd11d5"
}
},
}
}
```
=> chore(cd): update orca-armory version to 2022.07.08.15.35.58.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f7448fe9c68e950a63c1cc2d2019d857d3fc135c"
},
"details": {
"image": {
"imageId": "sha256:d0ed07f3c117478f2a44853a9ad48d1765de7157b4cf2e3cbb46eb15d7af1a9f",
"tag": "2022.07.08.15.30.03.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "adbe01b56d31389c9cad1274b894c740835c3834"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.07.08.15.30.03.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0f94933969e57c13423b088cc17cae628f5e3d22"
},
"details": {
"image": {
"imageId": "sha256:8ccfd59105696c416ff92efe2d5939f6a4f497a405df749ef86f5e6922faf811",
"tag": "2022.07.08.15.33.53.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "e4acd6a010d9bd810a09ba083a6b7ce26d153e37"
}
},
}
}
```
=> chore(cd): update fiat-armory version to 2022.07.08.15.33.53.release-2.27.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:f214e2e9d90b3a44c6d07117293f97c093ac9d9026d526bd5ccff3215874cd7a",
"tag": "2022.07.11.16.21.57.release-2.26.x"
},
"vcs": {
"repo": {
},
"sha": "8d2b95a66b967de63d90272ae30dd1c8621692cb"
}
},
}
}
```
=> chore(cd): update orca-armory version to 2022.07.11.16.21.57.release-2.26.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1256d50daded7459a54133b41eacb313d54fa7f4"
},
"details": {
"image": {
"imageId": "sha256:fa5df14cb20ce0c3293306b261c1fc622e30c632790d3a3706a909b747d0fa52",
"tag": "2022.07.11.18.14.32.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "ecdccb279800afaed8695588071e656631895225"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.07.11.18.14.32.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:178153ee1683abd7f5feef8ee0fdd24b9cea91ab5dad104f2da604befd428b37",
"tag": "2022.07.11.18.13.11.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "36a55d07da5f25fc385e67922e35f387f13a6fb1"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.07.11.18.13.11.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0693425345b689d495c9dc1c0f35dd585d5d96db"
},
"details": {
"image": {
"imageId": "sha256:8ee64addc90e2dc122404ee059abc6ecacd8be9998ffa364249aaf1eff3b847c",
"tag": "2022.07.13.16.18.30.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "8a74fc9b4209e75de313230e9e2129a80f357d0e"
}
},
}
}
```
=> chore(cd): update deck-armory version to 2022.07.13.16.18.30.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0693425345b689d495c9dc1c0f35dd585d5d96db"
},
"details": {
"image": {
"imageId": "sha256:12f97ec90567d9c8445d43a28d6aee5942a5d505a5d8bb5536792a45739ae906",
"tag": "2022.07.14.16.02.56.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "bf0e14141fa6b002d661e1d747f0ccc7f3992655"
}
},
}
}
```
=> chore(cd): update deck-armory version to 2022.07.14.16.02.56.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "8cc829378c0132ce42381d8769ca2f2df0316ca1"
},
"details": {
"image": {
"imageId": "sha256:ebb903df95007596fa4d7bba2b5faf7c057739eb627fec798ffd381359265f4c",
"tag": "2022.07.14.16.52.46.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "108847b83576abf24d437a0c89015a65f337ec54"
}
},
}
}
```
=> chore(cd): update deck-armory version to 2022.07.14.16.52.46.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "6416718b02904fb6b6188ed4a0eeccc46a154586"
},
"details": {
"image": {
"imageId": "sha256:d77b0907da8e7e9cdb00623a4ef0263330d753dfec06c0e008e3495a6ab9fdc9",
"tag": "2022.08.01.16.34.44.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "45436bf2926c066c9a6a6e1f49de4e213ab746e0"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.08.01.16.34.44.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "570d8d739abe6dd389553c3966a387413a4e8192"
},
"details": {
"image": {
"imageId": "sha256:d3012d4c5901110f74c95358bf89bc6c95eb05de07c30c79f6bf976d66722a3b",
"tag": "2022.08.03.03.23.19.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "336ada6c91041875a48043f92d2a85f2c0130532"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.08.03.03.23.19.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d27a99e4fdcd595b01534fd928f3efd7bcaaa0df"
},
"details": {
"image": {
"imageId": "sha256:7f6c948b07970360ff773bdbdb3c8221bd2b8a3f571353c209671a9019a35295",
"tag": "2022.08.03.03.22.24.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "fa55c3fcae8e1fed1fa22b8d7ae955d647deed2e"
}
},
}
}
```
=> chore(cd): update fiat-armory version to 2022.08.03.03.22.24.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "fac9d3b1b9ed3201eb2522d414d5a0b051ecba68"
},
"details": {
"image": {
"imageId": "sha256:ca964c0cc66202710004093fbbe1f7ba57397df224f0b620e5e99548d46239b6",
"tag": "2022.08.03.03.22.19.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "fce52482097b606389328d25d220be5eaaddab21"
}
},
}
}
```
=> chore(cd): update fiat-armory version to 2022.08.03.03.22.19.release-2.28.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:09cc23ac9f54ab23c6fce17482b529781c1a42394a95f74088e8a8cbc7adae6a",
"tag": "2022.08.03.03.24.35.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "85772bcc95532671dfe9313fa2dca4cc86884dd5"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.08.03.03.24.35.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "3d9dcec1741dcdccf44f30c0462eb7ce6d0324e8"
},
"details": {
"image": {
"imageId": "sha256:ebd05ef2a54d820114fdfab9e78b8f4304485dcedee9cea09e0a638468408502",
"tag": "2022.08.03.03.22.56.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "634b3a21b5a88f0b69320cb4ecae52d04f1bc19b"
}
},
}
}
```
=> chore(cd): update igor-armory version to 2022.08.03.03.22.56.release-2.28.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:3d63c88fb3771dd8fa185f6f4f3c365c9ae0542ee480a68f95cb51be7dfc554d",
"tag": "2022.08.03.03.23.26.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "440f69b6fb65f036f9869bbdcc14b9807e059405"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.08.03.03.23.26.release-2.27.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:4e01be4086ac3e3c9dca8a89216fc3f8198e129239140fcf482a45aeb830e3dc",
"tag": "2022.08.03.03.35.59.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "af143d6925556ff301c68efa527724c4b820f90b"
}
},
}
}
```
=> chore(cd): update orca-armory version to 2022.08.03.03.35.59.release-2.27.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:125b613e181e4957838ad70d42cece7362e95c8190a62be3bd082ce16859a245",
"tag": "2022.08.03.03.33.08.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "0f84f60ad447a5cbdf019b40aaa9b10111fa8f73"
}
},
}
}
```
=> chore(cd): update orca-armory version to 2022.08.03.03.33.08.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "bbb6861e136c9629c720f222313f356ee929139d"
},
"details": {
"image": {
"imageId": "sha256:b7a447d5489281b2350cea75c029cd51dfcffbbeceb2d05bf0bbadb87d64e78f",
"tag": "2022.08.03.03.25.54.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "225485883fd08f6c90f9961fd77de52e583f4fda"
}
},
}
}
```
=> chore(cd): update igor-armory version to 2022.08.03.03.25.54.release-2.27.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:bd361819cc9abe388ed5fa926408510a4bc0abd8bf578d826b3aec367164cbb3",
"tag": "2022.08.03.03.39.15.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "68d13f9cb6328e49dc3745bc0ab8a3b2c6f8d969"
}
},
}
}
```
=> chore(cd): update kayenta-armory version to 2022.08.03.03.39.15.release-2.27.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:c8e003019d8d23bba6a7ce6d39de21d648c08e4b6a384132705e1c9cee44dd83",
"tag": "2022.08.03.03.46.46.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "2e71ad5ac97015c41648a1446b452a61134543b5"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.08.03.03.46.46.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "aabbda054ffd4f3051ece8c34854c00750d9caa0"
},
"details": {
"image": {
"imageId": "sha256:7adbc93db35dbf6aaffaefeb6c9c55ee822e7b6f0fc15edda8f236c2b1077a04",
"tag": "2022.08.03.03.52.15.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "bb7b4cba6a1a542a4628015563216a353db5c680"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.08.03.03.52.15.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "19566df7adf057190dd41f8ff0044c686aa9b768"
},
"details": {
"image": {
"imageId": "sha256:3843aa54563fa23841f29108d0e5f0a35be84ee2f9068555dfa181c59a157436",
"tag": "2022.08.03.21.57.03.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "a8dfd004d1453280c546311c65e1db054106bd19"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.08.03.21.57.03.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "8215d49ee57686aa9c2dbc5b3ebd06fd1b985dd6"
},
"details": {
"image": {
"imageId": "sha256:6ec709750d205935f2a93e73cc1b7b4cc4fbe41cf3fc36ee1b640dc93fd7cd54",
"tag": "2022.08.03.21.55.44.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "2347a0cc42dfd1341159290557a2355e63e20962"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.08.03.21.55.44.release-2.28.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:ae32f13f1fa9df596eeb7c460d3cc66566cb4874707b0e2d1f732719c1f35bfb",
"tag": "2022.08.08.18.17.08.release-2.26.x"
},
"vcs": {
"repo": {
},
"sha": "5bcecf4bd2eb57b0c0d286b2101670f020a7e817"
}
},
}
}
```
=> chore(cd): update fiat-armory version to 2022.08.08.18.17.08.release-2.26.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:33f8af8a41d20bdc1ecfc447738b855f3fedbc7141e952bab4526b4515901833",
"tag": "2022.08.08.18.17.26.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "9d615d351b220ea846e3c31890ecea7757fe40f4"
}
},
}
}
```
=> chore(cd): update fiat-armory version to 2022.08.08.18.17.26.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "728f29cb10e02e4989b49ba6f1d69ab9b8f1ccce"
},
"details": {
"image": {
"imageId": "sha256:aa5988573d82436c8e121941e396a132df7c286d94755f50b9f1249ad3c87913",
"tag": "2022.08.08.18.20.31.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "417ac6a01e5dcd1e1343ae0b24606089bcecd035"
}
},
}
}
```
=> chore(cd): update orca-armory version to 2022.08.08.18.20.31.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7ce04bcbac5ee2cafac147b2c15e6f2d6109bc73"
},
"details": {
"image": {
"imageId": "sha256:e5ddf60fafb64461ec9ede2460197649c2fe23de797973c67b83e21422daea41",
"tag": "2022.08.08.18.20.55.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "77a6be86b2348600d682035865a0305672b3c486"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.08.08.18.20.55.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:04ee0b6692bf20b71952af69c4e39412a00249bc8bf910c93899c47167644ab2",
"tag": "2022.08.08.18.20.49.release-2.26.x"
},
"vcs": {
"repo": {
},
"sha": "e12833213a99580d2da6ecfcb98dcb2a480bab37"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.08.08.18.20.49.release-2.26.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:d73ac4af8fdef16c22f93921762917a7f708fb255f05a22205f3e4c57c90e629",
"tag": "2022.08.08.18.20.43.release-2.26.x"
},
"vcs": {
"repo": {
},
"sha": "e66034e3b6ab368cb2497b1c0346e6d2bc294e2b"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.08.08.18.20.43.release-2.26.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "19566df7adf057190dd41f8ff0044c686aa9b768"
},
"details": {
"image": {
"imageId": "sha256:8e37d896669836ed66799e14c49171eb20cd2054f191b013236efc696e01054f",
"tag": "2022.08.08.18.22.17.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "9276aab4e7f3c29a095eef75f46847276b1be1aa"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.08.08.18.22.17.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5a171294e107c614fff9386d2da1540975f6dd25"
},
"details": {
"image": {
"imageId": "sha256:32f4ef14b28a7279da72edfd014c32743b19b559923f29b903ae56ca02b0a902",
"tag": "2022.08.08.18.20.37.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "4af4c693e111fc90dae97c3fac43ec125ea3b7d5"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.08.08.18.20.37.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1256d50daded7459a54133b41eacb313d54fa7f4"
},
"details": {
"image": {
"imageId": "sha256:f0b5dfc80742841f7572bf9a84946f01395e74306c65a0766ff8a44c4e75ef7d",
"tag": "2022.08.08.18.21.23.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "82dc668c74611912fad86c29c987c6a8f5b400b2"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.08.08.18.21.23.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "eceee0e1d6d7e43a64f4cbf752d3c998ce672c6a"
},
"details": {
"image": {
"imageId": "sha256:056b1a454922a8395d882e6e330304e9f132fb85a230fb7a7607dae72c41608a",
"tag": "2022.08.03.03.22.30.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "60203d09e2f59ee71679fef98b8acf802d3ef0e9"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.08.03.03.22.30.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "06b2900e558b08247fee0854d391f3a8635da0ed"
},
"details": {
"image": {
"imageId": "sha256:a7b845c247d6bf1ddf0249a31af688f5a0b7f87b2e13a41659d6992060ff0a4a",
"tag": "2022.08.11.01.05.03.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "77806ba40e2e0031d6c76e28fc09c2c3511e9731"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.08.11.01.05.03.release-2.28.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:6322ba011b02ad482e63a92fbfb0f84283e637b21ad9af536db02c7b1b4bb268",
"tag": "2022.08.25.23.54.36.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "53c9f50a991a3f102e14a103340c3eea5c9ef982"
}
},
}
}
```
=> chore(cd): update terraformer version to 2022.08.25.23.54.36.release-2.27.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:cdd734ff6a86254155b4d9fbd47877df656c495d5fa372eb75109c215a9f6541",
"tag": "2022.08.17.01.12.06.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "a05405308878a6278522793b0d55f0f8a06cb6a5"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.08.17.01.12.06.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5a171294e107c614fff9386d2da1540975f6dd25"
},
"details": {
"image": {
"imageId": "sha256:58d87489279280c08b1dc7f6d8e00b0b45932d46b27b158a96df96e209e20a59",
"tag": "2022.08.17.22.37.15.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "749433b28e8c8724b00c7f853736296c06b7eaa9"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.08.17.22.37.15.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7ce04bcbac5ee2cafac147b2c15e6f2d6109bc73"
},
"details": {
"image": {
"imageId": "sha256:cc8486bd454730301b894db35f91fa475a6580f949eed727a847e4ad77932c9a",
"tag": "2022.08.17.22.38.33.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "0aa1dac24a046fa8ff37b7cdd6edb704a16b215c"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.08.17.22.38.33.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "bbb6861e136c9629c720f222313f356ee929139d"
},
"details": {
"image": {
"imageId": "sha256:56400948f1f5e2dfca9def236c748a9cd9f0e6d922b19133c47abc654b2ec9a0",
"tag": "2022.08.17.22.38.58.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "cb18ff7fe94fca85ab546b4304cb9fa9ce380b69"
}
},
}
}
```
=> chore(cd): update igor-armory version to 2022.08.17.22.38.58.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "99cb178a4bf47095ca1e8ea7b6f5921eec92dbc2"
},
"details": {
"image": {
"imageId": "sha256:fd8b12b2567d750abb3840800dbb48210cda2be1295259e31ff372d6c1a51394",
"tag": "2022.08.17.23.10.43.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "a6a2b412958bd3d5555dc74190df86ab2c4fb5a5"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.08.17.23.10.43.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "558550a07599e1599aff25562f0c7a229c960d7d"
},
"details": {
"image": {
"imageId": "sha256:7a153eb61e14c1be005f7403cd63939a557ff95a4518e2d121d5de0d3009bb3c",
"tag": "2022.08.18.00.36.33.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "08b8f4656b4f6285ae5b0a5577ab10f6c50ba8ec"
}
},
}
}
```
=> chore(cd): update kayenta-armory version to 2022.08.18.00.36.33.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0c195d77cac68b70f4559b63f87d573279a0e79f"
},
"details": {
"image": {
"imageId": "sha256:822ac3d49b9ba3eebbdf4361d33159de06c43ca9452577dd5a7be6e1f2ac9deb",
"tag": "2022.08.19.17.20.20.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "fc9593f3c4da98fa8c7f6753598a75f4ea19a49c"
}
},
}
}
```
=> chore(cd): update orca-armory version to 2022.08.19.17.20.20.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "921748132548e89c1015c5590c5dbad49eb773d7"
},
"details": {
"image": {
"imageId": "sha256:7702d6b138af399cbdef47d5833954bd9f46d5ea6809be4fec6b5c64f70b2a61",
"tag": "2022.08.23.02.52.49.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "eec2780305426ba8c38bcf599176a00b138b96cf"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.08.23.02.52.49.release-2.27.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:1d0dc4de0f08c948bddf1ad1f760981b4f5fff063d19e8853f82227c3880296b",
"tag": "2022.07.08.02.40.47.master"
},
"vcs": {
"repo": {
},
"sha": "b8ea85489ae8ba7f09e93573a364e9ba4c3512fb"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.07.08.02.40.47.master

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:0d0ed4a42d4362f96caf4dc45814abaf1e858b5df1f972135f07e62f8f12df6a",
"tag": "2022.08.15.08.23.24.master"
},
"vcs": {
"repo": {
},
"sha": "06274aea2918f7e47222856537224de91c9cf542"
}
},
}
}
```
=> chore(cd): update terraformer version to 2022.08.15.08.23.24.master

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:7c9c7ccd9b8480bda6b91558f2e729cb81c78b483ce87a2baf6fafd68a0705aa",
"tag": "2022.08.15.19.19.38.master"
},
"vcs": {
"repo": {
},
"sha": "494f9286dd029ac2c654e443c510b457ee28f0d1"
}
},
}
}
```
=> chore(cd): update fiat-armory version to 2022.08.15.19.19.38.master

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1c7614c9479f089d966378e4f1ae9c7aa14502bf"
},
"details": {
"image": {
"imageId": "sha256:19f689bf1763ebcd8e5ba27074f4748a5d801cdc37102a83c0b31bf55f8843ea",
"tag": "2022.08.15.20.12.08.master"
},
"vcs": {
"repo": {
},
"sha": "89f4744f1298326f951d56b4d5b7eef8186d80b9"
}
},
}
}
```
=> chore(cd): update deck-armory version to 2022.08.15.20.12.08.master

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7079155f353e9000d49da3caaab49023a986153a"
},
"details": {
"image": {
"imageId": "sha256:498b89df3147ddd71a80ca421880421a6c39399834174c4beabef6835de779ee",
"tag": "2022.08.25.20.08.07.master"
},
"vcs": {
"repo": {
},
"sha": "a9c39cebb6c5c714c82bf3d567a09992804c19f2"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.08.25.20.08.07.master

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0417e97fb2baea07bdff3acf3b40aa2008a9c30f"
},
"details": {
"image": {
"imageId": "sha256:17450df07d46711870ea82e05773b7e6f27ca506642271bd5513edbfba301121",
"tag": "2022.08.31.16.11.34.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "1b08ce5370fd95b9c4647734c36df71d729a386a"
}
},
}
}
```
=> chore(cd): update deck-armory version to 2022.08.31.16.11.34.release-2.27.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:525d84d08550cc084406dee400dd044d8c6f0ea9f03226bff4fa3b452b1cf3db",
"tag": "2022.08.22.19.52.29.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "1859781ad9a529c45f18693e239031cf1365fe1e"
}
},
}
}
```
=> chore(cd): update dinghy version to 2022.08.22.19.52.29.release-2.28.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:3701a12fcc9a11243a39258c2cdf80d9c3963be7db8fe659510ac7d9c3aca651",
"tag": "2022.08.17.16.27.21.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "a0469f1833aa01cfd92a5b46f3fad6bc5137b6d1"
}
},
}
}
```
=> chore(cd): update terraformer version to 2022.08.17.16.27.21.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4ef0ac247f91c9f7bb2422cd0d909a2f621051d0"
},
"details": {
"image": {
"imageId": "sha256:262a163e44e595b2bd41593912df361cf31f7061d0002059f5f5794621ca7a77",
"tag": "2022.08.19.03.36.22.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "2b2b668ac5d4cbf126190baf450116de6aa0aa4a"
}
},
}
}
```
=> chore(cd): update gate-armory version to 2022.08.19.03.36.22.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "cf6fe498b64c18bf2bed803aa3d59d8d3aee12ec"
},
"details": {
"image": {
"imageId": "sha256:7cdcf3d9c131107872f0176ecc7d82014323a32b1194c2d04fff13eb26f26db3",
"tag": "2022.08.19.03.35.52.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "508646c02d5053c63ca7892b613398cc012ba324"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.08.19.03.35.52.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f1b5baecc46715e1d9dacea3c980b8a5229590f0"
},
"details": {
"image": {
"imageId": "sha256:9c6f675dd1552e6ac8fcf7882146cf0ed937979f6dac35fe34ba131811d37de1",
"tag": "2022.08.19.03.39.07.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "fafda40bcfc87e897fcb4e83b3e0ad131be5ecc7"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.08.19.03.39.07.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "655f507fecbcdcd2d6c01280e82e2bfe092d7354"
},
"details": {
"image": {
"imageId": "sha256:b8d7d3cacb4bf9e4dd19c1cd8b40d6e7e451a26e26eb4df76f80674b8ea00792",
"tag": "2022.08.19.03.36.16.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "50db5b5e329651e8375eecda168b4b0e727f189e"
}
},
}
}
```
=> chore(cd): update igor-armory version to 2022.08.19.03.36.16.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1fc1c6673ef5a5e217e1826bd4bf574a18f866f3"
},
"details": {
"image": {
"imageId": "sha256:aab634207a3acb4a50cee21ff67e325d000a0eb268460243a656ef7dcda0993f",
"tag": "2022.09.07.21.56.45.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "2b4c0886ee46108dbca50500cefde88b0e64ce9b"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.09.07.21.56.45.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "178ccdb149c78bc4eb4ef6d6cdcfe54892f90851"
},
"details": {
"image": {
"imageId": "sha256:078d10efee216c63be9aecd102317cf114babe087cec14725e6deebaff064eec",
"tag": "2022.08.19.03.45.39.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "3b1c90e3afdb77f6a3b9b607f6f98d69cb8894a0"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.08.19.03.45.39.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a22e118aebc05f71fc647fc409104edccd7d19db"
},
"details": {
"image": {
"imageId": "sha256:c1f067a497e37cf9abee451f8bcd69d3bf777e78258670ce3bd5b041eba57023",
"tag": "2022.08.23.16.16.39.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "ae14cddd90ed2b969dd3e0fd1c023383a36126b9"
}
},
}
}
```
=> chore(cd): update rosco-armory version to 2022.08.23.16.16.39.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "19f325055820b7a93cea53fbe9130183d1177153"
},
"details": {
"image": {
"imageId": "sha256:9838378f1c74ba0701dfab201031e48ff465b558d04b2f0bd05b73d6f500418c",
"tag": "2022.08.19.04.54.33.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "6004bfd90ad2e4fa9b02dddc26253210b8aa3a3c"
}
},
}
}
```
=> chore(cd): update kayenta-armory version to 2022.08.19.04.54.33.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e303664f5b386d4f9cb2eafabe3f2d7465960aa9"
},
"details": {
"image": {
"imageId": "sha256:2c544411754ce7ed14984196a26d9ed323f24298b60539e94ff2b8bc71ae488d",
"tag": "2022.08.19.16.44.17.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "727e9dd1c99b1b32e4538c65e012f448a395276a"
}
},
}
}
```
=> chore(cd): update orca-armory version to 2022.08.19.16.44.17.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e825fb20176b893bf6f34c9f67d8dda94cec33ba"
},
"details": {
"image": {
"imageId": "sha256:f25b0e1772c742ac9600a0384cfe35ca11d74b16443d48c67911af057f9af54d",
"tag": "2022.09.09.20.27.11.master"
},
"vcs": {
"repo": {
},
"sha": "60f7d0c150e8b87fb4f504bbf2f0208faa6f6908"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.09.09.20.27.11.master

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f1b5baecc46715e1d9dacea3c980b8a5229590f0"
},
"details": {
"image": {
"imageId": "sha256:615e30d68e610d39e9142ad242ae997b4d7aa18f284301b128c52394ec481081",
"tag": "2022.09.12.22.49.17.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "1e5d3a5dfce38d26f809dee107d8145c00caa27e"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.09.12.22.49.17.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1fc1c6673ef5a5e217e1826bd4bf574a18f866f3"
},
"details": {
"image": {
"imageId": "sha256:91b59e23af363b7314cbc9fec9c99821e8e040ad276799ba07343e85a1acfeaf",
"tag": "2022.09.12.22.50.10.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "8be88a5e2efdf5ac85b6ea38c264d762e8ccf523"
}
},
}
}
```
=> chore(cd): update front50-armory version to 2022.09.12.22.50.10.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "fa75e6bdad8ddfb7424584bc16c9d502ace4600f"
},
"details": {
"image": {
"imageId": "sha256:5fdf8baeba0ec8fd5b602742c916f32a88181027b5e460d961f3832910ae3952",
"tag": "2022.09.12.19.35.13.master"
},
"vcs": {
"repo": {
},
"sha": "ee3bc40f7c58ce0574896af919ebc4bfcecc8048"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.09.12.19.35.13.master

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "be955553f45e3fe083a8d3971e348889eba76d8f"
},
"details": {
"image": {
"imageId": "sha256:2979e13c0fcf043d3caee6a27f8800ca4f41d76d30453e9aa3d84744d77427ee",
"tag": "2022.09.12.19.20.25.master"
},
"vcs": {
"repo": {
},
"sha": "92a4572bd2f866c49557975732a8c3c718ad410d"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.09.12.19.20.25.master

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5b5c0251759a6ff35b86cb1808705c9334170df5"
},
"details": {
"image": {
"imageId": "sha256:ef2aa4662d9eab6b853b581e3ad23fbc928f26874a8a8b6957cfac2539c639ca",
"tag": "2022.09.13.20.53.49.master"
},
"vcs": {
"repo": {
},
"sha": "462bff066ab33aab84ad798cf75e737bedc1caa4"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.09.13.20.53.49.master

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5b5c0251759a6ff35b86cb1808705c9334170df5"
},
"details": {
"image": {
"imageId": "sha256:253d6cff4c50f2748289df708fc444bb94723b4198865f05d649367723447b65",
"tag": "2022.09.14.16.38.52.master"
},
"vcs": {
"repo": {
},
"sha": "bd39fc4fdbe840755a56b61aded3815b3cd038f0"
}
},
}
}
```
=> chore(cd): update echo-armory version to 2022.09.14.16.38.52.master

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5bf15b7023ec83c0737640d4816bd5d3beee4d1d"
},
"details": {
"image": {
"imageId": "sha256:631fc0c6acbdef40bd9e9b1546b898388c3207ad373ea055f191580910ee02db",
"tag": "2022.09.14.17.01.20.master"
},
"vcs": {
"repo": {
},
"sha": "8a0b6b34ffcdd4b0b749a0452a339282bedda7eb"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.09.14.17.01.20.master

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c69ccc78a723b3969201df65fa0444d301fc7955"
},
"details": {
"image": {
"imageId": "sha256:737757dc749d333f7289b56a6ea60118081769a1f3c1bd31c7c4e69d1090a9ff",
"tag": "2022.10.19.21.04.24.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "2315edcd8c918c3b2baceae6742c757cb9d36c38"
}
},
},
"baseVcs": {
"repo": {
},
"sha": "c69ccc78a723b3969201df65fa0444d301fc7955"
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update orca-armory version to 2022.10.19.21.04.24.release-2.28.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:ae37354e64f87435f3f5d895641c4208a8f0d7b04e9cdb5dbb62049236bef629",
"tag": "2022.09.20.19.16.39.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "bb576e57561db2d957c25e00992e24f53a223bd5"
}
},
}
}
```
=> chore(cd): update terraformer version to 2022.09.20.19.16.39.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e96cae4671fb2155b4c91a5686849396ce8be8df"
},
"details": {
"image": {
"imageId": "sha256:5c745d199e2664dd57b05d053ac0308a212742a9a14c3bc740b2c47b4daff0fa",
"tag": "2022.10.19.19.19.29.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "88567fc0c710c63b2093fc95e674052314978250"
}
},
},
"baseVcs": {
"repo": {
},
"sha": "e96cae4671fb2155b4c91a5686849396ce8be8df"
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update rosco-armory version to 2022.10.19.19.19.29.release-2.28.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:b5f35d09884647a6b8ff9ac6e4bc34ce27def1af573f20786ff252531768a24d",
"tag": "2022.10.22.00.16.44.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "fc867f05b41e5e2756c42990b576341973e96276"
}
},
},
"details": {
"image": {
"imageId": "sha256:b5f35d09884647a6b8ff9ac6e4bc34ce27def1af573f20786ff252531768a24d",
"tag": "2022.10.22.00.16.44.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "fc867f05b41e5e2756c42990b576341973e96276"
}
},
}, …
```
=> chore(cd): update dinghy version to 2022.10.22.00.16.44.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a335ed4a36452ea2320de8048c20eb02b25de3ad"
},
"details": {
"image": {
"imageId": "sha256:5579ea9c2b2f59673027fef48ea495550f2b3b5cf7aa8389dffa4c601f6343bd",
"tag": "2022.10.19.20.14.04.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "010bdc55d57c1000ef93f826204e6ccf54f6f6e7"
}
},
},
"baseVcs": {
"repo": {
},
"sha": "a335ed4a36452ea2320de8048c20eb02b25de3ad"
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update echo-armory version to 2022.10.19.20.14.04.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "102be81644d61fff46f557fe7d2ba7183eefe484"
},
"details": {
"image": {
"imageId": "sha256:86640df898c979b20234eeaaa03918ee0cc80e528c834c2c246b174fdd563a71",
"tag": "2022.10.21.17.15.28.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "e2f05e01e2f3a69fbaee026a2aece3efd7be69fb"
}
},
},
"baseVcs": {
"repo": {
},
"sha": "102be81644d61fff46f557fe7d2ba7183eefe484"
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update deck-armory version to 2022.10.21.17.15.28.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0f5a2756d15494e9c05a3a08e5c4dd270f07b943"
},
"details": {
"image": {
"imageId": "sha256:255c74a7eaaf916cf81d96407a4f306170dd1f3b68e1ae2bed5ef61389a78e20",
"tag": "2022.11.01.19.11.06.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "9bba68d09adf45fb4d938fb19821a5692d2f003a"
}
},
},
"baseVcs": {
"repo": {
},
"sha": "0f5a2756d15494e9c05a3a08e5c4dd270f07b943"
},
"details": { …
```
=> chore(cd): update clouddriver-armory version to 2022.11.01.19.11.06.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c69ccc78a723b3969201df65fa0444d301fc7955"
},
"details": {
"image": {
"imageId": "sha256:5084920e8b9272c24eaca2df8bf75ec89316786dc616756f9f6d73512887e529",
"tag": "2022.11.02.03.44.17.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "d64435c42a1b1d27a463241a035873968db6475f"
}
},
},
"baseVcs": {
"repo": {
},
"sha": "c69ccc78a723b3969201df65fa0444d301fc7955"
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update orca-armory version to 2022.11.02.03.44.17.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c6801bed2e94538b836b2277f07332a027247c23"
},
"details": {
"image": {
"imageId": "sha256:87606ac9ab8d84ab9e067d161e8d99553122fbf23c3b1a9cc41b16a7a0766aa2",
"tag": "2022.11.02.03.45.12.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "e7e01c998423941507a7322e6891ea6e95a16792"
}
},
},
"baseVcs": {
"repo": {
},
"sha": "c6801bed2e94538b836b2277f07332a027247c23"
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update igor-armory version to 2022.11.02.03.45.12.release-2.28.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:6276ec1156ab725a20c6e5005cb0cd6baa740e23d08601555e1226a4f328cbbb",
"tag": "2022.10.27.14.21.24.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "ca161395d61ae5e93d1f9ecfbb503b68c2b54bc5"
}
},
},
"details": {
"image": {
"imageId": "sha256:6276ec1156ab725a20c6e5005cb0cd6baa740e23d08601555e1226a4f328cbbb",
"tag": "2022.10.27.14.21.24.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "ca161395d61ae5e93d1f9ecfbb503b68c2b54bc5"
}
},
}, …
```
=> chore(cd): update dinghy version to 2022.10.27.14.21.24.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "72204fd2058a5eff8f6b3f3905f32785ea8eee5e"
},
"details": {
"image": {
"imageId": "sha256:7efba43bba8b31872f83bc256487f2e0213401cda442e8b6f7f8db39060ebe84",
"tag": "2022.09.27.20.32.29.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "373baea2b2ac14a98057950b651ef5a4fd805da7"
}
},
}
}
```
=> chore(cd): update clouddriver-armory version to 2022.09.27.20.32.29.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0c195d77cac68b70f4559b63f87d573279a0e79f"
},
"details": {
"image": {
"imageId": "sha256:6027d53b103633ee532d3f292c38a0890d54a7a547660d544fe99a4cf9dfa2b8",
"tag": "2022.11.02.03.47.00.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "b0243135961367f4abcb9ee8612cacf241afa93f"
}
},
},
"baseVcs": {
"repo": {
},
"sha": "0c195d77cac68b70f4559b63f87d573279a0e79f"
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update orca-armory version to 2022.11.02.03.47.00.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "dd51bfcdf50e4a5e037353a33746d66fd7c22be9"
},
"details": {
"image": {
"imageId": "sha256:ec75c169df03f9a4d5afb8cbdc58673378a3c99047854b2f68cfceed8a4c23d5",
"tag": "2022.11.02.03.48.21.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "2ff1a3deaaa6b9c354bc945721345d602acc19c9"
}
},
},
"baseVcs": {
"repo": {
},
"sha": "dd51bfcdf50e4a5e037353a33746d66fd7c22be9"
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update igor-armory version to 2022.11.02.03.48.21.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d7d0c5ab1ab19a44a09711b31b128c24d93167b1"
},
"details": {
"image": {
"imageId": "sha256:c009e062eeb4450a7ba7ef0b0a39ecf983a71ebe68253f23f3b9ec0a40c228e0",
"tag": "2022.11.02.20.47.05.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "9216f0fae587d3af14ed41fb9f21e9195b30c269"
}
},
},
"baseVcs": {
"repo": {
},
"sha": "d7d0c5ab1ab19a44a09711b31b128c24d93167b1"
},
"details": { …
```
=> chore(cd): update clouddriver-armory version to 2022.11.02.20.47.05.release-2.28.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c49b64e06ca5f663fdd4c0452ab47bd2c82b0041"
},
"details": {
"image": {
"imageId": "sha256:4c6f9a1a49fae929c928d2cbdb2a8a09d2cfdf3247ac78434601ebc111e0de32",
"tag": "2022.10.21.17.17.19.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "aa802b8e788a897925df5caca0f63a7b12fe6b8d"
}
},
},
"baseVcs": {
"repo": {
},
"sha": "c49b64e06ca5f663fdd4c0452ab47bd2c82b0041"
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update deck-armory version to 2022.10.21.17.17.19.release-2.27.x

stack.yml
Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "6405f4305990c34ee481329b210e70f7bdab9a8f"
},
"details": {
"image": {
"imageId": "sha256:d41643a4352e5b06f10b3fa946567e7f1e90aeb87d7664dd543e5a9378f5f5ea",
"tag": "2022.11.08.18.20.28.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "583b59cfcea93cce9b221509d0d4ec03a9487939"
}
},
},
"baseVcs": {
"repo": {
},
"sha": "6405f4305990c34ee481329b210e70f7bdab9a8f"
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update orca-armory version to 2022.11.08.18.20.28.release-2.28.x

stack.yml
armory/gate-armory:2022.11.10.23.04.42.release-2.28.x
[4615a016768bf7e772189da05415d654a440e107](https://github.com/armory-io/gate-armory/commit/4615a016768bf7e772189da05415d654a440e107)
[64f64567612facf312b7fd3126051812d10c014d](https://github.com/spinnaker/gate/commit/64f64567612facf312b7fd3126051812d10c014d)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "64f64567612facf312b7fd3126051812d10c014d"
},
"details": {
"image": {
"imageId": "sha256:f7f1b05687e54d4b1f2a0a76e3264733e349de4fa71ee0d24aaa114c11ee1b68",
"tag": "2022.11.10.23.04.42.release-2.28.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update gate-armory version to 2022.11.10.23.04.42.release-2.28.x

stack.yml
armory/terraformer:2022.11.16.18.59.47.release-2.28.x
[6b721988b67473db3e4d9267432c609b5176274d](https://github.com/armory-io/terraformer/commit/6b721988b67473db3e4d9267432c609b5176274d)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:e1a7e1edb8b3aa564c9abb0f042ca10d4344b157e297f863149fa04a7891e986",
"tag": "2022.11.16.18.59.47.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "6b721988b67473db3e4d9267432c609b5176274d"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2022.11.16.18.59.47.release-2.28.x

stack.yml
armory/igor-armory:2022.11.21.13.27.25.release-2.28.x
[bbb095dd5fd6e5beffc349b7d16756f22e28978a](https://github.com/armory-io/igor-armory/commit/bbb095dd5fd6e5beffc349b7d16756f22e28978a)
[c6801bed2e94538b836b2277f07332a027247c23](https://github.com/spinnaker/igor/commit/c6801bed2e94538b836b2277f07332a027247c23)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c6801bed2e94538b836b2277f07332a027247c23"
},
"details": {
"image": {
"imageId": "sha256:3c3e380067b396ff4f822303ec0a8ba976c6fa2c96339f77e121ceddea5dd601",
"tag": "2022.11.21.13.27.25.release-2.28.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update igor-armory version to 2022.11.21.13.27.25.release-2.28.x

stack.yml
armory/igor-armory:2022.11.21.13.27.02.release-2.27.x
[e6f63ea3d557ed52c08e21b9845c0704c7d31cba](https://github.com/armory-io/igor-armory/commit/e6f63ea3d557ed52c08e21b9845c0704c7d31cba)
[35c25f7f77c31f7f60496184786258261a2f1def](https://github.com/spinnaker/igor/commit/35c25f7f77c31f7f60496184786258261a2f1def)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "35c25f7f77c31f7f60496184786258261a2f1def"
},
"details": {
"image": {
"imageId": "sha256:6470e80f25f74ef95eea3a9cd2303102c7accf136330900555f2ce9a941781ef",
"tag": "2022.11.21.13.27.02.release-2.27.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update igor-armory version to 2022.11.21.13.27.02.release-2.27.x

stack.yml
armory/echo-armory:2022.11.18.20.30.20.release-2.27.x
[d44e7969ec05bbfd7d48369c8c7221d6ba009c40](https://github.com/armory-io/echo-armory/commit/d44e7969ec05bbfd7d48369c8c7221d6ba009c40)
[b1bf2fcb59f72924004ffdf841276ca75cb0450f](https://github.com/spinnaker/echo/commit/b1bf2fcb59f72924004ffdf841276ca75cb0450f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b1bf2fcb59f72924004ffdf841276ca75cb0450f"
},
"details": {
"image": {
"imageId": "sha256:b69711d4c87b7dfe16d6c32d7267b1c35679a039db6d9b7cbbb2f86319c493fc",
"tag": "2022.11.18.20.30.20.release-2.27.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2022.11.18.20.30.20.release-2.27.x

stack.yml
armory/gate-armory:2022.11.18.20.31.26.release-2.27.x
[a3ce246e5d6f2588647c8654449100fc1aea25e0](https://github.com/armory-io/gate-armory/commit/a3ce246e5d6f2588647c8654449100fc1aea25e0)
[84dac9de8583388771d441cd342230e549d455fe](https://github.com/spinnaker/gate/commit/84dac9de8583388771d441cd342230e549d455fe)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "84dac9de8583388771d441cd342230e549d455fe"
},
"details": {
"image": {
"imageId": "sha256:ad4195ec9ea6405e4a654d4ac8c94def5a48504902193286c8a34006fe89d6cc",
"tag": "2022.11.18.20.31.26.release-2.27.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update gate-armory version to 2022.11.18.20.31.26.release-2.27.x

stack.yml
* **master**
armory/gate-armory:2022.11.17.22.19.35.master
[f22b9d124867bb865860e9419a1c9a1e6e910cd6](https://github.com/armory-io/gate-armory/commit/f22b9d124867bb865860e9419a1c9a1e6e910cd6)
[0e438e253524d8354c7f6f6c393b1aab3e97c64e](https://github.com/spinnaker/gate/commit/0e438e253524d8354c7f6f6c393b1aab3e97c64e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0e438e253524d8354c7f6f6c393b1aab3e97c64e"
},
"details": {
"image": {
"imageId": "sha256:67b4e14ca1adece5011a8425777bf61630fe0fabeb64d0ef9ab64d47c1ac965e",
"tag": "2022.11.17.22.19.35.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update gate-armory version to 2022.11.17.22.19.35.master

stack.yml
armory/igor-armory:2022.11.29.22.25.00.release-2.28.x
[61ce26babfcd0bdf62872c24e707ca5b5371a381](https://github.com/armory-io/igor-armory/commit/61ce26babfcd0bdf62872c24e707ca5b5371a381)
[90f72f8e22576adc839fbbb9b85f2c279bcb58e3](https://github.com/spinnaker/igor/commit/90f72f8e22576adc839fbbb9b85f2c279bcb58e3)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "90f72f8e22576adc839fbbb9b85f2c279bcb58e3"
},
"details": {
"image": {
"imageId": "sha256:51aa1f04074378b46714e3103f3df21fd95624879f76793be78b3dc33e354d93",
"tag": "2022.11.29.22.25.00.release-2.28.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update igor-armory version to 2022.11.29.22.25.00.release-2.28.x

stack.yml
armory/gate-armory:2022.12.01.03.50.54.release-2.28.x
[65bdd30238312bbca2dce613825eda7ae88f1dfa](https://github.com/armory-io/gate-armory/commit/65bdd30238312bbca2dce613825eda7ae88f1dfa)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:f8e03bbacca701c8bf297c5d0ba47cfb181fca05bd92055d9a3fb52ac10fef6e",
"tag": "2022.12.01.03.50.54.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "65bdd30238312bbca2dce613825eda7ae88f1dfa"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update gate-armory version to 2022.12.01.03.50.54.release-2.28.x

stack.yml
armory/orca-armory:2022.11.27.20.26.41.release-2.28.x
[76fe72a46566bb404eb4db4c842ecb0775c546bf](https://github.com/armory-io/orca-armory/commit/76fe72a46566bb404eb4db4c842ecb0775c546bf)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:095e67052dd638394036284875be872757e7fa46031269d701ed9f963ec22c29",
"tag": "2022.11.27.20.26.41.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "76fe72a46566bb404eb4db4c842ecb0775c546bf"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update orca-armory version to 2022.11.27.20.26.41.release-2.28.x

stack.yml
armory/terraformer:2022.11.25.15.53.33.release-2.27.x
[dce62750a6b8046bcc7b55c289980898954e9fa1](https://github.com/armory-io/terraformer/commit/dce62750a6b8046bcc7b55c289980898954e9fa1)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:2aeb20cd5828fdcda8c479eeb6dc7ea99b7d0bcf8ab4909c931d50d81a0ea2fc",
"tag": "2022.11.25.15.53.33.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "dce62750a6b8046bcc7b55c289980898954e9fa1"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2022.11.25.15.53.33.release-2.27.x

stack.yml
armory/igor-armory:2022.11.29.22.27.51.release-2.27.x
[9e2d7946da19c803eb0bd12e888c5119528a364c](https://github.com/armory-io/igor-armory/commit/9e2d7946da19c803eb0bd12e888c5119528a364c)
[6fa3a871011d2baa1c42cd5457b7ba5d83654e70](https://github.com/spinnaker/igor/commit/6fa3a871011d2baa1c42cd5457b7ba5d83654e70)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "6fa3a871011d2baa1c42cd5457b7ba5d83654e70"
},
"details": {
"image": {
"imageId": "sha256:9ca029ceb8543f21840b39b6c1de2f479ff32dd07d57b7c51a5b1b3b5b0c128e",
"tag": "2022.11.29.22.27.51.release-2.27.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update igor-armory version to 2022.11.29.22.27.51.release-2.27.x

stack.yml
armory/echo-armory:2022.12.06.20.33.41.release-2.28.x
[6d4e4ae054b7a13050a1d271b3c771a790e27fc6](https://github.com/armory-io/echo-armory/commit/6d4e4ae054b7a13050a1d271b3c771a790e27fc6)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:d68d89642440483b824ae20361e1095a13245112c52cfc0e260d073449c6e0c3",
"tag": "2022.12.06.20.33.41.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "6d4e4ae054b7a13050a1d271b3c771a790e27fc6"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update echo-armory version to 2022.12.06.20.33.41.release-2.28.x

stack.yml
armory/terraformer:2022.12.07.20.46.23.release-2.28.x
[57c6a9a72d4cfccb7caf229e360fa7f17410afea](https://github.com/armory-io/terraformer/commit/57c6a9a72d4cfccb7caf229e360fa7f17410afea)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:c362bbc42e0366eb502f9b6b363581d3675529dfddb36d86bd028010beb8eb99",
"tag": "2022.12.07.20.46.23.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "57c6a9a72d4cfccb7caf229e360fa7f17410afea"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2022.12.07.20.46.23.release-2.28.x

stack.yml
armory/dinghy:2022.12.08.13.48.09.release-2.28.x
[c4ed5b19dbcfefe8dea14cdff7df9a8ab540eba3](https://github.com/armory-io/dinghy/commit/c4ed5b19dbcfefe8dea14cdff7df9a8ab540eba3)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:a8f210423b9b1ceec1827fc184c9b298fbdb55fcd5f6f841bb1a354c71c5c1cd",
"tag": "2022.12.08.13.48.09.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "c4ed5b19dbcfefe8dea14cdff7df9a8ab540eba3"
}
},
},
"details": {
"image": {
"imageId": "sha256:a8f210423b9b1ceec1827fc184c9b298fbdb55fcd5f6f841bb1a354c71c5c1cd", …
```
=> chore(cd): update dinghy version to 2022.12.08.13.48.09.release-2.28.x

stack.yml
armory/terraformer:2022.12.14.21.17.39.release-2.27.x
[c0ee8b6f421a42e451b7016298365e493be5dd89](https://github.com/armory-io/terraformer/commit/c0ee8b6f421a42e451b7016298365e493be5dd89)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:9ff21004515623b711c86ac1c8487f45a0e51a04711b7b1bfc926d28736621cf",
"tag": "2022.12.14.21.17.39.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "c0ee8b6f421a42e451b7016298365e493be5dd89"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2022.12.14.21.17.39.release-2.27.x

stack.yml
armory/terraformer:2022.12.14.20.52.44.release-2.28.x
[0d18998cb4790dd4857d79e318d873450bd5975d](https://github.com/armory-io/terraformer/commit/0d18998cb4790dd4857d79e318d873450bd5975d)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:9d425ad59a69f3f303005661d1ec783631a0fc4c68c5db8402ad9af1b743b16b",
"tag": "2022.12.14.20.52.44.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "0d18998cb4790dd4857d79e318d873450bd5975d"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2022.12.14.20.52.44.release-2.28.x

stack.yml
Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:c66fe5557f46f25b5e7b2a7c75f1993a748ca4dfff1470f636836152ced5fcc3",
"tag": "2022.10.27.16.41.18.master"
},
"vcs": {
"repo": {
},
"sha": "505015ac9d2539290af87e9a1e234827905db645"
}
},
},
"details": {
"image": {
"imageId": "sha256:c66fe5557f46f25b5e7b2a7c75f1993a748ca4dfff1470f636836152ced5fcc3",
"tag": "2022.10.27.16.41.18.master"
},
"vcs": {
"repo": {
},
"sha": "505015ac9d2539290af87e9a1e234827905db645"
}
},
},
"stackFile": …
```
=> chore(cd): update dinghy version to 2022.10.27.16.41.18.master

stack.yml
* **master**
armory/terraformer:2022.12.13.18.29.41.master
[a839a3b78d5240564d15ca7525c49f1461a66b88](https://github.com/armory-io/terraformer/commit/a839a3b78d5240564d15ca7525c49f1461a66b88)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:35c5adcccd1fb758fc9bd8fc9cb9a4cd81bcd3b8ff8b693b178ddb6320b51193",
"tag": "2022.12.13.18.29.41.master"
},
"vcs": {
"repo": {
},
"sha": "a839a3b78d5240564d15ca7525c49f1461a66b88"
}
},
},
"details": {
"image": {
"imageId": "sha256:35c5adcccd1fb758fc9bd8fc9cb9a4cd81bcd3b8ff8b693b178ddb6320b51193", …
```
=> chore(cd): update terraformer version to 2022.12.13.18.29.41.master

stack.yml
armory/terraformer:2023.01.05.17.37.14.release-2.27.x
[f845ba2fc760c46b98794a10c32cc2b713c7c9e0](https://github.com/armory-io/terraformer/commit/f845ba2fc760c46b98794a10c32cc2b713c7c9e0)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:082054c1344df4d2e3bf137f3ee4e821a9850e6ab40b0bbb87446900d30d4167",
"tag": "2023.01.05.17.37.14.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "f845ba2fc760c46b98794a10c32cc2b713c7c9e0"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2023.01.05.17.37.14.release-2.27.x

stack.yml
armory/terraformer:2023.01.05.17.37.01.release-2.28.x
[3764e523e17dfdd4cf309dc2bd7c13d9b804f309](https://github.com/armory-io/terraformer/commit/3764e523e17dfdd4cf309dc2bd7c13d9b804f309)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:8bf86f7296b153e1d8c80a5819ee430b2753e0061e21919d391c615ab6e1bb5f",
"tag": "2023.01.05.17.37.01.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "3764e523e17dfdd4cf309dc2bd7c13d9b804f309"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2023.01.05.17.37.01.release-2.28.x

stack.yml
* **master**
armory/terraformer:2023.01.05.16.17.47.master
[418546f57129380e383e62b6178ed582e6d64a93](https://github.com/armory-io/terraformer/commit/418546f57129380e383e62b6178ed582e6d64a93)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:4b445cd48893742a41444f8bdee91cb5ce3ba49d3d9c8d4f1d496b03bc3f3ff6",
"tag": "2023.01.05.16.17.47.master"
},
"vcs": {
"repo": {
},
"sha": "418546f57129380e383e62b6178ed582e6d64a93"
}
},
},
"details": {
"image": {
"imageId": "sha256:4b445cd48893742a41444f8bdee91cb5ce3ba49d3d9c8d4f1d496b03bc3f3ff6", …
```
=> chore(cd): update terraformer version to 2023.01.05.16.17.47.master

stack.yml
armory/echo-armory:2023.01.20.15.00.33.release-2.27.x
[3204f90e951562245c62430d863617c34b3a0826](https://github.com/armory-io/echo-armory/commit/3204f90e951562245c62430d863617c34b3a0826)
[4e1eca563bd606268d3aacac528089a32ac88c3c](https://github.com/spinnaker/echo/commit/4e1eca563bd606268d3aacac528089a32ac88c3c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4e1eca563bd606268d3aacac528089a32ac88c3c"
},
"details": {
"image": {
"imageId": "sha256:66c27d6ec7b15c90d6ec76cc0492fb280a883fa32f445bd8e3a540fe3777ab7b",
"tag": "2023.01.20.15.00.33.release-2.27.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2023.01.20.15.00.33.release-2.27.x

stack.yml
armory/fiat-armory:2023.02.07.19.28.59.release-2.29.x
[dc7f3f901e1dae91858e3afe8cf767eae3b91d08](https://github.com/armory-io/fiat-armory/commit/dc7f3f901e1dae91858e3afe8cf767eae3b91d08)
[6d9f5050840c48040edb6435c7a22640412092c7](https://github.com/spinnaker/fiat/commit/6d9f5050840c48040edb6435c7a22640412092c7)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "6d9f5050840c48040edb6435c7a22640412092c7"
},
"details": {
"image": {
"imageId": "sha256:4d0c4dd25227a0b0807a9254d90614547df20a4ebbdbc631167d45ac8d51ab14",
"tag": "2023.02.07.19.28.59.release-2.29.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update fiat-armory version to 2023.02.07.19.28.59.release-2.29.x

stack.yml
* **master**
armory/clouddriver-armory:2023.02.25.00.41.05.master
[6566d73edd731789f8e50b503e3308efe2a76da0](https://github.com/armory-io/clouddriver-armory/commit/6566d73edd731789f8e50b503e3308efe2a76da0)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:a35cb910b0becc05df04364e6aa64184d2fa53257283cd6e4cd9ec98bf5ea845",
"tag": "2023.02.25.00.41.05.master"
},
"vcs": {
"repo": {
},
"sha": "6566d73edd731789f8e50b503e3308efe2a76da0"
}
},
},
"details": {
"image": …
```
=> chore(cd): update clouddriver-armory version to 2023.02.25.00.41.05.master

stack.yml
armory/fiat-armory:2023.02.28.17.55.33.release-2.27.x
[7ed71b06139518397611f2d78d3f9280b104ef9b](https://github.com/armory-io/fiat-armory/commit/7ed71b06139518397611f2d78d3f9280b104ef9b)
[a52e5a984012d103e13c25beeaf9fa9922a5e916](https://github.com/spinnaker/fiat/commit/a52e5a984012d103e13c25beeaf9fa9922a5e916)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a52e5a984012d103e13c25beeaf9fa9922a5e916"
},
"details": {
"image": {
"imageId": "sha256:eff229fdbd1cb1befe8e8d9e49f52551caf0075c91e3f89e0495f4ef147a6add",
"tag": "2023.02.28.17.55.33.release-2.27.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update fiat-armory version to 2023.02.28.17.55.33.release-2.27.x

stack.yml
armory/echo-armory:2023.02.28.19.33.40.release-2.27.x
[b220bcaa01be72ca2c4489203bc5ceb53d83e8af](https://github.com/armory-io/echo-armory/commit/b220bcaa01be72ca2c4489203bc5ceb53d83e8af)
[eef351c8484cc1146aacc43cc3b19ff5f33e3e0e](https://github.com/spinnaker/echo/commit/eef351c8484cc1146aacc43cc3b19ff5f33e3e0e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "eef351c8484cc1146aacc43cc3b19ff5f33e3e0e"
},
"details": {
"image": {
"imageId": "sha256:083b4feee6c7b5d0cbd68eaa9ccb0b06abcd08a4419217908831cf3971f7ec7f",
"tag": "2023.02.28.19.33.40.release-2.27.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2023.02.28.19.33.40.release-2.27.x

stack.yml
armory/echo-armory:2023.01.20.14.59.05.release-2.29.x
[543bd846ecb93ec1684f260c0d2d8c5f7c18d83f](https://github.com/armory-io/echo-armory/commit/543bd846ecb93ec1684f260c0d2d8c5f7c18d83f)
[d764c8d34281450c4a6d39789e78e89c8ee74e86](https://github.com/spinnaker/echo/commit/d764c8d34281450c4a6d39789e78e89c8ee74e86)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d764c8d34281450c4a6d39789e78e89c8ee74e86"
},
"details": {
"image": {
"imageId": "sha256:e36a658aa72749917fbf53d3c0457fd8eeb7c497c5d547d690eb30bc5b0f2494",
"tag": "2023.01.20.14.59.05.release-2.29.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2023.01.20.14.59.05.release-2.29.x

stack.yml
armory/echo-armory:2023.03.06.21.34.45.release-2.29.x
[e70179cff8436d11e8ea3009dc4874536a464592](https://github.com/armory-io/echo-armory/commit/e70179cff8436d11e8ea3009dc4874536a464592)
[20599741b9b23b3a973588b6abf782cc9a08705d](https://github.com/spinnaker/echo/commit/20599741b9b23b3a973588b6abf782cc9a08705d)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "20599741b9b23b3a973588b6abf782cc9a08705d"
},
"details": {
"image": {
"imageId": "sha256:b614ca221907b680b8f3930ba91136abe94a22a306be7d70575a8f3fe038d4be",
"tag": "2023.03.06.21.34.45.release-2.29.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2023.03.06.21.34.45.release-2.29.x

stack.yml
armory/front50-armory:2023.01.11.00.11.56.release-2.29.x
[5a957be754e0a61fc5b69e67cba6089768722b20](https://github.com/armory-io/front50-armory/commit/5a957be754e0a61fc5b69e67cba6089768722b20)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:5312299a0f13fe3804e7da4a5787fa08378230afe3d2be5de31b3448e1cd793f",
"tag": "2023.01.11.00.11.56.release-2.29.x"
},
"vcs": {
"repo": {
},
"sha": "5a957be754e0a61fc5b69e67cba6089768722b20"
}
},
},
"details": { …
```
=> chore(cd): update front50-armory version to 2023.01.11.00.11.56.release-2.29.x

stack.yml
armory/gate-armory:2023.01.11.00.11.13.release-2.29.x
[437065ccf4815f0349d22ff6d4fcb71b648847b0](https://github.com/armory-io/gate-armory/commit/437065ccf4815f0349d22ff6d4fcb71b648847b0)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:ed8ca9c070934d8782be6f457dd5e70d20579ec7fb021696ddfe03854361e109",
"tag": "2023.01.11.00.11.13.release-2.29.x"
},
"vcs": {
"repo": {
},
"sha": "437065ccf4815f0349d22ff6d4fcb71b648847b0"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update gate-armory version to 2023.01.11.00.11.13.release-2.29.x

stack.yml
armory/igor-armory:2022.09.14.16.39.54.release-2.29.x
[3c9dd843c3eddbfaa529f054b2df73de938391ca](https://github.com/armory-io/igor-armory/commit/3c9dd843c3eddbfaa529f054b2df73de938391ca)
[a6933b6ec4e53b65221715831f3b1a8f74696e3f](https://github.com/spinnaker/igor/commit/a6933b6ec4e53b65221715831f3b1a8f74696e3f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a6933b6ec4e53b65221715831f3b1a8f74696e3f"
},
"details": {
"image": {
"imageId": "sha256:9ffc2b3de93ed9620d9c5013e59067d5ffad20783be79a09dc56d174fa8d6ec3",
"tag": "2022.09.14.16.39.54.release-2.29.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update igor-armory version to 2022.09.14.16.39.54.release-2.29.x

stack.yml
armory/dinghy:2023.03.06.08.27.31.release-2.27.x
[4724296b0bece7ee155252c65f097d0cbe374acd](https://github.com/armory-io/dinghy/commit/4724296b0bece7ee155252c65f097d0cbe374acd)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:ee0b1ac95d4cee35baf5a773be9ddeccb45221c928f4c2c3725e4874437937cf",
"tag": "2023.03.06.08.27.31.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "4724296b0bece7ee155252c65f097d0cbe374acd"
}
},
},
"details": {
"image": {
"imageId": "sha256:ee0b1ac95d4cee35baf5a773be9ddeccb45221c928f4c2c3725e4874437937cf", …
```
=> chore(cd): update dinghy version to 2023.03.06.08.27.31.release-2.27.x

stack.yml
armory/fiat-armory:2023.03.02.20.07.45.release-2.28.x
[cf7ec371ff8850b4fe9ee01b4deaeb0ffbd0b321](https://github.com/armory-io/fiat-armory/commit/cf7ec371ff8850b4fe9ee01b4deaeb0ffbd0b321)
[3008028984f2870331aeb79c3ac56475a81f3d08](https://github.com/spinnaker/fiat/commit/3008028984f2870331aeb79c3ac56475a81f3d08)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "3008028984f2870331aeb79c3ac56475a81f3d08"
},
"details": {
"image": {
"imageId": "sha256:70d8a3893110c366ff4ba73093e2d59f041dc7dc1d3f6ec59237f2d265230b35",
"tag": "2023.03.02.20.07.45.release-2.28.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update fiat-armory version to 2023.03.02.20.07.45.release-2.28.x

stack.yml
armory/terraformer:2023.03.15.01.36.31.release-2.27.x
[736ece67b4a52a612262cbe844d1edd3ad176d19](https://github.com/armory-io/terraformer/commit/736ece67b4a52a612262cbe844d1edd3ad176d19)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:24f00b24e02b72f0344544d7731f509c096b1a6bf14ef34278f14c256edfb1e8",
"tag": "2023.03.15.01.36.31.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "736ece67b4a52a612262cbe844d1edd3ad176d19"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2023.03.15.01.36.31.release-2.27.x

stack.yml
armory/terraformer:2023.03.15.01.36.09.release-2.28.x
[ea9b0255b7d446bcbf0f0d4e03fc8699b7508431](https://github.com/armory-io/terraformer/commit/ea9b0255b7d446bcbf0f0d4e03fc8699b7508431)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:bdc895d272fa3064cf48b00031851e42710c3dd4e865d30f25f69aa8267f746b",
"tag": "2023.03.15.01.36.09.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "ea9b0255b7d446bcbf0f0d4e03fc8699b7508431"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2023.03.15.01.36.09.release-2.28.x

stack.yml
armory/fiat-armory:2023.03.16.18.14.54.release-2.27.x
[e23c8b8a65463100c7075b1aacc140a0e0dc5216](https://github.com/armory-io/fiat-armory/commit/e23c8b8a65463100c7075b1aacc140a0e0dc5216)
[19e4ef2d02fdfee439582ab11ed5a938bd4cd918](https://github.com/spinnaker/fiat/commit/19e4ef2d02fdfee439582ab11ed5a938bd4cd918)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "19e4ef2d02fdfee439582ab11ed5a938bd4cd918"
},
"details": {
"image": {
"imageId": "sha256:392412bf1775903309a8096037dae167537591ae9d47ebd37e22d193ff62ef3d",
"tag": "2023.03.16.18.14.54.release-2.27.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update fiat-armory version to 2023.03.16.18.14.54.release-2.27.x

stack.yml
armory/echo-armory:2023.03.27.19.27.26.release-2.28.x
[8b763d646f1a52db3a9de33acf4e7e420220c3e0](https://github.com/armory-io/echo-armory/commit/8b763d646f1a52db3a9de33acf4e7e420220c3e0)
[0957fef998ff136e04db59a5371780d5f0b8a9ca](https://github.com/spinnaker/echo/commit/0957fef998ff136e04db59a5371780d5f0b8a9ca)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0957fef998ff136e04db59a5371780d5f0b8a9ca"
},
"details": {
"image": {
"imageId": "sha256:616267cdc5496e89be03c86caaeef8d3bc5d8b3ce163eb692a82e936fcbc0bee",
"tag": "2023.03.27.19.27.26.release-2.28.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2023.03.27.19.27.26.release-2.28.x

stack.yml
armory/terraformer:2023.01.05.16.17.47.release-2.30.x
[418546f57129380e383e62b6178ed582e6d64a93](https://github.com/armory-io/terraformer/commit/418546f57129380e383e62b6178ed582e6d64a93)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:f7529582852992f1144118c0da7d099b1cb3c13c587e0dd065480769b7ca2184",
"tag": "2023.01.05.16.17.47.release-2.30.x"
},
"vcs": {
"repo": {
},
"sha": "418546f57129380e383e62b6178ed582e6d64a93"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2023.01.05.16.17.47.release-2.30.x

stack.yml
armory/gate-armory:2023.04.13.18.44.50.release-2.28.x
[c8058f4362f3f4ad108fa146d628a162445c7579](https://github.com/armory-io/gate-armory/commit/c8058f4362f3f4ad108fa146d628a162445c7579)
[228b57f7b40dd2d9711964c73e34ebb50603459d](https://github.com/spinnaker/gate/commit/228b57f7b40dd2d9711964c73e34ebb50603459d)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "228b57f7b40dd2d9711964c73e34ebb50603459d"
},
"details": {
"image": {
"imageId": "sha256:eae3e5de9e13fc5c5d5ec1a7e797b51d4ad3a996eac11fb45c3b687a61abfcb1",
"tag": "2023.04.13.18.44.50.release-2.28.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update gate-armory version to 2023.04.13.18.44.50.release-2.28.x

stack.yml
armory/fiat-armory:2023.04.13.18.27.26.release-2.30.x
[d17990ac98c2755dfbc593517280538d4e1e28b1](https://github.com/armory-io/fiat-armory/commit/d17990ac98c2755dfbc593517280538d4e1e28b1)
[8bf74c283b426496e864e27e567a9ea7de41155e](https://github.com/spinnaker/fiat/commit/8bf74c283b426496e864e27e567a9ea7de41155e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "8bf74c283b426496e864e27e567a9ea7de41155e"
},
"details": {
"image": {
"imageId": "sha256:b0cb295813ab6634241da3b13f041e847b2cd39bfc8f70c3d8a136b877955407",
"tag": "2023.04.13.18.27.26.release-2.30.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update fiat-armory version to 2023.04.13.18.27.26.release-2.30.x

stack.yml
armory/deck-armory:2023.04.15.02.43.25.release-2.28.x
[910b555c6249c2b71571040e86c7c1ddb8a79530](https://github.com/armory-io/deck-armory/commit/910b555c6249c2b71571040e86c7c1ddb8a79530)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:c11b03df0abd372d31214aa4d012ec91c59c5c615ab639dd0b0e5d380b03f085",
"tag": "2023.04.15.02.43.25.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "910b555c6249c2b71571040e86c7c1ddb8a79530"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update deck-armory version to 2023.04.15.02.43.25.release-2.28.x

stack.yml
armory/fiat-armory:2023.04.17.16.44.07.release-2.29.x
[e0b59e6b100086821e8185eea2fcbd084f8c8191](https://github.com/armory-io/fiat-armory/commit/e0b59e6b100086821e8185eea2fcbd084f8c8191)
[51fa0be1990264aef1670241a1a22e62f9a6268c](https://github.com/spinnaker/fiat/commit/51fa0be1990264aef1670241a1a22e62f9a6268c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "51fa0be1990264aef1670241a1a22e62f9a6268c"
},
"details": {
"image": {
"imageId": "sha256:ab965714bae9cefe67675c72d9880ba17963b31c89cf9cddfe7881c17da6123f",
"tag": "2023.04.17.16.44.07.release-2.29.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update fiat-armory version to 2023.04.17.16.44.07.release-2.29.x

stack.yml
armory/igor-armory:2023.04.20.21.55.48.release-2.28.x
[00998fa8b33acd6db5ffa8722e37593f608e9f64](https://github.com/armory-io/igor-armory/commit/00998fa8b33acd6db5ffa8722e37593f608e9f64)
[ac7fa51e55855967c04f021aeaad252d38a55b50](https://github.com/spinnaker/igor/commit/ac7fa51e55855967c04f021aeaad252d38a55b50)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "ac7fa51e55855967c04f021aeaad252d38a55b50"
},
"details": {
"image": {
"imageId": "sha256:2be87fc6527c238f4034b1272c531479e0192039fbcdf78afdb9766fb86c8461",
"tag": "2023.04.20.21.55.48.release-2.28.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update igor-armory version to 2023.04.20.21.55.48.release-2.28.x

stack.yml
armory/deck-armory:2023.05.01.05.50.20.release-2.28.x
[5e7cef7a443e096cf8158c0c405c3ebbf8b97c35](https://github.com/armory-io/deck-armory/commit/5e7cef7a443e096cf8158c0c405c3ebbf8b97c35)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:87ee380c047e59168d71411e1b26adcf8823bb65b63ec03ef5c10fbdb1812692",
"tag": "2023.05.01.05.50.20.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "5e7cef7a443e096cf8158c0c405c3ebbf8b97c35"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update deck-armory version to 2023.05.01.05.50.20.release-2.28.x

stack.yml
armory/igor-armory:2023.05.12.15.23.43.release-2.30.x
[020e01bbeaadf3d5eb745b33180bd1011c4b068f](https://github.com/armory-io/igor-armory/commit/020e01bbeaadf3d5eb745b33180bd1011c4b068f)
[d77263d8c7805bb0269340b02ac5ceb1b198e806](https://github.com/spinnaker/igor/commit/d77263d8c7805bb0269340b02ac5ceb1b198e806)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d77263d8c7805bb0269340b02ac5ceb1b198e806"
},
"details": {
"image": {
"imageId": "sha256:a0d5aab8e48affd69a374b686aa761a9db71972398b6344be1b76ab42d71bd47",
"tag": "2023.05.12.15.23.43.release-2.30.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update igor-armory version to 2023.05.12.15.23.43.release-2.30.x

stack.yml
* **master**
armory/terraformer:2023.03.14.19.56.35.master
[d98a6ad23678ed1b931297104c3102b3e363c5a1](https://github.com/armory-io/terraformer/commit/d98a6ad23678ed1b931297104c3102b3e363c5a1)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:307fed4911699ad124d3f43c0394766e723c696a03eee43a9df726412119ad4a",
"tag": "2023.03.14.19.56.35.master"
},
"vcs": {
"repo": {
},
"sha": "d98a6ad23678ed1b931297104c3102b3e363c5a1"
}
},
},
"details": {
"image": {
"imageId": "sha256:307fed4911699ad124d3f43c0394766e723c696a03eee43a9df726412119ad4a", …
```
=> chore(cd): update terraformer version to 2023.03.14.19.56.35.master

stack.yml
armory/fiat-armory:2023.03.29.19.04.20.release-2.27.x
[324ccf891901e8318cb5d32d73bc0e0f789b61cf](https://github.com/armory-io/fiat-armory/commit/324ccf891901e8318cb5d32d73bc0e0f789b61cf)
[19e4ef2d02fdfee439582ab11ed5a938bd4cd918](https://github.com/spinnaker/fiat/commit/19e4ef2d02fdfee439582ab11ed5a938bd4cd918)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "19e4ef2d02fdfee439582ab11ed5a938bd4cd918"
},
"details": {
"image": {
"imageId": "sha256:095be09b0ccc7754892ccc4cfc1dbcfb941493673f263899dc92817e9a1b2226",
"tag": "2023.03.29.19.04.20.release-2.27.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update fiat-armory version to 2023.03.29.19.04.20.release-2.27.x

stack.yml
armory/igor-armory:2023.04.01.01.42.54.release-2.27.x
[55ba9b573ddebf772a92feda5a8bc6bacb4dfc92](https://github.com/armory-io/igor-armory/commit/55ba9b573ddebf772a92feda5a8bc6bacb4dfc92)
[11b9dcd10cd2d96b0852a66212075c2f0b77ddcd](https://github.com/spinnaker/igor/commit/11b9dcd10cd2d96b0852a66212075c2f0b77ddcd)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "11b9dcd10cd2d96b0852a66212075c2f0b77ddcd"
},
"details": {
"image": {
"imageId": "sha256:1bd89072bb7a5077eac8d4c81aa17b100abb8f4c9ea09dea9523f3caae257ff5",
"tag": "2023.04.01.01.42.54.release-2.27.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update igor-armory version to 2023.04.01.01.42.54.release-2.27.x

stack.yml
armory/echo-armory:2023.06.27.09.55.53.release-2.30.x
[f7ae187ab1df1e0bc34596e24539c4032749f8d7](https://github.com/armory-io/echo-armory/commit/f7ae187ab1df1e0bc34596e24539c4032749f8d7)
[43d436386e855b884577e7df652e7778818ef0cd](https://github.com/spinnaker/echo/commit/43d436386e855b884577e7df652e7778818ef0cd)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "43d436386e855b884577e7df652e7778818ef0cd"
},
"details": {
"image": {
"imageId": "sha256:1826d7e3b1b50da70167fa5836a05bd07ba68879b18f98d372f07b7c5754d4a4",
"tag": "2023.06.27.09.55.53.release-2.30.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2023.06.27.09.55.53.release-2.30.x

stack.yml
armory/terraformer:2023.03.14.19.56.35.release-2.31.x
[d98a6ad23678ed1b931297104c3102b3e363c5a1](https://github.com/armory-io/terraformer/commit/d98a6ad23678ed1b931297104c3102b3e363c5a1)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:b512dc0127171f42152993a4d82c4b3b300d07e9e4f541739cc11a1908027280",
"tag": "2023.03.14.19.56.35.release-2.31.x"
},
"vcs": {
"repo": {
},
"sha": "d98a6ad23678ed1b931297104c3102b3e363c5a1"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2023.03.14.19.56.35.release-2.31.x

stack.yml
armory/terraformer:2023.08.16.21.22.42.release-2.30.x
[650746ae3f596f9c6458987487c81840c85dd2a0](https://github.com/armory-io/terraformer/commit/650746ae3f596f9c6458987487c81840c85dd2a0)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:8ab46f3b42105417e326cc06abbb9fc89af0e634cb16de1b3de2ab05e031241c",
"tag": "2023.08.16.21.22.42.release-2.30.x"
},
"vcs": {
"repo": {
},
"sha": "650746ae3f596f9c6458987487c81840c85dd2a0"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2023.08.16.21.22.42.release-2.30.x

stack.yml
armory/echo-armory:2023.09.21.17.06.47.release-2.30.x
[2ef241fd3da29fb70cdb05432d022f0edd752d51](https://github.com/armory-io/echo-armory/commit/2ef241fd3da29fb70cdb05432d022f0edd752d51)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:7013e32a8d95188e1b51ba104d02b75c0b3af6f0bba9fe4436c5c34f895d514e",
"tag": "2023.09.21.17.06.47.release-2.30.x"
},
"vcs": {
"repo": {
},
"sha": "2ef241fd3da29fb70cdb05432d022f0edd752d51"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update echo-armory version to 2023.09.21.17.06.47.release-2.30.x

stack.yml
armory/terraformer:2023.09.25.19.21.02.release-2.30.x
[249e7be18074af100212ddd554d9fb35afd65873](https://github.com/armory-io/terraformer/commit/249e7be18074af100212ddd554d9fb35afd65873)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:0978f34169f374128e0b7741e1b9cafb1366bc0e11837cac0fac5ed3aeebd279",
"tag": "2023.09.25.19.21.02.release-2.30.x"
},
"vcs": {
"repo": {
},
"sha": "249e7be18074af100212ddd554d9fb35afd65873"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2023.09.25.19.21.02.release-2.30.x

stack.yml
armory/igor-armory:2023.09.21.18.02.34.release-2.30.x
[f3d890427c79b7db6cf5fcb681e30542df97ff7c](https://github.com/armory-io/igor-armory/commit/f3d890427c79b7db6cf5fcb681e30542df97ff7c)
[4349ba154c386db91a828b928e97b53567e15a03](https://github.com/spinnaker/igor/commit/4349ba154c386db91a828b928e97b53567e15a03)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4349ba154c386db91a828b928e97b53567e15a03"
},
"details": {
"image": {
"imageId": "sha256:baf1d3382eda24f19e65e4cdd663f890e12ebd06d8a29a4f057faa6746f82b1a",
"tag": "2023.09.21.18.02.34.release-2.30.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update igor-armory version to 2023.09.21.18.02.34.release-2.30.x

stack.yml
* **master**
armory/front50-armory:2023.10.01.17.36.02.master
[ce56ccc4b2e509dd28331391766a656e3e7b1d69](https://github.com/armory-io/front50-armory/commit/ce56ccc4b2e509dd28331391766a656e3e7b1d69)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:634073ad49ac580f4f184fc68cccb05c096ae056b73e95237e337ed154b1d0f4",
"tag": "2023.10.01.17.36.02.master"
},
"vcs": {
"repo": {
},
"sha": "ce56ccc4b2e509dd28331391766a656e3e7b1d69"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update front50-armory version to 2023.10.01.17.36.02.master

stack.yml
* **master**
armory/terraformer:2023.09.28.21.40.45.master
[116e4e5973a03d341c43f4b460e2520dbdc72c36](https://github.com/armory-io/terraformer/commit/116e4e5973a03d341c43f4b460e2520dbdc72c36)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:c381756934162233635e0b6dc3b015882660dbc98c32f37fdb91b77fda705b58",
"tag": "2023.09.28.21.40.45.master"
},
"vcs": {
"repo": {
},
"sha": "116e4e5973a03d341c43f4b460e2520dbdc72c36"
}
},
},
"details": {
"image": {
"imageId": "sha256:c381756934162233635e0b6dc3b015882660dbc98c32f37fdb91b77fda705b58", …
```
=> chore(cd): update terraformer version to 2023.09.28.21.40.45.master

stack.yml
armory/gate-armory:2023.09.21.17.51.18.release-2.28.x
[9577f3887731db748c24cb732fd91e5b840332ce](https://github.com/armory-io/gate-armory/commit/9577f3887731db748c24cb732fd91e5b840332ce)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:28e16ff89f648fb108eb050a9a8b372b30d14d57c1986a900b8aec27acd84369",
"tag": "2023.09.21.17.51.18.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "9577f3887731db748c24cb732fd91e5b840332ce"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update gate-armory version to 2023.09.21.17.51.18.release-2.28.x

stack.yml
armory/terraformer:2023.09.25.18.42.38.release-2.31.x
[30d6e5f1f249df9d543f4e1e4738c1af59a53e8e](https://github.com/armory-io/terraformer/commit/30d6e5f1f249df9d543f4e1e4738c1af59a53e8e)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:6cea63e2d39454f4aae6eb7464432cfca2f338de64ba3863e2d73dd8ed99bea3",
"tag": "2023.09.25.18.42.38.release-2.31.x"
},
"vcs": {
"repo": {
},
"sha": "30d6e5f1f249df9d543f4e1e4738c1af59a53e8e"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2023.09.25.18.42.38.release-2.31.x

stack.yml
armory/terraformer:2023.09.25.19.21.30.release-2.28.x
[c5a362b8f3cbad67827efd307031be9ebd411742](https://github.com/armory-io/terraformer/commit/c5a362b8f3cbad67827efd307031be9ebd411742)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:874f70d53843c394c80ff32124c4a0cc87766930dcca6f874b2b2008d3432c7b",
"tag": "2023.09.25.19.21.30.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "c5a362b8f3cbad67827efd307031be9ebd411742"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2023.09.25.19.21.30.release-2.28.x

stack.yml
armory/echo-armory:2023.09.21.17.08.46.release-2.28.x
[f1b4d847d55595bdef347f77ddab33cf81c6a8c9](https://github.com/armory-io/echo-armory/commit/f1b4d847d55595bdef347f77ddab33cf81c6a8c9)
[0957fef998ff136e04db59a5371780d5f0b8a9ca](https://github.com/spinnaker/echo/commit/0957fef998ff136e04db59a5371780d5f0b8a9ca)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0957fef998ff136e04db59a5371780d5f0b8a9ca"
},
"details": {
"image": {
"imageId": "sha256:a6469de4e241cbdc1c482ea99645ad97817a4f6bb8e74a1a935cd6251f1ecd9d",
"tag": "2023.09.21.17.08.46.release-2.28.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2023.09.21.17.08.46.release-2.28.x

stack.yml
armory/deck-armory:2023.09.21.16.43.10.release-2.27.x
[65392dbd3ea90f0568653398a71c67d479892c90](https://github.com/armory-io/deck-armory/commit/65392dbd3ea90f0568653398a71c67d479892c90)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:3f037cc2510e24d6df1ef344041bebc440af244ff02798ffe9a8d7b23ba251eb",
"tag": "2023.09.21.16.43.10.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "65392dbd3ea90f0568653398a71c67d479892c90"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update deck-armory version to 2023.09.21.16.43.10.release-2.27.x

stack.yml
armory/fiat-armory:2023.09.21.17.27.38.release-2.27.x
[9511db53721ba109e58ab1d76a276dc793f5e63c](https://github.com/armory-io/fiat-armory/commit/9511db53721ba109e58ab1d76a276dc793f5e63c)
[19e4ef2d02fdfee439582ab11ed5a938bd4cd918](https://github.com/spinnaker/fiat/commit/19e4ef2d02fdfee439582ab11ed5a938bd4cd918)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "19e4ef2d02fdfee439582ab11ed5a938bd4cd918"
},
"details": {
"image": {
"imageId": "sha256:77aeb219292aea93bf702025d855eb01024da18bc069f3e663d1b6c8386047b2",
"tag": "2023.09.21.17.27.38.release-2.27.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update fiat-armory version to 2023.09.21.17.27.38.release-2.27.x

stack.yml
armory/terraformer:2023.09.25.19.21.38.release-2.27.x
[7c1768198c07996ad3c7452d1295308d85bf1fdc](https://github.com/armory-io/terraformer/commit/7c1768198c07996ad3c7452d1295308d85bf1fdc)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:77fece5b4719535bf23d226e2e1a3f0aa92826d3049ba2e3e421ce058f6318e9",
"tag": "2023.09.25.19.21.38.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "7c1768198c07996ad3c7452d1295308d85bf1fdc"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2023.09.25.19.21.38.release-2.27.x

stack.yml
armory/echo-armory:2023.09.21.17.10.17.release-2.27.x
[b4c9d1ec8acfe22e9f3db1d8fad4f6234e3e5fb0](https://github.com/armory-io/echo-armory/commit/b4c9d1ec8acfe22e9f3db1d8fad4f6234e3e5fb0)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:fb9629fdc4fda72fc6cf82be0fa8416526ac7139c458208d26bdbf1f2223734d",
"tag": "2023.09.21.17.10.17.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "b4c9d1ec8acfe22e9f3db1d8fad4f6234e3e5fb0"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update echo-armory version to 2023.09.21.17.10.17.release-2.27.x

stack.yml
armory/echo-armory:2023.10.11.14.33.25.release-2.31.x
[a2e32fc4b93e5472cc5d09d24a30fb8467fdc7d3](https://github.com/armory-io/echo-armory/commit/a2e32fc4b93e5472cc5d09d24a30fb8467fdc7d3)
[d20da255de1fabb96d67012c8d9bc370ba02982c](https://github.com/spinnaker/echo/commit/d20da255de1fabb96d67012c8d9bc370ba02982c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d20da255de1fabb96d67012c8d9bc370ba02982c"
},
"details": {
"image": {
"imageId": "sha256:0da50f18536aa1af9e682a914ee1474a9d9cca4db597131c257cc8c8e21e3558",
"tag": "2023.10.11.14.33.25.release-2.31.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2023.10.11.14.33.25.release-2.31.x

stack.yml
* **master**
armory/terraformer:2023.10.16.12.47.15.master
[008c470506096dbeb44e8b34ad1fbee2dd20468b](https://github.com/armory-io/terraformer/commit/008c470506096dbeb44e8b34ad1fbee2dd20468b)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:29bdad5c9d91735853c5b50864c0c45a02fbc1b368d6a77a5d078bdfac6c8d9f",
"tag": "2023.10.16.12.47.15.master"
},
"vcs": {
"repo": {
},
"sha": "008c470506096dbeb44e8b34ad1fbee2dd20468b"
}
},
},
"details": {
"image": {
"imageId": "sha256:29bdad5c9d91735853c5b50864c0c45a02fbc1b368d6a77a5d078bdfac6c8d9f", …
```
=> chore(cd): update terraformer version to 2023.10.16.12.47.15.master

stack.yml
armory/terraformer:2023.10.17.12.16.29.release-2.31.x
[50082463ccd180cb4763078671a105ab70dee5e6](https://github.com/armory-io/terraformer/commit/50082463ccd180cb4763078671a105ab70dee5e6)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:be5fa34bdacbf1d1804055339c4685b2a2aa6e0ff4c26121bae7bcaae18b3565",
"tag": "2023.10.17.12.16.29.release-2.31.x"
},
"vcs": {
"repo": {
},
"sha": "50082463ccd180cb4763078671a105ab70dee5e6"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2023.10.17.12.16.29.release-2.31.x

stack.yml
* **master**
armory/terraformer:2023.10.27.17.07.10.master
[163f689d9cc36d701bfb66ac5a0d3b38128d5afa](https://github.com/armory-io/terraformer/commit/163f689d9cc36d701bfb66ac5a0d3b38128d5afa)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:94c508a1ecf42caa4affa04b70e630a82d75060d7d39aae639ccd46836824fe4",
"tag": "2023.10.27.17.07.10.master"
},
"vcs": {
"repo": {
},
"sha": "163f689d9cc36d701bfb66ac5a0d3b38128d5afa"
}
},
},
"details": {
"image": {
"imageId": "sha256:94c508a1ecf42caa4affa04b70e630a82d75060d7d39aae639ccd46836824fe4", …
```
=> chore(cd): update terraformer version to 2023.10.27.17.07.10.master

stack.yml
* **master**
armory/terraformer:2023.11.03.19.38.36.master
[2d16a442fa6db7d7235ed822bff6009a56718077](https://github.com/armory-io/terraformer/commit/2d16a442fa6db7d7235ed822bff6009a56718077)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:fe6d4ab0d455ca3d05db3f2f22b7936baa45a21518d4e003b9c4a24baeccd261",
"tag": "2023.11.03.19.38.36.master"
},
"vcs": {
"repo": {
},
"sha": "2d16a442fa6db7d7235ed822bff6009a56718077"
}
},
},
"details": {
"image": {
"imageId": "sha256:fe6d4ab0d455ca3d05db3f2f22b7936baa45a21518d4e003b9c4a24baeccd261", …
```
=> chore(cd): update terraformer version to 2023.11.03.19.38.36.master

stack.yml
armory/echo-armory:2023.11.02.08.44.16.release-2.30.x
[ea2081903be070da4b217a4c54d070f1503e6d00](https://github.com/armory-io/echo-armory/commit/ea2081903be070da4b217a4c54d070f1503e6d00)
[efecf203dd0bb8a73b7bde3e265004bc8aff41ec](https://github.com/spinnaker/echo/commit/efecf203dd0bb8a73b7bde3e265004bc8aff41ec)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "efecf203dd0bb8a73b7bde3e265004bc8aff41ec"
},
"details": {
"image": {
"imageId": "sha256:84f0a391c190fe10b9566928dac8cf305bf83259bd731905c281fc8b5f51465e",
"tag": "2023.11.02.08.44.16.release-2.30.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2023.11.02.08.44.16.release-2.30.x

stack.yml
armory/terraformer:2023.03.14.19.56.35.release-2.32.x
[d98a6ad23678ed1b931297104c3102b3e363c5a1](https://github.com/armory-io/terraformer/commit/d98a6ad23678ed1b931297104c3102b3e363c5a1)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:a59389cfba1d421251c546c62ca0bab8c7616eef22e2997fe47bac53d8cb08c7",
"tag": "2023.03.14.19.56.35.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "d98a6ad23678ed1b931297104c3102b3e363c5a1"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2023.03.14.19.56.35.release-2.32.x

stack.yml
* **master**
armory/terraformer:2024.01.24.15.06.13.master
[727eb7a467099f28f12cab68930588fb5a6ec0cc](https://github.com/armory-io/terraformer/commit/727eb7a467099f28f12cab68930588fb5a6ec0cc)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:50fe27b5a2bb3b04f464577646ddd79f4f37b3cb5215c136cd2a31cd2aeb4b44",
"tag": "2024.01.24.15.06.13.master"
},
"vcs": {
"repo": {
},
"sha": "727eb7a467099f28f12cab68930588fb5a6ec0cc"
}
},
},
"details": {
"image": {
"imageId": "sha256:50fe27b5a2bb3b04f464577646ddd79f4f37b3cb5215c136cd2a31cd2aeb4b44", …
```
=> chore(cd): update terraformer version to 2024.01.24.15.06.13.master

stack.yml
armory/terraformer:2024.01.26.18.32.22.release-2.32.x
[d13481b3b561dd232adff996f119b95e25a626bc](https://github.com/armory-io/terraformer/commit/d13481b3b561dd232adff996f119b95e25a626bc)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:980035d159374055e44b7b549b0556663ed247f966726450c77c5bf08219a28a",
"tag": "2024.01.26.18.32.22.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "d13481b3b561dd232adff996f119b95e25a626bc"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2024.01.26.18.32.22.release-2.32.x

stack.yml
* **master**
armory/terraformer:2024.01.29.14.46.59.master
[3af8055b100be1c50162e2fa82dd5c4f99471225](https://github.com/armory-io/terraformer/commit/3af8055b100be1c50162e2fa82dd5c4f99471225)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:1506ec5c67610640e8491759bb0dc4ab2d75375185616ec0d3b66758b8459cd5",
"tag": "2024.01.29.14.46.59.master"
},
"vcs": {
"repo": {
},
"sha": "3af8055b100be1c50162e2fa82dd5c4f99471225"
}
},
},
"details": {
"image": {
"imageId": "sha256:1506ec5c67610640e8491759bb0dc4ab2d75375185616ec0d3b66758b8459cd5", …
```
=> chore(cd): update terraformer version to 2024.01.29.14.46.59.master

stack.yml
armory/dinghy:2024.02.02.14.34.21.release-2.32.x
[d08b49a5f8398018ab2a7c98b1706e4632df1684](https://github.com/armory-io/dinghy/commit/d08b49a5f8398018ab2a7c98b1706e4632df1684)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:cd94c892208591a1ae212954ff12777a5bf68e11462a06bae5a5eebdfce4bf01",
"tag": "2024.02.02.14.34.21.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "d08b49a5f8398018ab2a7c98b1706e4632df1684"
}
},
},
"details": {
"image": {
"imageId": "sha256:cd94c892208591a1ae212954ff12777a5bf68e11462a06bae5a5eebdfce4bf01", …
```
=> chore(cd): update dinghy version to 2024.02.02.14.34.21.release-2.32.x

stack.yml
armory/terraformer:2024.02.08.09.11.43.release-2.32.x
[d7d8c38ec7d009b6240a17e1225e9933558cdef4](https://github.com/armory-io/terraformer/commit/d7d8c38ec7d009b6240a17e1225e9933558cdef4)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:bcfdcae3793469dd15101f9dae45f83c5ccfb38cfbd1e6f05e2d000f149fe8d9",
"tag": "2024.02.08.09.11.43.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "d7d8c38ec7d009b6240a17e1225e9933558cdef4"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2024.02.08.09.11.43.release-2.32.x

stack.yml
* **master**
armory/terraformer:2024.02.08.16.14.10.master
[c18c1c5cdb6670fadeb3814d906ad99cabcfcac9](https://github.com/armory-io/terraformer/commit/c18c1c5cdb6670fadeb3814d906ad99cabcfcac9)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:092f0fe5ee1ea1ba893d3733d9f932ba3463ce6866da0c836efb2fe5399e6ef7",
"tag": "2024.02.08.16.14.10.master"
},
"vcs": {
"repo": {
},
"sha": "c18c1c5cdb6670fadeb3814d906ad99cabcfcac9"
}
},
},
"details": {
"image": {
"imageId": "sha256:092f0fe5ee1ea1ba893d3733d9f932ba3463ce6866da0c836efb2fe5399e6ef7", …
```
=> chore(cd): update terraformer version to 2024.02.08.16.14.10.master

stack.yml
armory/terraformer:2024.02.08.17.41.52.release-2.32.x
[58c3386295676fccf44aa9d38c69e1e0482109ca](https://github.com/armory-io/terraformer/commit/58c3386295676fccf44aa9d38c69e1e0482109ca)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:b091f683f9501580a0a15aa5c904b29785f4bc37fabf45f95742ffcbb19c5eed",
"tag": "2024.02.08.17.41.52.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "58c3386295676fccf44aa9d38c69e1e0482109ca"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2024.02.08.17.41.52.release-2.32.x

stack.yml
armory/terraformer:2024.02.19.15.54.39.release-2.32.x
[6dbdb8b4c277cca4285b4d29d10f6cf3765f7590](https://github.com/armory-io/terraformer/commit/6dbdb8b4c277cca4285b4d29d10f6cf3765f7590)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:7e21a53d53ba6b140ee8365c864c0714ce4fd215b69e8239e06ec09d6f7fa0e9",
"tag": "2024.02.19.15.54.39.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "6dbdb8b4c277cca4285b4d29d10f6cf3765f7590"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2024.02.19.15.54.39.release-2.32.x

stack.yml
armory/echo-armory:2024.02.27.15.50.55.release-2.32.x
[5d8f6310d1bb8d931975c107d29862e0e34c8772](https://github.com/armory-io/echo-armory/commit/5d8f6310d1bb8d931975c107d29862e0e34c8772)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:3c6f39c41329cdf7a7fa7b03e1f32e2b8d4723b9a3a5eb50f34c17071e1fb8ae",
"tag": "2024.02.27.15.50.55.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "5d8f6310d1bb8d931975c107d29862e0e34c8772"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update echo-armory version to 2024.02.27.15.50.55.release-2.32.x

stack.yml
armory/fiat-armory:2024.03.08.16.57.58.release-2.32.x
[3f3fe6bf09708847a0f853bc74f6755920a4312b](https://github.com/armory-io/fiat-armory/commit/3f3fe6bf09708847a0f853bc74f6755920a4312b)
[1ba9526d339abecddbf12accfdd4ef9d1d25ce75](https://github.com/spinnaker/fiat/commit/1ba9526d339abecddbf12accfdd4ef9d1d25ce75)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1ba9526d339abecddbf12accfdd4ef9d1d25ce75"
},
"details": {
"image": {
"imageId": "sha256:d898ecf9b1dacaa77444cf8aebc6e26acbb49a9c21cd9dd9e374fdc7c173f581",
"tag": "2024.03.08.16.57.58.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update fiat-armory version to 2024.03.08.16.57.58.release-2.32.x

stack.yml
* **master**
armory/terraformer:2024.02.19.13.02.55.master
[4aa75b62a5862753fbdadb6d8e55618b39e27a0f](https://github.com/armory-io/terraformer/commit/4aa75b62a5862753fbdadb6d8e55618b39e27a0f)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:e1fd639993fe40766241d14a4698d6560ce0e24f796661a1dd17e18150bd55f2",
"tag": "2024.02.19.13.02.55.master"
},
"vcs": {
"repo": {
},
"sha": "4aa75b62a5862753fbdadb6d8e55618b39e27a0f"
}
},
},
"details": {
"image": {
"imageId": "sha256:e1fd639993fe40766241d14a4698d6560ce0e24f796661a1dd17e18150bd55f2", …
```
=> chore(cd): update terraformer version to 2024.02.19.13.02.55.master

stack.yml
* **master**
armory/terraformer:2024.03.19.15.16.03.master
[f261d55c45b23a4861b699eaac8e5f8ccc204b82](https://github.com/armory-io/terraformer/commit/f261d55c45b23a4861b699eaac8e5f8ccc204b82)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:737edefb6a0fbbcfb7caeb56bee0236c32438a6bb898d9977022d61c47fdac91",
"tag": "2024.03.19.15.16.03.master"
},
"vcs": {
"repo": {
},
"sha": "f261d55c45b23a4861b699eaac8e5f8ccc204b82"
}
},
},
"details": {
"image": {
"imageId": "sha256:737edefb6a0fbbcfb7caeb56bee0236c32438a6bb898d9977022d61c47fdac91", …
```
=> chore(cd): update terraformer version to 2024.03.19.15.16.03.master

stack.yml
* **master**
armory/terraformer:2024.04.10.11.50.18.master
[ac32b80cc4dfa89c12d77d8d210c67a62ac0e5fc](https://github.com/armory-io/terraformer/commit/ac32b80cc4dfa89c12d77d8d210c67a62ac0e5fc)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:f4fbf25299db56b78ef779944c0fd1c6d00125b9eada0ef7c6dd765f538d44fa",
"tag": "2024.04.10.11.50.18.master"
},
"vcs": {
"repo": {
},
"sha": "ac32b80cc4dfa89c12d77d8d210c67a62ac0e5fc"
}
},
},
"details": {
"image": {
"imageId": "sha256:f4fbf25299db56b78ef779944c0fd1c6d00125b9eada0ef7c6dd765f538d44fa", …
```
=> chore(cd): update terraformer version to 2024.04.10.11.50.18.master

stack.yml
armory/terraformer:2024.04.16.11.45.56.release-2.32.x
[4bfe9b699d739eb09956ceeeb3191853f75d8274](https://github.com/armory-io/terraformer/commit/4bfe9b699d739eb09956ceeeb3191853f75d8274)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:875f6a7bcb138150e2c0c8adb96d627fd4da3341ca71748f7b2f56e4eadf333f",
"tag": "2024.04.16.11.45.56.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "4bfe9b699d739eb09956ceeeb3191853f75d8274"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2024.04.16.11.45.56.release-2.32.x

stack.yml
armory/terraformer:2024.04.16.15.38.19.release-2.32.x
[2dc7666ca2d25acb85ab2b9f8efc864599061c45](https://github.com/armory-io/terraformer/commit/2dc7666ca2d25acb85ab2b9f8efc864599061c45)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:c80ca7c9040516dff82262b828a3e2184141c5bedcf4e0d2e8f818b1cff9209d",
"tag": "2024.04.16.15.38.19.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "2dc7666ca2d25acb85ab2b9f8efc864599061c45"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2024.04.16.15.38.19.release-2.32.x

stack.yml
* **master**
armory/terraformer:2024.04.16.15.31.12.master
[559abc8056e0f1c90d6bc737c57688f7c747c0ba](https://github.com/armory-io/terraformer/commit/559abc8056e0f1c90d6bc737c57688f7c747c0ba)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:4a77c15350e2434de97d01f8287ffb59343d6486dc3385b552d0e4dd2e7c16c2",
"tag": "2024.04.16.15.31.12.master"
},
"vcs": {
"repo": {
},
"sha": "559abc8056e0f1c90d6bc737c57688f7c747c0ba"
}
},
},
"details": {
"image": {
"imageId": "sha256:4a77c15350e2434de97d01f8287ffb59343d6486dc3385b552d0e4dd2e7c16c2", …
```
=> chore(cd): update terraformer version to 2024.04.16.15.31.12.master

stack.yml
armory/terraformer:2024.04.16.15.31.12.release-2.34.x
[559abc8056e0f1c90d6bc737c57688f7c747c0ba](https://github.com/armory-io/terraformer/commit/559abc8056e0f1c90d6bc737c57688f7c747c0ba)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:7cb7f4ff1d865979b8cc8a9c7659aebf7e9cef639060cb2055a92f3462851540",
"tag": "2024.04.16.15.31.12.release-2.34.x"
},
"vcs": {
"repo": {
},
"sha": "559abc8056e0f1c90d6bc737c57688f7c747c0ba"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2024.04.16.15.31.12.release-2.34.x

stack.yml
* **master**
armory/terraformer:2024.06.17.18.33.44.master
[142cece2dc965fc7b3643be2e590489721f5e0e0](https://github.com/armory-io/terraformer/commit/142cece2dc965fc7b3643be2e590489721f5e0e0)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:ca9bcea9f4fa7768a98e25edfc2e8b7e7bf8f26574a826be919780f0b433745a",
"tag": "2024.06.17.18.33.44.master"
},
"vcs": {
"repo": {
},
"sha": "142cece2dc965fc7b3643be2e590489721f5e0e0"
}
},
},
"details": {
"image": {
"imageId": "sha256:ca9bcea9f4fa7768a98e25edfc2e8b7e7bf8f26574a826be919780f0b433745a", …
```
=> chore(cd): update terraformer version to 2024.06.17.18.33.44.master

stack.yml
* **master**
armory/terraformer:2024.06.18.15.32.51.master
[34529fa87c5499c03828a3181b717be7b84428d4](https://github.com/armory-io/terraformer/commit/34529fa87c5499c03828a3181b717be7b84428d4)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:f727147d767355bb02906af9a4297bc1cc89a609bc557b44be65dadf51756068",
"tag": "2024.06.18.15.32.51.master"
},
"vcs": {
"repo": {
},
"sha": "34529fa87c5499c03828a3181b717be7b84428d4"
}
},
},
"details": {
"image": {
"imageId": "sha256:f727147d767355bb02906af9a4297bc1cc89a609bc557b44be65dadf51756068", …
```
=> chore(cd): update terraformer version to 2024.06.18.15.32.51.master

stack.yml
armory/echo-armory:2024.06.28.14.26.40.release-2.34.x
[23909434bf95a0891a5ab256e5fccf5d7d8b6ed3](https://github.com/armory-io/echo-armory/commit/23909434bf95a0891a5ab256e5fccf5d7d8b6ed3)
[78c7d3e6cf1081fa358b38a735b1de04705e3d3f](https://github.com/spinnaker/echo/commit/78c7d3e6cf1081fa358b38a735b1de04705e3d3f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "78c7d3e6cf1081fa358b38a735b1de04705e3d3f"
},
"details": {
"image": {
"imageId": "sha256:ab893ec9b98216c9dbeb01949c7d8144591821cc2ba2cf0dcbf1a1d4d3525ea0",
"tag": "2024.06.28.14.26.40.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2024.06.28.14.26.40.release-2.34.x

stack.yml
armory/igor-armory:2024.06.28.14.28.11.release-2.34.x
[e327e854cd7487881c15f4005f739b69ca4d7850](https://github.com/armory-io/igor-armory/commit/e327e854cd7487881c15f4005f739b69ca4d7850)
[da14a3aee2c49405ffc58f021bbf755b7519d4eb](https://github.com/spinnaker/igor/commit/da14a3aee2c49405ffc58f021bbf755b7519d4eb)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "da14a3aee2c49405ffc58f021bbf755b7519d4eb"
},
"details": {
"image": {
"imageId": "sha256:1d8ac413de6ff61cd64ca4fdb46943a4fcefe88ca4e4df9a53a4203e339a6384",
"tag": "2024.06.28.14.28.11.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update igor-armory version to 2024.06.28.14.28.11.release-2.34.x

stack.yml
armory/clouddriver-armory:2024.08.26.08.47.51.release-2.32.x
[2736c8796b346d892fb68180ed1534cd882c5f6c](https://github.com/armory-io/clouddriver-armory/commit/2736c8796b346d892fb68180ed1534cd882c5f6c)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:bf85b7799aceb28c255c0f5c9b5d6f2e4eb7ca885cc95f1769bb5c8a18b266d1",
"tag": "2024.08.26.08.47.51.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "2736c8796b346d892fb68180ed1534cd882c5f6c"
}
},
},
"details": { …
```
=> chore(cd): update clouddriver-armory version to 2024.08.26.08.47.51.release-2.32.x

stack.yml
armory/front50-armory:2024.08.26.11.59.52.release-2.32.x
[e45bcd4cd5e059036982e1a23ef9360379cdaf77](https://github.com/armory-io/front50-armory/commit/e45bcd4cd5e059036982e1a23ef9360379cdaf77)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:976348271c5693ed41daa40a394bfbb7b32f937bdf54998120bddfd3ee7833b5",
"tag": "2024.08.26.11.59.52.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "e45bcd4cd5e059036982e1a23ef9360379cdaf77"
}
},
},
"details": { …
```
=> chore(cd): update front50-armory version to 2024.08.26.11.59.52.release-2.32.x

stack.yml
armory/terraformer:2024.08.28.11.24.22.release-2.34.x
[d4b6e9f53f3a2b595ce25e0b044318d47fd239b6](https://github.com/armory-io/terraformer/commit/d4b6e9f53f3a2b595ce25e0b044318d47fd239b6)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:6cb6869d7ce2b3245313946bf6cea1ff3b54fd922c7b02dcd1f204883f87a381",
"tag": "2024.08.28.11.24.22.release-2.34.x"
},
"vcs": {
"repo": {
},
"sha": "d4b6e9f53f3a2b595ce25e0b044318d47fd239b6"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2024.08.28.11.24.22.release-2.34.x

stack.yml
armory/terraformer:2024.07.19.17.05.08.release-2.35.x
[9756bee07eaabbb25b54812996314c22554ec1c0](https://github.com/armory-io/terraformer/commit/9756bee07eaabbb25b54812996314c22554ec1c0)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:b9f1b234147862f47c4fb77973e8bfbdc897f96bee9547ce9833e8203c535af4",
"tag": "2024.07.19.17.05.08.release-2.35.x"
},
"vcs": {
"repo": {
},
"sha": "9756bee07eaabbb25b54812996314c22554ec1c0"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2024.07.19.17.05.08.release-2.35.x

stack.yml
armory/fiat-armory:2024.11.04.22.39.05.release-2.35.x
[ce4a5e689b66fce9f5aa4e3039f0fe1af5e69f74](https://github.com/armory-io/fiat-armory/commit/ce4a5e689b66fce9f5aa4e3039f0fe1af5e69f74)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:4323fa66c5d52bdd92582282689cb23a449e7cfd19826de70da59f5c168d6ceb",
"tag": "2024.11.04.22.39.05.release-2.35.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update fiat-armory version to 2024.11.04.22.39.05.release-2.35.x

stack.yml
armory/terraformer:2024.07.19.17.05.08.release-2.36.x
[9756bee07eaabbb25b54812996314c22554ec1c0](https://github.com/armory-io/terraformer/commit/9756bee07eaabbb25b54812996314c22554ec1c0)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:4b537f3dc43fe9328b2238a78788cf4d0b212552544dcc6152be65386df1dc08",
"tag": "2024.07.19.17.05.08.release-2.36.x"
},
"vcs": {
"repo": {
},
"sha": "9756bee07eaabbb25b54812996314c22554ec1c0"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update terraformer version to 2024.07.19.17.05.08.release-2.36.x

stack.yml
armory/fiat-armory:2024.11.27.18.40.05.release-2.36.x
[c8f5d4381b0a288f554d37ae3d96ae154eccc57d](https://github.com/armory-io/fiat-armory/commit/c8f5d4381b0a288f554d37ae3d96ae154eccc57d)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:dc253ef72e010467c47be0a2f75711be6309c31718ca383eb09222a3d3bf7e70",
"tag": "2024.11.27.18.40.05.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update fiat-armory version to 2024.11.27.18.40.05.release-2.36.x

stack.yml
armory/echo-armory:2024.11.26.04.37.43.release-2.36.x
[1a83a99cb4b8cf6e6ca32ab5418666dce6fd2158](https://github.com/armory-io/echo-armory/commit/1a83a99cb4b8cf6e6ca32ab5418666dce6fd2158)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:bbc7578b1a04b5f315428bdf11f13cd42040cea7847816530f1e221331ebeafc",
"tag": "2024.11.26.04.37.43.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2024.11.26.04.37.43.release-2.36.x

stack.yml
armory/gate-armory:2024.11.29.02.47.20.release-2.36.x
[0e5faf620267761450973a08f8d222fee1a87abe](https://github.com/armory-io/gate-armory/commit/0e5faf620267761450973a08f8d222fee1a87abe)
[79dc08e63646c2bd70e39d63f489197913dfbc82](https://github.com/spinnaker/gate/commit/79dc08e63646c2bd70e39d63f489197913dfbc82)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "79dc08e63646c2bd70e39d63f489197913dfbc82"
},
"details": {
"image": {
"imageId": "sha256:62ec62b622c021824d856ef4f81e3e3720e436c706b28be537940598ec6dd8ec",
"tag": "2024.11.29.02.47.20.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update gate-armory version to 2024.11.29.02.47.20.release-2.36.x

stack.yml
armory/echo-armory:2025.01.28.17.33.17.release-2.36.x
[4c2efbbb9e57b64a1a4fa85aef8eeccc8aaa80a7](https://github.com/armory-io/echo-armory/commit/4c2efbbb9e57b64a1a4fa85aef8eeccc8aaa80a7)
[4a009d6a31b722157ae94dc35dafd1a9997682ab](https://github.com/spinnaker/echo/commit/4a009d6a31b722157ae94dc35dafd1a9997682ab)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4a009d6a31b722157ae94dc35dafd1a9997682ab"
},
"details": {
"image": {
"imageId": "sha256:c44bce617e589bd2b04052ee197ba0614e4f34fd436933797ef7d47985540269",
"tag": "2025.01.28.17.33.17.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2025.01.28.17.33.17.release-2.36.x

stack.yml
armory/fiat-armory:2025.01.29.19.24.31.release-2.36.x
[bd424d60f055e6694aeaf74af5b92862932b09c3](https://github.com/armory-io/fiat-armory/commit/bd424d60f055e6694aeaf74af5b92862932b09c3)
[68c63dd29a673ebd7e37016aeed787f4a3c4d328](https://github.com/spinnaker/fiat/commit/68c63dd29a673ebd7e37016aeed787f4a3c4d328)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "68c63dd29a673ebd7e37016aeed787f4a3c4d328"
},
"details": {
"image": {
"imageId": "sha256:0f3bbcbccb8e6299dba89eea639b954ba3c2185bb3498bddba76615ea7063531",
"tag": "2025.01.29.19.24.31.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update fiat-armory version to 2025.01.29.19.24.31.release-2.36.x

stack.yml
armory/gate-armory:2025.02.11.22.56.17.release-2.36.x
[cc3f1b3059533feb0bc770eebde4f2c0714c7800](https://github.com/armory-io/gate-armory/commit/cc3f1b3059533feb0bc770eebde4f2c0714c7800)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:a7b76fa8a410a543a14d131f012edbfc2f0cb5ab305e3a97b330fe1184ef0959",
"tag": "2025.02.11.22.56.17.release-2.36.x"
},
"vcs": {
"repo": {
},
"sha": "cc3f1b3059533feb0bc770eebde4f2c0714c7800"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update gate-armory version to 2025.02.11.22.56.17.release-2.36.x

stack.yml
* **master**
armory/terraformer:2024.10.29.18.18.06.master
[b90a0332c2117ae5afb27258b7ba38a16825e502](https://github.com/armory-io/terraformer/commit/b90a0332c2117ae5afb27258b7ba38a16825e502)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:5879363ba5a06a4be495945860d3f2a799c5ae4ccde0ec72eeb9a8efc1b763fa",
"tag": "2024.10.29.18.18.06.master"
},
"vcs": {
"repo": {
},
"sha": "b90a0332c2117ae5afb27258b7ba38a16825e502"
}
},
},
"details": {
"image": {
"imageId": "sha256:5879363ba5a06a4be495945860d3f2a799c5ae4ccde0ec72eeb9a8efc1b763fa", …
```
=> chore(cd): update terraformer version to 2024.10.29.18.18.06.master

stack.yml
armory/gate-armory:2025.03.24.11.44.17.release-2.37.x
[0ad07dfef0d038a883e3b785a674d6bd56a9defe](https://github.com/armory-io/gate-armory/commit/0ad07dfef0d038a883e3b785a674d6bd56a9defe)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:9d4a1dc53854a17f8f75075ed3ebf09f0a5ed01d45264b625d786bde99a180c7",
"tag": "2025.03.24.11.44.17.release-2.37.x"
},
"vcs": {
"repo": {
},
"sha": "0ad07dfef0d038a883e3b785a674d6bd56a9defe"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update gate-armory version to 2025.03.24.11.44.17.release-2.37.x

stack.yml
armory/echo-armory:2025.04.30.00.31.56.release-2.36.x
[055cd84583be75fa1bb0cfa823bd3288c3d04f50](https://github.com/armory-io/echo-armory/commit/055cd84583be75fa1bb0cfa823bd3288c3d04f50)
[4a009d6a31b722157ae94dc35dafd1a9997682ab](https://github.com/spinnaker/echo/commit/4a009d6a31b722157ae94dc35dafd1a9997682ab)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4a009d6a31b722157ae94dc35dafd1a9997682ab"
},
"details": {
"image": {
"imageId": "sha256:55afe0a460c165e64fd5c9e15ae2fdab61c0595bb96dacca71ba9cef0e51126b",
"tag": "2025.04.30.00.31.56.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2025.04.30.00.31.56.release-2.36.x

stack.yml
armory/gate-armory:2025.05.15.16.42.59.release-2.37.x
[2a9581d3f43178e85ea71b987961e3eb909cf596](https://github.com/armory-io/gate-armory/commit/2a9581d3f43178e85ea71b987961e3eb909cf596)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:15a9c109b573a562045ff085d21eeae44374179d3d9ad3c7c092dc52a9e6dd4d",
"tag": "2025.05.15.16.42.59.release-2.37.x"
},
"vcs": {
"repo": {
},
"sha": "2a9581d3f43178e85ea71b987961e3eb909cf596"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update gate-armory version to 2025.05.15.16.42.59.release-2.37.x

stack.yml
armory/echo-armory:2025.08.11.11.25.33.release-2.36.x
[93303566f7d718f115520dd0b00852cfa183f413](https://github.com/armory-io/echo-armory/commit/93303566f7d718f115520dd0b00852cfa183f413)
[babe781908d3fda655564e3dd5ac6b4176e298e4](https://github.com/spinnaker/echo/commit/babe781908d3fda655564e3dd5ac6b4176e298e4)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "babe781908d3fda655564e3dd5ac6b4176e298e4"
},
"details": {
"image": {
"imageId": "sha256:c8ceaf17d1c675b4bf70c567c5dd3eef9d5c8297eaad586f62d0639ec230a0a3",
"tag": "2025.08.11.11.25.33.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2025.08.11.11.25.33.release-2.36.x

stack.yml
armory/igor-armory:2025.08.11.11.42.19.release-2.36.x
[7fccfb59279c325d5368a82ed9859f9cc7253302](https://github.com/armory-io/igor-armory/commit/7fccfb59279c325d5368a82ed9859f9cc7253302)
[c23e997baf53834878a7e7a170031cc6cea2bda9](https://github.com/spinnaker/igor/commit/c23e997baf53834878a7e7a170031cc6cea2bda9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c23e997baf53834878a7e7a170031cc6cea2bda9"
},
"details": {
"image": {
"imageId": "sha256:5cb584060ee07a6d83b012e67eb0d5cb7fc16a8ccae90034a6f48b95193df029",
"tag": "2025.08.11.11.42.19.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update igor-armory version to 2025.08.11.11.42.19.release-2.36.x
