stack.yml

Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:39579d305c4fb015606b32af6baad3403af309fbcf9414f607a50eeee7d3ac5c",
"tag": "2021.06.17.18.20.07.master"
},
"vcs": {
"repo": {
},
"sha": "1a703c58aedd288bfb43b144d133b462cc81c892"
}
},
}
}
```

chore(cd): update rosco-armory version to 2021.06.17.18.20.07.master

---

stack.yml

Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:664f1ab1da08caaf6a197d7cae224fcdf8e636c9528b452d829ff9455931cbcd",
"tag": "2021.06.17.18.17.23.master"
},
"vcs": {
"repo": {
},
"sha": "f823d117523867f56504669fc3fc077f5019a05e"
}
},
}
}
```

chore(cd): update fiat-armory version to 2021.06.17.18.17.23.master

---

stack.yml

Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:000593ddb37cfd6e8e9aa5cfe2eb7a8962229fe80f5740153f5e62d196fb1417",
"tag": "2021.06.22.18.41.16.master"
},
"vcs": {
"repo": {
},
"sha": "7f58e8dd4d34c0251b1d13acd8a5dfc707a487c6"
}
},
}
}
```

chore(cd): update dinghy version to 2021.06.22.18.41.16.master

---

stack.yml

Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:fba7557e5d72fd72d55407b79597de89487ccd76849be9eb785392ec92f7e3ea",
"tag": "2021.06.25.20.08.50.master"
},
"vcs": {
"repo": {
},
"sha": "bf43a3294ee87bba7b534900b928308f4003bfee"
}
},
}
}
```

chore(cd): update rosco-armory version to 2021.06.25.20.08.50.master

---

stack.yml

Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:ec293e7ff9709c577fd6e111ad2c28e9a349d0ed2e998d2ddd862f7c184dbfdc",
"tag": "2021.06.25.20.09.15.master"
},
"vcs": {
"repo": {
},
"sha": "c5106a55ad118c8140563320ee7d6533a1518390"
}
},
}
}
```

chore(cd): update igor-armory version to 2021.06.25.20.09.15.master

---

stack.yml

Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:6d1e9f953675ea60063ec11e7986a89db8467d0ffcf4fdfd3cc8191b6a724836",
"tag": "2021.06.25.20.09.46.master"
},
"vcs": {
"repo": {
},
"sha": "19284cdbaa403233893da111d46d1b1a1cdec0b1"
}
},
}
}
```

chore(cd): update gate-armory version to 2021.06.25.20.09.46.master

---

stack.yml

Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:832f3d9965cfca91abb3ce541d2fee93e74c943417c341224c6531f523269dd0",
"tag": "2021.06.29.07.01.07.master"
},
"vcs": {
"repo": {
},
"sha": "f4010629377b626c666b77edee082f379dba1672"
}
},
}
}
```

chore(cd): update igor-armory version to 2021.06.29.07.01.07.master

---

stack.yml

Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:c58e749f2371ddbf013685b3dabc57f940cc47c7d480db60d4b0b971d2309021",
"tag": "2021.07.06.16.56.13.master"
},
"vcs": {
"repo": {
},
"sha": "4f17e78a10bf579eda993f343ee5651d073f0915"
}
},
}
}
```

chore(cd): update orca-armory version to 2021.07.06.16.56.13.master

---

stack.yml

Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:21a310c17abc4a641f0849f9e517e23c51240ec0a25b4b16c3db19d8d409ef7a",
"tag": "2021.07.02.22.22.09.master"
},
"vcs": {
"repo": {
},
"sha": "34a3f0a0505ffc6091af83a5e774247e7fe04bcf"
}
},
}
}
```

chore(cd): update rosco-armory version to 2021.07.02.22.22.09.master

---

stack.yml

Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:c72d63ce40178c5b29bff7415e039c57da871fab70f7cbb8dca8666ccf1657e3",
"tag": "2021.07.07.21.43.34.master"
},
"vcs": {
"repo": {
},
"sha": "a08ea272f752ebcce01e59e790abbe0381b10d00"
}
},
}
}
```

chore(cd): update orca-armory version to 2021.07.07.21.43.34.master

---

stack.yml

Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:7b3bae4f7f8968f132deec3e1e88e116986d340ea00e1d4f1b4dcb640221ca26",
"tag": "2021.07.13.20.12.37.master"
},
"vcs": {
"repo": {
},
"sha": "d604612e2b2555c57a5dd64763e8fe70ea4d38db"
}
},
}
}
```

chore(cd): update orca-armory version to 2021.07.13.20.12.37.master

---

stack.yml

Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:152413ad8e52ec829141c603ae94f4d65f6d65ce57b457876bbcc6ef2aeadf29",
"tag": "2021.07.21.22.52.32.master"
},
"vcs": {
"repo": {
},
"sha": "fd91290091563b96ad5973860e7858ae7d63292e"
}
},
}
}
```

chore(cd): update kayenta-armory version to 2021.07.21.22.52.32.master

---

stack.yml

Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:50d9d20565743722e5b7df94f5df710cacd3b61e771f097b38322107ba8f9837",
"tag": "2021.07.21.20.01.30.master"
},
"vcs": {
"repo": {
},
"sha": "74dcaf639c6c51ffee0f5c5d9fe809e4cb06600e"
}
},
}
}
```

chore(cd): update orca-armory version to 2021.07.21.20.01.30.master

---

stack.yml

Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:fff91a3d1888052faa1fc6fb72b677d6c563c76567266f206abe0aff7c757aab",
"tag": "2021.07.19.20.54.25.master"
},
"vcs": {
"repo": {
},
"sha": "de5233ec95845206e20f9b969426c2bf35c98d73"
}
},
}
}
```

chore(cd): update dinghy version to 2021.07.19.20.54.25.master

---

stack.yml

Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c033eb7dba0e985ce9d2cb207d7989a4054a63a3"
},
"details": {
"image": {
"imageId": "sha256:dfca47bce3c79b545f79f8304ee6857143f6a40d51529605ce38c662b9e66216",
"tag": "2021.07.27.05.09.08.master"
},
"vcs": {
"repo": {
},
"sha": "d0b897f67bad90e81dcc0ec3d15c21f1ea6669b1"
}
},
}
}
```

chore(cd): update igor-armory version to 2021.07.27.05.09.08.master

---

stack.yml

Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "98b0b86b8be6f31af875bdf5af95b242e7697006"
},
"details": {
"image": {
"imageId": "sha256:f0ef46ef6319225772a5093a7f48a9b7d374f4eac6c9e9f6591537846d1aafbb",
"tag": "2021.08.04.20.27.21.master"
},
"vcs": {
"repo": {
},
"sha": "d60f65a0449370a2cab25137664f498903607924"
}
},
}
}
```

chore(cd): update igor-armory version to 2021.08.04.20.27.21.master

---

stack.yml

Event
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:b5e7b211aea8d18d9324cc3b08900e7617d4da65455eecfa93a5c49be245383b",
"tag": "2021.08.04.22.53.18.master"
},
"vcs": {
"repo": {
},
"sha": "48a62fe101731b590055728f5ec3b12a2a9e74c0"
}
},
}
}
```

chore(cd): update igor-armory version to 2021.08.04.22.53.18.master

---

.github/workflows/deploy-staging.yml

Co-authored-by: armory-astrolabe <armory-astrolabe@users.noreply.github.com>

fix(gha): update to match master

---

stack.yml

Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:981030662d93b8b18f61e4db576d5ee961996be5ed7cc1281fbc84314ee76ff5",
"tag": "2021.09.09.20.08.42.master"
},
"vcs": {
"repo": {
},
"sha": "9f3deb2352c26b6355edd085d2e139967338129d"
}
},
}
}
```

chore(cd): update dinghy version to 2021.09.09.20.08.42.master

---

stack.yml

Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e11a3db51a2558f41be7e7cb923329053c0fd1b7"
},
"details": {
"image": {
"imageId": "sha256:d1240cc7c50cb7e2a0463c37631d05bc7b82f30d2bb4682f98cb4ac6982bbcef",
"tag": "2022.08.26.16.08.36.master"
},
"vcs": {
"repo": {
},
"sha": "3ff744b29b295ee63637f0ef6f0ab82fe12bb256"
}
},
}
}
```

chore(cd): update igor-armory version to 2022.08.26.16.08.36.master

---

stack.yml

Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:abd46eb18872b4ad3941da36c842bb0aba44e579d21d6f3fb2b528abea7433b8",
"tag": "2022.07.12.12.50.15.master"
},
"vcs": {
"repo": {
},
"sha": "43857c12304997f2ec93390ae1e6755e251e9d2d"
}
},
}
}
```

chore(cd): update gate-armory version to 2022.07.12.12.50.15.master

---

stack.yml

Event
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:d8106551bb65f60b1eccb2b3c3b6ea44ca41f9c40e95a3a23132932d57034b0b",
"tag": "2022.08.25.17.05.13.master"
},
"vcs": {
"repo": {
},
"sha": "168ddc21ba83b6e634f998b339b458c82ba27420"
}
},
}
}
```

chore(cd): update dinghy version to 2022.08.25.17.05.13.master

---

.github/workflows/run-e2e-tests.yml

(cherry picked from commit edc0092c1d76ee11747d973f1b99668c7f96b2c4)

chore(action): Destroy ephemeral 2.26.x

---

.github/workflows/run-e2e-tests.yml

(cherry picked from commit 5754ba007ac9c5c09e655831f9539647c058fd4d)

fix(action): pass env to destroy (#1899)

---

.github/workflows/run-e2e-tests.yml

(cherry picked from commit 32f842d4068b00b79662a5b8c80ce7b998c013fa)

fix(action): do not destroy env if action is cancelled

---

.github/workflows/run-e2e-tests.yml

(cherry picked from commit ef70b0360dd879a5bb87784b0c0732024d0e2655)

fix(action): evaluate expression correctly (#1908)

---

stack.yml

Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e11a3db51a2558f41be7e7cb923329053c0fd1b7"
},
"details": {
"image": {
"imageId": "sha256:b1deb071076f0bf4862749563b5eb6247d5c62e764dfa3f7a851e9b91933a88d",
"tag": "2022.09.12.19.20.20.master"
},
"vcs": {
"repo": {
},
"sha": "daac521b66d09fca82376a1a6fbeefa9e44adb0f"
}
},
}
}
```

chore(cd): update igor-armory version to 2022.09.12.19.20.20.master

---

stack.yml

Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7c090492e472a6c500ac366223c8b5f730d8435b"
},
"details": {
"image": {
"imageId": "sha256:d9498ab90b76c900d305a9cedd2fd65d5a8423a4893f0a5705f78e38b2c00c2f",
"tag": "2022.09.14.16.39.54.master"
},
"vcs": {
"repo": {
},
"sha": "3c9dd843c3eddbfaa529f054b2df73de938391ca"
}
},
}
}
```

chore(cd): update igor-armory version to 2022.09.14.16.39.54.master

---

.github/workflows/run-e2e-tests.yml

* feat(action): send slack notification when e2e test failed
* feat(action): skip tests if stack file doesn't change
* feat(action): skip tests in the same job
* feat(action): fix output variable
* feat(action): use double curly braces
(cherry picked from commit 17dbfc22d905a8d4abce2e020c779ed379641db5)

feat(action): send slack notification when e2e test failed (#1928)

---

stack.yml

Event
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "010288b7b0eeba076f4269cf5187cb78bfd0cc3a"
},
"details": {
"image": {
"imageId": "sha256:5f64ad1eb74a6d4d85f43cb682bc8aa13b599cc5bc5a1c93f150c5992460a0d5",
"tag": "2022.10.19.20.13.42.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "b9fd41de4d06e2c444ea8e916d8711389c9e6a2b"
}
},
},
"baseVcs": {
"repo": {
},
"sha": "010288b7b0eeba076f4269cf5187cb78bfd0cc3a"
},
"details": {
"image": {
"imageId": …
```

chore(cd): update igor-armory version to 2022.10.19.20.13.42.release-2.28.x

---

stack.yml

* **master**
armory/gate-armory:2022.11.10.22.54.28.master
[22e61ea13407c2e378cabd6c4b3675a9e21fd500](https://github.com/armory-io/gate-armory/commit/22e61ea13407c2e378cabd6c4b3675a9e21fd500)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:28f8aaff13ef4cc59fec50fe05a3927fdcf6cf875aa631092a9e568bbdb9b77a",
"tag": "2022.11.10.22.54.28.master"
},
"vcs": {
"repo": {
},
"sha": "22e61ea13407c2e378cabd6c4b3675a9e21fd500"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update gate-armory version to 2022.11.10.22.54.28.master

---

stack.yml

armory/orca-armory:2022.11.08.23.29.29.release-2.27.x
[9c2785fededd2e9557ff845d8da3181cd8cbec69](https://github.com/armory-io/orca-armory/commit/9c2785fededd2e9557ff845d8da3181cd8cbec69)
[1a6014496eb96c538c566ec5da70c73457ace2c5](https://github.com/spinnaker/orca/commit/1a6014496eb96c538c566ec5da70c73457ace2c5)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1a6014496eb96c538c566ec5da70c73457ace2c5"
},
"details": {
"image": {
"imageId": "sha256:c09e3a0c699248cf4e6819b281f95ca5a193a20ecdd798ff631cdf489bb2a0e1",
"tag": "2022.11.08.23.29.29.release-2.27.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2022.11.08.23.29.29.release-2.27.x

---

stack.yml

armory/clouddriver-armory:2022.11.17.17.38.42.release-2.28.x
[0593b5de34d62acb440d9708f6cd4d5b99bc63c0](https://github.com/armory-io/clouddriver-armory/commit/0593b5de34d62acb440d9708f6cd4d5b99bc63c0)
[61858506d89bd905e96446ddd3329ee00a48b00a](https://github.com/spinnaker/clouddriver/commit/61858506d89bd905e96446ddd3329ee00a48b00a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "61858506d89bd905e96446ddd3329ee00a48b00a"
},
"details": {
"image": {
"imageId": "sha256:d0dbd3631eee7c9dc601109da749da5f72e1a87924485aa0dba832e9ee48740f",
"tag": "2022.11.17.17.38.42.release-2.28.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2022.11.17.17.38.42.release-2.28.x

---

stack.yml

armory/gate-armory:2022.11.17.22.26.09.release-2.28.x
[eeeead3f065f60e82dbbe22df78e371132b81f09](https://github.com/armory-io/gate-armory/commit/eeeead3f065f60e82dbbe22df78e371132b81f09)
[64f64567612facf312b7fd3126051812d10c014d](https://github.com/spinnaker/gate/commit/64f64567612facf312b7fd3126051812d10c014d)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "64f64567612facf312b7fd3126051812d10c014d"
},
"details": {
"image": {
"imageId": "sha256:6522dde8e03b8abe20e3507b7e4a3d86d1f418e5ab0d2d2f8ecac68da80bd615",
"tag": "2022.11.17.22.26.09.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update gate-armory version to 2022.11.17.22.26.09.release-2.28.x

---

stack.yml

armory/igor-armory:2022.11.18.20.31.44.release-2.27.x
[5b35c23e6dce5154faceff7507e7167e58b6ab18](https://github.com/armory-io/igor-armory/commit/5b35c23e6dce5154faceff7507e7167e58b6ab18)
[35c25f7f77c31f7f60496184786258261a2f1def](https://github.com/spinnaker/igor/commit/35c25f7f77c31f7f60496184786258261a2f1def)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "35c25f7f77c31f7f60496184786258261a2f1def"
},
"details": {
"image": {
"imageId": "sha256:802c9ae47715d43ea6673929e0007407e579cd12e9a4274371026ded0e31351b",
"tag": "2022.11.18.20.31.44.release-2.27.x"
},
"vcs": {
"repo": { …
```

chore(cd): update igor-armory version to 2022.11.18.20.31.44.release-2.27.x

---

stack.yml

armory/orca-armory:2022.11.18.19.30.44.release-2.28.x
[fc2e783edfc16f358049258f300db0924bc05e36](https://github.com/armory-io/orca-armory/commit/fc2e783edfc16f358049258f300db0924bc05e36)
[447ffbb190a298da671fb2a36e75aea527480a67](https://github.com/spinnaker/orca/commit/447ffbb190a298da671fb2a36e75aea527480a67)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "447ffbb190a298da671fb2a36e75aea527480a67"
},
"details": {
"image": {
"imageId": "sha256:adafec8cb00e1e27a6b00b4c51466c95aebb1ae53ec7dbf22c81f98fef5ecbd7",
"tag": "2022.11.18.19.30.44.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2022.11.18.19.30.44.release-2.28.x

---

stack.yml

armory/clouddriver-armory:2022.11.18.20.49.25.release-2.27.x
[4b3fcd34c3db46525d2594d7d8003e5c34aa63c1](https://github.com/armory-io/clouddriver-armory/commit/4b3fcd34c3db46525d2594d7d8003e5c34aa63c1)
[b15ef986c519544c7397b0861f5b74ade1863c8c](https://github.com/spinnaker/clouddriver/commit/b15ef986c519544c7397b0861f5b74ade1863c8c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b15ef986c519544c7397b0861f5b74ade1863c8c"
},
"details": {
"image": {
"imageId": "sha256:575ae497a7778c58b939877464bc51348c362b92464ef524821cfdef92e2ccfd",
"tag": "2022.11.18.20.49.25.release-2.27.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2022.11.18.20.49.25.release-2.27.x

---

stack.yml

armory/orca-armory:2022.11.21.16.47.31.release-2.28.x
[81226e48744c3ab5ce1afe68e20ae4aa8e6487dd](https://github.com/armory-io/orca-armory/commit/81226e48744c3ab5ce1afe68e20ae4aa8e6487dd)
[89fdccc7f43260e3896ecf89aedfff7a12bfaf2f](https://github.com/spinnaker/orca/commit/89fdccc7f43260e3896ecf89aedfff7a12bfaf2f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "89fdccc7f43260e3896ecf89aedfff7a12bfaf2f"
},
"details": {
"image": {
"imageId": "sha256:bead16ac9781a8fff3306abf865818f39afeadcedbc0f2bd9f49c899d1ddaf17",
"tag": "2022.11.21.16.47.31.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2022.11.21.16.47.31.release-2.28.x

---

stack.yml

armory/orca-armory:2022.11.21.16.49.35.release-2.27.x
[ff2776bf6a966f73f5f217c2fd145a8d08c8c0c3](https://github.com/armory-io/orca-armory/commit/ff2776bf6a966f73f5f217c2fd145a8d08c8c0c3)
[9709ee0c6555782f97a2771686f70507d2eab683](https://github.com/spinnaker/orca/commit/9709ee0c6555782f97a2771686f70507d2eab683)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9709ee0c6555782f97a2771686f70507d2eab683"
},
"details": {
"image": {
"imageId": "sha256:4eff0d4f684ac6e4bc34088d94a9e5668290717df34416ff20c641e0199eb3a6",
"tag": "2022.11.21.16.49.35.release-2.27.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2022.11.21.16.49.35.release-2.27.x

---

stack.yml

* **master**
armory/deck-armory:2022.11.30.23.02.51.master
[1c1608baa1f636e52fd0a7c27b2c49d00cda8065](https://github.com/armory-io/deck-armory/commit/1c1608baa1f636e52fd0a7c27b2c49d00cda8065)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:995fcf657d27ea8ab463e019d71a992bb2257824d7effdbea7649e3aba6dd991",
"tag": "2022.11.30.23.02.51.master"
},
"vcs": {
"repo": {
},
"sha": "1c1608baa1f636e52fd0a7c27b2c49d00cda8065"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update deck-armory version to 2022.11.30.23.02.51.master

---

stack.yml

armory/clouddriver-armory:2022.11.29.23.12.07.release-2.28.x
[960c72d1e7e7b9e857d94af9731c3441426ee073](https://github.com/armory-io/clouddriver-armory/commit/960c72d1e7e7b9e857d94af9731c3441426ee073)
[b12e1dec95691b14603f74f0b49e8fb3e942598a](https://github.com/spinnaker/clouddriver/commit/b12e1dec95691b14603f74f0b49e8fb3e942598a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b12e1dec95691b14603f74f0b49e8fb3e942598a"
},
"details": {
"image": {
"imageId": "sha256:3b4e58b26c57cf31e72b5435dfcffea6e7daeb856c501042f39c460cc1359334",
"tag": "2022.11.29.23.12.07.release-2.28.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2022.11.29.23.12.07.release-2.28.x

---

stack.yml

armory/rosco-armory:2022.11.29.22.28.54.release-2.28.x
[33e7e7db7e2475f0a5ce8c42f7ccc986d8c134fa](https://github.com/armory-io/rosco-armory/commit/33e7e7db7e2475f0a5ce8c42f7ccc986d8c134fa)
[f1e67bed0410d23d085eece10b2cc9308ecda412](https://github.com/spinnaker/rosco/commit/f1e67bed0410d23d085eece10b2cc9308ecda412)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f1e67bed0410d23d085eece10b2cc9308ecda412"
},
"details": {
"image": {
"imageId": "sha256:b72f595dc6010490fa7e2ccfac9cdde0ece360747951d0cca8701f8dbb72437c",
"tag": "2022.11.29.22.28.54.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2022.11.29.22.28.54.release-2.28.x

---

stack.yml

armory/echo-armory:2022.11.29.22.24.33.release-2.28.x
[b0a56058fbfe6f49f3c3032d5a9a42b625fe1d9d](https://github.com/armory-io/echo-armory/commit/b0a56058fbfe6f49f3c3032d5a9a42b625fe1d9d)
[fec591654cea221675c357f0b617f4f4c117ff5d](https://github.com/spinnaker/echo/commit/fec591654cea221675c357f0b617f4f4c117ff5d)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "fec591654cea221675c357f0b617f4f4c117ff5d"
},
"details": {
"image": {
"imageId": "sha256:ba504a329d53beab2c12cb44d6a5a9f140fbd0bcc5092959afb5a52bd28179f6",
"tag": "2022.11.29.22.24.33.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update echo-armory version to 2022.11.29.22.24.33.release-2.28.x

---

stack.yml

armory/gate-armory:2022.12.01.20.21.08.release-2.27.x
[adf9732bc7b3c8df48b21b86ef9783efcadec78b](https://github.com/armory-io/gate-armory/commit/adf9732bc7b3c8df48b21b86ef9783efcadec78b)
[4d90c87116686d0f0dbc65af9291ce404656bcb7](https://github.com/spinnaker/gate/commit/4d90c87116686d0f0dbc65af9291ce404656bcb7)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4d90c87116686d0f0dbc65af9291ce404656bcb7"
},
"details": {
"image": {
"imageId": "sha256:daaff9d55de53f51a0fb8d98dc0e52a46d14d1e569b89af4551f011314304a55",
"tag": "2022.12.01.20.21.08.release-2.27.x"
},
"vcs": {
"repo": { …
```

chore(cd): update gate-armory version to 2022.12.01.20.21.08.release-2.27.x

---

stack.yml

armory/echo-armory:2022.11.29.22.26.13.release-2.27.x
[ed3c35253d27af121a5a6874de9b006d3b5d3bcf](https://github.com/armory-io/echo-armory/commit/ed3c35253d27af121a5a6874de9b006d3b5d3bcf)
[303a55fb72eb44c901a19da4ebfe052191965ae0](https://github.com/spinnaker/echo/commit/303a55fb72eb44c901a19da4ebfe052191965ae0)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "303a55fb72eb44c901a19da4ebfe052191965ae0"
},
"details": {
"image": {
"imageId": "sha256:10ec0678e24fa69400c0e51604fb4bbcb5e0fe6bee4aa07e012047917bd3c094",
"tag": "2022.11.29.22.26.13.release-2.27.x"
},
"vcs": {
"repo": { …
```

chore(cd): update echo-armory version to 2022.11.29.22.26.13.release-2.27.x

---

stack.yml

armory/clouddriver-armory:2022.11.29.23.17.27.release-2.27.x
[f310d91adf02ab892147e02fd549fd09af05a332](https://github.com/armory-io/clouddriver-armory/commit/f310d91adf02ab892147e02fd549fd09af05a332)
[b1cd05549b5eb32c34c7ad8d94cf12cc9651b7d3](https://github.com/spinnaker/clouddriver/commit/b1cd05549b5eb32c34c7ad8d94cf12cc9651b7d3)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b1cd05549b5eb32c34c7ad8d94cf12cc9651b7d3"
},
"details": {
"image": {
"imageId": "sha256:6dd379718ce710d42929d3f2142e3f571220752b5069c8cc686c93ab26daaf57",
"tag": "2022.11.29.23.17.27.release-2.27.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2022.11.29.23.17.27.release-2.27.x

---

stack.yml

armory/deck-armory:2022.12.06.16.18.24.release-2.28.x
[6798fd1789d2c062c4a1cd2e33615e6bad9aa90b](https://github.com/armory-io/deck-armory/commit/6798fd1789d2c062c4a1cd2e33615e6bad9aa90b)
[f889c7183503ae41585d304cfb0e1d6ec88a9568](https://github.com/spinnaker/deck/commit/f889c7183503ae41585d304cfb0e1d6ec88a9568)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f889c7183503ae41585d304cfb0e1d6ec88a9568"
},
"details": {
"image": {
"imageId": "sha256:788776c95a8c996bebcc9d61749218368add7276e5698fde71e18329e3ecd09e",
"tag": "2022.12.06.16.18.24.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2022.12.06.16.18.24.release-2.28.x

---

stack.yml

armory/rosco-armory:2022.11.29.22.30.21.release-2.27.x
[67ad436fa3ffe8b3caa1059abfa9596e6a2a506e](https://github.com/armory-io/rosco-armory/commit/67ad436fa3ffe8b3caa1059abfa9596e6a2a506e)
[1becf314b2591fd68c25fec990ff7f3e2174fbe3](https://github.com/spinnaker/rosco/commit/1becf314b2591fd68c25fec990ff7f3e2174fbe3)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1becf314b2591fd68c25fec990ff7f3e2174fbe3"
},
"details": {
"image": {
"imageId": "sha256:193f5561e4b8a20ec0c6f12274929e80ba2aee095e0e230f26cdff2d5152ceb9",
"tag": "2022.11.29.22.30.21.release-2.27.x"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2022.11.29.22.30.21.release-2.27.x

---

stack.yml

armory/orca-armory:2022.11.27.20.28.36.release-2.27.x
[fa3449f0202512534382d2d2a0431f25f4f408c5](https://github.com/armory-io/orca-armory/commit/fa3449f0202512534382d2d2a0431f25f4f408c5)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:841166a35da9848c3dd774ecd6ed21fd052affdfa109ea2847118f64632e7659",
"tag": "2022.11.27.20.28.36.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "fa3449f0202512534382d2d2a0431f25f4f408c5"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update orca-armory version to 2022.11.27.20.28.36.release-2.27.x

---

stack.yml

armory/deck-armory:2022.11.29.22.49.26.release-2.27.x
[1d2408e6d94fa62200bd0b776fdc021c5ff9f83d](https://github.com/armory-io/deck-armory/commit/1d2408e6d94fa62200bd0b776fdc021c5ff9f83d)
[c7ac4908512892d7b925277617f2c54260108098](https://github.com/spinnaker/deck/commit/c7ac4908512892d7b925277617f2c54260108098)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c7ac4908512892d7b925277617f2c54260108098"
},
"details": {
"image": {
"imageId": "sha256:97184a4120e23dabda832e32ab9c1662f3227e1358644fdd06b70eb84253ef3f",
"tag": "2022.11.29.22.49.26.release-2.27.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2022.11.29.22.49.26.release-2.27.x

---

stack.yml

armory/rosco-armory:2022.12.08.22.01.17.release-2.28.x
[945f21dec252da7dd2e00c8d23a1687aa3b9841a](https://github.com/armory-io/rosco-armory/commit/945f21dec252da7dd2e00c8d23a1687aa3b9841a)
[577d19c6d1a062fdbf63f008600af6386ee8e073](https://github.com/spinnaker/rosco/commit/577d19c6d1a062fdbf63f008600af6386ee8e073)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "577d19c6d1a062fdbf63f008600af6386ee8e073"
},
"details": {
"image": {
"imageId": "sha256:6506612f316494a25f4c408fdd28c06b8ea1d0eca0abf2e7c2835a4e6f8f1500",
"tag": "2022.12.08.22.01.17.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2022.12.08.22.01.17.release-2.28.x

---

stack.yml

armory/rosco-armory:2022.12.08.22.03.21.release-2.27.x
[f4164fdcfa275b62e0c0fefbe26b5cbd845c543d](https://github.com/armory-io/rosco-armory/commit/f4164fdcfa275b62e0c0fefbe26b5cbd845c543d)
[713d1944fc3fd5b980d1678c46089dc54905c4f2](https://github.com/spinnaker/rosco/commit/713d1944fc3fd5b980d1678c46089dc54905c4f2)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "713d1944fc3fd5b980d1678c46089dc54905c4f2"
},
"details": {
"image": {
"imageId": "sha256:62c60270fedab88e01c0ac90fcb8075d80b7ae78a038629baf09da4ca4c597d4",
"tag": "2022.12.08.22.03.21.release-2.27.x"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2022.12.08.22.03.21.release-2.27.x

---

stack.yml

armory/fiat-armory:2022.12.13.21.00.40.release-2.28.x
[48c8759b0878fd1b86b91dae9ee288afcf03dd39](https://github.com/armory-io/fiat-armory/commit/48c8759b0878fd1b86b91dae9ee288afcf03dd39)
[325886ada3578827bdee6a0ecb541f7d1258806c](https://github.com/spinnaker/fiat/commit/325886ada3578827bdee6a0ecb541f7d1258806c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "325886ada3578827bdee6a0ecb541f7d1258806c"
},
"details": {
"image": {
"imageId": "sha256:4bdd475a9aa16b2d2682b3ddc78b990e79598d101be326d044ecba46701b0c16",
"tag": "2022.12.13.21.00.40.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update fiat-armory version to 2022.12.13.21.00.40.release-2.28.x

---

stack.yml

armory/front50-armory:2022.12.09.13.31.58.release-2.28.x
[fab8841982330e7537629c9f24f41205cd5863fd](https://github.com/armory-io/front50-armory/commit/fab8841982330e7537629c9f24f41205cd5863fd)
[c50094edf41f649f2ca77807637297971b3f5b60](https://github.com/spinnaker/front50/commit/c50094edf41f649f2ca77807637297971b3f5b60)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c50094edf41f649f2ca77807637297971b3f5b60"
},
"details": {
"image": {
"imageId": "sha256:f587f52a141ffa3b5dac6688744b4782287b6136839f999181d558d8e846bfa8",
"tag": "2022.12.09.13.31.58.release-2.28.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update front50-armory version to 2022.12.09.13.31.58.release-2.28.x

---

stack.yml

armory/front50-armory:2022.12.09.13.31.46.release-2.27.x
[5e1fe36c4b8df29cc9cb4d7af581a44b0ca44e59](https://github.com/armory-io/front50-armory/commit/5e1fe36c4b8df29cc9cb4d7af581a44b0ca44e59)
[462b6807003a561ca2168d32f817bce061a01d07](https://github.com/spinnaker/front50/commit/462b6807003a561ca2168d32f817bce061a01d07)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "462b6807003a561ca2168d32f817bce061a01d07"
},
"details": {
"image": {
"imageId": "sha256:2b1c2dbf8a196eb1ad5224af4ae28a5605988ca0d61d0f3dd6aee0e3ff8e9363",
"tag": "2022.12.09.13.31.46.release-2.27.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update front50-armory version to 2022.12.09.13.31.46.release-2.27.x

---

stack.yml

armory/deck-armory:2022.12.15.10.19.52.release-2.28.x
[dd17c153eaf117ab7990c11182a6bdc887d020f9](https://github.com/armory-io/deck-armory/commit/dd17c153eaf117ab7990c11182a6bdc887d020f9)
[f889c7183503ae41585d304cfb0e1d6ec88a9568](https://github.com/spinnaker/deck/commit/f889c7183503ae41585d304cfb0e1d6ec88a9568)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f889c7183503ae41585d304cfb0e1d6ec88a9568"
},
"details": {
"image": {
"imageId": "sha256:831b5991014a71528336fe158a78a12c48f32bd9bd97eb9c704354a3aa892ff0",
"tag": "2022.12.15.10.19.52.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2022.12.15.10.19.52.release-2.28.x

---

stack.yml

armory/deck-armory:2022.12.15.10.21.22.release-2.27.x
[0802cbb92aa32eb6b387b5a6e54db14843fc6f31](https://github.com/armory-io/deck-armory/commit/0802cbb92aa32eb6b387b5a6e54db14843fc6f31)
[c7ac4908512892d7b925277617f2c54260108098](https://github.com/spinnaker/deck/commit/c7ac4908512892d7b925277617f2c54260108098)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c7ac4908512892d7b925277617f2c54260108098"
},
"details": {
"image": {
"imageId": "sha256:545cf7cc693665a5b56a26394252dc512f68f07e9448e2dc288c64f2a9b52037",
"tag": "2022.12.15.10.21.22.release-2.27.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2022.12.15.10.21.22.release-2.27.x

---

stack.yml

* **master**
armory/fiat-armory:2022.12.15.15.45.26.master
[407b59b9d9a8953f5d8e30c1a6380efc3ef7a932](https://github.com/armory-io/fiat-armory/commit/407b59b9d9a8953f5d8e30c1a6380efc3ef7a932)
[f5c3ea15d4c30d209815196bbacf845c764869b6](https://github.com/spinnaker/fiat/commit/f5c3ea15d4c30d209815196bbacf845c764869b6)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f5c3ea15d4c30d209815196bbacf845c764869b6"
},
"details": {
"image": {
"imageId": "sha256:0de91d7250463a4cceb1180ff5d0607aa9f684fe12c526ab7e9c0ca9e2f77edd",
"tag": "2022.12.15.15.45.26.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update fiat-armory version to 2022.12.15.15.45.26.master

---

stack.yml

* **master**
armory/fiat-armory:2022.12.15.16.58.24.master
[74f38812ea704138674bf76c36ee1b7a1515e45f](https://github.com/armory-io/fiat-armory/commit/74f38812ea704138674bf76c36ee1b7a1515e45f)
[63f1a1823e87ef0702279bcd7f92f5f3565f35ee](https://github.com/spinnaker/fiat/commit/63f1a1823e87ef0702279bcd7f92f5f3565f35ee)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "63f1a1823e87ef0702279bcd7f92f5f3565f35ee"
},
"details": {
"image": {
"imageId": "sha256:23285eb60dd84ce39a180c33bd974de7cdfd66c4e3b99092ab07f505c8953750",
"tag": "2022.12.15.16.58.24.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update fiat-armory version to 2022.12.15.16.58.24.master

---

stack.yml

* **master**
armory/kayenta-armory:2022.12.12.20.02.56.master
[f2d4eff01b915fdbc132ff607212d14fe9551594](https://github.com/armory-io/kayenta-armory/commit/f2d4eff01b915fdbc132ff607212d14fe9551594)
[3b8d61e26a2108ee8a7fe69840657ec1a14175ab](https://github.com/spinnaker/kayenta/commit/3b8d61e26a2108ee8a7fe69840657ec1a14175ab)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "3b8d61e26a2108ee8a7fe69840657ec1a14175ab"
},
"details": {
"image": {
"imageId": "sha256:e40ff31955b2870536497a09e3c2ba08d99e32d1483c57aed9dbca77a972278b",
"tag": "2022.12.12.20.02.56.master"
},
"vcs": {
"repo": {
"repoName": …
```

chore(cd): update kayenta-armory version to 2022.12.12.20.02.56.master

---

stack.yml

* **master**
armory/kayenta-armory:2022.12.15.22.14.36.master
[af685ffc6580e162fd05f247fe07586cc679c10e](https://github.com/armory-io/kayenta-armory/commit/af685ffc6580e162fd05f247fe07586cc679c10e)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:275d58704d7d6f14397f17ccc954108940d9f5937c02e886494206f6b50edea0",
"tag": "2022.12.15.22.14.36.master"
},
"vcs": {
"repo": {
},
"sha": "af685ffc6580e162fd05f247fe07586cc679c10e"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update kayenta-armory version to 2022.12.15.22.14.36.master

---

stack.yml

* **master**
armory/deck-armory:2022.12.12.16.45.20.master
[b24f68d6c44a5ad222aeb4f57f15a5c3e1b36082](https://github.com/armory-io/deck-armory/commit/b24f68d6c44a5ad222aeb4f57f15a5c3e1b36082)
[66207875f1386a3271ced770cd38227b5888c1da](https://github.com/spinnaker/deck/commit/66207875f1386a3271ced770cd38227b5888c1da)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "66207875f1386a3271ced770cd38227b5888c1da"
},
"details": {
"image": {
"imageId": "sha256:e8ce4457d60adffc5fc7d095425d333dfdaafac023323df2082e443ed788d27e",
"tag": "2022.12.12.16.45.20.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update deck-armory version to 2022.12.12.16.45.20.master

---

stack.yml

* **master**
armory/kayenta-armory:2022.12.16.13.07.57.master
[5f177bd5fe02d77de1a5909663d20a8daa9ae2b1](https://github.com/armory-io/kayenta-armory/commit/5f177bd5fe02d77de1a5909663d20a8daa9ae2b1)
[65c837327cd8fe2b49dd6dd2c997cf123e901b2d](https://github.com/spinnaker/kayenta/commit/65c837327cd8fe2b49dd6dd2c997cf123e901b2d)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "65c837327cd8fe2b49dd6dd2c997cf123e901b2d"
},
"details": {
"image": {
"imageId": "sha256:aa31c3e777e60ccde291c7390e5f16376c84ebef21de584700badecaaf8ae790",
"tag": "2022.12.16.13.07.57.master"
},
"vcs": {
"repo": {
"repoName": …
```

chore(cd): update kayenta-armory version to 2022.12.16.13.07.57.master

---

stack.yml

armory/kayenta-armory:2022.12.16.05.57.53.release-2.28.x
[0333b9ed6153acfc090edcfa38e3514439e2863c](https://github.com/armory-io/kayenta-armory/commit/0333b9ed6153acfc090edcfa38e3514439e2863c)
[b90c703436e12a6c05d7e782fc68c66b523dc934](https://github.com/spinnaker/kayenta/commit/b90c703436e12a6c05d7e782fc68c66b523dc934)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b90c703436e12a6c05d7e782fc68c66b523dc934"
},
"details": {
"image": {
"imageId": "sha256:af024d71f2edb7cc8543bf6657faffee660a02eb3e574804b54acde8bd9cc6b6",
"tag": "2022.12.16.05.57.53.release-2.28.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update kayenta-armory version to 2022.12.16.05.57.53.release-2.28.x

---

stack.yml

armory/kayenta-armory:2022.12.16.05.58.57.release-2.27.x
[5a1efcefddfe78f37550f5bee723570e3737ce04](https://github.com/armory-io/kayenta-armory/commit/5a1efcefddfe78f37550f5bee723570e3737ce04)
[fa061cad97b941add78f1fd9fc4da0eb86f4e35b](https://github.com/spinnaker/kayenta/commit/fa061cad97b941add78f1fd9fc4da0eb86f4e35b)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "fa061cad97b941add78f1fd9fc4da0eb86f4e35b"
},
"details": {
"image": {
"imageId": "sha256:95c940b3bb81953710db7f02d16b204e67edb9250360f735f6b730387f7d0d18",
"tag": "2022.12.16.05.58.57.release-2.27.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update kayenta-armory version to 2022.12.16.05.58.57.release-2.27.x

---

stack.yml

* **master**
armory/deck-armory:2022.12.19.13.18.36.master
[73c09670d7b2ad87e4ae5eaa7cb9d8755fdeb19c](https://github.com/armory-io/deck-armory/commit/73c09670d7b2ad87e4ae5eaa7cb9d8755fdeb19c)
[66207875f1386a3271ced770cd38227b5888c1da](https://github.com/spinnaker/deck/commit/66207875f1386a3271ced770cd38227b5888c1da)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "66207875f1386a3271ced770cd38227b5888c1da"
},
"details": {
"image": {
"imageId": "sha256:7b7ca8aaeafe3e13e28112e31b54213eb8b7809e7a3d9a0e3d2ca88d45512186",
"tag": "2022.12.19.13.18.36.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update deck-armory version to 2022.12.19.13.18.36.master

---

stack.yml

armory/clouddriver-armory:2023.01.10.17.54.12.release-2.27.x
[c978d08b3f5d155e8efbfb9010520d848bf4a93c](https://github.com/armory-io/clouddriver-armory/commit/c978d08b3f5d155e8efbfb9010520d848bf4a93c)
[b1cd05549b5eb32c34c7ad8d94cf12cc9651b7d3](https://github.com/spinnaker/clouddriver/commit/b1cd05549b5eb32c34c7ad8d94cf12cc9651b7d3)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b1cd05549b5eb32c34c7ad8d94cf12cc9651b7d3"
},
"details": {
"image": {
"imageId": "sha256:210292ec03a0118c1d208a6e055c11217136d785eef6ac39a724c438018dfa95",
"tag": "2023.01.10.17.54.12.release-2.27.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.01.10.17.54.12.release-2.27.x

---

stack.yml

* **master**
armory/clouddriver-armory:2023.01.11.19.04.16.master
[85aeb8ebf69ef9e912574bc0af57619dbd359109](https://github.com/armory-io/clouddriver-armory/commit/85aeb8ebf69ef9e912574bc0af57619dbd359109)
[2dc786fd4cef9ff584e9cbc0a1d94db8941ea384](https://github.com/spinnaker/clouddriver/commit/2dc786fd4cef9ff584e9cbc0a1d94db8941ea384)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "2dc786fd4cef9ff584e9cbc0a1d94db8941ea384"
},
"details": {
"image": {
"imageId": "sha256:ced627053fbfdc38895607c9dc8432cdd182d1f4f7fb886c64948af72344dbe1",
"tag": "2023.01.11.19.04.16.master"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update clouddriver-armory version to 2023.01.11.19.04.16.master

---

stack.yml

* **master**
armory/fiat-armory:2023.01.19.19.11.07.master
[c6e39f81ec73fc49a560a6bed17e0410f0cd727e](https://github.com/armory-io/fiat-armory/commit/c6e39f81ec73fc49a560a6bed17e0410f0cd727e)
[8c622d1a3983e0b7b0e3211c6ed0fa11dc37e3ee](https://github.com/spinnaker/fiat/commit/8c622d1a3983e0b7b0e3211c6ed0fa11dc37e3ee)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "8c622d1a3983e0b7b0e3211c6ed0fa11dc37e3ee"
},
"details": {
"image": {
"imageId": "sha256:4f768f5b6ace76cb58c00d336b17df5c08a29b7ff09890bf283c300757852517",
"tag": "2023.01.19.19.11.07.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update fiat-armory version to 2023.01.19.19.11.07.master

---

stack.yml

armory/echo-armory:2023.01.20.16.22.48.release-2.28.x
[53bebfd6900b3de124dde043a00d164aa2e50773](https://github.com/armory-io/echo-armory/commit/53bebfd6900b3de124dde043a00d164aa2e50773)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:55488757334cdbb5206452525c18f91898205d8d20441fb48c26595184ffa0ec",
"tag": "2023.01.20.16.22.48.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "53bebfd6900b3de124dde043a00d164aa2e50773"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update echo-armory version to 2023.01.20.16.22.48.release-2.28.x

---

stack.yml

armory/clouddriver-armory:2023.01.20.18.41.30.release-2.27.x
[60eafebf9875071709e3d8ec53d2729a197574f1](https://github.com/armory-io/clouddriver-armory/commit/60eafebf9875071709e3d8ec53d2729a197574f1)
[b6a03baffa569f6e6455dac9fd89f6747e9a8683](https://github.com/spinnaker/clouddriver/commit/b6a03baffa569f6e6455dac9fd89f6747e9a8683)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b6a03baffa569f6e6455dac9fd89f6747e9a8683"
},
"details": {
"image": {
"imageId": "sha256:e99e8f12cdf10b1872f0619343534d9e2f445906b29647cf28eca436bfa746bb",
"tag": "2023.01.20.18.41.30.release-2.27.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.01.20.18.41.30.release-2.27.x

---

stack.yml

* **master**
armory/kayenta-armory:2023.01.23.22.14.56.master
[4b35422823777882715906c017f0ddb7afb7768c](https://github.com/armory-io/kayenta-armory/commit/4b35422823777882715906c017f0ddb7afb7768c)
[eaaadcbd8490e247f86fd56b5faf9293d303e894](https://github.com/spinnaker/kayenta/commit/eaaadcbd8490e247f86fd56b5faf9293d303e894)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "eaaadcbd8490e247f86fd56b5faf9293d303e894"
},
"details": {
"image": {
"imageId": "sha256:a1e2203057c8f3fe9da1c14623101f39a485e2d9ca12c58f61f2bd3ddfd0fb71",
"tag": "2023.01.23.22.14.56.master"
},
"vcs": {
"repo": {
"repoName": …
```

chore(cd): update kayenta-armory version to 2023.01.23.22.14.56.master

---

stack.yml

* **master**
armory/deck-armory:2023.01.10.16.41.16.master
[7843a304131e155de97036640df7015f3e60f767](https://github.com/armory-io/deck-armory/commit/7843a304131e155de97036640df7015f3e60f767)
[deba01ed7ba275194f51bcc0cbf414bbf3266562](https://github.com/spinnaker/deck/commit/deba01ed7ba275194f51bcc0cbf414bbf3266562)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "deba01ed7ba275194f51bcc0cbf414bbf3266562"
},
"details": {
"image": {
"imageId": "sha256:6225c262864513e57f64b08d937485e998db451fcf60889b0fe5f401d87f0777",
"tag": "2023.01.10.16.41.16.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update deck-armory version to 2023.01.10.16.41.16.master

---

stack.yml

armory/clouddriver-armory:2023.01.30.19.04.27.release-2.28.x
[d52c864053d77a05eef806926591427bc866b529](https://github.com/armory-io/clouddriver-armory/commit/d52c864053d77a05eef806926591427bc866b529)
[2fa2b60dae9bc4f32ffdec9404160acd4fb3069d](https://github.com/spinnaker/clouddriver/commit/2fa2b60dae9bc4f32ffdec9404160acd4fb3069d)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "2fa2b60dae9bc4f32ffdec9404160acd4fb3069d"
},
"details": {
"image": {
"imageId": "sha256:feca1b9adcb14d3cbf86b6882aa67bf27e2e6805c53078f14a710a49d70ab08c",
"tag": "2023.01.30.19.04.27.release-2.28.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.01.30.19.04.27.release-2.28.x

---

stack.yml

armory/deck-armory:2023.02.03.16.46.18.release-2.28.x
[bd57caffcdc86c9fb7560e958ba89141372d5d3d](https://github.com/armory-io/deck-armory/commit/bd57caffcdc86c9fb7560e958ba89141372d5d3d)
[3b8b22aaf8ae66457212fa617718f73f0e675349](https://github.com/spinnaker/deck/commit/3b8b22aaf8ae66457212fa617718f73f0e675349)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "3b8b22aaf8ae66457212fa617718f73f0e675349"
},
"details": {
"image": {
"imageId": "sha256:24bcef6bcff23a9e673681a09e6ddbaedc693f5e853a869190c2d075a55892fc",
"tag": "2023.02.03.16.46.18.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2023.02.03.16.46.18.release-2.28.x

---

stack.yml

armory/orca-armory:2023.02.03.15.22.10.release-2.28.x
[37f945ea4ca839267ddd95e436912ef8f82d559e](https://github.com/armory-io/orca-armory/commit/37f945ea4ca839267ddd95e436912ef8f82d559e)
[107ff38dff1c90243606b80faf6a97f76d327fbd](https://github.com/spinnaker/orca/commit/107ff38dff1c90243606b80faf6a97f76d327fbd)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "107ff38dff1c90243606b80faf6a97f76d327fbd"
},
"details": {
"image": {
"imageId": "sha256:bc640b0e1238e73e767f50bde0162db5da4cd259b6062414008f2d28df25d5a4",
"tag": "2023.02.03.15.22.10.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2023.02.03.15.22.10.release-2.28.x

---

stack.yml

armory/deck-armory:2023.02.03.16.43.49.release-2.27.x
[be6776c69c18743de1df214acaa500250569a146](https://github.com/armory-io/deck-armory/commit/be6776c69c18743de1df214acaa500250569a146)
[91df4ee661450b04c73232d6c54ae00e96844945](https://github.com/spinnaker/deck/commit/91df4ee661450b04c73232d6c54ae00e96844945)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "91df4ee661450b04c73232d6c54ae00e96844945"
},
"details": {
"image": {
"imageId": "sha256:daea9538724714ead42000cf1cfe3c1fe1f88936acedc195fe960d26f217f5c7",
"tag": "2023.02.03.16.43.49.release-2.27.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2023.02.03.16.43.49.release-2.27.x

---

stack.yml

* **master**
armory/fiat-armory:2023.02.07.15.34.39.master
[d855d9d47fc2772e4beb561d67d3fdd23db6b974](https://github.com/armory-io/fiat-armory/commit/d855d9d47fc2772e4beb561d67d3fdd23db6b974)
[7f84ae1c746b997f3528a68bde50cd0cdc9d3519](https://github.com/spinnaker/fiat/commit/7f84ae1c746b997f3528a68bde50cd0cdc9d3519)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7f84ae1c746b997f3528a68bde50cd0cdc9d3519"
},
"details": {
"image": {
"imageId": "sha256:1317b9be6d48d6b57a64b4f2d59f8bd63fb9d1270b817bf0ebc0d9271cb6076c",
"tag": "2023.02.07.15.34.39.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update fiat-armory version to 2023.02.07.15.34.39.master

---

stack.yml

* **master**
armory/kayenta-armory:2023.01.24.16.36.23.master
[ff12c509aec3f18ebf6b817dd260be10297ab241](https://github.com/armory-io/kayenta-armory/commit/ff12c509aec3f18ebf6b817dd260be10297ab241)
[7925c8927a66b706f4a5ee222e06334819af4675](https://github.com/spinnaker/kayenta/commit/7925c8927a66b706f4a5ee222e06334819af4675)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7925c8927a66b706f4a5ee222e06334819af4675"
},
"details": {
"image": {
"imageId": "sha256:c4b9f8fc12d74ceb877f4949a6faa02bbbbb607203991b1f57120cdaa126fb90",
"tag": "2023.01.24.16.36.23.master"
},
"vcs": {
"repo": {
"repoName": …
```

chore(cd): update kayenta-armory version to 2023.01.24.16.36.23.master

---

stack.yml

* **master**
armory/echo-armory:2023.01.30.16.37.40.master
[17198e9b6ad50a96077f8fe861e34528f7e0c38f](https://github.com/armory-io/echo-armory/commit/17198e9b6ad50a96077f8fe861e34528f7e0c38f)
[7b7abee4f57f0b35f46e51b84d926706f99afc23](https://github.com/spinnaker/echo/commit/7b7abee4f57f0b35f46e51b84d926706f99afc23)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7b7abee4f57f0b35f46e51b84d926706f99afc23"
},
"details": {
"image": {
"imageId": "sha256:b86d5cbdff3fa28922d1777c373298c47113ba9dcc8bb5ad23b99c1322eb0508",
"tag": "2023.01.30.16.37.40.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update echo-armory version to 2023.01.30.16.37.40.master

---

stack.yml

* **master**
armory/deck-armory:2023.02.07.09.40.18.master
[af26c011045528b2af60ff5f9f6bf775a38afc27](https://github.com/armory-io/deck-armory/commit/af26c011045528b2af60ff5f9f6bf775a38afc27)
[898a59504ea58a456baf19e0a21a4cace683feb7](https://github.com/spinnaker/deck/commit/898a59504ea58a456baf19e0a21a4cace683feb7)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "898a59504ea58a456baf19e0a21a4cace683feb7"
},
"details": {
"image": {
"imageId": "sha256:97fdd7d2dad4cce7827ae913a5f2c3e09710ad6a7c43515913f6ae6eb55d3a26",
"tag": "2023.02.07.09.40.18.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update deck-armory version to 2023.02.07.09.40.18.master

---

stack.yml

* **master**
armory/dinghy:2023.02.06.12.26.38.master
[eaf522291c3ce3ff654adac5b46cac2c1dca25a4](https://github.com/armory-io/dinghy/commit/eaf522291c3ce3ff654adac5b46cac2c1dca25a4)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:cf82dee33077a62da59aed4ddc0cc1fe58a786c8ba0397913e008169d22a3e97",
"tag": "2023.02.06.12.26.38.master"
},
"vcs": {
"repo": {
},
"sha": "eaf522291c3ce3ff654adac5b46cac2c1dca25a4"
}
},
},
"details": {
"image": {
"imageId": "sha256:cf82dee33077a62da59aed4ddc0cc1fe58a786c8ba0397913e008169d22a3e97", …
```

chore(cd): update dinghy version to 2023.02.06.12.26.38.master

---

stack.yml

armory/rosco-armory:2023.01.11.00.14.21.release-2.29.x
[c341c29fe5f8ec293a7b62763a7a528bdd51b50f](https://github.com/armory-io/rosco-armory/commit/c341c29fe5f8ec293a7b62763a7a528bdd51b50f)
[7ef77ca293cccde2f3263e3c0d5b8c663dfe62aa](https://github.com/spinnaker/rosco/commit/7ef77ca293cccde2f3263e3c0d5b8c663dfe62aa)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7ef77ca293cccde2f3263e3c0d5b8c663dfe62aa"
},
"details": {
"image": {
"imageId": "sha256:43006e805c3d3db7160f9faf6e23b5deead7288eba1212a5eee6c4207d2b900a",
"tag": "2023.01.11.00.14.21.release-2.29.x"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2023.01.11.00.14.21.release-2.29.x

---

stack.yml

armory/clouddriver-armory:2023.01.27.18.06.25.release-2.27.x
[dc29b777268954cce13b1b36b152d4e2a493caa9](https://github.com/armory-io/clouddriver-armory/commit/dc29b777268954cce13b1b36b152d4e2a493caa9)
[79ee9e88fb0d7c5aaf6565ff3128b76e71ff286e](https://github.com/spinnaker/clouddriver/commit/79ee9e88fb0d7c5aaf6565ff3128b76e71ff286e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "79ee9e88fb0d7c5aaf6565ff3128b76e71ff286e"
},
"details": {
"image": {
"imageId": "sha256:b19071ad12aff26c91e48cd2437d63ae3d3cddbae2fdec92732d6a3b56420cd9",
"tag": "2023.01.27.18.06.25.release-2.27.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.01.27.18.06.25.release-2.27.x

---

stack.yml

armory/orca-armory:2023.02.08.03.06.01.release-2.27.x
[b239fa305820b1102d38fe4d0beeaca847c0f4f2](https://github.com/armory-io/orca-armory/commit/b239fa305820b1102d38fe4d0beeaca847c0f4f2)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:03e42e7048c8bf9f1a34d261ec25079f16dd624d0b7f634c4c4d4604ef553365",
"tag": "2023.02.08.03.06.01.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "b239fa305820b1102d38fe4d0beeaca847c0f4f2"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update orca-armory version to 2023.02.08.03.06.01.release-2.27.x

---

stack.yml

armory/fiat-armory:2023.02.07.19.28.22.release-2.28.x
[e5eb6837f87b029248e3068119e05acbb85cf22c](https://github.com/armory-io/fiat-armory/commit/e5eb6837f87b029248e3068119e05acbb85cf22c)
[2088171e5a2fb327c70982634e3db3a2d9291896](https://github.com/spinnaker/fiat/commit/2088171e5a2fb327c70982634e3db3a2d9291896)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "2088171e5a2fb327c70982634e3db3a2d9291896"
},
"details": {
"image": {
"imageId": "sha256:20b8099fd97351afee82b120c21dd32c37e8d99bca59c0d13349458c0ff9ef3e",
"tag": "2023.02.07.19.28.22.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update fiat-armory version to 2023.02.07.19.28.22.release-2.28.x

---

stack.yml

* **master**
armory/clouddriver-armory:2023.02.14.05.23.07.master
[ed5958f3fc3e6138cdbbcae72654cd9314f4347d](https://github.com/armory-io/clouddriver-armory/commit/ed5958f3fc3e6138cdbbcae72654cd9314f4347d)
[27ed95187797d8553676d54fc75b240586902386](https://github.com/spinnaker/clouddriver/commit/27ed95187797d8553676d54fc75b240586902386)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "27ed95187797d8553676d54fc75b240586902386"
},
"details": {
"image": {
"imageId": "sha256:ebf85c7fe31e25b2a0804bbc85c683c8aaf792d3cd580405da0c7a1132c1a8d5",
"tag": "2023.02.14.05.23.07.master"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update clouddriver-armory version to 2023.02.14.05.23.07.master

---

stack.yml

* **master**
armory/echo-armory:2023.02.10.05.44.53.master
[120b88bf6af082a3272e525fdb64d857d7978130](https://github.com/armory-io/echo-armory/commit/120b88bf6af082a3272e525fdb64d857d7978130)
[8edb2b7ce5081c9558309d02c8d49e913a06e4ad](https://github.com/spinnaker/echo/commit/8edb2b7ce5081c9558309d02c8d49e913a06e4ad)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "8edb2b7ce5081c9558309d02c8d49e913a06e4ad"
},
"details": {
"image": {
"imageId": "sha256:624054275ced242744fdf94001d181bf0532a8626e04cdf13bc15b3628ab9d72",
"tag": "2023.02.10.05.44.53.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update echo-armory version to 2023.02.10.05.44.53.master

---

stack.yml

* **master**
armory/fiat-armory:2023.02.09.06.40.35.master
[9575cd95c8174bd5d26414af68946b2f9b09145b](https://github.com/armory-io/fiat-armory/commit/9575cd95c8174bd5d26414af68946b2f9b09145b)
[8248d57cd0ef5af2af751276a445e6a1a5d6296d](https://github.com/spinnaker/fiat/commit/8248d57cd0ef5af2af751276a445e6a1a5d6296d)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "8248d57cd0ef5af2af751276a445e6a1a5d6296d"
},
"details": {
"image": {
"imageId": "sha256:d4c3f0214ba146cf4005d2a77550a7abe3bfa1d89ca2dc3b25a979e0b79353bb",
"tag": "2023.02.09.06.40.35.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update fiat-armory version to 2023.02.09.06.40.35.master

---

stack.yml

* **master**
armory/clouddriver-armory:2023.02.15.21.27.04.master
[4c7802f08a069be91f3b954957a7436c0bf9e322](https://github.com/armory-io/clouddriver-armory/commit/4c7802f08a069be91f3b954957a7436c0bf9e322)
[19aca8488a3bc9a6df381721b1e791a9487be9f6](https://github.com/spinnaker/clouddriver/commit/19aca8488a3bc9a6df381721b1e791a9487be9f6)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "19aca8488a3bc9a6df381721b1e791a9487be9f6"
},
"details": {
"image": {
"imageId": "sha256:2c89d9064563752bca88a347b60215a78c16e8e380dfd51b5767bf969528a7e3",
"tag": "2023.02.15.21.27.04.master"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update clouddriver-armory version to 2023.02.15.21.27.04.master

---

stack.yml

armory/clouddriver-armory:2023.02.15.21.56.07.release-2.28.x
[35dd10a5a2a262c4456d54e2bffd3db4a434fbf3](https://github.com/armory-io/clouddriver-armory/commit/35dd10a5a2a262c4456d54e2bffd3db4a434fbf3)
[eb54d18bca75c2d6cca74a57d9e0e4699696ce6f](https://github.com/spinnaker/clouddriver/commit/eb54d18bca75c2d6cca74a57d9e0e4699696ce6f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "eb54d18bca75c2d6cca74a57d9e0e4699696ce6f"
},
"details": {
"image": {
"imageId": "sha256:b1c4e950951ea2bdb38d5987e00b34be39d3fbd9ad7aead4fc0257ba387dc752",
"tag": "2023.02.15.21.56.07.release-2.28.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.02.15.21.56.07.release-2.28.x

---

stack.yml

armory/clouddriver-armory:2023.02.22.23.13.46.release-2.28.x
[49c6d33aebf5c6edcd85904680afac4698e9e208](https://github.com/armory-io/clouddriver-armory/commit/49c6d33aebf5c6edcd85904680afac4698e9e208)
[b7a4239b30cacf31cbf121d803e5956091e8534f](https://github.com/spinnaker/clouddriver/commit/b7a4239b30cacf31cbf121d803e5956091e8534f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b7a4239b30cacf31cbf121d803e5956091e8534f"
},
"details": {
"image": {
"imageId": "sha256:d078a432ad35641b7add5a13c62286f6ae446b81a9277b96e2fb568b37cc9afe",
"tag": "2023.02.22.23.13.46.release-2.28.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.02.22.23.13.46.release-2.28.x

---

stack.yml

armory/clouddriver-armory:2023.02.22.23.28.39.release-2.27.x
[a72e4a50b6477f836e7e99d1df8fc050f4988988](https://github.com/armory-io/clouddriver-armory/commit/a72e4a50b6477f836e7e99d1df8fc050f4988988)
[4c9578485f586a8761074f484225989f0e0c2b42](https://github.com/spinnaker/clouddriver/commit/4c9578485f586a8761074f484225989f0e0c2b42)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4c9578485f586a8761074f484225989f0e0c2b42"
},
"details": {
"image": {
"imageId": "sha256:05314810b7d3bfe076414de1322ed0a963746bd6507fade2f8f47e885be3b886",
"tag": "2023.02.22.23.28.39.release-2.27.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.02.22.23.28.39.release-2.27.x

---

stack.yml

* **master**
armory/clouddriver-armory:2023.02.23.17.41.23.master
[ba836d1e6e2825c0745caec226a57858836b3ec9](https://github.com/armory-io/clouddriver-armory/commit/ba836d1e6e2825c0745caec226a57858836b3ec9)
[a4557e9a7ff2e8307fca2eb11eba9aa65d24438a](https://github.com/spinnaker/clouddriver/commit/a4557e9a7ff2e8307fca2eb11eba9aa65d24438a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a4557e9a7ff2e8307fca2eb11eba9aa65d24438a"
},
"details": {
"image": {
"imageId": "sha256:db1b28e2be1355ffeb662acc0399dee3e1f49cebf13b3a16d696452d252561fa",
"tag": "2023.02.23.17.41.23.master"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update clouddriver-armory version to 2023.02.23.17.41.23.master

---

stack.yml

* **master**
armory/deck-armory:2023.02.20.13.55.59.master
[4e2541bb15f06ce8b1e4e2b0c6356207a1faaa35](https://github.com/armory-io/deck-armory/commit/4e2541bb15f06ce8b1e4e2b0c6356207a1faaa35)
[21bd84315ab519ae2c72adb6605b237b728352a0](https://github.com/spinnaker/deck/commit/21bd84315ab519ae2c72adb6605b237b728352a0)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "21bd84315ab519ae2c72adb6605b237b728352a0"
},
"details": {
"image": {
"imageId": "sha256:c0e97a3357b870db185b136b602b8f744f433c30d26a1830fa16fbb218dcde45",
"tag": "2023.02.20.13.55.59.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update deck-armory version to 2023.02.20.13.55.59.master

---

stack.yml

* **master**
armory/fiat-armory:2023.02.20.20.00.50.master
[af81ca00fba193cfe464dad7e776c7eb4fc2d83f](https://github.com/armory-io/fiat-armory/commit/af81ca00fba193cfe464dad7e776c7eb4fc2d83f)
[37b8a059d96f4e52147a1b406bedf771e4b02f81](https://github.com/spinnaker/fiat/commit/37b8a059d96f4e52147a1b406bedf771e4b02f81)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "37b8a059d96f4e52147a1b406bedf771e4b02f81"
},
"details": {
"image": {
"imageId": "sha256:67fd5d9e5a4cfb93829ca59ea8cdbc34b5c7642df903daefacb7b67634a648bd",
"tag": "2023.02.20.20.00.50.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update fiat-armory version to 2023.02.20.20.00.50.master

---

stack.yml

* **master**
armory/echo-armory:2023.02.20.21.18.14.master
[1a368a8dba383bfe661ae55a51db71a9edf5a595](https://github.com/armory-io/echo-armory/commit/1a368a8dba383bfe661ae55a51db71a9edf5a595)
[37a155e7ac12ee7b8e01757c4d93ca375fa9c176](https://github.com/spinnaker/echo/commit/37a155e7ac12ee7b8e01757c4d93ca375fa9c176)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "37a155e7ac12ee7b8e01757c4d93ca375fa9c176"
},
"details": {
"image": {
"imageId": "sha256:d5518c6ad0d93f45cd181567b688f672029e845e802529e60f987be5e4b1d5d8",
"tag": "2023.02.20.21.18.14.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update echo-armory version to 2023.02.20.21.18.14.master

---

stack.yml

armory/gate-armory:2023.02.28.17.57.41.release-2.27.x
[1c78a1af5c23eb5328de67ce37439337b8bade33](https://github.com/armory-io/gate-armory/commit/1c78a1af5c23eb5328de67ce37439337b8bade33)
[4875a9202979bfe10757172969ea128dd620975f](https://github.com/spinnaker/gate/commit/4875a9202979bfe10757172969ea128dd620975f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4875a9202979bfe10757172969ea128dd620975f"
},
"details": {
"image": {
"imageId": "sha256:9977a0d2e6500d61e44ae87eaf944a03e97bc96e2f1b7639ee558f2c349f1083",
"tag": "2023.02.28.17.57.41.release-2.27.x"
},
"vcs": {
"repo": { …
```

chore(cd): update gate-armory version to 2023.02.28.17.57.41.release-2.27.x

---

stack.yml

armory/orca-armory:2023.02.28.19.38.44.release-2.27.x
[2aa5a723767a5972a3b31278a1dcf5af32e66b99](https://github.com/armory-io/orca-armory/commit/2aa5a723767a5972a3b31278a1dcf5af32e66b99)
[2c26b6574d683ccaec7e50216da65ae009f233a2](https://github.com/spinnaker/orca/commit/2c26b6574d683ccaec7e50216da65ae009f233a2)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "2c26b6574d683ccaec7e50216da65ae009f233a2"
},
"details": {
"image": {
"imageId": "sha256:7ec6c5fcc5d87036871cbc05daba809b953ac3593a5873903e5f3c27719451e8",
"tag": "2023.02.28.19.38.44.release-2.27.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2023.02.28.19.38.44.release-2.27.x

---

stack.yml

armory/clouddriver-armory:2023.02.28.18.32.41.release-2.27.x
[f3d4f75475874178325d53fa488c37cd9e3814fa](https://github.com/armory-io/clouddriver-armory/commit/f3d4f75475874178325d53fa488c37cd9e3814fa)
[2d0d6e0105ef0af2c669345efe945cecfdd19314](https://github.com/spinnaker/clouddriver/commit/2d0d6e0105ef0af2c669345efe945cecfdd19314)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "2d0d6e0105ef0af2c669345efe945cecfdd19314"
},
"details": {
"image": {
"imageId": "sha256:ab65737a1b0288134a020097dabf8fda6fb53b2ff8f4bf504a7c1001e313ac0a",
"tag": "2023.02.28.18.32.41.release-2.27.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.02.28.18.32.41.release-2.27.x

---

stack.yml

armory/kayenta-armory:2023.02.28.21.43.52.release-2.27.x
[822b3339a4dbbccb9a135c102d8ba1ff199d49ec](https://github.com/armory-io/kayenta-armory/commit/822b3339a4dbbccb9a135c102d8ba1ff199d49ec)
[a67db92fb2ac468bddd6d44feadc91fb4c4df51e](https://github.com/spinnaker/kayenta/commit/a67db92fb2ac468bddd6d44feadc91fb4c4df51e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a67db92fb2ac468bddd6d44feadc91fb4c4df51e"
},
"details": {
"image": {
"imageId": "sha256:5c258ef23ac0cf3f6b9aa565ab2d1d5603811ae7374480a172e5939e4fbe1b4d",
"tag": "2023.02.28.21.43.52.release-2.27.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update kayenta-armory version to 2023.02.28.21.43.52.release-2.27.x

---

stack.yml

armory/rosco-armory:2023.02.28.18.00.39.release-2.27.x
[8b94ccff09fe762d896df9052e4199af6dd9b666](https://github.com/armory-io/rosco-armory/commit/8b94ccff09fe762d896df9052e4199af6dd9b666)
[7310481cc629423f4c4b3ea8b58717abb1582876](https://github.com/spinnaker/rosco/commit/7310481cc629423f4c4b3ea8b58717abb1582876)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7310481cc629423f4c4b3ea8b58717abb1582876"
},
"details": {
"image": {
"imageId": "sha256:74d457dda98df9e922ea31cfe61201e11ed302c7a2a7d7bcd16175b27adbec59",
"tag": "2023.02.28.18.00.39.release-2.27.x"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2023.02.28.18.00.39.release-2.27.x

---

stack.yml

armory/gate-armory:2023.02.28.19.34.47.release-2.27.x
[9cd1a1174ee0bd19577ffdbd6aa11ad432a67082](https://github.com/armory-io/gate-armory/commit/9cd1a1174ee0bd19577ffdbd6aa11ad432a67082)
[b8360a013ded6a5961a3f57a4deed67c27eec944](https://github.com/spinnaker/gate/commit/b8360a013ded6a5961a3f57a4deed67c27eec944)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b8360a013ded6a5961a3f57a4deed67c27eec944"
},
"details": {
"image": {
"imageId": "sha256:3589b85a88edea8a8dfc6c837d6a4d2816b1fa7d96186fd6cbb75225bfff58bd",
"tag": "2023.02.28.19.34.47.release-2.27.x"
},
"vcs": {
"repo": { …
```

chore(cd): update gate-armory version to 2023.02.28.19.34.47.release-2.27.x

---

stack.yml

armory/igor-armory:2023.02.28.19.35.11.release-2.27.x
[ebfdd8b8068fe1ff1ba3e7c25cd2b0c0fa803bd9](https://github.com/armory-io/igor-armory/commit/ebfdd8b8068fe1ff1ba3e7c25cd2b0c0fa803bd9)
[11b9dcd10cd2d96b0852a66212075c2f0b77ddcd](https://github.com/spinnaker/igor/commit/11b9dcd10cd2d96b0852a66212075c2f0b77ddcd)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "11b9dcd10cd2d96b0852a66212075c2f0b77ddcd"
},
"details": {
"image": {
"imageId": "sha256:709fe8ff37f77c67df88a7d44e4a10a4bf7811e2a692c6896a0bdf37525e8a13",
"tag": "2023.02.28.19.35.11.release-2.27.x"
},
"vcs": {
"repo": { …
```

chore(cd): update igor-armory version to 2023.02.28.19.35.11.release-2.27.x

---

stack.yml

armory/clouddriver-armory:2023.03.02.21.53.00.release-2.27.x
[477cb53ae00642331377db1ad21ae52b5ff998a7](https://github.com/armory-io/clouddriver-armory/commit/477cb53ae00642331377db1ad21ae52b5ff998a7)
[b6cfc3b352d4ba812b70a08b1fdc1755f49a3edb](https://github.com/spinnaker/clouddriver/commit/b6cfc3b352d4ba812b70a08b1fdc1755f49a3edb)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b6cfc3b352d4ba812b70a08b1fdc1755f49a3edb"
},
"details": {
"image": {
"imageId": "sha256:e64f9bec3c3cf181b34679ed0afbaf15eb0e6cf1eb5c4a3de76eb026c2b7adbc",
"tag": "2023.03.02.21.53.00.release-2.27.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.03.02.21.53.00.release-2.27.x

---

stack.yml

armory/echo-armory:2023.03.02.21.31.31.release-2.28.x
[0f80b381e69e958784302fa9506e2f7e17bdcd11](https://github.com/armory-io/echo-armory/commit/0f80b381e69e958784302fa9506e2f7e17bdcd11)
[48b04bc2038abb5f3f66cca05309ed2cf5a119b9](https://github.com/spinnaker/echo/commit/48b04bc2038abb5f3f66cca05309ed2cf5a119b9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "48b04bc2038abb5f3f66cca05309ed2cf5a119b9"
},
"details": {
"image": {
"imageId": "sha256:5837c2fad5f0daf8760604d3124e27c038764903cd6d6a6adc8e45e970d5be44",
"tag": "2023.03.02.21.31.31.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update echo-armory version to 2023.03.02.21.31.31.release-2.28.x

---

stack.yml

armory/rosco-armory:2023.03.02.20.13.03.release-2.28.x
[12b901a2270bba8971c4b44b47e9256db95cd9b4](https://github.com/armory-io/rosco-armory/commit/12b901a2270bba8971c4b44b47e9256db95cd9b4)
[17d001df520a0d2256055f99f8bc4989346c8910](https://github.com/spinnaker/rosco/commit/17d001df520a0d2256055f99f8bc4989346c8910)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "17d001df520a0d2256055f99f8bc4989346c8910"
},
"details": {
"image": {
"imageId": "sha256:31696ed26cab6ecf5b28890b1cb9a8ae9a517cc0adb04d93bb29b48b97a6195b",
"tag": "2023.03.02.20.13.03.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2023.03.02.20.13.03.release-2.28.x

---

stack.yml

armory/orca-armory:2023.03.02.21.36.38.release-2.28.x
[50649da9a4a707f49b180ae50df5ff617ed5e159](https://github.com/armory-io/orca-armory/commit/50649da9a4a707f49b180ae50df5ff617ed5e159)
[66ef088a2a53476e94c10c9140bb4ac33ca8da93](https://github.com/spinnaker/orca/commit/66ef088a2a53476e94c10c9140bb4ac33ca8da93)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "66ef088a2a53476e94c10c9140bb4ac33ca8da93"
},
"details": {
"image": {
"imageId": "sha256:db2454b9cf4b50f095ae56de4b484e8fa84f7d96b4f9e6a25cab088c31a42484",
"tag": "2023.03.02.21.36.38.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2023.03.02.21.36.38.release-2.28.x

---

stack.yml

armory/gate-armory:2023.03.02.21.32.13.release-2.28.x
[a8f59e2ccf13e7cd4072decd2b80eb4542f9e884](https://github.com/armory-io/gate-armory/commit/a8f59e2ccf13e7cd4072decd2b80eb4542f9e884)
[be97e2adf5e366162fab128b305dae1616cd42cb](https://github.com/spinnaker/gate/commit/be97e2adf5e366162fab128b305dae1616cd42cb)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "be97e2adf5e366162fab128b305dae1616cd42cb"
},
"details": {
"image": {
"imageId": "sha256:25dcc0d77e07cf828c9ccbef1c96894394fb2c2424e89414bc86fcd04ac0e867",
"tag": "2023.03.02.21.32.13.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update gate-armory version to 2023.03.02.21.32.13.release-2.28.x

---

stack.yml

armory/clouddriver-armory:2023.03.03.02.47.51.release-2.28.x
[809dbbab935ebdd5bfa78a9b7259c00d7d1c9d5b](https://github.com/armory-io/clouddriver-armory/commit/809dbbab935ebdd5bfa78a9b7259c00d7d1c9d5b)
[b0d6a8ef4d935eeaa78190d111198e9229cfc189](https://github.com/spinnaker/clouddriver/commit/b0d6a8ef4d935eeaa78190d111198e9229cfc189)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b0d6a8ef4d935eeaa78190d111198e9229cfc189"
},
"details": {
"image": {
"imageId": "sha256:d9f112ae03175cf5dd95c177fffcb19fec39dabb0c45e215478c107b31fbe102",
"tag": "2023.03.03.02.47.51.release-2.28.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.03.03.02.47.51.release-2.28.x

---

stack.yml

armory/kayenta-armory:2023.03.03.05.15.20.release-2.28.x
[705629b88f6532d4f81dcd8063a31ad55a0ee29b](https://github.com/armory-io/kayenta-armory/commit/705629b88f6532d4f81dcd8063a31ad55a0ee29b)
[c99c5f1e6e458586ae6bffc651f5934571fc4138](https://github.com/spinnaker/kayenta/commit/c99c5f1e6e458586ae6bffc651f5934571fc4138)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c99c5f1e6e458586ae6bffc651f5934571fc4138"
},
"details": {
"image": {
"imageId": "sha256:821e1915a0af0acddbcb4bcb00747e980148a28f088363f1ba16963973d52a87",
"tag": "2023.03.03.05.15.20.release-2.28.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update kayenta-armory version to 2023.03.03.05.15.20.release-2.28.x

---

stack.yml

* **master**
armory/dinghy:2023.03.08.19.45.23.master
[5250de80948732c8caac6ffc5293a8af80a63a0f](https://github.com/armory-io/dinghy/commit/5250de80948732c8caac6ffc5293a8af80a63a0f)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:40a7e7b7e5234a369b646a6c1dbceaf87f66e0537e150204fe3ae1e0360ecb29",
"tag": "2023.03.08.19.45.23.master"
},
"vcs": {
"repo": {
},
"sha": "5250de80948732c8caac6ffc5293a8af80a63a0f"
}
},
},
"details": {
"image": {
"imageId": "sha256:40a7e7b7e5234a369b646a6c1dbceaf87f66e0537e150204fe3ae1e0360ecb29", …
```

chore(cd): update dinghy version to 2023.03.08.19.45.23.master

---

stack.yml

armory/dinghy:2023.03.08.23.37.20.release-2.28.x
[912007004f7720b418cd133301c7fb20207e1f2f](https://github.com/armory-io/dinghy/commit/912007004f7720b418cd133301c7fb20207e1f2f)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:45ab1532bbb9d48da50951e110e7283ec6a9fc312db6fcb4bd0cc8a7860c35e5",
"tag": "2023.03.08.23.37.20.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "912007004f7720b418cd133301c7fb20207e1f2f"
}
},
},
"details": {
"image": {
"imageId": "sha256:45ab1532bbb9d48da50951e110e7283ec6a9fc312db6fcb4bd0cc8a7860c35e5", …
```

chore(cd): update dinghy version to 2023.03.08.23.37.20.release-2.28.x

---

stack.yml

armory/deck-armory:2023.03.08.23.36.56.release-2.27.x
[57f5d89f15f6f9ddc5c3f4554e4b0a3bb6f03e2b](https://github.com/armory-io/deck-armory/commit/57f5d89f15f6f9ddc5c3f4554e4b0a3bb6f03e2b)
[91df4ee661450b04c73232d6c54ae00e96844945](https://github.com/spinnaker/deck/commit/91df4ee661450b04c73232d6c54ae00e96844945)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "91df4ee661450b04c73232d6c54ae00e96844945"
},
"details": {
"image": {
"imageId": "sha256:9f1f1bfeb904148e1f4f6b56aa30968c2571ea45a78456e70ef8ebd5e8e167d4",
"tag": "2023.03.08.23.36.56.release-2.27.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2023.03.08.23.36.56.release-2.27.x

---

stack.yml

armory/dinghy:2023.03.08.23.37.23.release-2.27.x
[d9146416b57d6c7008cfe6323ba3b0e6527181d0](https://github.com/armory-io/dinghy/commit/d9146416b57d6c7008cfe6323ba3b0e6527181d0)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:40c6b3a0bf4340f5feaa2e5f0b7759b17ce78ad49e4e739eacf678e0e3bfed68",
"tag": "2023.03.08.23.37.23.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "d9146416b57d6c7008cfe6323ba3b0e6527181d0"
}
},
},
"details": {
"image": {
"imageId": "sha256:40c6b3a0bf4340f5feaa2e5f0b7759b17ce78ad49e4e739eacf678e0e3bfed68", …
```

chore(cd): update dinghy version to 2023.03.08.23.37.23.release-2.27.x

---

stack.yml

armory/fiat-armory:2023.03.16.18.09.25.release-2.28.x
[45039aa7952cc409329faa30b8443667566459c1](https://github.com/armory-io/fiat-armory/commit/45039aa7952cc409329faa30b8443667566459c1)
[9beee9519381ff736657746b3b0cd4dfdf21fd73](https://github.com/spinnaker/fiat/commit/9beee9519381ff736657746b3b0cd4dfdf21fd73)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9beee9519381ff736657746b3b0cd4dfdf21fd73"
},
"details": {
"image": {
"imageId": "sha256:752c53ef8b2cb6e141935af8e92b31dfb5f2e4b0dde2e52c2a6a5e6febaae5d8",
"tag": "2023.03.16.18.09.25.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update fiat-armory version to 2023.03.16.18.09.25.release-2.28.x

---

stack.yml

* **master**
armory/clouddriver-armory:2023.03.18.00.21.35.master
[c4d9a05349937fa04d368b863d48a70885c470c5](https://github.com/armory-io/clouddriver-armory/commit/c4d9a05349937fa04d368b863d48a70885c470c5)
[2386e1ba0949bd266a9ba861d7fcb9b1ab9bfd0c](https://github.com/spinnaker/clouddriver/commit/2386e1ba0949bd266a9ba861d7fcb9b1ab9bfd0c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "2386e1ba0949bd266a9ba861d7fcb9b1ab9bfd0c"
},
"details": {
"image": {
"imageId": "sha256:78a143ce572fc40e955b5d0eefce96301b1c21ac063522e0067a758d7796d75b",
"tag": "2023.03.18.00.21.35.master"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update clouddriver-armory version to 2023.03.18.00.21.35.master

---

stack.yml

armory/clouddriver-armory:2023.03.21.20.33.52.release-2.28.x
[269ed642f875b059714f38e43774ee8fe9d0e680](https://github.com/armory-io/clouddriver-armory/commit/269ed642f875b059714f38e43774ee8fe9d0e680)
[42df94e7b1578517f96a33bb9ba09dd652e9ce79](https://github.com/spinnaker/clouddriver/commit/42df94e7b1578517f96a33bb9ba09dd652e9ce79)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "42df94e7b1578517f96a33bb9ba09dd652e9ce79"
},
"details": {
"image": {
"imageId": "sha256:ed5f1e8bb18810d5a1759119c45fb05acb3697462413fad88ebd1ad0b88bc653",
"tag": "2023.03.21.20.33.52.release-2.28.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.03.21.20.33.52.release-2.28.x

---

stack.yml

armory/clouddriver-armory:2023.03.21.20.57.07.release-2.27.x
[a3347ca5e207273abe60ca48e98bf494e6d8d359](https://github.com/armory-io/clouddriver-armory/commit/a3347ca5e207273abe60ca48e98bf494e6d8d359)
[29460a330cbff6b3621f7d923ead658aed10a0d7](https://github.com/spinnaker/clouddriver/commit/29460a330cbff6b3621f7d923ead658aed10a0d7)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "29460a330cbff6b3621f7d923ead658aed10a0d7"
},
"details": {
"image": {
"imageId": "sha256:08973cab8699e10c8ee7336c1397651abd4f0bbbae56fbfa9840e9f07c18bd84",
"tag": "2023.03.21.20.57.07.release-2.27.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.03.21.20.57.07.release-2.27.x

---

stack.yml

armory/gate-armory:2023.03.27.19.21.48.release-2.28.x
[43c004af54657dba4a8a429f450de0dad240ed7e](https://github.com/armory-io/gate-armory/commit/43c004af54657dba4a8a429f450de0dad240ed7e)
[228b57f7b40dd2d9711964c73e34ebb50603459d](https://github.com/spinnaker/gate/commit/228b57f7b40dd2d9711964c73e34ebb50603459d)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "228b57f7b40dd2d9711964c73e34ebb50603459d"
},
"details": {
"image": {
"imageId": "sha256:0c42aa761fa47ffa1011e64908c710657dd5736dfd8887e92bf686bf0a3a5ecc",
"tag": "2023.03.27.19.21.48.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update gate-armory version to 2023.03.27.19.21.48.release-2.28.x

---

stack.yml

armory/orca-armory:2023.03.28.16.03.03.release-2.28.x
[6bec7e613ce3cbb8b3ea9223311579e433efc7b1](https://github.com/armory-io/orca-armory/commit/6bec7e613ce3cbb8b3ea9223311579e433efc7b1)
[7a36cb8242725ee16f629e3631dedff37bfc8e3c](https://github.com/spinnaker/orca/commit/7a36cb8242725ee16f629e3631dedff37bfc8e3c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7a36cb8242725ee16f629e3631dedff37bfc8e3c"
},
"details": {
"image": {
"imageId": "sha256:7e1961dce698b8efd3fed36eeda53b41c971ff71c9ea894374406476924a9f9a",
"tag": "2023.03.28.16.03.03.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2023.03.28.16.03.03.release-2.28.x

---

stack.yml

armory/clouddriver-armory:2023.04.07.02.30.20.release-2.30.x
[2d2a10d02a458b01021b982babb587fefa995d36](https://github.com/armory-io/clouddriver-armory/commit/2d2a10d02a458b01021b982babb587fefa995d36)
[b2919632982ef90bc6ce45f5f88dc944c0034cec](https://github.com/spinnaker/clouddriver/commit/b2919632982ef90bc6ce45f5f88dc944c0034cec)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b2919632982ef90bc6ce45f5f88dc944c0034cec"
},
"details": {
"image": {
"imageId": "sha256:d9dcdc39c5d377beffec9924f73a0348d8dbf9ca07718df4cdaebc67dfcc1c36",
"tag": "2023.04.07.02.30.20.release-2.30.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.04.07.02.30.20.release-2.30.x

---

stack.yml

armory/kayenta-armory:2023.01.24.16.36.23.release-2.30.x
[ff12c509aec3f18ebf6b817dd260be10297ab241](https://github.com/armory-io/kayenta-armory/commit/ff12c509aec3f18ebf6b817dd260be10297ab241)
[7925c8927a66b706f4a5ee222e06334819af4675](https://github.com/spinnaker/kayenta/commit/7925c8927a66b706f4a5ee222e06334819af4675)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7925c8927a66b706f4a5ee222e06334819af4675"
},
"details": {
"image": {
"imageId": "sha256:928d3373d70666a44b451bd85f2106b5f1f3eaf517776379fe9db0002953cce2",
"tag": "2023.01.24.16.36.23.release-2.30.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update kayenta-armory version to 2023.01.24.16.36.23.release-2.30.x

---

stack.yml

armory/front50-armory:2022.07.08.02.40.47.release-2.30.x
[b8ea85489ae8ba7f09e93573a364e9ba4c3512fb](https://github.com/armory-io/front50-armory/commit/b8ea85489ae8ba7f09e93573a364e9ba4c3512fb)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:651b09266bca326c24286e8ada7cb29a12490b86b485d9d9d378553805c4cc3f",
"tag": "2022.07.08.02.40.47.release-2.30.x"
},
"vcs": {
"repo": {
},
"sha": "b8ea85489ae8ba7f09e93573a364e9ba4c3512fb"
}
},
},
"details": { …
```

chore(cd): update front50-armory version to 2022.07.08.02.40.47.release-2.30.x

---

stack.yml

armory/dinghy:2023.03.08.19.45.23.release-2.30.x
[5250de80948732c8caac6ffc5293a8af80a63a0f](https://github.com/armory-io/dinghy/commit/5250de80948732c8caac6ffc5293a8af80a63a0f)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:0c5ac601aabb6bced977c27355b40bdfde0f39b870b131db919190d2cc590066",
"tag": "2023.03.08.19.45.23.release-2.30.x"
},
"vcs": {
"repo": {
},
"sha": "5250de80948732c8caac6ffc5293a8af80a63a0f"
}
},
},
"details": {
"image": {
"imageId": "sha256:0c5ac601aabb6bced977c27355b40bdfde0f39b870b131db919190d2cc590066", …
```

chore(cd): update dinghy version to 2023.03.08.19.45.23.release-2.30.x

---

stack.yml

armory/gate-armory:2023.03.30.16.07.04.release-2.30.x
[20db50cef5d38df9ea25f0a6e6fa1f128d77fbc0](https://github.com/armory-io/gate-armory/commit/20db50cef5d38df9ea25f0a6e6fa1f128d77fbc0)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:75b857db97637580d45157aac7967f5fe5bff9f6d47beba1bc810d9691c28599",
"tag": "2023.03.30.16.07.04.release-2.30.x"
},
"vcs": {
"repo": {
},
"sha": "20db50cef5d38df9ea25f0a6e6fa1f128d77fbc0"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update gate-armory version to 2023.03.30.16.07.04.release-2.30.x

---

stack.yml

armory/gate-armory:2023.04.13.18.27.14.release-2.30.x
[5bad459a3919b0421fa23bb784fab991823ce5eb](https://github.com/armory-io/gate-armory/commit/5bad459a3919b0421fa23bb784fab991823ce5eb)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:6a95c7ede37d9077e3e1ccce23db4e06228985f8f2f4d4e582eaefe685464e56",
"tag": "2023.04.13.18.27.14.release-2.30.x"
},
"vcs": {
"repo": {
},
"sha": "5bad459a3919b0421fa23bb784fab991823ce5eb"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update gate-armory version to 2023.04.13.18.27.14.release-2.30.x

---

stack.yml

armory/deck-armory:2023.04.10.18.34.11.release-2.28.x
[e48cbfde774c8ea25e671baf55f2ce68d296e9e1](https://github.com/armory-io/deck-armory/commit/e48cbfde774c8ea25e671baf55f2ce68d296e9e1)
[c43b1057af7ea06917c08db19265d6033440b7c2](https://github.com/spinnaker/deck/commit/c43b1057af7ea06917c08db19265d6033440b7c2)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c43b1057af7ea06917c08db19265d6033440b7c2"
},
"details": {
"image": {
"imageId": "sha256:fd0c408a711483b673940a76906ad08d5fcb98a65ac1fdddb81779f752062c91",
"tag": "2023.04.10.18.34.11.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2023.04.10.18.34.11.release-2.28.x

---

stack.yml

armory/deck-armory:2023.04.15.02.46.39.release-2.30.x
[a5ae63596f79df5c3dd4999253a9ed72dece7de3](https://github.com/armory-io/deck-armory/commit/a5ae63596f79df5c3dd4999253a9ed72dece7de3)
[21bd84315ab519ae2c72adb6605b237b728352a0](https://github.com/spinnaker/deck/commit/21bd84315ab519ae2c72adb6605b237b728352a0)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "21bd84315ab519ae2c72adb6605b237b728352a0"
},
"details": {
"image": {
"imageId": "sha256:61a1f24bc465553aff2614cfb81cf0e6f1d8e9bce7a3a17cb5edc70b2381b475",
"tag": "2023.04.15.02.46.39.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2023.04.15.02.46.39.release-2.30.x

---

stack.yml

armory/orca-armory:2023.04.13.18.43.26.release-2.28.x
[06352546281e21597eb59d3e993e842b9259f142](https://github.com/armory-io/orca-armory/commit/06352546281e21597eb59d3e993e842b9259f142)
[7a36cb8242725ee16f629e3631dedff37bfc8e3c](https://github.com/spinnaker/orca/commit/7a36cb8242725ee16f629e3631dedff37bfc8e3c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7a36cb8242725ee16f629e3631dedff37bfc8e3c"
},
"details": {
"image": {
"imageId": "sha256:cb645fcee3537097ae1f1b14f7c841f0d81e7eb2e04ddcc30b5e199b679ce486",
"tag": "2023.04.13.18.43.26.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2023.04.13.18.43.26.release-2.28.x

---

stack.yml

armory/echo-armory:2023.04.13.18.27.07.release-2.30.x
[92e021dd91bf86a9f02149aef0b547be12e68089](https://github.com/armory-io/echo-armory/commit/92e021dd91bf86a9f02149aef0b547be12e68089)
[43d436386e855b884577e7df652e7778818ef0cd](https://github.com/spinnaker/echo/commit/43d436386e855b884577e7df652e7778818ef0cd)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "43d436386e855b884577e7df652e7778818ef0cd"
},
"details": {
"image": {
"imageId": "sha256:ea5028e7709b0073b71cf3f7e696d3d3b90bbeab9fa885050783e5771776d0bf",
"tag": "2023.04.13.18.27.07.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update echo-armory version to 2023.04.13.18.27.07.release-2.30.x

---

stack.yml

armory/kayenta-armory:2023.03.28.19.39.02.release-2.28.x
[fae0c8bdef77d4cd647bee5a26bcdc2c884b6f2e](https://github.com/armory-io/kayenta-armory/commit/fae0c8bdef77d4cd647bee5a26bcdc2c884b6f2e)
[e4bae4ed74eb64f324e136dabf62d6952c6bebbb](https://github.com/spinnaker/kayenta/commit/e4bae4ed74eb64f324e136dabf62d6952c6bebbb)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e4bae4ed74eb64f324e136dabf62d6952c6bebbb"
},
"details": {
"image": {
"imageId": "sha256:b91c5eeccffc6e650a46a4687f8fb205ed57c15620354ac82e5ae32bc9e0c064",
"tag": "2023.03.28.19.39.02.release-2.28.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update kayenta-armory version to 2023.03.28.19.39.02.release-2.28.x

---

stack.yml

armory/igor-armory:2023.04.13.18.27.20.release-2.30.x
[c3d1e709e68845aa1289f5615c7d9d0a1e2025b5](https://github.com/armory-io/igor-armory/commit/c3d1e709e68845aa1289f5615c7d9d0a1e2025b5)
[d77263d8c7805bb0269340b02ac5ceb1b198e806](https://github.com/spinnaker/igor/commit/d77263d8c7805bb0269340b02ac5ceb1b198e806)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d77263d8c7805bb0269340b02ac5ceb1b198e806"
},
"details": {
"image": {
"imageId": "sha256:f90c0cbf6523c4def231ddb0778d7b59bb68205a2384268c3fdb2e525bfe968a",
"tag": "2023.04.13.18.27.20.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update igor-armory version to 2023.04.13.18.27.20.release-2.30.x

---

stack.yml

armory/kayenta-armory:2023.01.11.00.24.54.release-2.29.x
[4a429225f35b826c77314934239b5ba13ee0c95c](https://github.com/armory-io/kayenta-armory/commit/4a429225f35b826c77314934239b5ba13ee0c95c)
[65c837327cd8fe2b49dd6dd2c997cf123e901b2d](https://github.com/spinnaker/kayenta/commit/65c837327cd8fe2b49dd6dd2c997cf123e901b2d)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "65c837327cd8fe2b49dd6dd2c997cf123e901b2d"
},
"details": {
"image": {
"imageId": "sha256:d83b81b547ebea3d33775b6af74ccc75836c9b98ef357beacc05ebff28dbed75",
"tag": "2023.01.11.00.24.54.release-2.29.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update kayenta-armory version to 2023.01.11.00.24.54.release-2.29.x

---

stack.yml

armory/deck-armory:2022.12.19.13.18.36.release-2.29.x
[73c09670d7b2ad87e4ae5eaa7cb9d8755fdeb19c](https://github.com/armory-io/deck-armory/commit/73c09670d7b2ad87e4ae5eaa7cb9d8755fdeb19c)
[66207875f1386a3271ced770cd38227b5888c1da](https://github.com/spinnaker/deck/commit/66207875f1386a3271ced770cd38227b5888c1da)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "66207875f1386a3271ced770cd38227b5888c1da"
},
"details": {
"image": {
"imageId": "sha256:2c45814d88d9a5c342a3e51d1636ab9b7ec82c689da425fcbe7d870ea36d6b91",
"tag": "2022.12.19.13.18.36.release-2.29.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2022.12.19.13.18.36.release-2.29.x

---

stack.yml

armory/gate-armory:2023.04.18.00.37.10.release-2.30.x
[8119f3e4da3415187852df81cb6406d3ed111da1](https://github.com/armory-io/gate-armory/commit/8119f3e4da3415187852df81cb6406d3ed111da1)
[f6408bd500d9fb86629ba72ec657c65b6f69c151](https://github.com/spinnaker/gate/commit/f6408bd500d9fb86629ba72ec657c65b6f69c151)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f6408bd500d9fb86629ba72ec657c65b6f69c151"
},
"details": {
"image": {
"imageId": "sha256:f38e35b9fd8d0a8f1c20bb139d127609c5b13d55db297d192575b08909a9d70a",
"tag": "2023.04.18.00.37.10.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update gate-armory version to 2023.04.18.00.37.10.release-2.30.x

---

stack.yml

armory/kayenta-armory:2023.04.17.23.00.22.release-2.30.x
[66b9c61ca22cf25b0c1f3e7b5d09e03ec36c0909](https://github.com/armory-io/kayenta-armory/commit/66b9c61ca22cf25b0c1f3e7b5d09e03ec36c0909)
[7925c8927a66b706f4a5ee222e06334819af4675](https://github.com/spinnaker/kayenta/commit/7925c8927a66b706f4a5ee222e06334819af4675)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7925c8927a66b706f4a5ee222e06334819af4675"
},
"details": {
"image": {
"imageId": "sha256:5d18343fef870c634f01801346b8dc79806c2eb0d0d636cda16023eb560eb439",
"tag": "2023.04.17.23.00.22.release-2.30.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update kayenta-armory version to 2023.04.17.23.00.22.release-2.30.x

---

stack.yml

armory/echo-armory:2023.04.20.21.54.21.release-2.28.x
[a602d9d5def0815cb52bdf6d695ca69cbf0abe3b](https://github.com/armory-io/echo-armory/commit/a602d9d5def0815cb52bdf6d695ca69cbf0abe3b)
[0957fef998ff136e04db59a5371780d5f0b8a9ca](https://github.com/spinnaker/echo/commit/0957fef998ff136e04db59a5371780d5f0b8a9ca)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0957fef998ff136e04db59a5371780d5f0b8a9ca"
},
"details": {
"image": {
"imageId": "sha256:3b58640dba54ddc6de7d99dbf471a610c27e68db3ae9a7510371c80da2be926d",
"tag": "2023.04.20.21.54.21.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update echo-armory version to 2023.04.20.21.54.21.release-2.28.x

---

stack.yml

armory/clouddriver-armory:2023.04.20.21.53.23.release-2.30.x
[a7b3b64ae629ba6c471d638d7e82ad367f0a0ca4](https://github.com/armory-io/clouddriver-armory/commit/a7b3b64ae629ba6c471d638d7e82ad367f0a0ca4)
[b2919632982ef90bc6ce45f5f88dc944c0034cec](https://github.com/spinnaker/clouddriver/commit/b2919632982ef90bc6ce45f5f88dc944c0034cec)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b2919632982ef90bc6ce45f5f88dc944c0034cec"
},
"details": {
"image": {
"imageId": "sha256:aac9b3d725d40bc557405049feb80c5900e5ef46f13dff3e9d2cc5a474000ae4",
"tag": "2023.04.20.21.53.23.release-2.30.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.04.20.21.53.23.release-2.30.x

---

stack.yml

armory/rosco-armory:2023.04.20.21.58.55.release-2.28.x
[27d4a2b4a1d5f099b68471303d4fd14af156d46d](https://github.com/armory-io/rosco-armory/commit/27d4a2b4a1d5f099b68471303d4fd14af156d46d)
[17d001df520a0d2256055f99f8bc4989346c8910](https://github.com/spinnaker/rosco/commit/17d001df520a0d2256055f99f8bc4989346c8910)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "17d001df520a0d2256055f99f8bc4989346c8910"
},
"details": {
"image": {
"imageId": "sha256:bec48f5d9056cc9b29b3a740d3ed6cc7ce77bf9877e537ea09b4f364d6e14cbd",
"tag": "2023.04.20.21.58.55.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2023.04.20.21.58.55.release-2.28.x

---

stack.yml

armory/clouddriver-armory:2023.04.20.21.53.08.release-2.28.x
[95037f6d709c2dd03318b78c42c426106ee16a01](https://github.com/armory-io/clouddriver-armory/commit/95037f6d709c2dd03318b78c42c426106ee16a01)
[a84dfe906a48ab5033ad043f116b427bb1cde4f9](https://github.com/spinnaker/clouddriver/commit/a84dfe906a48ab5033ad043f116b427bb1cde4f9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a84dfe906a48ab5033ad043f116b427bb1cde4f9"
},
"details": {
"image": {
"imageId": "sha256:b3a2658fc4cb15a9a240630fa65db13177763012d10b4739a0910b6e7dabc265",
"tag": "2023.04.20.21.53.08.release-2.28.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.04.20.21.53.08.release-2.28.x

---

stack.yml

armory/kayenta-armory:2023.04.20.22.10.17.release-2.28.x
[22fe5d47baacce77917c9026cefdedf91c64a956](https://github.com/armory-io/kayenta-armory/commit/22fe5d47baacce77917c9026cefdedf91c64a956)
[e4bae4ed74eb64f324e136dabf62d6952c6bebbb](https://github.com/spinnaker/kayenta/commit/e4bae4ed74eb64f324e136dabf62d6952c6bebbb)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e4bae4ed74eb64f324e136dabf62d6952c6bebbb"
},
"details": {
"image": {
"imageId": "sha256:1868311d3d2f65cb7b1db3c7a2f9d06ffa14006ed691e8c1adf7c790fc4af8cd",
"tag": "2023.04.20.22.10.17.release-2.28.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update kayenta-armory version to 2023.04.20.22.10.17.release-2.28.x

---

stack.yml

armory/echo-armory:2023.04.20.21.54.39.release-2.30.x
[324514ad69a6479cca0d31e206a30c70b034720c](https://github.com/armory-io/echo-armory/commit/324514ad69a6479cca0d31e206a30c70b034720c)
[43d436386e855b884577e7df652e7778818ef0cd](https://github.com/spinnaker/echo/commit/43d436386e855b884577e7df652e7778818ef0cd)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "43d436386e855b884577e7df652e7778818ef0cd"
},
"details": {
"image": {
"imageId": "sha256:bf2789991fb03683000719d463bfa113435c1214fe87c9e3a99da7164bf88df7",
"tag": "2023.04.20.21.54.39.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update echo-armory version to 2023.04.20.21.54.39.release-2.30.x

---

stack.yml

armory/gate-armory:2023.04.19.20.37.29.release-2.30.x
[d304d29ca38a80e73fbf896260a0311d4fb56e92](https://github.com/armory-io/gate-armory/commit/d304d29ca38a80e73fbf896260a0311d4fb56e92)
[f6408bd500d9fb86629ba72ec657c65b6f69c151](https://github.com/spinnaker/gate/commit/f6408bd500d9fb86629ba72ec657c65b6f69c151)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f6408bd500d9fb86629ba72ec657c65b6f69c151"
},
"details": {
"image": {
"imageId": "sha256:7aa6e3d2ef4dd27bf41ab3d7f33687ded21c8ff202004c84442ef796605048a4",
"tag": "2023.04.19.20.37.29.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update gate-armory version to 2023.04.19.20.37.29.release-2.30.x

---

stack.yml

armory/deck-armory:2023.04.20.20.06.27.release-2.28.x
[e24db15a97545fd5dda3bdb88a70f640bc5a1104](https://github.com/armory-io/deck-armory/commit/e24db15a97545fd5dda3bdb88a70f640bc5a1104)
[ccd39595fabd88bcf35e0704d2e61dc2b66de1b9](https://github.com/spinnaker/deck/commit/ccd39595fabd88bcf35e0704d2e61dc2b66de1b9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "ccd39595fabd88bcf35e0704d2e61dc2b66de1b9"
},
"details": {
"image": {
"imageId": "sha256:507b5106a05ccb37e21e8253d8542048f96fbca0d1184f807c23dfe0d53b4424",
"tag": "2023.04.20.20.06.27.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2023.04.20.20.06.27.release-2.28.x

---

stack.yml

armory/front50-armory:2023.04.14.18.13.14.release-2.28.x
[3292cf2715a9e52bb4690601d4fd877407505ced](https://github.com/armory-io/front50-armory/commit/3292cf2715a9e52bb4690601d4fd877407505ced)
[c4721267952624f5adb77b7d449523fe44c93271](https://github.com/spinnaker/front50/commit/c4721267952624f5adb77b7d449523fe44c93271)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c4721267952624f5adb77b7d449523fe44c93271"
},
"details": {
"image": {
"imageId": "sha256:0342f2373fe9eeeab5ea12f3d037af970a2b37de402fbf4b223899f5fc5f64b3",
"tag": "2023.04.14.18.13.14.release-2.28.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update front50-armory version to 2023.04.14.18.13.14.release-2.28.x

---

stack.yml

armory/orca-armory:2023.04.20.21.55.02.release-2.30.x
[3c3f876319b71daa41230d0904a896a2cb8bf5a7](https://github.com/armory-io/orca-armory/commit/3c3f876319b71daa41230d0904a896a2cb8bf5a7)
[283c5051d5f4952752e9263b97077a31d0201686](https://github.com/spinnaker/orca/commit/283c5051d5f4952752e9263b97077a31d0201686)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "283c5051d5f4952752e9263b97077a31d0201686"
},
"details": {
"image": {
"imageId": "sha256:ff720c531910c0efbee07ebbe3b893893783192315c53a6762364c511d47d000",
"tag": "2023.04.20.21.55.02.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2023.04.20.21.55.02.release-2.30.x

---

stack.yml

armory/fiat-armory:2023.04.19.20.36.38.release-2.30.x
[f32a26379f64825d6233ffd24922b1437e045a17](https://github.com/armory-io/fiat-armory/commit/f32a26379f64825d6233ffd24922b1437e045a17)
[8bf74c283b426496e864e27e567a9ea7de41155e](https://github.com/spinnaker/fiat/commit/8bf74c283b426496e864e27e567a9ea7de41155e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "8bf74c283b426496e864e27e567a9ea7de41155e"
},
"details": {
"image": {
"imageId": "sha256:2a6dcfbb6dc993e431e23a11ed6aea6c6e32a0099ae7173c1838e41120825acf",
"tag": "2023.04.19.20.36.38.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update fiat-armory version to 2023.04.19.20.36.38.release-2.30.x

---

stack.yml

armory/rosco-armory:2023.04.19.20.40.46.release-2.30.x
[cfb76862ca94047a4474e8660a6ca30f5b8e8b50](https://github.com/armory-io/rosco-armory/commit/cfb76862ca94047a4474e8660a6ca30f5b8e8b50)
[10fa720a66778aae21af3619742c13001175f0d9](https://github.com/spinnaker/rosco/commit/10fa720a66778aae21af3619742c13001175f0d9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "10fa720a66778aae21af3619742c13001175f0d9"
},
"details": {
"image": {
"imageId": "sha256:7be4c29b9f71a79298f0e12c1f99684a8cfb41c7322177fa10d51071c1181ef0",
"tag": "2023.04.19.20.40.46.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2023.04.19.20.40.46.release-2.30.x

---

stack.yml

armory/igor-armory:2023.04.19.20.37.13.release-2.30.x
[efe9069d9e7aaed8810642939a63d46b3e110d0a](https://github.com/armory-io/igor-armory/commit/efe9069d9e7aaed8810642939a63d46b3e110d0a)
[d77263d8c7805bb0269340b02ac5ceb1b198e806](https://github.com/spinnaker/igor/commit/d77263d8c7805bb0269340b02ac5ceb1b198e806)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d77263d8c7805bb0269340b02ac5ceb1b198e806"
},
"details": {
"image": {
"imageId": "sha256:8b9df26d8bde97c43fea260d1359e8e2b4737890919056bc9ea95b2a741d7001",
"tag": "2023.04.19.20.37.13.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update igor-armory version to 2023.04.19.20.37.13.release-2.30.x

---

stack.yml

armory/kayenta-armory:2023.04.20.10.20.36.release-2.30.x
[4ae297f97ae68ff49209e548b253413983686d2d](https://github.com/armory-io/kayenta-armory/commit/4ae297f97ae68ff49209e548b253413983686d2d)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:b852b77834827952c570ca957f674d8dff7a40fe717436796ff8c313479630ea",
"tag": "2023.04.20.10.20.36.release-2.30.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update kayenta-armory version to 2023.04.20.10.20.36.release-2.30.x

---

stack.yml

armory/fiat-armory:2023.04.20.21.54.45.release-2.28.x
[d0874307a60cbc457616569be910f4142c152586](https://github.com/armory-io/fiat-armory/commit/d0874307a60cbc457616569be910f4142c152586)
[9beee9519381ff736657746b3b0cd4dfdf21fd73](https://github.com/spinnaker/fiat/commit/9beee9519381ff736657746b3b0cd4dfdf21fd73)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9beee9519381ff736657746b3b0cd4dfdf21fd73"
},
"details": {
"image": {
"imageId": "sha256:c726fd6d7bee12b46047488c37cad680455416c26c48e5a3cc00756a06dcd7ab",
"tag": "2023.04.20.21.54.45.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update fiat-armory version to 2023.04.20.21.54.45.release-2.28.x

---

stack.yml

armory/front50-armory:2023.04.27.22.29.30.release-2.30.x
[e0b2300fa54221c4168c560fc8a0191e180bf801](https://github.com/armory-io/front50-armory/commit/e0b2300fa54221c4168c560fc8a0191e180bf801)
[4657feec33e15c76302e52651579b9b0e5dfaf76](https://github.com/spinnaker/front50/commit/4657feec33e15c76302e52651579b9b0e5dfaf76)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4657feec33e15c76302e52651579b9b0e5dfaf76"
},
"details": {
"image": {
"imageId": "sha256:30028171351f442b738244c6d22bc224e3016dbaad6e75cf0eff102f22128d08",
"tag": "2023.04.27.22.29.30.release-2.30.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update front50-armory version to 2023.04.27.22.29.30.release-2.30.x

---

stack.yml

armory/kayenta-armory:2023.05.03.13.06.24.release-2.30.x
[ff455e8462bbabd8e5f594b69ae289561e1ad95a](https://github.com/armory-io/kayenta-armory/commit/ff455e8462bbabd8e5f594b69ae289561e1ad95a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:2c8cd7bc9b54d8aec8b5f04e8eb0674253c819c8b69a59062294cb30137d9d04",
"tag": "2023.05.03.13.06.24.release-2.30.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update kayenta-armory version to 2023.05.03.13.06.24.release-2.30.x

---

stack.yml

armory/kayenta-armory:2023.05.05.17.30.25.release-2.30.x
[42f7d8329600606ec93c38420594a98c8cadcadf](https://github.com/armory-io/kayenta-armory/commit/42f7d8329600606ec93c38420594a98c8cadcadf)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:112f8fc311cf3700c56d2e2f5562fb372393b37a6603c8233eb64f355c27d336",
"tag": "2023.05.05.17.30.25.release-2.30.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update kayenta-armory version to 2023.05.05.17.30.25.release-2.30.x

---

stack.yml

armory/kayenta-armory:2023.05.08.15.56.39.release-2.30.x
[389b63e338def68a639fa71dd263af5ca50b77db](https://github.com/armory-io/kayenta-armory/commit/389b63e338def68a639fa71dd263af5ca50b77db)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:cdf4a1619fc6740fc5837ae99ee5170331cfa4062638773b8a1e5d2c2df1cdd5",
"tag": "2023.05.08.15.56.39.release-2.30.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update kayenta-armory version to 2023.05.08.15.56.39.release-2.30.x

---

stack.yml

armory/kayenta-armory:2023.05.12.15.39.01.release-2.30.x
[16aa401c453de95b670524b491cbaa682bcf2817](https://github.com/armory-io/kayenta-armory/commit/16aa401c453de95b670524b491cbaa682bcf2817)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:2ad90b5f29d1eed73a840bec39ce5b631ac6e3489728e793acb2770afee35e4f",
"tag": "2023.05.12.15.39.01.release-2.30.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update kayenta-armory version to 2023.05.12.15.39.01.release-2.30.x

---

stack.yml

armory/rosco-armory:2023.05.12.15.27.29.release-2.30.x
[c72a24d8c560ea7b27fd8ecf45c9c11ca63682f4](https://github.com/armory-io/rosco-armory/commit/c72a24d8c560ea7b27fd8ecf45c9c11ca63682f4)
[10fa720a66778aae21af3619742c13001175f0d9](https://github.com/spinnaker/rosco/commit/10fa720a66778aae21af3619742c13001175f0d9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "10fa720a66778aae21af3619742c13001175f0d9"
},
"details": {
"image": {
"imageId": "sha256:5642a04c46c45dfc3b115ef751429c8a82c606859d95fde44b809af2e4ccce03",
"tag": "2023.05.12.15.27.29.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2023.05.12.15.27.29.release-2.30.x

---

stack.yml

armory/orca-armory:2023.05.18.14.45.36.release-2.28.x
[27a66c125270377772675b0e24d93566d878cfb9](https://github.com/armory-io/orca-armory/commit/27a66c125270377772675b0e24d93566d878cfb9)
[cd4e9ab5e1fe01656c2992d0fe5aef971e5f65be](https://github.com/spinnaker/orca/commit/cd4e9ab5e1fe01656c2992d0fe5aef971e5f65be)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "cd4e9ab5e1fe01656c2992d0fe5aef971e5f65be"
},
"details": {
"image": {
"imageId": "sha256:6ec0d9762d75cb33e8ce9643326e1f4a8d54b2b52b4ff86d5bdabc064d03c6c0",
"tag": "2023.05.18.14.45.36.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2023.05.18.14.45.36.release-2.28.x

---

stack.yml

armory/clouddriver-armory:2023.05.12.15.21.39.release-2.30.x
[4325f8f5d4bb6bc783b37645f0e8eb5c99056829](https://github.com/armory-io/clouddriver-armory/commit/4325f8f5d4bb6bc783b37645f0e8eb5c99056829)
[b2919632982ef90bc6ce45f5f88dc944c0034cec](https://github.com/spinnaker/clouddriver/commit/b2919632982ef90bc6ce45f5f88dc944c0034cec)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b2919632982ef90bc6ce45f5f88dc944c0034cec"
},
"details": {
"image": {
"imageId": "sha256:45580c6cda0cf8da8f9b60d34cf9386e1045701c0fe4596023641f631cf1ea1e",
"tag": "2023.05.12.15.21.39.release-2.30.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.05.12.15.21.39.release-2.30.x

---

stack.yml

* **master**
armory/clouddriver-armory:2023.05.18.17.52.42.master
[f76947d851877194a3293c9e7f4950410bc5da70](https://github.com/armory-io/clouddriver-armory/commit/f76947d851877194a3293c9e7f4950410bc5da70)
[98c2e075a0fa89059e0eb4aaa97dc5d4ee4bc06b](https://github.com/spinnaker/clouddriver/commit/98c2e075a0fa89059e0eb4aaa97dc5d4ee4bc06b)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "98c2e075a0fa89059e0eb4aaa97dc5d4ee4bc06b"
},
"details": {
"image": {
"imageId": "sha256:c36ade91e54b33b769dbb8c809751051ff25930a6ceac4c61cb5c6950d8fc09d",
"tag": "2023.05.18.17.52.42.master"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update clouddriver-armory version to 2023.05.18.17.52.42.master

---

stack.yml

armory/gate-armory:2023.05.12.15.24.13.release-2.30.x
[679225a36b20fe39ecb175813929972c497d1a92](https://github.com/armory-io/gate-armory/commit/679225a36b20fe39ecb175813929972c497d1a92)
[f6408bd500d9fb86629ba72ec657c65b6f69c151](https://github.com/spinnaker/gate/commit/f6408bd500d9fb86629ba72ec657c65b6f69c151)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f6408bd500d9fb86629ba72ec657c65b6f69c151"
},
"details": {
"image": {
"imageId": "sha256:a223e589da67f33a4059eaa8908f312e411a1c5a918150ef0e94f23ad9de983b",
"tag": "2023.05.12.15.24.13.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update gate-armory version to 2023.05.12.15.24.13.release-2.30.x

---

stack.yml

armory/echo-armory:2023.05.12.15.22.43.release-2.30.x
[86c586f7c523a4c320189eff00731271b8d31e32](https://github.com/armory-io/echo-armory/commit/86c586f7c523a4c320189eff00731271b8d31e32)
[43d436386e855b884577e7df652e7778818ef0cd](https://github.com/spinnaker/echo/commit/43d436386e855b884577e7df652e7778818ef0cd)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "43d436386e855b884577e7df652e7778818ef0cd"
},
"details": {
"image": {
"imageId": "sha256:a1807d84952dcc610ed32c061a932f3734708ede8a68bc63d500675e6c51071b",
"tag": "2023.05.12.15.22.43.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update echo-armory version to 2023.05.12.15.22.43.release-2.30.x

---

stack.yml

armory/fiat-armory:2023.05.12.15.23.21.release-2.30.x
[0150c145b239568c294ab88251dc2fbb20ace279](https://github.com/armory-io/fiat-armory/commit/0150c145b239568c294ab88251dc2fbb20ace279)
[8bf74c283b426496e864e27e567a9ea7de41155e](https://github.com/spinnaker/fiat/commit/8bf74c283b426496e864e27e567a9ea7de41155e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "8bf74c283b426496e864e27e567a9ea7de41155e"
},
"details": {
"image": {
"imageId": "sha256:2792b1ebe09cf7d1e943f2c08d6fd2ba8c8d506ecc4e07acbec1276e5a94bc93",
"tag": "2023.05.12.15.23.21.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update fiat-armory version to 2023.05.12.15.23.21.release-2.30.x

---

stack.yml

armory/front50-armory:2023.05.23.15.48.49.release-2.30.x
[bdbf36960c30b3599bdf0fa31620dfaf08927074](https://github.com/armory-io/front50-armory/commit/bdbf36960c30b3599bdf0fa31620dfaf08927074)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:5afe911bf2f854f7a5faa7e1045b72433104729e8e72b0b60e09a31ac807556b",
"tag": "2023.05.23.15.48.49.release-2.30.x"
},
"vcs": {
"repo": {
},
"sha": "bdbf36960c30b3599bdf0fa31620dfaf08927074"
}
},
},
"details": { …
```

chore(cd): update front50-armory version to 2023.05.23.15.48.49.release-2.30.x

---

stack.yml

armory/clouddriver-armory:2023.05.30.19.58.33.release-2.28.x
[50b4f4881597a374a9ba85aac90c0c0b9b22cee5](https://github.com/armory-io/clouddriver-armory/commit/50b4f4881597a374a9ba85aac90c0c0b9b22cee5)
[8a7993eb05f930d81ad940029f63e5d39c47b777](https://github.com/spinnaker/clouddriver/commit/8a7993eb05f930d81ad940029f63e5d39c47b777)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "8a7993eb05f930d81ad940029f63e5d39c47b777"
},
"details": {
"image": {
"imageId": "sha256:1bf1df18cedabe35d1a4ea07826018a679efc2382e85701983f1b9bf889425b5",
"tag": "2023.05.30.19.58.33.release-2.28.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.05.30.19.58.33.release-2.28.x

---

stack.yml

armory/clouddriver-armory:2023.05.30.20.03.51.release-2.30.x
[5dfa9fe9e2285a875f0f39cb29e46a6470f34665](https://github.com/armory-io/clouddriver-armory/commit/5dfa9fe9e2285a875f0f39cb29e46a6470f34665)
[39ff8112f8451a4c79bfa9d1537aeec4b65f0a45](https://github.com/spinnaker/clouddriver/commit/39ff8112f8451a4c79bfa9d1537aeec4b65f0a45)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "39ff8112f8451a4c79bfa9d1537aeec4b65f0a45"
},
"details": {
"image": {
"imageId": "sha256:0635b716260c3bcc2e22dc8253b4d404ac70b6b3028fe76f9d1296051791d923",
"tag": "2023.05.30.20.03.51.release-2.30.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.05.30.20.03.51.release-2.30.x

---

stack.yml

armory/clouddriver-armory:2023.05.30.19.58.54.release-2.27.x
[ba48307745c969100683777cb9e2e900e1b3e514](https://github.com/armory-io/clouddriver-armory/commit/ba48307745c969100683777cb9e2e900e1b3e514)
[8fc7f9bbb987866a97c982d194a504ce80574255](https://github.com/spinnaker/clouddriver/commit/8fc7f9bbb987866a97c982d194a504ce80574255)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "8fc7f9bbb987866a97c982d194a504ce80574255"
},
"details": {
"image": {
"imageId": "sha256:ec9a0643bfb927c46985a24bf8c32d611125ac1ee9b67c01638baef6aeaf8158",
"tag": "2023.05.30.19.58.54.release-2.27.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.05.30.19.58.54.release-2.27.x

---

stack.yml

armory/orca-armory:2023.04.01.01.42.38.release-2.27.x
[06a4afc64ed0062ac599ccf8829fde4a63aa0be0](https://github.com/armory-io/orca-armory/commit/06a4afc64ed0062ac599ccf8829fde4a63aa0be0)
[c990e3561c134d2c5336e0250b590ccf971183ea](https://github.com/spinnaker/orca/commit/c990e3561c134d2c5336e0250b590ccf971183ea)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c990e3561c134d2c5336e0250b590ccf971183ea"
},
"details": {
"image": {
"imageId": "sha256:c7977748750dc07a0feb6f73e0c4060e386f5fcf7087a3db2ca64265a454dc36",
"tag": "2023.04.01.01.42.38.release-2.27.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2023.04.01.01.42.38.release-2.27.x

---

stack.yml

armory/kayenta-armory:2023.06.01.03.38.49.release-2.28.x
[3da923fd822202425b90a181c9734910c5c4a609](https://github.com/armory-io/kayenta-armory/commit/3da923fd822202425b90a181c9734910c5c4a609)
[48db746d13249d5435eca64d5e7a6f0fa23f740b](https://github.com/spinnaker/kayenta/commit/48db746d13249d5435eca64d5e7a6f0fa23f740b)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "48db746d13249d5435eca64d5e7a6f0fa23f740b"
},
"details": {
"image": {
"imageId": "sha256:71e2e15cf4e8343abb102bcb7f1b6987e961f8b3c9acd0584b0bf3b783edbc72",
"tag": "2023.06.01.03.38.49.release-2.28.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update kayenta-armory version to 2023.06.01.03.38.49.release-2.28.x

---

stack.yml

* **master**
armory/clouddriver-armory:2023.06.05.21.09.07.master
[2fe864ff5ad61cc19b6fb6364d176a7ba53e029f](https://github.com/armory-io/clouddriver-armory/commit/2fe864ff5ad61cc19b6fb6364d176a7ba53e029f)
[107a4cc006cc34a6d57379464540792351c8781b](https://github.com/spinnaker/clouddriver/commit/107a4cc006cc34a6d57379464540792351c8781b)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "107a4cc006cc34a6d57379464540792351c8781b"
},
"details": {
"image": {
"imageId": "sha256:2feb4f003945b1d3528313395649e65911b59bdf6fe045aec026d93d4c7ad4ad",
"tag": "2023.06.05.21.09.07.master"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update clouddriver-armory version to 2023.06.05.21.09.07.master

---

stack.yml

* **master**
armory/deck-armory:2023.04.03.11.51.17.master
[a1c72b6721e6e13c82895df9c474081c95974f91](https://github.com/armory-io/deck-armory/commit/a1c72b6721e6e13c82895df9c474081c95974f91)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:7525b16fb00b2612589ea13670cb420f7ce98054239265bc6c71e6b1e55f8264",
"tag": "2023.04.03.11.51.17.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update deck-armory version to 2023.04.03.11.51.17.master

---

stack.yml

* **master**
armory/kayenta-armory:2023.05.08.15.35.55.master
[5bd60aa26b1fea12db678f71f8fec71b774e1f25](https://github.com/armory-io/kayenta-armory/commit/5bd60aa26b1fea12db678f71f8fec71b774e1f25)
[7925c8927a66b706f4a5ee222e06334819af4675](https://github.com/spinnaker/kayenta/commit/7925c8927a66b706f4a5ee222e06334819af4675)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7925c8927a66b706f4a5ee222e06334819af4675"
},
"details": {
"image": {
"imageId": "sha256:0ec1ad4d70fc24f09834b9180b63b79aa037b95192a9a06fabced4286961b421",
"tag": "2023.05.08.15.35.55.master"
},
"vcs": {
"repo": {
"repoName": …
```

chore(cd): update kayenta-armory version to 2023.05.08.15.35.55.master

---

stack.yml

armory/clouddriver-armory:2023.06.15.08.45.13.release-2.30.x
[4512ba1b391b06d49a017b29113010631ddabb14](https://github.com/armory-io/clouddriver-armory/commit/4512ba1b391b06d49a017b29113010631ddabb14)
[39ff8112f8451a4c79bfa9d1537aeec4b65f0a45](https://github.com/spinnaker/clouddriver/commit/39ff8112f8451a4c79bfa9d1537aeec4b65f0a45)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "39ff8112f8451a4c79bfa9d1537aeec4b65f0a45"
},
"details": {
"image": {
"imageId": "sha256:221fdb9eded6763a2ebab10555c2274d83450df7306454f7c1a261cb7cfc9086",
"tag": "2023.06.15.08.45.13.release-2.30.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.06.15.08.45.13.release-2.30.x

---

stack.yml

armory/kayenta-armory:2023.06.01.03.43.02.release-2.30.x
[81c3f853d5a604b4d03815d95f8ea4b63acb4429](https://github.com/armory-io/kayenta-armory/commit/81c3f853d5a604b4d03815d95f8ea4b63acb4429)
[2583bbf4eb7ed32c093f4de371c390ae7dbdabda](https://github.com/spinnaker/kayenta/commit/2583bbf4eb7ed32c093f4de371c390ae7dbdabda)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "2583bbf4eb7ed32c093f4de371c390ae7dbdabda"
},
"details": {
"image": {
"imageId": "sha256:693cc1a96640583f147fdd7c22b98fd7ffd703e6a8680a7854b03bf0a5cec899",
"tag": "2023.06.01.03.43.02.release-2.30.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update kayenta-armory version to 2023.06.01.03.43.02.release-2.30.x

---

stack.yml

armory/deck-armory:2023.04.05.07.52.39.release-2.27.x
[2c0743383e35f64765eded0c8a5036c29b63ef08](https://github.com/armory-io/deck-armory/commit/2c0743383e35f64765eded0c8a5036c29b63ef08)
[91df4ee661450b04c73232d6c54ae00e96844945](https://github.com/spinnaker/deck/commit/91df4ee661450b04c73232d6c54ae00e96844945)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "91df4ee661450b04c73232d6c54ae00e96844945"
},
"details": {
"image": {
"imageId": "sha256:edc8272e46d6dce7678bacb67da07b7e9a92e2fdde9132f52bd5fe98a24cd955",
"tag": "2023.04.05.07.52.39.release-2.27.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2023.04.05.07.52.39.release-2.27.x

---

stack.yml

armory/gate-armory:2023.04.01.01.41.08.release-2.27.x
[a7113de29cbcf45e43e4b14dcd58b5fd85b74227](https://github.com/armory-io/gate-armory/commit/a7113de29cbcf45e43e4b14dcd58b5fd85b74227)
[b8360a013ded6a5961a3f57a4deed67c27eec944](https://github.com/spinnaker/gate/commit/b8360a013ded6a5961a3f57a4deed67c27eec944)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b8360a013ded6a5961a3f57a4deed67c27eec944"
},
"details": {
"image": {
"imageId": "sha256:f12384344ededf748195982f14dfc4ffd172a5ea32804ace89d2aec29b6e1888",
"tag": "2023.04.01.01.41.08.release-2.27.x"
},
"vcs": {
"repo": { …
```

chore(cd): update gate-armory version to 2023.04.01.01.41.08.release-2.27.x

---

stack.yml

armory/kayenta-armory:2023.04.01.02.03.52.release-2.27.x
[a1909625c292b130230a6334e69e288f4319c973](https://github.com/armory-io/kayenta-armory/commit/a1909625c292b130230a6334e69e288f4319c973)
[a67db92fb2ac468bddd6d44feadc91fb4c4df51e](https://github.com/spinnaker/kayenta/commit/a67db92fb2ac468bddd6d44feadc91fb4c4df51e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a67db92fb2ac468bddd6d44feadc91fb4c4df51e"
},
"details": {
"image": {
"imageId": "sha256:0837fb27344b70ae1ebf6636c6278d4f45eeb8e35f504fd870f6168f10b3ddcb",
"tag": "2023.04.01.02.03.52.release-2.27.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update kayenta-armory version to 2023.04.01.02.03.52.release-2.27.x

---

stack.yml

armory/front50-armory:2023.04.01.02.04.16.release-2.27.x
[7bead7ab07fe1ff4933a26f40622445c24a04478](https://github.com/armory-io/front50-armory/commit/7bead7ab07fe1ff4933a26f40622445c24a04478)
[462b6807003a561ca2168d32f817bce061a01d07](https://github.com/spinnaker/front50/commit/462b6807003a561ca2168d32f817bce061a01d07)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "462b6807003a561ca2168d32f817bce061a01d07"
},
"details": {
"image": {
"imageId": "sha256:a677dda52cc871e70d39e5054818f6e49e8d365cff947717364d2c5546ef737b",
"tag": "2023.04.01.02.04.16.release-2.27.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update front50-armory version to 2023.04.01.02.04.16.release-2.27.x

---

stack.yml

armory/orca-armory:2023.06.29.21.06.18.release-2.30.x
[efd892c9c43301bd79c318601dc4eca09c7346d3](https://github.com/armory-io/orca-armory/commit/efd892c9c43301bd79c318601dc4eca09c7346d3)
[2ff457f01515c9ac94122312f9c2d550553cb840](https://github.com/spinnaker/orca/commit/2ff457f01515c9ac94122312f9c2d550553cb840)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "2ff457f01515c9ac94122312f9c2d550553cb840"
},
"details": {
"image": {
"imageId": "sha256:98edb89db24d7f39501ce4bec84c1d3470f0e83c82cbc3ef07ef5ea74409f647",
"tag": "2023.06.29.21.06.18.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2023.06.29.21.06.18.release-2.30.x

---

stack.yml

armory/deck-armory:2023.06.23.23.43.14.release-2.30.x
[7737669d9a68843f448cc4c93ac2a6ea3485f95e](https://github.com/armory-io/deck-armory/commit/7737669d9a68843f448cc4c93ac2a6ea3485f95e)
[4ad1f067571af3353ba548f5e315e09c8d08006b](https://github.com/spinnaker/deck/commit/4ad1f067571af3353ba548f5e315e09c8d08006b)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4ad1f067571af3353ba548f5e315e09c8d08006b"
},
"details": {
"image": {
"imageId": "sha256:a7e1ce2d7fe2e8524c533775f8ed861749cab79c25053a1576690396429ea34f",
"tag": "2023.06.23.23.43.14.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2023.06.23.23.43.14.release-2.30.x

---

stack.yml

armory/fiat-armory:2023.07.21.15.57.14.release-2.30.x
[0f9598b6ef39c0a05af12d70fafcd9622b636ff5](https://github.com/armory-io/fiat-armory/commit/0f9598b6ef39c0a05af12d70fafcd9622b636ff5)
[cd168217a82d30b1965d2ed2b01555388d17658a](https://github.com/spinnaker/fiat/commit/cd168217a82d30b1965d2ed2b01555388d17658a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "cd168217a82d30b1965d2ed2b01555388d17658a"
},
"details": {
"image": {
"imageId": "sha256:ff90521811480be6ac60b446d7271d0ee8145d857777831ef76c42ab5e09f288",
"tag": "2023.07.21.15.57.14.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update fiat-armory version to 2023.07.21.15.57.14.release-2.30.x

---

stack.yml

* **master**
armory/gate-armory:2023.07.26.19.41.44.master
[9de143e2d0c1c7e7bf96afbe0f7388f3f8e937ba](https://github.com/armory-io/gate-armory/commit/9de143e2d0c1c7e7bf96afbe0f7388f3f8e937ba)
[fff621ad5ecfbb6b973b001567aa37eda83c7f0e](https://github.com/spinnaker/gate/commit/fff621ad5ecfbb6b973b001567aa37eda83c7f0e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "fff621ad5ecfbb6b973b001567aa37eda83c7f0e"
},
"details": {
"image": {
"imageId": "sha256:a36b884fbae941646b0534e5eb1a4b64eab5b112f7fb304c655cd37528bb75e4",
"tag": "2023.07.26.19.41.44.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update gate-armory version to 2023.07.26.19.41.44.master

---

stack.yml

* **master**
armory/front50-armory:2023.07.27.18.16.22.master
[445717e39fe7531b63a9a75bc990cab138ecd9c7](https://github.com/armory-io/front50-armory/commit/445717e39fe7531b63a9a75bc990cab138ecd9c7)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:38da5a93d98deef07aad486607f707c773f471404fb5972e026aa3d8e69ca90b",
"tag": "2023.07.27.18.16.22.master"
},
"vcs": {
"repo": {
},
"sha": "445717e39fe7531b63a9a75bc990cab138ecd9c7"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update front50-armory version to 2023.07.27.18.16.22.master

---

stack.yml

* **master**
armory/fiat-armory:2023.07.26.18.53.18.master
[5510b4fe5511766aee0addd0b800ba517bc5a70d](https://github.com/armory-io/fiat-armory/commit/5510b4fe5511766aee0addd0b800ba517bc5a70d)
[37b8a059d96f4e52147a1b406bedf771e4b02f81](https://github.com/spinnaker/fiat/commit/37b8a059d96f4e52147a1b406bedf771e4b02f81)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "37b8a059d96f4e52147a1b406bedf771e4b02f81"
},
"details": {
"image": {
"imageId": "sha256:1f3dc53c68b2ba5681de92570ea026f259e0689eed84109f46f3a98f55e0fdda",
"tag": "2023.07.26.18.53.18.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update fiat-armory version to 2023.07.26.18.53.18.master

---

stack.yml

* **master**
armory/rosco-armory:2023.07.27.16.18.30.master
[aa1a32c7576864e22a4b10ea8e5a177c6979659a](https://github.com/armory-io/rosco-armory/commit/aa1a32c7576864e22a4b10ea8e5a177c6979659a)
[b303f2a861333173c9f91bc068b81bfd5edb12e1](https://github.com/spinnaker/rosco/commit/b303f2a861333173c9f91bc068b81bfd5edb12e1)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b303f2a861333173c9f91bc068b81bfd5edb12e1"
},
"details": {
"image": {
"imageId": "sha256:9cbf8ee306424192d1a1bb72153c16f9bb95cdb467f9e3486e67a495fc9b818e",
"tag": "2023.07.27.16.18.30.master"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2023.07.27.16.18.30.master

---

stack.yml

armory/front50-armory:2023.08.01.01.40.32.release-2.31.x
[c84a228751e7ac798602d1c0d8b3540f5ad5f8a8](https://github.com/armory-io/front50-armory/commit/c84a228751e7ac798602d1c0d8b3540f5ad5f8a8)
[267b26ce861e11548a5ad35a82433caece725a67](https://github.com/spinnaker/front50/commit/267b26ce861e11548a5ad35a82433caece725a67)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "267b26ce861e11548a5ad35a82433caece725a67"
},
"details": {
"image": {
"imageId": "sha256:e7b2b792b4cadd8575a57c1dd5cbac998b6b1a2ec726d980fc2ca3c95508d89e",
"tag": "2023.08.01.01.40.32.release-2.31.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update front50-armory version to 2023.08.01.01.40.32.release-2.31.x

---

stack.yml

armory/deck-armory:2023.04.03.11.51.17.release-2.31.x
[a1c72b6721e6e13c82895df9c474081c95974f91](https://github.com/armory-io/deck-armory/commit/a1c72b6721e6e13c82895df9c474081c95974f91)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:862bd03d4844f63f9e1fe7faac75560aacae68b5caa4b3c3335c25d98befda38",
"tag": "2023.04.03.11.51.17.release-2.31.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2023.04.03.11.51.17.release-2.31.x

---

stack.yml

armory/fiat-armory:2023.08.01.01.38.57.release-2.31.x
[590b03a656dba3c8a0a4c3218cad3ccd3ff18b71](https://github.com/armory-io/fiat-armory/commit/590b03a656dba3c8a0a4c3218cad3ccd3ff18b71)
[37b8a059d96f4e52147a1b406bedf771e4b02f81](https://github.com/spinnaker/fiat/commit/37b8a059d96f4e52147a1b406bedf771e4b02f81)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "37b8a059d96f4e52147a1b406bedf771e4b02f81"
},
"details": {
"image": {
"imageId": "sha256:7a00a498c72533cc1f640d173ab49a36af23d37e748edd76e4fd6b4b07d0ee91",
"tag": "2023.08.01.01.38.57.release-2.31.x"
},
"vcs": {
"repo": { …
```

chore(cd): update fiat-armory version to 2023.08.01.01.38.57.release-2.31.x

---

stack.yml

armory/igor-armory:2022.09.14.16.39.54.release-2.31.x
[3c9dd843c3eddbfaa529f054b2df73de938391ca](https://github.com/armory-io/igor-armory/commit/3c9dd843c3eddbfaa529f054b2df73de938391ca)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:a4825f47347250a5cd28a1236ad48fdb41459b94bf78acb56ea61b9d08c50b23",
"tag": "2022.09.14.16.39.54.release-2.31.x"
},
"vcs": {
"repo": {
},
"sha": "3c9dd843c3eddbfaa529f054b2df73de938391ca"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update igor-armory version to 2022.09.14.16.39.54.release-2.31.x

---

stack.yml

armory/dinghy:2023.03.08.19.45.23.release-2.31.x
[5250de80948732c8caac6ffc5293a8af80a63a0f](https://github.com/armory-io/dinghy/commit/5250de80948732c8caac6ffc5293a8af80a63a0f)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:7bfa85c59011246195515b6a8cf1d72bbf81c52560a3c7f181afe60a9f154b9b",
"tag": "2023.03.08.19.45.23.release-2.31.x"
},
"vcs": {
"repo": {
},
"sha": "5250de80948732c8caac6ffc5293a8af80a63a0f"
}
},
},
"details": {
"image": {
"imageId": "sha256:7bfa85c59011246195515b6a8cf1d72bbf81c52560a3c7f181afe60a9f154b9b", …
```

chore(cd): update dinghy version to 2023.03.08.19.45.23.release-2.31.x

---

stack.yml

armory/rosco-armory:2023.08.01.01.43.34.release-2.31.x
[989bf8d946aae6602463fa97d78f8134478b438a](https://github.com/armory-io/rosco-armory/commit/989bf8d946aae6602463fa97d78f8134478b438a)
[b303f2a861333173c9f91bc068b81bfd5edb12e1](https://github.com/spinnaker/rosco/commit/b303f2a861333173c9f91bc068b81bfd5edb12e1)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b303f2a861333173c9f91bc068b81bfd5edb12e1"
},
"details": {
"image": {
"imageId": "sha256:27c9553e21da999e7f74f7f70ac32631f3068bed79264105b47d9933b7bf6a0e",
"tag": "2023.08.01.01.43.34.release-2.31.x"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2023.08.01.01.43.34.release-2.31.x

---

stack.yml

armory/fiat-armory:2023.08.18.20.15.56.release-2.30.x
[12e4ccd27d90b556a65ffc76231ae84623e38e84](https://github.com/armory-io/fiat-armory/commit/12e4ccd27d90b556a65ffc76231ae84623e38e84)
[80b6e407ce8b53f8877f186187ee883d6903e6ef](https://github.com/spinnaker/fiat/commit/80b6e407ce8b53f8877f186187ee883d6903e6ef)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "80b6e407ce8b53f8877f186187ee883d6903e6ef"
},
"details": {
"image": {
"imageId": "sha256:453cad156563fe55bdd463f88dfff75198b33312ba4dbdd58782d7c79470e7e6",
"tag": "2023.08.18.20.15.56.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update fiat-armory version to 2023.08.18.20.15.56.release-2.30.x

---

stack.yml

armory/rosco-armory:2023.08.18.20.25.26.release-2.30.x
[e74de6eaccbed6301505d9f3d2f6745b410211a7](https://github.com/armory-io/rosco-armory/commit/e74de6eaccbed6301505d9f3d2f6745b410211a7)
[2f2b7ffae75a4305cc934eaf30f21a9adaf9e5d9](https://github.com/spinnaker/rosco/commit/2f2b7ffae75a4305cc934eaf30f21a9adaf9e5d9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "2f2b7ffae75a4305cc934eaf30f21a9adaf9e5d9"
},
"details": {
"image": {
"imageId": "sha256:5401cbbb38f417723be7cc02335896574fb6de0eb58f649aaee468e76671212d",
"tag": "2023.08.18.20.25.26.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2023.08.18.20.25.26.release-2.30.x

---

stack.yml

armory/front50-armory:2023.08.18.23.14.11.release-2.30.x
[ec0919166ced870668d787708c249945e9291a01](https://github.com/armory-io/front50-armory/commit/ec0919166ced870668d787708c249945e9291a01)
[9a606e21fa060bee3e5cfa97704d64530a021a35](https://github.com/spinnaker/front50/commit/9a606e21fa060bee3e5cfa97704d64530a021a35)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9a606e21fa060bee3e5cfa97704d64530a021a35"
},
"details": {
"image": {
"imageId": "sha256:fed6a8072a4e3e3b7aabacb1aefc621064db8d247fefdd42530f5b56b2d4ab75",
"tag": "2023.08.18.23.14.11.release-2.30.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update front50-armory version to 2023.08.18.23.14.11.release-2.30.x

---

stack.yml

armory/gate-armory:2023.08.18.23.13.44.release-2.30.x
[2dc9b4b767ab502faaa1b99c131eb7263cf519da](https://github.com/armory-io/gate-armory/commit/2dc9b4b767ab502faaa1b99c131eb7263cf519da)
[4fa3335afec12fd8a8642aba4c031b0984aee8bb](https://github.com/spinnaker/gate/commit/4fa3335afec12fd8a8642aba4c031b0984aee8bb)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4fa3335afec12fd8a8642aba4c031b0984aee8bb"
},
"details": {
"image": {
"imageId": "sha256:7d7882288821a41949135069a23196cc8023f10ed7c2054b43ac348e2763b01e",
"tag": "2023.08.18.23.13.44.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update gate-armory version to 2023.08.18.23.13.44.release-2.30.x

---

stack.yml

armory/kayenta-armory:2023.08.19.01.11.27.release-2.30.x
[aafaf170d12818396f867b7370fdd2fd10048bfe](https://github.com/armory-io/kayenta-armory/commit/aafaf170d12818396f867b7370fdd2fd10048bfe)
[5b781577a4d5d54289536d1ed41094927d5641f1](https://github.com/spinnaker/kayenta/commit/5b781577a4d5d54289536d1ed41094927d5641f1)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5b781577a4d5d54289536d1ed41094927d5641f1"
},
"details": {
"image": {
"imageId": "sha256:9991e59d2d644f5ea52254d5d9da1ac4a4150a54304a5fd3e8ed561b459e24a4",
"tag": "2023.08.19.01.11.27.release-2.30.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update kayenta-armory version to 2023.08.19.01.11.27.release-2.30.x

---

stack.yml

armory/echo-armory:2023.08.18.23.17.42.release-2.30.x
[56844c654cd1b3981686933a9d5bc68011ee2bae](https://github.com/armory-io/echo-armory/commit/56844c654cd1b3981686933a9d5bc68011ee2bae)
[3ad7e607bbaf91c1196b329561defec6a6ee033b](https://github.com/spinnaker/echo/commit/3ad7e607bbaf91c1196b329561defec6a6ee033b)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "3ad7e607bbaf91c1196b329561defec6a6ee033b"
},
"details": {
"image": {
"imageId": "sha256:36deb2548373eed96f72c4d0886de6ee04238f85f4500824248656baa83732dc",
"tag": "2023.08.18.23.17.42.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update echo-armory version to 2023.08.18.23.17.42.release-2.30.x

---

stack.yml

armory/igor-armory:2023.08.18.23.13.19.release-2.30.x
[67b4c66f33b8b97b89e6b052654bebfea460a41f](https://github.com/armory-io/igor-armory/commit/67b4c66f33b8b97b89e6b052654bebfea460a41f)
[343c062b5c85dfbd10e0775f3bbf5559d93c7164](https://github.com/spinnaker/igor/commit/343c062b5c85dfbd10e0775f3bbf5559d93c7164)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "343c062b5c85dfbd10e0775f3bbf5559d93c7164"
},
"details": {
"image": {
"imageId": "sha256:7c42238b40d959753c8f0b2e3102b4ce455a6c921d6b51ca2b0f386c88c152d6",
"tag": "2023.08.18.23.13.19.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update igor-armory version to 2023.08.18.23.13.19.release-2.30.x

---

stack.yml

armory/clouddriver-armory:2023.08.19.00.00.47.release-2.30.x
[e83f27627c37921732db249ca823b2e6485a6f97](https://github.com/armory-io/clouddriver-armory/commit/e83f27627c37921732db249ca823b2e6485a6f97)
[2cdfe2ec647bcedc2ea142a4a15cf2a82d69f847](https://github.com/spinnaker/clouddriver/commit/2cdfe2ec647bcedc2ea142a4a15cf2a82d69f847)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "2cdfe2ec647bcedc2ea142a4a15cf2a82d69f847"
},
"details": {
"image": {
"imageId": "sha256:4c28110fa466fca4068d60bd64029c629fc01abd55d7a748fd4e52e83d945e7d",
"tag": "2023.08.19.00.00.47.release-2.30.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.08.19.00.00.47.release-2.30.x

---

stack.yml

armory/kayenta-armory:2023.08.22.17.30.45.release-2.30.x
[4d82ef4a72129a715749005235ce0d6ba4778603](https://github.com/armory-io/kayenta-armory/commit/4d82ef4a72129a715749005235ce0d6ba4778603)
[00a3c33494dcac1f06922921ae090d4d53a079d8](https://github.com/spinnaker/kayenta/commit/00a3c33494dcac1f06922921ae090d4d53a079d8)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "00a3c33494dcac1f06922921ae090d4d53a079d8"
},
"details": {
"image": {
"imageId": "sha256:09e545df31917b7c3f7a938481ddf92fa542a3f352a920c0f49ae6ff6c2b1178",
"tag": "2023.08.22.17.30.45.release-2.30.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update kayenta-armory version to 2023.08.22.17.30.45.release-2.30.x

---

stack.yml

armory/fiat-armory:2023.08.22.18.19.54.release-2.30.x
[30319b57d40a7e9fd61067b7e0d9fb73bf9a6c46](https://github.com/armory-io/fiat-armory/commit/30319b57d40a7e9fd61067b7e0d9fb73bf9a6c46)
[6f40a11f7432d69bb47d4246920a3f417336f099](https://github.com/spinnaker/fiat/commit/6f40a11f7432d69bb47d4246920a3f417336f099)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "6f40a11f7432d69bb47d4246920a3f417336f099"
},
"details": {
"image": {
"imageId": "sha256:d13d67e932f4881c20326164a060f0c887f110184be43be49f38973398415cf6",
"tag": "2023.08.22.18.19.54.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update fiat-armory version to 2023.08.22.18.19.54.release-2.30.x

---

stack.yml

armory/clouddriver-armory:2023.08.28.14.29.52.release-2.30.x
[9e69fcd6cd17f31e35eeb7d443cdbf9c2d9ac187](https://github.com/armory-io/clouddriver-armory/commit/9e69fcd6cd17f31e35eeb7d443cdbf9c2d9ac187)
[6f7a522cfb2415a494465fcf76878ec134d75309](https://github.com/spinnaker/clouddriver/commit/6f7a522cfb2415a494465fcf76878ec134d75309)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "6f7a522cfb2415a494465fcf76878ec134d75309"
},
"details": {
"image": {
"imageId": "sha256:96e0a96d35b4db860a5237fdf217c63562ae64e7ff8eea01ba6dd82e64c53346",
"tag": "2023.08.28.14.29.52.release-2.30.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.08.28.14.29.52.release-2.30.x

---

stack.yml

armory/gate-armory:2023.08.29.00.04.52.release-2.30.x
[df941ff5c34d14e794c8784c28a1b30b28754971](https://github.com/armory-io/gate-armory/commit/df941ff5c34d14e794c8784c28a1b30b28754971)
[4fa3335afec12fd8a8642aba4c031b0984aee8bb](https://github.com/spinnaker/gate/commit/4fa3335afec12fd8a8642aba4c031b0984aee8bb)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4fa3335afec12fd8a8642aba4c031b0984aee8bb"
},
"details": {
"image": {
"imageId": "sha256:05b312ac71b8077dcfa00c732828c509d4ce01f8acf0e5932e06627991b6bce7",
"tag": "2023.08.29.00.04.52.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update gate-armory version to 2023.08.29.00.04.52.release-2.30.x

---

stack.yml

armory/clouddriver-armory:2023.09.25.09.21.12.release-2.30.x
[767aa739e9c38d2ec7822e9e9a1838b69a56d4c0](https://github.com/armory-io/clouddriver-armory/commit/767aa739e9c38d2ec7822e9e9a1838b69a56d4c0)
[c5109598a240b3d3c778f3eb20c0f2da802d6fab](https://github.com/spinnaker/clouddriver/commit/c5109598a240b3d3c778f3eb20c0f2da802d6fab)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c5109598a240b3d3c778f3eb20c0f2da802d6fab"
},
"details": {
"image": {
"imageId": "sha256:a235a0cf15bbf8f7070541cfe2881001d261e40ff0b33cbcb026bee66dc64116",
"tag": "2023.09.25.09.21.12.release-2.30.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.09.25.09.21.12.release-2.30.x

---

stack.yml

armory/fiat-armory:2023.09.21.17.17.23.release-2.30.x
[5d44e1f53d2f33b17f8decfb057a18cfe4b6fa08](https://github.com/armory-io/fiat-armory/commit/5d44e1f53d2f33b17f8decfb057a18cfe4b6fa08)
[6f40a11f7432d69bb47d4246920a3f417336f099](https://github.com/spinnaker/fiat/commit/6f40a11f7432d69bb47d4246920a3f417336f099)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "6f40a11f7432d69bb47d4246920a3f417336f099"
},
"details": {
"image": {
"imageId": "sha256:d8fdff2ed12983fbaaf9f3cad6c5cbeb220977a4fb3ddc40a4cc40bac0dfbee2",
"tag": "2023.09.21.17.17.23.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update fiat-armory version to 2023.09.21.17.17.23.release-2.30.x

---

stack.yml

armory/clouddriver-armory:2023.09.25.09.23.56.release-2.31.x
[ea07a68277aa69b0b102f0f8544d1dbec8272efa](https://github.com/armory-io/clouddriver-armory/commit/ea07a68277aa69b0b102f0f8544d1dbec8272efa)
[e1de704201a761271f79981c769fff37a34e8bfe](https://github.com/spinnaker/clouddriver/commit/e1de704201a761271f79981c769fff37a34e8bfe)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e1de704201a761271f79981c769fff37a34e8bfe"
},
"details": {
"image": {
"imageId": "sha256:e1442fdfab2b65c60f3779f9873183cb9bcdfcc58e5fe1082169e5a78a6676f9",
"tag": "2023.09.25.09.23.56.release-2.31.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.09.25.09.23.56.release-2.31.x

---

stack.yml

armory/dinghy:2023.09.22.22.23.11.release-2.31.x
[5d44db0f3b4815075a90ef7121df6b830a39e6d5](https://github.com/armory-io/dinghy/commit/5d44db0f3b4815075a90ef7121df6b830a39e6d5)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:89204973b76cdc70ae881233e91db4d27501614c9f66cb05aa8cb8df33f46722",
"tag": "2023.09.22.22.23.11.release-2.31.x"
},
"vcs": {
"repo": {
},
"sha": "5d44db0f3b4815075a90ef7121df6b830a39e6d5"
}
},
},
"details": {
"image": {
"imageId": "sha256:89204973b76cdc70ae881233e91db4d27501614c9f66cb05aa8cb8df33f46722", …
```

chore(cd): update dinghy version to 2023.09.22.22.23.11.release-2.31.x

---

stack.yml

armory/kayenta-armory:2023.09.21.18.53.46.release-2.31.x
[cb7a0d94e995c51486cc214cec45b1f983817c0d](https://github.com/armory-io/kayenta-armory/commit/cb7a0d94e995c51486cc214cec45b1f983817c0d)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:49d246749fb0bce370d35bdb2302719fc9bd69852449744b5233c667f4b48d8e",
"tag": "2023.09.21.18.53.46.release-2.31.x"
},
"vcs": {
"repo": {
},
"sha": "cb7a0d94e995c51486cc214cec45b1f983817c0d"
}
},
},
"details": { …
```

chore(cd): update kayenta-armory version to 2023.09.21.18.53.46.release-2.31.x

---

stack.yml

armory/dinghy:2023.09.27.08.40.28.release-2.30.x
[a3b59d9e4b810cc968d0f5e8e8370e1670574768](https://github.com/armory-io/dinghy/commit/a3b59d9e4b810cc968d0f5e8e8370e1670574768)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:2d9e1a5dead5785478ac05055c2e49fb91e0eba37c62383353058cca4a81c851",
"tag": "2023.09.27.08.40.28.release-2.30.x"
},
"vcs": {
"repo": {
},
"sha": "a3b59d9e4b810cc968d0f5e8e8370e1670574768"
}
},
},
"details": {
"image": {
"imageId": "sha256:2d9e1a5dead5785478ac05055c2e49fb91e0eba37c62383353058cca4a81c851", …
```

chore(cd): update dinghy version to 2023.09.27.08.40.28.release-2.30.x

---

stack.yml

armory/kayenta-armory:2023.09.21.18.54.08.release-2.30.x
[1d2f5193ec681b5122fe7c34da6bbd569da8e0b8](https://github.com/armory-io/kayenta-armory/commit/1d2f5193ec681b5122fe7c34da6bbd569da8e0b8)
[00a3c33494dcac1f06922921ae090d4d53a079d8](https://github.com/spinnaker/kayenta/commit/00a3c33494dcac1f06922921ae090d4d53a079d8)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "00a3c33494dcac1f06922921ae090d4d53a079d8"
},
"details": {
"image": {
"imageId": "sha256:54cc2433698852492f4eb90adb18ebad4c811815503d9fbb79e18dbbc0546315",
"tag": "2023.09.21.18.54.08.release-2.30.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update kayenta-armory version to 2023.09.21.18.54.08.release-2.30.x

---

stack.yml

armory/front50-armory:2023.09.26.07.25.54.release-2.30.x
[5d9bb31f65f96087be30ce96cea1b6d481a6bef4](https://github.com/armory-io/front50-armory/commit/5d9bb31f65f96087be30ce96cea1b6d481a6bef4)
[66d8f0096ba1199909acd48d0446cf824cf17a35](https://github.com/spinnaker/front50/commit/66d8f0096ba1199909acd48d0446cf824cf17a35)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "66d8f0096ba1199909acd48d0446cf824cf17a35"
},
"details": {
"image": {
"imageId": "sha256:bbbefedc14ee66c841e7a685d48b5f101833c4c50355a12b7ace4d847e167b04",
"tag": "2023.09.26.07.25.54.release-2.30.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update front50-armory version to 2023.09.26.07.25.54.release-2.30.x

---

stack.yml

armory/deck-armory:2023.09.22.21.35.15.release-2.30.x
[18e1727665cc52111760bf8e7f41cbf23da3b1a9](https://github.com/armory-io/deck-armory/commit/18e1727665cc52111760bf8e7f41cbf23da3b1a9)
[f8dc0af04fc6cb71082601310668b1f2c5e30148](https://github.com/spinnaker/deck/commit/f8dc0af04fc6cb71082601310668b1f2c5e30148)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f8dc0af04fc6cb71082601310668b1f2c5e30148"
},
"details": {
"image": {
"imageId": "sha256:024010b90e18f2ae01b254c7ef10171f0c1b86716e88535cf05d6edc75608a37",
"tag": "2023.09.22.21.35.15.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2023.09.22.21.35.15.release-2.30.x

---

stack.yml

armory/gate-armory:2023.09.21.17.50.23.release-2.30.x
[04598366642300d6f028df33b6206b5ce75f1038](https://github.com/armory-io/gate-armory/commit/04598366642300d6f028df33b6206b5ce75f1038)
[59227922224610f0f6bc594a633215f5a6222d48](https://github.com/spinnaker/gate/commit/59227922224610f0f6bc594a633215f5a6222d48)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "59227922224610f0f6bc594a633215f5a6222d48"
},
"details": {
"image": {
"imageId": "sha256:eda229d0ec7544a471f0f62163c82fa7e43541f59fffd1d2ca394b8b807bd8ac",
"tag": "2023.09.21.17.50.23.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update gate-armory version to 2023.09.21.17.50.23.release-2.30.x

---

stack.yml

armory/orca-armory:2023.09.22.14.53.29.release-2.28.x
[24f72e5dfe9d4be1b9843b50c411d6f918f29110](https://github.com/armory-io/orca-armory/commit/24f72e5dfe9d4be1b9843b50c411d6f918f29110)
[14fd03c11edbede0194aea866316be1c154c9f80](https://github.com/spinnaker/orca/commit/14fd03c11edbede0194aea866316be1c154c9f80)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "14fd03c11edbede0194aea866316be1c154c9f80"
},
"details": {
"image": {
"imageId": "sha256:2da84007faa1e57e18a52a0b0397cd462db56fc2d6f71a923c80fc27c237b1b5",
"tag": "2023.09.22.14.53.29.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2023.09.22.14.53.29.release-2.28.x

---

stack.yml

armory/rosco-armory:2023.09.21.19.17.34.release-2.30.x
[a2b4662a40281e553de2182b680d5fd7e6bc3955](https://github.com/armory-io/rosco-armory/commit/a2b4662a40281e553de2182b680d5fd7e6bc3955)
[2f2b7ffae75a4305cc934eaf30f21a9adaf9e5d9](https://github.com/spinnaker/rosco/commit/2f2b7ffae75a4305cc934eaf30f21a9adaf9e5d9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "2f2b7ffae75a4305cc934eaf30f21a9adaf9e5d9"
},
"details": {
"image": {
"imageId": "sha256:68795245d0599cdd653c483838930cb8321d5ff130fa7f70f4d4c682d4557c6d",
"tag": "2023.09.21.19.17.34.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2023.09.21.19.17.34.release-2.30.x

---

stack.yml

armory/orca-armory:2023.09.26.15.21.44.release-2.30.x
[ba62a86ef3af0007506b589a4272e3c2e03de00b](https://github.com/armory-io/orca-armory/commit/ba62a86ef3af0007506b589a4272e3c2e03de00b)
[a4404a6a38e080903a8702f0c667ad943c69f49c](https://github.com/spinnaker/orca/commit/a4404a6a38e080903a8702f0c667ad943c69f49c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a4404a6a38e080903a8702f0c667ad943c69f49c"
},
"details": {
"image": {
"imageId": "sha256:bfc8ec73a2ed9b949903617b906fb403ea50f707c665913e54787b0b21521a88",
"tag": "2023.09.26.15.21.44.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2023.09.26.15.21.44.release-2.30.x

---

stack.yml

* **master**
armory/kayenta-armory:2023.09.15.17.28.32.master
[9dbd0784223410acdfa588ecbc8252c66fa3f53e](https://github.com/armory-io/kayenta-armory/commit/9dbd0784223410acdfa588ecbc8252c66fa3f53e)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:9c122739c815548a67cd72f9257edd26fe1efcd5eac1226fe54570ee50fb0510",
"tag": "2023.09.15.17.28.32.master"
},
"vcs": {
"repo": {
},
"sha": "9dbd0784223410acdfa588ecbc8252c66fa3f53e"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update kayenta-armory version to 2023.09.15.17.28.32.master

---

stack.yml

* **master**
armory/fiat-armory:2023.09.28.21.41.57.master
[8f2c2ac3a454a2d0008d45a93197f48adc611c3f](https://github.com/armory-io/fiat-armory/commit/8f2c2ac3a454a2d0008d45a93197f48adc611c3f)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:162628ed4f271ff2f0f10041b4bc23eb1f77f56427930970370d0d6fc9957fd5",
"tag": "2023.09.28.21.41.57.master"
},
"vcs": {
"repo": {
},
"sha": "8f2c2ac3a454a2d0008d45a93197f48adc611c3f"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update fiat-armory version to 2023.09.28.21.41.57.master

---

stack.yml

* **master**
armory/deck-armory:2023.09.28.20.58.27.master
[3bc9c124480234f61256247148f613dcc8d8dcd4](https://github.com/armory-io/deck-armory/commit/3bc9c124480234f61256247148f613dcc8d8dcd4)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:4c1295b31087898aea09d084d4b1ee913eb31a64908cc566bd301c3f91f67c26",
"tag": "2023.09.28.20.58.27.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update deck-armory version to 2023.09.28.20.58.27.master

---

stack.yml

* **master**
armory/clouddriver-armory:2023.10.02.09.54.08.master
[8d9d60e285d898a7638e8531207cf9adc5cd32b8](https://github.com/armory-io/clouddriver-armory/commit/8d9d60e285d898a7638e8531207cf9adc5cd32b8)
[caa202e6cad1f1c1d9ce4e0e39687b53488d106b](https://github.com/spinnaker/clouddriver/commit/caa202e6cad1f1c1d9ce4e0e39687b53488d106b)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "caa202e6cad1f1c1d9ce4e0e39687b53488d106b"
},
"details": {
"image": {
"imageId": "sha256:60f19bbebaeec61914d74921f131e6825ab8703d84cee677cc413079cb66a221",
"tag": "2023.10.02.09.54.08.master"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update clouddriver-armory version to 2023.10.02.09.54.08.master

---

stack.yml

armory/gate-armory:2023.09.29.14.51.35.release-2.30.x
[5758316afba1260d2012730c471fd461819e7f39](https://github.com/armory-io/gate-armory/commit/5758316afba1260d2012730c471fd461819e7f39)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:0227acb8d4867ddcf6471d1ba5dd906ac5123a64a32e5bc30fdf97d6860a6da0",
"tag": "2023.09.29.14.51.35.release-2.30.x"
},
"vcs": {
"repo": {
},
"sha": "5758316afba1260d2012730c471fd461819e7f39"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update gate-armory version to 2023.09.29.14.51.35.release-2.30.x

---

stack.yml

* **master**
armory/gate-armory:2023.10.02.10.38.15.master
[65a44b32f97553460e282e77598b966301fc7b6c](https://github.com/armory-io/gate-armory/commit/65a44b32f97553460e282e77598b966301fc7b6c)
[f1ac512af286e676f087f2b9cb2373f19501d6b9](https://github.com/spinnaker/gate/commit/f1ac512af286e676f087f2b9cb2373f19501d6b9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f1ac512af286e676f087f2b9cb2373f19501d6b9"
},
"details": {
"image": {
"imageId": "sha256:3583fddf7ef9a8683973d5a48a971c4e52f46a63856f349609a2b94f3eebeacb",
"tag": "2023.10.02.10.38.15.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update gate-armory version to 2023.10.02.10.38.15.master

---

stack.yml

* **master**
armory/echo-armory:2023.10.01.17.02.53.master
[ed123f1597e8c2ab3c7adb4affcc46cb323fa588](https://github.com/armory-io/echo-armory/commit/ed123f1597e8c2ab3c7adb4affcc46cb323fa588)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:cbc57b830741a269914ba9b7bf78d4361dce45ba87d8ef8b5a1712a0fffe180a",
"tag": "2023.10.01.17.02.53.master"
},
"vcs": {
"repo": {
},
"sha": "ed123f1597e8c2ab3c7adb4affcc46cb323fa588"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update echo-armory version to 2023.10.01.17.02.53.master

---

stack.yml

* **master**
armory/igor-armory:2023.10.01.17.34.48.master
[2ff49d6ec204794585dff639cd17196aae432cb6](https://github.com/armory-io/igor-armory/commit/2ff49d6ec204794585dff639cd17196aae432cb6)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:7af0df7a1c9933568bef79a94adf3bd79bb7940d90521ec355905a413cfb84b6",
"tag": "2023.10.01.17.34.48.master"
},
"vcs": {
"repo": {
},
"sha": "2ff49d6ec204794585dff639cd17196aae432cb6"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update igor-armory version to 2023.10.01.17.34.48.master

---

stack.yml

* **master**
armory/rosco-armory:2023.09.29.14.47.43.master
[2987c37d9af70e8c177d21bed718d34222509730](https://github.com/armory-io/rosco-armory/commit/2987c37d9af70e8c177d21bed718d34222509730)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:5cd3c5cad0562f5d26412c165a6011e6278d292d9adadf4529526fc6a87c6cfb",
"tag": "2023.09.29.14.47.43.master"
},
"vcs": {
"repo": {
},
"sha": "2987c37d9af70e8c177d21bed718d34222509730"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update rosco-armory version to 2023.09.29.14.47.43.master

---

stack.yml

* **master**
armory/dinghy:2023.09.28.21.43.22.master
[ea6073360e9516054e82fe2b02b87c4a846b8938](https://github.com/armory-io/dinghy/commit/ea6073360e9516054e82fe2b02b87c4a846b8938)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:9d0418700be687a3e973ab13d404b23f7a09ff6c73033dc47c35a4d5ebbb91ab",
"tag": "2023.09.28.21.43.22.master"
},
"vcs": {
"repo": {
},
"sha": "ea6073360e9516054e82fe2b02b87c4a846b8938"
}
},
},
"details": {
"image": {
"imageId": "sha256:9d0418700be687a3e973ab13d404b23f7a09ff6c73033dc47c35a4d5ebbb91ab", …
```

chore(cd): update dinghy version to 2023.09.28.21.43.22.master

---

stack.yml

armory/deck-armory:2023.09.22.21.59.46.release-2.28.x
[a6070ad80ccd8ccbef63415121d20cd5a25b02e4](https://github.com/armory-io/deck-armory/commit/a6070ad80ccd8ccbef63415121d20cd5a25b02e4)
[d8e2597b2eeacf5a9f1103158d949f82b4702114](https://github.com/spinnaker/deck/commit/d8e2597b2eeacf5a9f1103158d949f82b4702114)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d8e2597b2eeacf5a9f1103158d949f82b4702114"
},
"details": {
"image": {
"imageId": "sha256:6f03e3a282a432483c1c8cb4901944d140561a031280b4e32569d71a4e46be00",
"tag": "2023.09.22.21.59.46.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2023.09.22.21.59.46.release-2.28.x

---

stack.yml

armory/clouddriver-armory:2023.09.21.16.27.16.release-2.28.x
[28e862e0f4fce10121b986645ab9eda752ee8a8d](https://github.com/armory-io/clouddriver-armory/commit/28e862e0f4fce10121b986645ab9eda752ee8a8d)
[3180485c6f67cd02f5fe8a0b5d936fdc843bf336](https://github.com/spinnaker/clouddriver/commit/3180485c6f67cd02f5fe8a0b5d936fdc843bf336)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "3180485c6f67cd02f5fe8a0b5d936fdc843bf336"
},
"details": {
"image": {
"imageId": "sha256:510f271f4ac4834fcf9b277fe2c9e72bbf66c2daf895a6e3aec620afede024d0",
"tag": "2023.09.21.16.27.16.release-2.28.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.09.21.16.27.16.release-2.28.x

---

stack.yml

armory/front50-armory:2023.09.21.17.42.07.release-2.28.x
[cabb1a0b252e943c8c6fa5b9c301cae4100444ef](https://github.com/armory-io/front50-armory/commit/cabb1a0b252e943c8c6fa5b9c301cae4100444ef)
[c4721267952624f5adb77b7d449523fe44c93271](https://github.com/spinnaker/front50/commit/c4721267952624f5adb77b7d449523fe44c93271)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c4721267952624f5adb77b7d449523fe44c93271"
},
"details": {
"image": {
"imageId": "sha256:d641ac2f0b1f502f7e92124a81e830fd77f9338eece36bc620122c959c1cf338",
"tag": "2023.09.21.17.42.07.release-2.28.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update front50-armory version to 2023.09.21.17.42.07.release-2.28.x

---

stack.yml

armory/echo-armory:2023.09.28.23.04.19.release-2.31.x
[97578efdbccaa5ffe64586166382d9d667bad93f](https://github.com/armory-io/echo-armory/commit/97578efdbccaa5ffe64586166382d9d667bad93f)
[d20da255de1fabb96d67012c8d9bc370ba02982c](https://github.com/spinnaker/echo/commit/d20da255de1fabb96d67012c8d9bc370ba02982c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d20da255de1fabb96d67012c8d9bc370ba02982c"
},
"details": {
"image": {
"imageId": "sha256:12201aceb40b66b8a548155f0c36bebcef823ca718d7300da4e0ca56f44784d8",
"tag": "2023.09.28.23.04.19.release-2.31.x"
},
"vcs": {
"repo": { …
```

chore(cd): update echo-armory version to 2023.09.28.23.04.19.release-2.31.x

---

stack.yml

armory/fiat-armory:2023.09.21.17.16.38.release-2.31.x
[218510ad92451ccfcaf345332fa09087e0229341](https://github.com/armory-io/fiat-armory/commit/218510ad92451ccfcaf345332fa09087e0229341)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:c902cf321257cec1b99448d612d93ecbe924945fef845c03db668272b3e654f3",
"tag": "2023.09.21.17.16.38.release-2.31.x"
},
"vcs": {
"repo": {
},
"sha": "218510ad92451ccfcaf345332fa09087e0229341"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update fiat-armory version to 2023.09.21.17.16.38.release-2.31.x

---

stack.yml

armory/deck-armory:2023.09.21.16.42.56.release-2.31.x
[7622cd858f68342b11262cebffc60b6b04f6a9b0](https://github.com/armory-io/deck-armory/commit/7622cd858f68342b11262cebffc60b6b04f6a9b0)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:65940e8ff98644411d0fb6355e40f3f1dc7cd2d0fe310017056300c13d5fe61c",
"tag": "2023.09.21.16.42.56.release-2.31.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2023.09.21.16.42.56.release-2.31.x

---

stack.yml

armory/front50-armory:2023.09.21.17.40.52.release-2.31.x
[07267503a90b987c1c6dbdeee88160d7a1b6c7f2](https://github.com/armory-io/front50-armory/commit/07267503a90b987c1c6dbdeee88160d7a1b6c7f2)
[f0494570576de5aa33d969fdd7fad93dee2479cc](https://github.com/spinnaker/front50/commit/f0494570576de5aa33d969fdd7fad93dee2479cc)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f0494570576de5aa33d969fdd7fad93dee2479cc"
},
"details": {
"image": {
"imageId": "sha256:61de89ed3f1e3dff8d0b2833674a54c8c546a8fc3a34beb62030d05963925c5f",
"tag": "2023.09.21.17.40.52.release-2.31.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update front50-armory version to 2023.09.21.17.40.52.release-2.31.x

---

stack.yml

armory/fiat-armory:2023.09.21.17.17.47.release-2.28.x
[8c2bf34638ed1dc46b5380113e730803953d2a64](https://github.com/armory-io/fiat-armory/commit/8c2bf34638ed1dc46b5380113e730803953d2a64)
[9beee9519381ff736657746b3b0cd4dfdf21fd73](https://github.com/spinnaker/fiat/commit/9beee9519381ff736657746b3b0cd4dfdf21fd73)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9beee9519381ff736657746b3b0cd4dfdf21fd73"
},
"details": {
"image": {
"imageId": "sha256:db85516fdd4a92df92ca57ade32e4f26e684fa438d0bbf12d744bf58a206481d",
"tag": "2023.09.21.17.17.47.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update fiat-armory version to 2023.09.21.17.17.47.release-2.28.x

---

stack.yml

armory/rosco-armory:2023.09.21.19.14.39.release-2.31.x
[09dc047e12d131e8962abe627251c73cf2f29c25](https://github.com/armory-io/rosco-armory/commit/09dc047e12d131e8962abe627251c73cf2f29c25)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:774d09f069053da6dc77b6c4f19c6fb1222fa02f098817dc962e26b8a1d512aa",
"tag": "2023.09.21.19.14.39.release-2.31.x"
},
"vcs": {
"repo": {
},
"sha": "09dc047e12d131e8962abe627251c73cf2f29c25"
}
},
},
"details": {
"image": { …
```

chore(cd): update rosco-armory version to 2023.09.21.19.14.39.release-2.31.x

---

stack.yml

armory/igor-armory:2023.09.21.18.03.43.release-2.28.x
[73f38d85dabc6630cf13663cb2450c16be669c70](https://github.com/armory-io/igor-armory/commit/73f38d85dabc6630cf13663cb2450c16be669c70)
[ac7fa51e55855967c04f021aeaad252d38a55b50](https://github.com/spinnaker/igor/commit/ac7fa51e55855967c04f021aeaad252d38a55b50)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "ac7fa51e55855967c04f021aeaad252d38a55b50"
},
"details": {
"image": {
"imageId": "sha256:05af80d63ef3330db65af27b8979af0277101c35f0090ab76cb26940bd9878e5",
"tag": "2023.09.21.18.03.43.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update igor-armory version to 2023.09.21.18.03.43.release-2.28.x

---

stack.yml

armory/gate-armory:2023.09.21.17.49.05.release-2.31.x
[7b4de74187812e3e12f783661de79b223d9f53b4](https://github.com/armory-io/gate-armory/commit/7b4de74187812e3e12f783661de79b223d9f53b4)
[7bc7898bee5c38a200fafbf391126a41dd4aa594](https://github.com/spinnaker/gate/commit/7bc7898bee5c38a200fafbf391126a41dd4aa594)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7bc7898bee5c38a200fafbf391126a41dd4aa594"
},
"details": {
"image": {
"imageId": "sha256:08709701e46dd89f6d22391c77add7983f35048d84b93964d487dc3ccbbcbf8c",
"tag": "2023.09.21.17.49.05.release-2.31.x"
},
"vcs": {
"repo": { …
```

chore(cd): update gate-armory version to 2023.09.21.17.49.05.release-2.31.x

---

stack.yml

armory/kayenta-armory:2023.09.21.18.55.08.release-2.28.x
[1667cf052d155c00b71913e202605a5a100d067c](https://github.com/armory-io/kayenta-armory/commit/1667cf052d155c00b71913e202605a5a100d067c)
[48db746d13249d5435eca64d5e7a6f0fa23f740b](https://github.com/spinnaker/kayenta/commit/48db746d13249d5435eca64d5e7a6f0fa23f740b)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "48db746d13249d5435eca64d5e7a6f0fa23f740b"
},
"details": {
"image": {
"imageId": "sha256:d2fc1a4750fe2673aa6b8256f70c7f4fa114ba7954a2e5d5efd7f2c5d1fd8fa0",
"tag": "2023.09.21.18.55.08.release-2.28.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update kayenta-armory version to 2023.09.21.18.55.08.release-2.28.x

---

stack.yml

armory/rosco-armory:2023.09.21.19.18.43.release-2.28.x
[d0d1962d00dc3ec0ec5f8d868fd4bb655b00e88a](https://github.com/armory-io/rosco-armory/commit/d0d1962d00dc3ec0ec5f8d868fd4bb655b00e88a)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:a66b37c4f4a8c6de74b25cd9d7a435a540184981919ee79c6987e3a3394fee20",
"tag": "2023.09.21.19.18.43.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "d0d1962d00dc3ec0ec5f8d868fd4bb655b00e88a"
}
},
},
"details": {
"image": { …
```

chore(cd): update rosco-armory version to 2023.09.21.19.18.43.release-2.28.x

---

stack.yml

armory/dinghy:2023.09.22.22.28.23.release-2.28.x
[2491f95e9d0ba7d737054f581de852f8af8a6d5e](https://github.com/armory-io/dinghy/commit/2491f95e9d0ba7d737054f581de852f8af8a6d5e)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:8735c13a80cd9cb2d9bb9c7b40893b6c4a2d23a87899dc0623a5c41669d72582",
"tag": "2023.09.22.22.28.23.release-2.28.x"
},
"vcs": {
"repo": {
},
"sha": "2491f95e9d0ba7d737054f581de852f8af8a6d5e"
}
},
},
"details": {
"image": {
"imageId": "sha256:8735c13a80cd9cb2d9bb9c7b40893b6c4a2d23a87899dc0623a5c41669d72582", …
```

chore(cd): update dinghy version to 2023.09.22.22.28.23.release-2.28.x

---

stack.yml

* **master**
armory/gate-armory:2023.10.04.14.25.38.master
[861dbce57ff7625457d087a7b8b072f4812edb32](https://github.com/armory-io/gate-armory/commit/861dbce57ff7625457d087a7b8b072f4812edb32)
[77d22831030c6e3f74436496def3d80392410fb0](https://github.com/spinnaker/gate/commit/77d22831030c6e3f74436496def3d80392410fb0)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "77d22831030c6e3f74436496def3d80392410fb0"
},
"details": {
"image": {
"imageId": "sha256:87dacc7640971bc639d2b23f3463000e9c319c8cc698633adc63bf1cb3bf38dc",
"tag": "2023.10.04.14.25.38.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update gate-armory version to 2023.10.04.14.25.38.master

---

stack.yml

* **master**
armory/echo-armory:2023.10.04.16.22.37.master
[3508036f9f26e13280a969281ecc0cf2ac6601a5](https://github.com/armory-io/echo-armory/commit/3508036f9f26e13280a969281ecc0cf2ac6601a5)
[e1bbdd5d6e9878e923ce5ec345eeaab712acdd28](https://github.com/spinnaker/echo/commit/e1bbdd5d6e9878e923ce5ec345eeaab712acdd28)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e1bbdd5d6e9878e923ce5ec345eeaab712acdd28"
},
"details": {
"image": {
"imageId": "sha256:b2e4e610d6b21ce358e72ef369eed28c27584b694dd254c6cc1d96a72c87bdf5",
"tag": "2023.10.04.16.22.37.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update echo-armory version to 2023.10.04.16.22.37.master

---

stack.yml

armory/kayenta-armory:2023.09.21.18.54.01.release-2.27.x
[4ec14609cd58f2f85561ddcc00ecf97af838d4ec](https://github.com/armory-io/kayenta-armory/commit/4ec14609cd58f2f85561ddcc00ecf97af838d4ec)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:5c158c67b7b32a7e18d3adc182fd94102a9d73080a72023538fd5ce3e2d51919",
"tag": "2023.09.21.18.54.01.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "4ec14609cd58f2f85561ddcc00ecf97af838d4ec"
}
},
},
"details": { …
```

chore(cd): update kayenta-armory version to 2023.09.21.18.54.01.release-2.27.x

---

stack.yml

armory/igor-armory:2023.09.21.18.03.36.release-2.27.x
[643687b7dfc3a7fa068d4590a932ad079427a2fa](https://github.com/armory-io/igor-armory/commit/643687b7dfc3a7fa068d4590a932ad079427a2fa)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:98d66617bc43c6a2b1dd44de2b1e898b283e5650388b86b056da022adc051744",
"tag": "2023.09.21.18.03.36.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "643687b7dfc3a7fa068d4590a932ad079427a2fa"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update igor-armory version to 2023.09.21.18.03.36.release-2.27.x

---

stack.yml

armory/gate-armory:2023.09.21.17.51.24.release-2.27.x
[a0d7630cae3c3d09094843286c7f4cf7f5b4615f](https://github.com/armory-io/gate-armory/commit/a0d7630cae3c3d09094843286c7f4cf7f5b4615f)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:aa0ba765bd0564fa4d1a821f497e1e7bd1678e1fc8716f048cdc0d2985c153b7",
"tag": "2023.09.21.17.51.24.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "a0d7630cae3c3d09094843286c7f4cf7f5b4615f"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update gate-armory version to 2023.09.21.17.51.24.release-2.27.x

---

stack.yml

armory/rosco-armory:2023.09.21.19.18.28.release-2.27.x
[495a3ad0183ffaeb52c40471bbf7f8b5c0839203](https://github.com/armory-io/rosco-armory/commit/495a3ad0183ffaeb52c40471bbf7f8b5c0839203)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:d349da156c35ca79c7426a4f82e900af401e8f8c8592c9d6ce0a1a2bc945283e",
"tag": "2023.09.21.19.18.28.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "495a3ad0183ffaeb52c40471bbf7f8b5c0839203"
}
},
},
"details": {
"image": { …
```

chore(cd): update rosco-armory version to 2023.09.21.19.18.28.release-2.27.x

---

stack.yml

* **master**
armory/igor-armory:2023.10.04.14.25.16.master
[e6fb437c6076c836ace715aeac60546e9685c64a](https://github.com/armory-io/igor-armory/commit/e6fb437c6076c836ace715aeac60546e9685c64a)
[04a8c748c290a6c6af59727ff51f6a3011e0db16](https://github.com/spinnaker/igor/commit/04a8c748c290a6c6af59727ff51f6a3011e0db16)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "04a8c748c290a6c6af59727ff51f6a3011e0db16"
},
"details": {
"image": {
"imageId": "sha256:e4b6bde386419e094feb1c175d780f472b99398b35c1e66f8b71ef59f85b3b5c",
"tag": "2023.10.04.14.25.16.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update igor-armory version to 2023.10.04.14.25.16.master

---

stack.yml

* **master**
armory/front50-armory:2023.10.04.16.25.12.master
[3e7b319c87149f130901909c88e77e6b8751edd4](https://github.com/armory-io/front50-armory/commit/3e7b319c87149f130901909c88e77e6b8751edd4)
[3b52b3ae68fcaf115e4236d22443575b44a72511](https://github.com/spinnaker/front50/commit/3b52b3ae68fcaf115e4236d22443575b44a72511)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "3b52b3ae68fcaf115e4236d22443575b44a72511"
},
"details": {
"image": {
"imageId": "sha256:a2048203394cb1228713a6cd8a1c7459f248ce22acb3ac11f2717ef2244f6907",
"tag": "2023.10.04.16.25.12.master"
},
"vcs": {
"repo": {
"repoName": …
```

chore(cd): update front50-armory version to 2023.10.04.16.25.12.master

---

stack.yml

* **master**
armory/clouddriver-armory:2023.10.04.17.11.33.master
[cc5eaefe3ec3f5967ea22fe032582d1499d1b582](https://github.com/armory-io/clouddriver-armory/commit/cc5eaefe3ec3f5967ea22fe032582d1499d1b582)
[d22be37b46e06abf5169a7f328390132553b7937](https://github.com/spinnaker/clouddriver/commit/d22be37b46e06abf5169a7f328390132553b7937)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d22be37b46e06abf5169a7f328390132553b7937"
},
"details": {
"image": {
"imageId": "sha256:26bd8331a388937d4a766b807cc55804c8517490672cc552616ff466475e621b",
"tag": "2023.10.04.17.11.33.master"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update clouddriver-armory version to 2023.10.04.17.11.33.master

---

stack.yml

armory/orca-armory:2023.09.21.19.02.00.release-2.27.x
[acf8171524c5d3f09a577f05a4f9560b3025e847](https://github.com/armory-io/orca-armory/commit/acf8171524c5d3f09a577f05a4f9560b3025e847)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:617c03f388277eedee50f46d20d16317c65729357f4e5a487b3dbd6a1c1cea3b",
"tag": "2023.09.21.19.02.00.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "acf8171524c5d3f09a577f05a4f9560b3025e847"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update orca-armory version to 2023.09.21.19.02.00.release-2.27.x

---

stack.yml

armory/front50-armory:2023.09.21.17.48.19.release-2.27.x
[3629176e4a7ae563f04175dd1110687a635e7050](https://github.com/armory-io/front50-armory/commit/3629176e4a7ae563f04175dd1110687a635e7050)
[0367e48c9e25da8faceefe3268797c43d3602486](https://github.com/spinnaker/front50/commit/0367e48c9e25da8faceefe3268797c43d3602486)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0367e48c9e25da8faceefe3268797c43d3602486"
},
"details": {
"image": {
"imageId": "sha256:a44ba1866d1eab7f3727a25cc9c9072c0763af6f146aae14b8fe46e51e5d2047",
"tag": "2023.09.21.17.48.19.release-2.27.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update front50-armory version to 2023.09.21.17.48.19.release-2.27.x

---

stack.yml

* **master**
armory/dinghy:2023.10.06.09.43.38.master
[d8e30ec2aab4d2480b9ac9a1bd52d39cc9777a17](https://github.com/armory-io/dinghy/commit/d8e30ec2aab4d2480b9ac9a1bd52d39cc9777a17)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:f3bcb274837546c3b8817bed145887056ef569c52d92693f2b516a40924f57b7",
"tag": "2023.10.06.09.43.38.master"
},
"vcs": {
"repo": {
},
"sha": "d8e30ec2aab4d2480b9ac9a1bd52d39cc9777a17"
}
},
},
"details": {
"image": {
"imageId": "sha256:f3bcb274837546c3b8817bed145887056ef569c52d92693f2b516a40924f57b7", …
```

chore(cd): update dinghy version to 2023.10.06.09.43.38.master

---

stack.yml

* **master**
armory/echo-armory:2023.10.06.16.17.15.master
[a584b3a55ce63455d476ecbe88ccdffe9c491851](https://github.com/armory-io/echo-armory/commit/a584b3a55ce63455d476ecbe88ccdffe9c491851)
[31779124727a5eda13224a3ba9082c2c215996af](https://github.com/spinnaker/echo/commit/31779124727a5eda13224a3ba9082c2c215996af)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "31779124727a5eda13224a3ba9082c2c215996af"
},
"details": {
"image": {
"imageId": "sha256:db6c604d811a04c7840bde4666cc47af948b87d0f599257ba9c67357bd6bcf20",
"tag": "2023.10.06.16.17.15.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update echo-armory version to 2023.10.06.16.17.15.master

---

stack.yml

* **master**
armory/clouddriver-armory:2023.10.09.15.36.17.master
[9e97db6238964b67dd9263af2200ddcfb654b046](https://github.com/armory-io/clouddriver-armory/commit/9e97db6238964b67dd9263af2200ddcfb654b046)
[12939454d3d2389a34758f3acf7b19d9fb1d3be8](https://github.com/spinnaker/clouddriver/commit/12939454d3d2389a34758f3acf7b19d9fb1d3be8)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "12939454d3d2389a34758f3acf7b19d9fb1d3be8"
},
"details": {
"image": {
"imageId": "sha256:8c4953be6b9503d7e2547d7344c49165aaca687f7558c83e1ba403febdbf6a26",
"tag": "2023.10.09.15.36.17.master"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update clouddriver-armory version to 2023.10.09.15.36.17.master

---

stack.yml

* **master**
armory/clouddriver-armory:2023.10.09.16.19.27.master
[a19a5bfef66b39a2938b3d91db43d74f6a0d5922](https://github.com/armory-io/clouddriver-armory/commit/a19a5bfef66b39a2938b3d91db43d74f6a0d5922)
[4dccd10ddf6e210f0235b3ec23493d78ec0ede51](https://github.com/spinnaker/clouddriver/commit/4dccd10ddf6e210f0235b3ec23493d78ec0ede51)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4dccd10ddf6e210f0235b3ec23493d78ec0ede51"
},
"details": {
"image": {
"imageId": "sha256:0348ca722870e1a2e5c46d2dfa8faf8abc0b109e9c9522422ec4b916dc994874",
"tag": "2023.10.09.16.19.27.master"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update clouddriver-armory version to 2023.10.09.16.19.27.master

---

stack.yml

armory/orca-armory:2023.10.10.00.17.25.release-2.30.x
[29b4206bf866ac71e8856bab1c223a0b14dfa5f9](https://github.com/armory-io/orca-armory/commit/29b4206bf866ac71e8856bab1c223a0b14dfa5f9)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:fe3d201536f38b385355d800d5e7ba955aa419aa0c1174c11f6903a63c7def90",
"tag": "2023.10.10.00.17.25.release-2.30.x"
},
"vcs": {
"repo": {
},
"sha": "29b4206bf866ac71e8856bab1c223a0b14dfa5f9"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update orca-armory version to 2023.10.10.00.17.25.release-2.30.x

---

stack.yml

armory/orca-armory:2023.10.10.00.11.05.release-2.28.x
[0fabceb755d80ed1cd6c1020979d4a75473edd24](https://github.com/armory-io/orca-armory/commit/0fabceb755d80ed1cd6c1020979d4a75473edd24)
[a65d34f986d97f7a9a22aca4edfd898b694cbd2a](https://github.com/spinnaker/orca/commit/a65d34f986d97f7a9a22aca4edfd898b694cbd2a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a65d34f986d97f7a9a22aca4edfd898b694cbd2a"
},
"details": {
"image": {
"imageId": "sha256:e2051d79ec465b25790a7c9a452af9a466c1feca999c8c687ead04b54b48a660",
"tag": "2023.10.10.00.11.05.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2023.10.10.00.11.05.release-2.28.x

---

stack.yml

* **master**
armory/rosco-armory:2023.10.09.23.50.16.master
[6490aa8059e995f67e48fde05327ac98e52cc8a8](https://github.com/armory-io/rosco-armory/commit/6490aa8059e995f67e48fde05327ac98e52cc8a8)
[4a12958abb4898428e6840e8753b9ca9a3b1a674](https://github.com/spinnaker/rosco/commit/4a12958abb4898428e6840e8753b9ca9a3b1a674)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4a12958abb4898428e6840e8753b9ca9a3b1a674"
},
"details": {
"image": {
"imageId": "sha256:0fe04a575a35b032b43f05bffbd63ab3f3c4816c46ac86f355855d021fb702a6",
"tag": "2023.10.09.23.50.16.master"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2023.10.09.23.50.16.master

---

stack.yml

armory/rosco-armory:2023.10.10.00.08.57.release-2.31.x
[ca913887ada366fcb17987672a6315c6c65ca634](https://github.com/armory-io/rosco-armory/commit/ca913887ada366fcb17987672a6315c6c65ca634)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:0dc70c77bb7e2ea028c4588ef38c4e83283c05dd1271796f7fae29d74f7cb614",
"tag": "2023.10.10.00.08.57.release-2.31.x"
},
"vcs": {
"repo": {
},
"sha": "ca913887ada366fcb17987672a6315c6c65ca634"
}
},
},
"details": {
"image": { …
```

chore(cd): update rosco-armory version to 2023.10.10.00.08.57.release-2.31.x

---

stack.yml

* **master**
armory/deck-armory:2023.10.10.11.19.01.master
[f94020cf390b405c2b21ddc50edb88ec9bd90cd2](https://github.com/armory-io/deck-armory/commit/f94020cf390b405c2b21ddc50edb88ec9bd90cd2)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:0f90cb2d8ba7ed0f3f28a43cd214abe5b1dd2e52410ade62b533bbd866faf121",
"tag": "2023.10.10.11.19.01.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update deck-armory version to 2023.10.10.11.19.01.master

---

stack.yml

* **master**
armory/igor-armory:2023.10.10.14.24.21.master
[176d55245983c5bb68860902dba47871cb308df0](https://github.com/armory-io/igor-armory/commit/176d55245983c5bb68860902dba47871cb308df0)
[04a8c748c290a6c6af59727ff51f6a3011e0db16](https://github.com/spinnaker/igor/commit/04a8c748c290a6c6af59727ff51f6a3011e0db16)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "04a8c748c290a6c6af59727ff51f6a3011e0db16"
},
"details": {
"image": {
"imageId": "sha256:2dc59356f7628b708e7e4112330ed852dc47c5adb65d36df3a4519bb082fad13",
"tag": "2023.10.10.14.24.21.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update igor-armory version to 2023.10.10.14.24.21.master

---

stack.yml

armory/orca-armory:2023.10.10.14.00.40.release-2.30.x
[efaf4403989093d9d46e3cae818b3d2a3ec3b977](https://github.com/armory-io/orca-armory/commit/efaf4403989093d9d46e3cae818b3d2a3ec3b977)
[5ad5cce6b6782429bac3fb243ccf70d1bcf873eb](https://github.com/spinnaker/orca/commit/5ad5cce6b6782429bac3fb243ccf70d1bcf873eb)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5ad5cce6b6782429bac3fb243ccf70d1bcf873eb"
},
"details": {
"image": {
"imageId": "sha256:138c44e75c81f9eac00702a217a8d1dfe2c1f08a8fc857fd1e19cbf741abd5cd",
"tag": "2023.10.10.14.00.40.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2023.10.10.14.00.40.release-2.30.x

---

stack.yml

* **master**
armory/orca-armory:2023.10.10.14.23.58.master
[a68fa5c9c9b06b4162c85558e0f33ae69457d160](https://github.com/armory-io/orca-armory/commit/a68fa5c9c9b06b4162c85558e0f33ae69457d160)
[7523f5dc539cabb9e1da290b1a43f081da95ddb9](https://github.com/spinnaker/orca/commit/7523f5dc539cabb9e1da290b1a43f081da95ddb9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7523f5dc539cabb9e1da290b1a43f081da95ddb9"
},
"details": {
"image": {
"imageId": "sha256:6fa73cab6f4aaf77178b0d2dd2cf2569b6b72177ce6dff2547efaf080d71c864",
"tag": "2023.10.10.14.23.58.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update orca-armory version to 2023.10.10.14.23.58.master

---

stack.yml

* **master**
armory/fiat-armory:2023.10.10.14.21.44.master
[40ccba96ce417c3e4d6145ffca109d7f0cbc8c56](https://github.com/armory-io/fiat-armory/commit/40ccba96ce417c3e4d6145ffca109d7f0cbc8c56)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:71fab03a6dc8790c77046206a4670e2c0ca53b85bdff99176c0d123938b5d240",
"tag": "2023.10.10.14.21.44.master"
},
"vcs": {
"repo": {
},
"sha": "40ccba96ce417c3e4d6145ffca109d7f0cbc8c56"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update fiat-armory version to 2023.10.10.14.21.44.master

---

stack.yml

* **master**
armory/rosco-armory:2023.10.10.14.22.57.master
[5eb8cfaf4980efbcf9e6e45ca72a014438daa197](https://github.com/armory-io/rosco-armory/commit/5eb8cfaf4980efbcf9e6e45ca72a014438daa197)
[4a12958abb4898428e6840e8753b9ca9a3b1a674](https://github.com/spinnaker/rosco/commit/4a12958abb4898428e6840e8753b9ca9a3b1a674)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4a12958abb4898428e6840e8753b9ca9a3b1a674"
},
"details": {
"image": {
"imageId": "sha256:af5bb3486f48c4e84a559186c6f0b2d7deaf35348c6287c7ef20c8a7f7c73502",
"tag": "2023.10.10.14.22.57.master"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2023.10.10.14.22.57.master

---

stack.yml

* **master**
armory/dinghy:2023.10.11.14.10.48.master
[3380324ef645b3aa718882b26c4bcb51b16f2c56](https://github.com/armory-io/dinghy/commit/3380324ef645b3aa718882b26c4bcb51b16f2c56)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:ef0cbd342dd00f8e0818b11fb43ca8f80dab67135912077d71ac341e0e72fd0e",
"tag": "2023.10.11.14.10.48.master"
},
"vcs": {
"repo": {
},
"sha": "3380324ef645b3aa718882b26c4bcb51b16f2c56"
}
},
},
"details": {
"image": {
"imageId": "sha256:ef0cbd342dd00f8e0818b11fb43ca8f80dab67135912077d71ac341e0e72fd0e", …
```

chore(cd): update dinghy version to 2023.10.11.14.10.48.master

---

stack.yml

* **master**
armory/gate-armory:2023.10.10.14.24.34.master
[00b42e695cb9a690568017760304967b21865389](https://github.com/armory-io/gate-armory/commit/00b42e695cb9a690568017760304967b21865389)
[77d22831030c6e3f74436496def3d80392410fb0](https://github.com/spinnaker/gate/commit/77d22831030c6e3f74436496def3d80392410fb0)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "77d22831030c6e3f74436496def3d80392410fb0"
},
"details": {
"image": {
"imageId": "sha256:255f5aa51dcd9653795f0c7a6ecd0fa77ae2a4cd871d180df928a6473b130b7b",
"tag": "2023.10.10.14.24.34.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update gate-armory version to 2023.10.10.14.24.34.master

---

stack.yml

armory/orca-armory:2023.10.11.21.28.04.release-2.31.x
[4704b2b1072a3caa380ace975da9206252b310f6](https://github.com/armory-io/orca-armory/commit/4704b2b1072a3caa380ace975da9206252b310f6)
[eccc5c07770aa4183791f48f8c283ae893db364e](https://github.com/spinnaker/orca/commit/eccc5c07770aa4183791f48f8c283ae893db364e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "eccc5c07770aa4183791f48f8c283ae893db364e"
},
"details": {
"image": {
"imageId": "sha256:d5923a1beaa68574eae63cab8ff7b4a0d53c56c2584f87fbda1426c9bf26be7b",
"tag": "2023.10.11.21.28.04.release-2.31.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2023.10.11.21.28.04.release-2.31.x

---

stack.yml

armory/fiat-armory:2023.10.10.14.26.39.release-2.31.x
[d0f268bfbcd374bfc104e0fd95d6c76d0d0a5770](https://github.com/armory-io/fiat-armory/commit/d0f268bfbcd374bfc104e0fd95d6c76d0d0a5770)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:b755976301f14c6d9386fe7cf15569d773497baadc144f42cda9db0a3cc74d87",
"tag": "2023.10.10.14.26.39.release-2.31.x"
},
"vcs": {
"repo": {
},
"sha": "d0f268bfbcd374bfc104e0fd95d6c76d0d0a5770"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update fiat-armory version to 2023.10.10.14.26.39.release-2.31.x

---

stack.yml

armory/rosco-armory:2023.10.11.07.51.24.release-2.31.x
[f814f8fd29eb634de47cf116699177e354b74dc0](https://github.com/armory-io/rosco-armory/commit/f814f8fd29eb634de47cf116699177e354b74dc0)
[4ec52a45986da73e27a8ceba1f3c34f53283d614](https://github.com/spinnaker/rosco/commit/4ec52a45986da73e27a8ceba1f3c34f53283d614)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4ec52a45986da73e27a8ceba1f3c34f53283d614"
},
"details": {
"image": {
"imageId": "sha256:accafaf2c06403f971d6e791db58ccfe4e6e0b9ea43024eb972dc9bdb73e0a33",
"tag": "2023.10.11.07.51.24.release-2.31.x"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2023.10.11.07.51.24.release-2.31.x

---

stack.yml

armory/deck-armory:2023.10.11.14.22.07.release-2.31.x
[7149c5a389e4cf0e700c149c6fb5d5a2a9557903](https://github.com/armory-io/deck-armory/commit/7149c5a389e4cf0e700c149c6fb5d5a2a9557903)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:17f6f317ae7653ef9a09692fc39af1ac68e9e461e1d27655ab8e5b8bb64ecc75",
"tag": "2023.10.11.14.22.07.release-2.31.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2023.10.11.14.22.07.release-2.31.x

---

stack.yml

armory/clouddriver-armory:2023.10.11.14.21.24.release-2.31.x
[33d6e81178123f1d0bf3441075c1bc18f9d951c2](https://github.com/armory-io/clouddriver-armory/commit/33d6e81178123f1d0bf3441075c1bc18f9d951c2)
[e1de704201a761271f79981c769fff37a34e8bfe](https://github.com/spinnaker/clouddriver/commit/e1de704201a761271f79981c769fff37a34e8bfe)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e1de704201a761271f79981c769fff37a34e8bfe"
},
"details": {
"image": {
"imageId": "sha256:1bd98a2e23838c6eaa8056b138f6b694ba3e680ae89e9ae48c2e0ae53873b304",
"tag": "2023.10.11.14.21.24.release-2.31.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.10.11.14.21.24.release-2.31.x

---

stack.yml

armory/orca-armory:2023.10.10.19.09.12.release-2.27.x
[09d45bfb374d2dbebd1df913771634c5238be678](https://github.com/armory-io/orca-armory/commit/09d45bfb374d2dbebd1df913771634c5238be678)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:2e6e9e39f7055ac6d720399540449d46181d8046632740ff9fdf01654827e574",
"tag": "2023.10.10.19.09.12.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "09d45bfb374d2dbebd1df913771634c5238be678"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update orca-armory version to 2023.10.10.19.09.12.release-2.27.x

---

stack.yml

armory/gate-armory:2023.10.12.06.06.55.release-2.31.x
[1a4fc24d3d4870c375f6bc10fe6892c6b39a789e](https://github.com/armory-io/gate-armory/commit/1a4fc24d3d4870c375f6bc10fe6892c6b39a789e)
[7bc7898bee5c38a200fafbf391126a41dd4aa594](https://github.com/spinnaker/gate/commit/7bc7898bee5c38a200fafbf391126a41dd4aa594)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7bc7898bee5c38a200fafbf391126a41dd4aa594"
},
"details": {
"image": {
"imageId": "sha256:bf9b57ae0484cc7997beeed81616b6647aee7be93073e4cb32175b3d6e08b8b3",
"tag": "2023.10.12.06.06.55.release-2.31.x"
},
"vcs": {
"repo": { …
```

chore(cd): update gate-armory version to 2023.10.12.06.06.55.release-2.31.x

---

stack.yml

armory/front50-armory:2023.10.12.06.05.58.release-2.31.x
[5db553c003950174757e6438ba024b6a4b51c9ed](https://github.com/armory-io/front50-armory/commit/5db553c003950174757e6438ba024b6a4b51c9ed)
[f0494570576de5aa33d969fdd7fad93dee2479cc](https://github.com/spinnaker/front50/commit/f0494570576de5aa33d969fdd7fad93dee2479cc)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f0494570576de5aa33d969fdd7fad93dee2479cc"
},
"details": {
"image": {
"imageId": "sha256:b989bf437a860304905f23af0874e0dec8a246986d4e13f56af1ff07b99e0980",
"tag": "2023.10.12.06.05.58.release-2.31.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update front50-armory version to 2023.10.12.06.05.58.release-2.31.x

---

stack.yml

armory/orca-armory:2023.10.12.06.32.48.release-2.31.x
[d1c9d2239ad0fb2e2a1b9d3d1eb6ea37cbf994bd](https://github.com/armory-io/orca-armory/commit/d1c9d2239ad0fb2e2a1b9d3d1eb6ea37cbf994bd)
[eccc5c07770aa4183791f48f8c283ae893db364e](https://github.com/spinnaker/orca/commit/eccc5c07770aa4183791f48f8c283ae893db364e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "eccc5c07770aa4183791f48f8c283ae893db364e"
},
"details": {
"image": {
"imageId": "sha256:8a80101a0bfcba7f41682bfbe2df752f193933619d431dd9c8eda94749038b7f",
"tag": "2023.10.12.06.32.48.release-2.31.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2023.10.12.06.32.48.release-2.31.x

---

stack.yml

armory/kayenta-armory:2023.10.12.07.25.23.release-2.31.x
[291ff224d1098f34823010ba2335e16ae149d39b](https://github.com/armory-io/kayenta-armory/commit/291ff224d1098f34823010ba2335e16ae149d39b)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:4a6fbda9dc95a51a45ee2c2fbf77d3b7df5769bbde50d974f73d6aec0d9e913f",
"tag": "2023.10.12.07.25.23.release-2.31.x"
},
"vcs": {
"repo": {
},
"sha": "291ff224d1098f34823010ba2335e16ae149d39b"
}
},
},
"details": { …
```

chore(cd): update kayenta-armory version to 2023.10.12.07.25.23.release-2.31.x

---

stack.yml

* **master**
armory/echo-armory:2023.10.10.14.21.17.master
[e05db459d4d60fa574a5c4744fdb84cd0094e48f](https://github.com/armory-io/echo-armory/commit/e05db459d4d60fa574a5c4744fdb84cd0094e48f)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:d2f209231f62cb62556889c24576ce5178d3e33ccbc32ea9d835d1373769c4a1",
"tag": "2023.10.10.14.21.17.master"
},
"vcs": {
"repo": {
},
"sha": "e05db459d4d60fa574a5c4744fdb84cd0094e48f"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update echo-armory version to 2023.10.10.14.21.17.master

---

stack.yml

* **master**
armory/clouddriver-armory:2023.10.11.21.06.46.master
[bbb837536efe1c77b6bf3928cca243577efce743](https://github.com/armory-io/clouddriver-armory/commit/bbb837536efe1c77b6bf3928cca243577efce743)
[29d5f1c36cec85b4cc7630c3bb6e6fc70c0bd01f](https://github.com/spinnaker/clouddriver/commit/29d5f1c36cec85b4cc7630c3bb6e6fc70c0bd01f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "29d5f1c36cec85b4cc7630c3bb6e6fc70c0bd01f"
},
"details": {
"image": {
"imageId": "sha256:863a6b48861e6c9669aa41e8ed545fe2e8c6e36f5f5b5a418b8711b2f184873b",
"tag": "2023.10.11.21.06.46.master"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update clouddriver-armory version to 2023.10.11.21.06.46.master

---

stack.yml

* **master**
armory/kayenta-armory:2023.10.12.07.04.23.master
[5e8acf76a47219207a3b30110756daf5ed0fc95e](https://github.com/armory-io/kayenta-armory/commit/5e8acf76a47219207a3b30110756daf5ed0fc95e)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:ed5768e9a260c73e2ebb06e4b36a02ff81b74933175b9682844cea62102cb262",
"tag": "2023.10.12.07.04.23.master"
},
"vcs": {
"repo": {
},
"sha": "5e8acf76a47219207a3b30110756daf5ed0fc95e"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update kayenta-armory version to 2023.10.12.07.04.23.master

---

stack.yml

armory/orca-armory:2023.10.16.07.01.57.release-2.28.x
[aeb85450ede996e0b7097c3daba5521e9c9df659](https://github.com/armory-io/orca-armory/commit/aeb85450ede996e0b7097c3daba5521e9c9df659)
[a65d34f986d97f7a9a22aca4edfd898b694cbd2a](https://github.com/spinnaker/orca/commit/a65d34f986d97f7a9a22aca4edfd898b694cbd2a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a65d34f986d97f7a9a22aca4edfd898b694cbd2a"
},
"details": {
"image": {
"imageId": "sha256:1298cf8cd5267b946541b1a142d0dbce52f6cc4f6668c7855b6a75fdd786e7ec",
"tag": "2023.10.16.07.01.57.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2023.10.16.07.01.57.release-2.28.x

---

stack.yml

* **master**
armory/gate-armory:2023.10.17.20.27.23.master
[51cda8b8b8fb82be92191969d9f8cff770bb91e4](https://github.com/armory-io/gate-armory/commit/51cda8b8b8fb82be92191969d9f8cff770bb91e4)
[77d22831030c6e3f74436496def3d80392410fb0](https://github.com/spinnaker/gate/commit/77d22831030c6e3f74436496def3d80392410fb0)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "77d22831030c6e3f74436496def3d80392410fb0"
},
"details": {
"image": {
"imageId": "sha256:55984848917ffca055f98f8f81b43f5389fccbd83d54dff72ef7cfa40d26dd4e",
"tag": "2023.10.17.20.27.23.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update gate-armory version to 2023.10.17.20.27.23.master

---

stack.yml

* **master**
armory/gate-armory:2023.10.17.23.16.30.master
[83aae58b77919c6f474a877f0a6e08bf6ea6bcdc](https://github.com/armory-io/gate-armory/commit/83aae58b77919c6f474a877f0a6e08bf6ea6bcdc)
[4412a029be154a59a0d9170e2625cde31c0fc3fe](https://github.com/spinnaker/gate/commit/4412a029be154a59a0d9170e2625cde31c0fc3fe)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4412a029be154a59a0d9170e2625cde31c0fc3fe"
},
"details": {
"image": {
"imageId": "sha256:095ed0d8a91dcb0abb655f91901ebe20899d55288892d02e46f65248a61a01e8",
"tag": "2023.10.17.23.16.30.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update gate-armory version to 2023.10.17.23.16.30.master

---

stack.yml

* **master**
armory/deck-armory:2023.10.17.18.27.27.master
[a39a63e8a30db0d236080da18a0f3bd0c7a212ab](https://github.com/armory-io/deck-armory/commit/a39a63e8a30db0d236080da18a0f3bd0c7a212ab)
[217b75396c5ec25d9b2019a849593b0b8d52e916](https://github.com/spinnaker/deck/commit/217b75396c5ec25d9b2019a849593b0b8d52e916)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "217b75396c5ec25d9b2019a849593b0b8d52e916"
},
"details": {
"image": {
"imageId": "sha256:e031f6170af4c4e879f6c43ce68f42e44be8b22bacb357d211b1aa76209e09cd",
"tag": "2023.10.17.18.27.27.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update deck-armory version to 2023.10.17.18.27.27.master

---

stack.yml

* **master**
armory/front50-armory:2023.10.17.23.10.21.master
[eea97579d95236513bc44daaedda3f11495a80b9](https://github.com/armory-io/front50-armory/commit/eea97579d95236513bc44daaedda3f11495a80b9)
[960e31490cced246ca188e510d7c82d2b3bb2719](https://github.com/spinnaker/front50/commit/960e31490cced246ca188e510d7c82d2b3bb2719)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "960e31490cced246ca188e510d7c82d2b3bb2719"
},
"details": {
"image": {
"imageId": "sha256:4dd475995a23b3ce60bc99f0113c0970a37a249bfb3c834fe81689854bba1e87",
"tag": "2023.10.17.23.10.21.master"
},
"vcs": {
"repo": {
"repoName": …
```

chore(cd): update front50-armory version to 2023.10.17.23.10.21.master

---

stack.yml

* **master**
armory/echo-armory:2023.10.17.23.16.01.master
[1be73d7e8eee516caabca841f0321112403bd6d5](https://github.com/armory-io/echo-armory/commit/1be73d7e8eee516caabca841f0321112403bd6d5)
[89a810a26b7149dc31d4e43b461152510a8a22e8](https://github.com/spinnaker/echo/commit/89a810a26b7149dc31d4e43b461152510a8a22e8)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "89a810a26b7149dc31d4e43b461152510a8a22e8"
},
"details": {
"image": {
"imageId": "sha256:e06dda343ba2671f17d28f6ea4ca9c8f96bd218abccb7846af39617abd9b93f0",
"tag": "2023.10.17.23.16.01.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update echo-armory version to 2023.10.17.23.16.01.master

---

stack.yml

* **master**
armory/orca-armory:2023.10.17.23.15.40.master
[8947db89672812b09848e895bc9e9ac7bbf741e9](https://github.com/armory-io/orca-armory/commit/8947db89672812b09848e895bc9e9ac7bbf741e9)
[4ba2cc05f2edc83e69b01dfbbc96917f7c33c13b](https://github.com/spinnaker/orca/commit/4ba2cc05f2edc83e69b01dfbbc96917f7c33c13b)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4ba2cc05f2edc83e69b01dfbbc96917f7c33c13b"
},
"details": {
"image": {
"imageId": "sha256:89a0a6d102e6f992fb533873b3aee2f88be8020d974b4e858a1481de9eef8dbd",
"tag": "2023.10.17.23.15.40.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update orca-armory version to 2023.10.17.23.15.40.master

---

stack.yml

armory/rosco-armory:2023.10.18.06.17.23.release-2.31.x
[a30386ed64ae490e4788fe80b453528731a923bd](https://github.com/armory-io/rosco-armory/commit/a30386ed64ae490e4788fe80b453528731a923bd)
[6a866e7c74ce241f5c849978d0a2bafc739cf882](https://github.com/spinnaker/rosco/commit/6a866e7c74ce241f5c849978d0a2bafc739cf882)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "6a866e7c74ce241f5c849978d0a2bafc739cf882"
},
"details": {
"image": {
"imageId": "sha256:3623c466ada03554779a51165b4c10adf8ce0283cd8240a9dc22333cbaea165b",
"tag": "2023.10.18.06.17.23.release-2.31.x"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2023.10.18.06.17.23.release-2.31.x

---

stack.yml

armory/deck-armory:2023.10.19.03.31.19.release-2.31.x
[afb472fb69bec1b9d41c2f572de861413b032df7](https://github.com/armory-io/deck-armory/commit/afb472fb69bec1b9d41c2f572de861413b032df7)
[c0c1f5297e82560231958fa9bfbaaf2b499249b2](https://github.com/spinnaker/deck/commit/c0c1f5297e82560231958fa9bfbaaf2b499249b2)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c0c1f5297e82560231958fa9bfbaaf2b499249b2"
},
"details": {
"image": {
"imageId": "sha256:f0d3fd807547fe89c8e9694071e6c8d01eba3844aef8fec19cec4544c8158b21",
"tag": "2023.10.19.03.31.19.release-2.31.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2023.10.19.03.31.19.release-2.31.x

---

stack.yml

armory/orca-armory:2023.10.18.06.20.42.release-2.31.x
[c64d5d70447e60ebaa7686d3588fa7738938063c](https://github.com/armory-io/orca-armory/commit/c64d5d70447e60ebaa7686d3588fa7738938063c)
[eccc5c07770aa4183791f48f8c283ae893db364e](https://github.com/spinnaker/orca/commit/eccc5c07770aa4183791f48f8c283ae893db364e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "eccc5c07770aa4183791f48f8c283ae893db364e"
},
"details": {
"image": {
"imageId": "sha256:21f1731d02c3b1fa61b427e14cc0619dcf2580fb66c1ab8cd222baf15669830d",
"tag": "2023.10.18.06.20.42.release-2.31.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2023.10.18.06.20.42.release-2.31.x

---

stack.yml

armory/rosco-armory:2023.10.18.06.16.00.release-2.30.x
[7907c80fd9ca1d956d5927a3e190617671b7e012](https://github.com/armory-io/rosco-armory/commit/7907c80fd9ca1d956d5927a3e190617671b7e012)
[5dba8f113491c666514910ac6013f06c15220f8a](https://github.com/spinnaker/rosco/commit/5dba8f113491c666514910ac6013f06c15220f8a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5dba8f113491c666514910ac6013f06c15220f8a"
},
"details": {
"image": {
"imageId": "sha256:3b65ecc3e0d2cf83ddb65912a3e2161fc1df9e1a7571b0ff4032d71895dced49",
"tag": "2023.10.18.06.16.00.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2023.10.18.06.16.00.release-2.30.x

---

stack.yml

armory/orca-armory:2023.10.18.06.20.27.release-2.30.x
[abf688128f3557e53d8873b5f2fe623b1ad478f9](https://github.com/armory-io/orca-armory/commit/abf688128f3557e53d8873b5f2fe623b1ad478f9)
[5ad5cce6b6782429bac3fb243ccf70d1bcf873eb](https://github.com/spinnaker/orca/commit/5ad5cce6b6782429bac3fb243ccf70d1bcf873eb)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5ad5cce6b6782429bac3fb243ccf70d1bcf873eb"
},
"details": {
"image": {
"imageId": "sha256:30f28e6bde51df3e5f528a6795546ed5dd6b328ed01984b1886de6b23de937ea",
"tag": "2023.10.18.06.20.27.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2023.10.18.06.20.27.release-2.30.x

---

stack.yml

armory/igor-armory:2023.10.19.12.30.06.release-2.30.x
[3123451525458f96548859b9bf2b15c89810f577](https://github.com/armory-io/igor-armory/commit/3123451525458f96548859b9bf2b15c89810f577)
[4349ba154c386db91a828b928e97b53567e15a03](https://github.com/spinnaker/igor/commit/4349ba154c386db91a828b928e97b53567e15a03)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4349ba154c386db91a828b928e97b53567e15a03"
},
"details": {
"image": {
"imageId": "sha256:7d70c242c36e36f2700d0c1c38917cca13de3304e6a851d0ddbb5352123ea757",
"tag": "2023.10.19.12.30.06.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update igor-armory version to 2023.10.19.12.30.06.release-2.30.x

---

stack.yml

armory/deck-armory:2023.10.18.06.32.14.release-2.30.x
[305d4e3ccdd7ad009c14a0093cd64bdb0ad9aeaa](https://github.com/armory-io/deck-armory/commit/305d4e3ccdd7ad009c14a0093cd64bdb0ad9aeaa)
[e9358ab59131eb53c171e753fce72f25dcba0805](https://github.com/spinnaker/deck/commit/e9358ab59131eb53c171e753fce72f25dcba0805)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e9358ab59131eb53c171e753fce72f25dcba0805"
},
"details": {
"image": {
"imageId": "sha256:0879b7917b825c704184ed66341022548cc76a91bd9393055ca32f1752e2cbb9",
"tag": "2023.10.18.06.32.14.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2023.10.18.06.32.14.release-2.30.x

---

stack.yml

armory/orca-armory:2023.10.18.06.20.02.release-2.28.x
[0c7158b66e4251ed8662abee94c51bcd61dfa36e](https://github.com/armory-io/orca-armory/commit/0c7158b66e4251ed8662abee94c51bcd61dfa36e)
[a65d34f986d97f7a9a22aca4edfd898b694cbd2a](https://github.com/spinnaker/orca/commit/a65d34f986d97f7a9a22aca4edfd898b694cbd2a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a65d34f986d97f7a9a22aca4edfd898b694cbd2a"
},
"details": {
"image": {
"imageId": "sha256:8d4901fe4058935a7ce5822e3f68f9db495912a18200d362283c693a0620159d",
"tag": "2023.10.18.06.20.02.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2023.10.18.06.20.02.release-2.28.x

---

stack.yml

armory/rosco-armory:2023.10.18.15.42.48.release-2.28.x
[de907c904140088d22deeafa948761190f1bdf38](https://github.com/armory-io/rosco-armory/commit/de907c904140088d22deeafa948761190f1bdf38)
[e8bf6c58c64111c6c15ce501d27df6b40dce3243](https://github.com/spinnaker/rosco/commit/e8bf6c58c64111c6c15ce501d27df6b40dce3243)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e8bf6c58c64111c6c15ce501d27df6b40dce3243"
},
"details": {
"image": {
"imageId": "sha256:ebe0a76ca13d7e2a6cf0d9e71e46fac0b8d1ac4d944547e44bf0d68c0666abd8",
"tag": "2023.10.18.15.42.48.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2023.10.18.15.42.48.release-2.28.x

---

stack.yml

armory/deck-armory:2023.10.18.06.33.21.release-2.28.x
[4296c0504f0e3bd286e5ea85822ac9b8f3a1a18c](https://github.com/armory-io/deck-armory/commit/4296c0504f0e3bd286e5ea85822ac9b8f3a1a18c)
[e51a58bc13147d4582a6170c7c8417c3409b98af](https://github.com/spinnaker/deck/commit/e51a58bc13147d4582a6170c7c8417c3409b98af)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e51a58bc13147d4582a6170c7c8417c3409b98af"
},
"details": {
"image": {
"imageId": "sha256:2a3b8eeafaafcdb977baf181c017799e457c931b4b1b0c076bab405ae60d77f9",
"tag": "2023.10.18.06.33.21.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2023.10.18.06.33.21.release-2.28.x

---

stack.yml

* **master**
armory/echo-armory:2023.10.20.18.03.11.master
[892120292de9a3b506510dc1650289ff8f9af458](https://github.com/armory-io/echo-armory/commit/892120292de9a3b506510dc1650289ff8f9af458)
[4fa2665c1a2ce9a1905b62bd961560095a409ee9](https://github.com/spinnaker/echo/commit/4fa2665c1a2ce9a1905b62bd961560095a409ee9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4fa2665c1a2ce9a1905b62bd961560095a409ee9"
},
"details": {
"image": {
"imageId": "sha256:dfdfd28024496ac32c04b0ec97292654af248c037cd803fdfda0c5285b665ae2",
"tag": "2023.10.20.18.03.11.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update echo-armory version to 2023.10.20.18.03.11.master

---

stack.yml

* **master**
armory/orca-armory:2023.10.20.18.09.53.master
[b4a7c95d064ec8531ed9975cba08364a30c84ba1](https://github.com/armory-io/orca-armory/commit/b4a7c95d064ec8531ed9975cba08364a30c84ba1)
[342dcc6e6ee1870506e5fc5bef6890d79ff741ec](https://github.com/spinnaker/orca/commit/342dcc6e6ee1870506e5fc5bef6890d79ff741ec)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "342dcc6e6ee1870506e5fc5bef6890d79ff741ec"
},
"details": {
"image": {
"imageId": "sha256:24d0c68b5663b00f0462f1043667a0c208bb3ec910697bf1f918a1abd661e59e",
"tag": "2023.10.20.18.09.53.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update orca-armory version to 2023.10.20.18.09.53.master

---

stack.yml

* **master**
armory/gate-armory:2023.10.20.18.03.28.master
[c32c488a1a3f5ff82536cb33aec4d93accbdae77](https://github.com/armory-io/gate-armory/commit/c32c488a1a3f5ff82536cb33aec4d93accbdae77)
[87a5dcb61a28d432beac7cd3bae020746cd151d6](https://github.com/spinnaker/gate/commit/87a5dcb61a28d432beac7cd3bae020746cd151d6)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "87a5dcb61a28d432beac7cd3bae020746cd151d6"
},
"details": {
"image": {
"imageId": "sha256:f0c30601f9ec33309675e18563b0b54fa1f6750c3152e52b996f551e853ab65d",
"tag": "2023.10.20.18.03.28.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update gate-armory version to 2023.10.20.18.03.28.master

---

stack.yml

* **master**
armory/front50-armory:2023.10.20.18.13.52.master
[f2241499005b32ec1b9b18ba8b46efc77f20409d](https://github.com/armory-io/front50-armory/commit/f2241499005b32ec1b9b18ba8b46efc77f20409d)
[3bec84a92d461f430005c5c989cc4c28d2d877ec](https://github.com/spinnaker/front50/commit/3bec84a92d461f430005c5c989cc4c28d2d877ec)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "3bec84a92d461f430005c5c989cc4c28d2d877ec"
},
"details": {
"image": {
"imageId": "sha256:074c9c85f36997c3998402f302558642e9b0ade9300571872e5141f376f13ba3",
"tag": "2023.10.20.18.13.52.master"
},
"vcs": {
"repo": {
"repoName": …
```

chore(cd): update front50-armory version to 2023.10.20.18.13.52.master

---

stack.yml

* **master**
armory/clouddriver-armory:2023.10.20.19.02.14.master
[2cb199908c3f649df5b7778699f69aaac2ef8c8c](https://github.com/armory-io/clouddriver-armory/commit/2cb199908c3f649df5b7778699f69aaac2ef8c8c)
[9beb889c961d8231a8290b3b18d663f787bb33a4](https://github.com/spinnaker/clouddriver/commit/9beb889c961d8231a8290b3b18d663f787bb33a4)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9beb889c961d8231a8290b3b18d663f787bb33a4"
},
"details": {
"image": {
"imageId": "sha256:c23d9135623e9ca5d626b1e6bbff7b9d96ebb585be17ee3220ba885cdccb8f21",
"tag": "2023.10.20.19.02.14.master"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update clouddriver-armory version to 2023.10.20.19.02.14.master

---

stack.yml

* **master**
armory/echo-armory:2023.10.26.17.42.35.master
[c52ea6cfa71b3fa57070cd820ffd201e3c99664c](https://github.com/armory-io/echo-armory/commit/c52ea6cfa71b3fa57070cd820ffd201e3c99664c)
[8bdcaa558085a11ad03cb3f49ce550f8cadc5c20](https://github.com/spinnaker/echo/commit/8bdcaa558085a11ad03cb3f49ce550f8cadc5c20)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "8bdcaa558085a11ad03cb3f49ce550f8cadc5c20"
},
"details": {
"image": {
"imageId": "sha256:d1f3cc5c3d24744e9c2da9365862c31804a8182f4a896137b4e9120e4cf59800",
"tag": "2023.10.26.17.42.35.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update echo-armory version to 2023.10.26.17.42.35.master

---

stack.yml

* **master**
armory/orca-armory:2023.10.27.14.57.16.master
[35ae8c07fbdff35f85d7fcb87815a79f3f7eaa3b](https://github.com/armory-io/orca-armory/commit/35ae8c07fbdff35f85d7fcb87815a79f3f7eaa3b)
[b1071bd1725c6c73eb06465e1529eb421aa594cf](https://github.com/spinnaker/orca/commit/b1071bd1725c6c73eb06465e1529eb421aa594cf)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b1071bd1725c6c73eb06465e1529eb421aa594cf"
},
"details": {
"image": {
"imageId": "sha256:a75a0626f4c1e1da83f02eaeed5d5d46c9c4f14eb6a80c17eb698f892de6958c",
"tag": "2023.10.27.14.57.16.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update orca-armory version to 2023.10.27.14.57.16.master

---

stack.yml

* **master**
armory/orca-armory:2023.10.30.21.54.22.master
[f5dc0607cd3d2d05e006262f8a84b02c7710851d](https://github.com/armory-io/orca-armory/commit/f5dc0607cd3d2d05e006262f8a84b02c7710851d)
[2e3c5f066b3e3e1e106fd6c9100ca02aae966bdb](https://github.com/spinnaker/orca/commit/2e3c5f066b3e3e1e106fd6c9100ca02aae966bdb)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "2e3c5f066b3e3e1e106fd6c9100ca02aae966bdb"
},
"details": {
"image": {
"imageId": "sha256:da64ccea499f722a5210bb854e5011a07cfca2ad6671cf0337cac2c7d2020675",
"tag": "2023.10.30.21.54.22.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update orca-armory version to 2023.10.30.21.54.22.master

---

stack.yml

* **master**
armory/deck-armory:2023.10.24.13.54.38.master
[0cf158dfe45ca5d7c87ca969a9dd3a5bda5b2dd8](https://github.com/armory-io/deck-armory/commit/0cf158dfe45ca5d7c87ca969a9dd3a5bda5b2dd8)
[889d769c600e298917ec2471cd88a4bdd808ed91](https://github.com/spinnaker/deck/commit/889d769c600e298917ec2471cd88a4bdd808ed91)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "889d769c600e298917ec2471cd88a4bdd808ed91"
},
"details": {
"image": {
"imageId": "sha256:e6b2e7b5435da981dfa2e6255bfb20aff095059613d26eb42e220d159df85873",
"tag": "2023.10.24.13.54.38.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update deck-armory version to 2023.10.24.13.54.38.master

---

stack.yml

* **master**
armory/clouddriver-armory:2023.10.30.04.51.08.master
[7ac78f330e74b7667dfbb3b53c4edbdabdb9587b](https://github.com/armory-io/clouddriver-armory/commit/7ac78f330e74b7667dfbb3b53c4edbdabdb9587b)
[7a61a2e6bfe4abfe755b55c36a7ef5a61f49fe44](https://github.com/spinnaker/clouddriver/commit/7a61a2e6bfe4abfe755b55c36a7ef5a61f49fe44)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7a61a2e6bfe4abfe755b55c36a7ef5a61f49fe44"
},
"details": {
"image": {
"imageId": "sha256:c971039445a1f749abc9c29a6592614de09b9b76e868f2583ff742fc4f33dad5",
"tag": "2023.10.30.04.51.08.master"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update clouddriver-armory version to 2023.10.30.04.51.08.master

---

stack.yml

* **master**
armory/clouddriver-armory:2023.11.01.06.03.16.master
[e08cd3fe8bc127bd857e6e45eb50ee0698774b84](https://github.com/armory-io/clouddriver-armory/commit/e08cd3fe8bc127bd857e6e45eb50ee0698774b84)
[3e0bcfb35e6979d37e411978f5155b2f7b513f5b](https://github.com/spinnaker/clouddriver/commit/3e0bcfb35e6979d37e411978f5155b2f7b513f5b)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "3e0bcfb35e6979d37e411978f5155b2f7b513f5b"
},
"details": {
"image": {
"imageId": "sha256:56b613e29406ec958503cfbcdb434e5c91d615f98b5e8bfe18634a908f40432f",
"tag": "2023.11.01.06.03.16.master"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update clouddriver-armory version to 2023.11.01.06.03.16.master

---

stack.yml

* **master**
armory/echo-armory:2023.10.30.00.29.48.master
[309f91770bd4c7c8285f488057ceb054599354ec](https://github.com/armory-io/echo-armory/commit/309f91770bd4c7c8285f488057ceb054599354ec)
[b4097ca708c1834a771a155199f69285107b17cc](https://github.com/spinnaker/echo/commit/b4097ca708c1834a771a155199f69285107b17cc)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b4097ca708c1834a771a155199f69285107b17cc"
},
"details": {
"image": {
"imageId": "sha256:09297df7e0bccb025591428e44feb7cd2e9e9c945c171bfa95558eeee3656452",
"tag": "2023.10.30.00.29.48.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update echo-armory version to 2023.10.30.00.29.48.master

---

stack.yml

* **master**
armory/clouddriver-armory:2023.11.01.10.58.30.master
[f8cebefd2fd08129f4e150c86a8abf18f00be02f](https://github.com/armory-io/clouddriver-armory/commit/f8cebefd2fd08129f4e150c86a8abf18f00be02f)
[20a8cf6a6c5b744bb96a78d6aa329981fc6fb704](https://github.com/spinnaker/clouddriver/commit/20a8cf6a6c5b744bb96a78d6aa329981fc6fb704)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "20a8cf6a6c5b744bb96a78d6aa329981fc6fb704"
},
"details": {
"image": {
"imageId": "sha256:77c627c20827a12ef3031ae47fbb21fc67eee54bf45ad462bceeaf926d5edda1",
"tag": "2023.11.01.10.58.30.master"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update clouddriver-armory version to 2023.11.01.10.58.30.master

---

stack.yml

* **master**
armory/rosco-armory:2023.10.31.23.03.34.master
[32d03a257c51f057fa7bb96b5f9c10a9379804b3](https://github.com/armory-io/rosco-armory/commit/32d03a257c51f057fa7bb96b5f9c10a9379804b3)
[e8ffd89afe0ecaea47ed913dbdc8abad7eb6d181](https://github.com/spinnaker/rosco/commit/e8ffd89afe0ecaea47ed913dbdc8abad7eb6d181)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e8ffd89afe0ecaea47ed913dbdc8abad7eb6d181"
},
"details": {
"image": {
"imageId": "sha256:ba8ddf993783fcd856b21abdcc1e83d90850d22809a6524e2bec0b5ba829b9f4",
"tag": "2023.10.31.23.03.34.master"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2023.10.31.23.03.34.master

---

stack.yml

armory/deck-armory:2023.10.24.16.20.19.release-2.31.x
[1dd95e4ef5ed631f24253bf917200c3cf52655af](https://github.com/armory-io/deck-armory/commit/1dd95e4ef5ed631f24253bf917200c3cf52655af)
[669d1ede44df1172a7503fe8eeb09884dac1b103](https://github.com/spinnaker/deck/commit/669d1ede44df1172a7503fe8eeb09884dac1b103)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "669d1ede44df1172a7503fe8eeb09884dac1b103"
},
"details": {
"image": {
"imageId": "sha256:b2089a4923f746facc2941ee2ccc5ac7f3f48b69f1371961e51a7976d53db94b",
"tag": "2023.10.24.16.20.19.release-2.31.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2023.10.24.16.20.19.release-2.31.x

---

stack.yml

* **master**
armory/orca-armory:2023.11.03.16.57.49.master
[626fcfefa2a7dd4ad242b37381b71b29eca64a59](https://github.com/armory-io/orca-armory/commit/626fcfefa2a7dd4ad242b37381b71b29eca64a59)
[5385ad267f027de83522e66655e499e1d699b8b2](https://github.com/spinnaker/orca/commit/5385ad267f027de83522e66655e499e1d699b8b2)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5385ad267f027de83522e66655e499e1d699b8b2"
},
"details": {
"image": {
"imageId": "sha256:77493b087e2a33a36d1d47f64e7646be8b173c82715b23f773320695a286a3c3",
"tag": "2023.11.03.16.57.49.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update orca-armory version to 2023.11.03.16.57.49.master

---

stack.yml

* **master**
armory/deck-armory:2023.11.01.18.27.41.master
[dada6f9a22f290cfb22748d9d354eedd2b6025c0](https://github.com/armory-io/deck-armory/commit/dada6f9a22f290cfb22748d9d354eedd2b6025c0)
[c7d804ce56cc698a576a37d3d30369cec63cbe23](https://github.com/spinnaker/deck/commit/c7d804ce56cc698a576a37d3d30369cec63cbe23)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c7d804ce56cc698a576a37d3d30369cec63cbe23"
},
"details": {
"image": {
"imageId": "sha256:692fd5741f333c6e4dba85143ba953c6e7f1707fd2880743f4cd6e3600b8f23a",
"tag": "2023.11.01.18.27.41.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update deck-armory version to 2023.11.01.18.27.41.master

---

stack.yml

* **master**
armory/orca-armory:2023.11.05.19.52.01.master
[2a3e846a8c099fc33c9a357c1a456ae20014e728](https://github.com/armory-io/orca-armory/commit/2a3e846a8c099fc33c9a357c1a456ae20014e728)
[a5d151f8fd36853ebd8786e1b51e6c356ec654c5](https://github.com/spinnaker/orca/commit/a5d151f8fd36853ebd8786e1b51e6c356ec654c5)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a5d151f8fd36853ebd8786e1b51e6c356ec654c5"
},
"details": {
"image": {
"imageId": "sha256:ad6e88e5dcb016e70ca5dbbb07b40056145b98c9ac0562678b7807923442d6c2",
"tag": "2023.11.05.19.52.01.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update orca-armory version to 2023.11.05.19.52.01.master

---

stack.yml

* **master**
armory/echo-armory:2023.11.02.20.10.21.master
[c358a175dfd3747bce2e2fef61abe4622edef4fe](https://github.com/armory-io/echo-armory/commit/c358a175dfd3747bce2e2fef61abe4622edef4fe)
[329ba0440ee68e6728beeaa94884593d0bb1e9b5](https://github.com/spinnaker/echo/commit/329ba0440ee68e6728beeaa94884593d0bb1e9b5)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "329ba0440ee68e6728beeaa94884593d0bb1e9b5"
},
"details": {
"image": {
"imageId": "sha256:b1883575fdbebac121d2f094a46fe9481da804bae01286907bab603fa01c78fe",
"tag": "2023.11.02.20.10.21.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update echo-armory version to 2023.11.02.20.10.21.master

---

stack.yml

* **master**
armory/gate-armory:2023.11.02.20.19.03.master
[c617f31ae0d385fbeebdc6d3a94b22aa744ed341](https://github.com/armory-io/gate-armory/commit/c617f31ae0d385fbeebdc6d3a94b22aa744ed341)
[e79565522e3cb2598623556db8cd3861e6c045a6](https://github.com/spinnaker/gate/commit/e79565522e3cb2598623556db8cd3861e6c045a6)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e79565522e3cb2598623556db8cd3861e6c045a6"
},
"details": {
"image": {
"imageId": "sha256:af8bb21820170b30b09343477143398cca836bda04725e72c90fa8ac67c3dbf9",
"tag": "2023.11.02.20.19.03.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update gate-armory version to 2023.11.02.20.19.03.master

---

stack.yml

* **master**
armory/front50-armory:2023.11.02.20.19.56.master
[47f17ee3743632188e889df0d766db3308d2660a](https://github.com/armory-io/front50-armory/commit/47f17ee3743632188e889df0d766db3308d2660a)
[0b92adc074f58fcfd758afeabcfa44f837247a39](https://github.com/spinnaker/front50/commit/0b92adc074f58fcfd758afeabcfa44f837247a39)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0b92adc074f58fcfd758afeabcfa44f837247a39"
},
"details": {
"image": {
"imageId": "sha256:c82bdd4b89434655434c3e572c66e5265c58b471d3a871c3ac519d56cccb7905",
"tag": "2023.11.02.20.19.56.master"
},
"vcs": {
"repo": {
"repoName": …
```

chore(cd): update front50-armory version to 2023.11.02.20.19.56.master

---

stack.yml

armory/orca-armory:2023.11.06.18.38.02.release-2.31.x
[9ded4918670615ace3a4c0e871bbaf6d1d99a22c](https://github.com/armory-io/orca-armory/commit/9ded4918670615ace3a4c0e871bbaf6d1d99a22c)
[6ad5cd01dad7656ec7c8e9794180f07b15c942ce](https://github.com/spinnaker/orca/commit/6ad5cd01dad7656ec7c8e9794180f07b15c942ce)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "6ad5cd01dad7656ec7c8e9794180f07b15c942ce"
},
"details": {
"image": {
"imageId": "sha256:04c436bd8168e670a89223c6b45c73f60fbe94f9ead75483c34a805df2b1ab0a",
"tag": "2023.11.06.18.38.02.release-2.31.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2023.11.06.18.38.02.release-2.31.x

---

stack.yml

* **master**
armory/rosco-armory:2023.11.02.20.25.02.master
[aee8b24cab3ec5a7ed88c9fa26b858191bfdbc0e](https://github.com/armory-io/rosco-armory/commit/aee8b24cab3ec5a7ed88c9fa26b858191bfdbc0e)
[0c0c97eb5f6bbd47eac194a32466fd7572f61a88](https://github.com/spinnaker/rosco/commit/0c0c97eb5f6bbd47eac194a32466fd7572f61a88)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0c0c97eb5f6bbd47eac194a32466fd7572f61a88"
},
"details": {
"image": {
"imageId": "sha256:5cc2abdd0785f7293f64847e7c6a75cf7ad7bf175320a076723641c92a6fa534",
"tag": "2023.11.02.20.25.02.master"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2023.11.02.20.25.02.master

---

stack.yml

* **master**
armory/orca-armory:2023.11.06.18.28.47.master
[9e9ddef710f4b8532f4fb7fa833719dcc36709d5](https://github.com/armory-io/orca-armory/commit/9e9ddef710f4b8532f4fb7fa833719dcc36709d5)
[645059dc2a487fbfaf9ab31b5f2d25b4265bfcb5](https://github.com/spinnaker/orca/commit/645059dc2a487fbfaf9ab31b5f2d25b4265bfcb5)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "645059dc2a487fbfaf9ab31b5f2d25b4265bfcb5"
},
"details": {
"image": {
"imageId": "sha256:22c8ce25da91c933825e121898ac0e5e2c01dc3a239827ca7b728fd0c65d9566",
"tag": "2023.11.06.18.28.47.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update orca-armory version to 2023.11.06.18.28.47.master

---

stack.yml

armory/orca-armory:2023.11.07.02.18.11.release-2.30.x
[36d09765a0f61ee9ce32322a6b34dd990a716e12](https://github.com/armory-io/orca-armory/commit/36d09765a0f61ee9ce32322a6b34dd990a716e12)
[1fc563b1cc99ec268b9a55afbca818c78808cda2](https://github.com/spinnaker/orca/commit/1fc563b1cc99ec268b9a55afbca818c78808cda2)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1fc563b1cc99ec268b9a55afbca818c78808cda2"
},
"details": {
"image": {
"imageId": "sha256:5c733260929efd0a522460ad678a93f9649017a33ffd03d8dc2148e4d5961fe1",
"tag": "2023.11.07.02.18.11.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2023.11.07.02.18.11.release-2.30.x

---

stack.yml

* **master**
armory/gate-armory:2023.11.06.17.06.19.master
[b3138da8428e7c58e5c6e99536e85c3537fd66cd](https://github.com/armory-io/gate-armory/commit/b3138da8428e7c58e5c6e99536e85c3537fd66cd)
[f748e0343b170b12beee7b2eeff9ec7802f37484](https://github.com/spinnaker/gate/commit/f748e0343b170b12beee7b2eeff9ec7802f37484)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f748e0343b170b12beee7b2eeff9ec7802f37484"
},
"details": {
"image": {
"imageId": "sha256:45e29dfe08b77e7909642923271ade0ca92959a66847e19082f76eff307bce60",
"tag": "2023.11.06.17.06.19.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update gate-armory version to 2023.11.06.17.06.19.master

---

stack.yml

* **master**
armory/clouddriver-armory:2023.11.02.20.44.53.master
[5cf500dfccd59bc1e0c7d8d6006a8f0d8be651ab](https://github.com/armory-io/clouddriver-armory/commit/5cf500dfccd59bc1e0c7d8d6006a8f0d8be651ab)
[023ff65d9217abcb3d78f3b6e72357a65db01463](https://github.com/spinnaker/clouddriver/commit/023ff65d9217abcb3d78f3b6e72357a65db01463)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "023ff65d9217abcb3d78f3b6e72357a65db01463"
},
"details": {
"image": {
"imageId": "sha256:8e32a424cf2629fb9e8da1ecf33ec802c612b7bcb4ba22ab3086fab1afd7a564",
"tag": "2023.11.02.20.44.53.master"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update clouddriver-armory version to 2023.11.02.20.44.53.master

---

stack.yml

armory/echo-armory:2023.11.02.10.19.09.release-2.31.x
[a700e1233d1eca8642b54413c87860737662d4c2](https://github.com/armory-io/echo-armory/commit/a700e1233d1eca8642b54413c87860737662d4c2)
[d20da255de1fabb96d67012c8d9bc370ba02982c](https://github.com/spinnaker/echo/commit/d20da255de1fabb96d67012c8d9bc370ba02982c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d20da255de1fabb96d67012c8d9bc370ba02982c"
},
"details": {
"image": {
"imageId": "sha256:2e9ec59a3d227ce94ea0aac1cd82dc1f2c040cfb0a0aa3afdc308ef1996ed7bf",
"tag": "2023.11.02.10.19.09.release-2.31.x"
},
"vcs": {
"repo": { …
```

chore(cd): update echo-armory version to 2023.11.02.10.19.09.release-2.31.x

---

stack.yml

armory/deck-armory:2023.10.24.17.00.51.release-2.30.x
[b14f5660fbe9cde883dfaf25442a1e8cfe0c27b0](https://github.com/armory-io/deck-armory/commit/b14f5660fbe9cde883dfaf25442a1e8cfe0c27b0)
[25e472ea0293337c3fb497ec92775143be11e57e](https://github.com/spinnaker/deck/commit/25e472ea0293337c3fb497ec92775143be11e57e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "25e472ea0293337c3fb497ec92775143be11e57e"
},
"details": {
"image": {
"imageId": "sha256:233046465d1bc3a66f24361782bf42daf061e5561b52784898d78e78f765728d",
"tag": "2023.10.24.17.00.51.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2023.10.24.17.00.51.release-2.30.x

---

stack.yml

armory/orca-armory:2023.11.07.16.49.32.release-2.31.x
[10e6902b0062520b1fb9d5749f880df4a29b563a](https://github.com/armory-io/orca-armory/commit/10e6902b0062520b1fb9d5749f880df4a29b563a)
[91de7c3b43df7edb3f7bfd406185b9450a23c3a9](https://github.com/spinnaker/orca/commit/91de7c3b43df7edb3f7bfd406185b9450a23c3a9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "91de7c3b43df7edb3f7bfd406185b9450a23c3a9"
},
"details": {
"image": {
"imageId": "sha256:c9165c3d16b6f397381c365a7c9e15f1944fe42e280d4cecb9096e28a7b138da",
"tag": "2023.11.07.16.49.32.release-2.31.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2023.11.07.16.49.32.release-2.31.x

---

stack.yml

armory/orca-armory:2023.11.08.16.10.43.release-2.30.x
[fdac510ea4f54b33abafbc840d7380100c6ab689](https://github.com/armory-io/orca-armory/commit/fdac510ea4f54b33abafbc840d7380100c6ab689)
[4740c1676f86dd4e24531f689df350fc9a14f302](https://github.com/spinnaker/orca/commit/4740c1676f86dd4e24531f689df350fc9a14f302)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4740c1676f86dd4e24531f689df350fc9a14f302"
},
"details": {
"image": {
"imageId": "sha256:8142983a25a91270cfe30dbacdd8bd74395ea5aee92299ad9fdf3755949b87ce",
"tag": "2023.11.08.16.10.43.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2023.11.08.16.10.43.release-2.30.x

---

stack.yml

armory/rosco-armory:2023.11.09.09.27.15.release-2.30.x
[fe54e55b53f9bc9fdaa313a99127fe04e5fc000c](https://github.com/armory-io/rosco-armory/commit/fe54e55b53f9bc9fdaa313a99127fe04e5fc000c)
[5dba8f113491c666514910ac6013f06c15220f8a](https://github.com/spinnaker/rosco/commit/5dba8f113491c666514910ac6013f06c15220f8a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5dba8f113491c666514910ac6013f06c15220f8a"
},
"details": {
"image": {
"imageId": "sha256:05ceae66e9a7a02236f5671a9213daca8fc701c424ac42d5102766463e7496cd",
"tag": "2023.11.09.09.27.15.release-2.30.x"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2023.11.09.09.27.15.release-2.30.x

---

stack.yml

* **master**
armory/rosco-armory:2023.11.09.08.50.18.master
[9cdf0617f5d30a45030756417309ead92bf275c6](https://github.com/armory-io/rosco-armory/commit/9cdf0617f5d30a45030756417309ead92bf275c6)
[0c0c97eb5f6bbd47eac194a32466fd7572f61a88](https://github.com/spinnaker/rosco/commit/0c0c97eb5f6bbd47eac194a32466fd7572f61a88)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0c0c97eb5f6bbd47eac194a32466fd7572f61a88"
},
"details": {
"image": {
"imageId": "sha256:689651e2e7f935a38fde4d9e6918478c7fe3d363931d0b4fb2b4d1cc7311686e",
"tag": "2023.11.09.08.50.18.master"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2023.11.09.08.50.18.master

---

stack.yml

* **master**
armory/clouddriver-armory:2023.11.08.15.34.21.master
[ed776c6f96a363fae22a5580d433dd5b5587fc80](https://github.com/armory-io/clouddriver-armory/commit/ed776c6f96a363fae22a5580d433dd5b5587fc80)
[8825c133897ae962c9de674ef5cf1b6f9fe8a3c6](https://github.com/spinnaker/clouddriver/commit/8825c133897ae962c9de674ef5cf1b6f9fe8a3c6)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "8825c133897ae962c9de674ef5cf1b6f9fe8a3c6"
},
"details": {
"image": {
"imageId": "sha256:b6d2bfc3926630b49cd072b3d53e5298fb08dd52916a17b6e9790afd95870d71",
"tag": "2023.11.08.15.34.21.master"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update clouddriver-armory version to 2023.11.08.15.34.21.master

---

stack.yml

* **master**
armory/deck-armory:2023.11.10.02.52.39.master
[b6840e2cc79a889dd52a8a5fea6bcaadea93e0fb](https://github.com/armory-io/deck-armory/commit/b6840e2cc79a889dd52a8a5fea6bcaadea93e0fb)
[5c1ebfdf924e73aa6877943cb008c216177b8256](https://github.com/spinnaker/deck/commit/5c1ebfdf924e73aa6877943cb008c216177b8256)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5c1ebfdf924e73aa6877943cb008c216177b8256"
},
"details": {
"image": {
"imageId": "sha256:a933411bca706441c2fdc55821ce6c37c72decb9c3d99a2f1442757b7059b99e",
"tag": "2023.11.10.02.52.39.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update deck-armory version to 2023.11.10.02.52.39.master

---

stack.yml

* **master**
armory/clouddriver-armory:2023.11.10.17.55.00.master
[4f402b8a208ddf829fc9fdee462b5ab39d6d3673](https://github.com/armory-io/clouddriver-armory/commit/4f402b8a208ddf829fc9fdee462b5ab39d6d3673)
[015c948b58caa74ab5d925be6037c977c24a5467](https://github.com/spinnaker/clouddriver/commit/015c948b58caa74ab5d925be6037c977c24a5467)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "015c948b58caa74ab5d925be6037c977c24a5467"
},
"details": {
"image": {
"imageId": "sha256:4bbd1c8107c8889217da7c7e60a223914563b4404eb7a00c98a7a56a9362475e",
"tag": "2023.11.10.17.55.00.master"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update clouddriver-armory version to 2023.11.10.17.55.00.master

---

stack.yml

* **master**
armory/echo-armory:2023.11.10.20.10.28.master
[5de1ebb4ba04593879e4481a231a6b3acbee5eb8](https://github.com/armory-io/echo-armory/commit/5de1ebb4ba04593879e4481a231a6b3acbee5eb8)
[329ba0440ee68e6728beeaa94884593d0bb1e9b5](https://github.com/spinnaker/echo/commit/329ba0440ee68e6728beeaa94884593d0bb1e9b5)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "329ba0440ee68e6728beeaa94884593d0bb1e9b5"
},
"details": {
"image": {
"imageId": "sha256:76bae1c1c8520fa25f067845fa46e9489ad1243cda8870f6b135b106976d0608",
"tag": "2023.11.10.20.10.28.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update echo-armory version to 2023.11.10.20.10.28.master

---

stack.yml

* **master**
armory/orca-armory:2023.11.10.20.21.34.master
[f750454e912b9852bacb131bb7132bf014946151](https://github.com/armory-io/orca-armory/commit/f750454e912b9852bacb131bb7132bf014946151)
[a3d15bd6b01551f42b8b3d06660b03b2308534d7](https://github.com/spinnaker/orca/commit/a3d15bd6b01551f42b8b3d06660b03b2308534d7)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a3d15bd6b01551f42b8b3d06660b03b2308534d7"
},
"details": {
"image": {
"imageId": "sha256:0b6ceb6c37905b95a37c24d5f319258ee4bd054639e3336b4852b18d54b7853d",
"tag": "2023.11.10.20.21.34.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update orca-armory version to 2023.11.10.20.21.34.master

---

stack.yml

* **master**
armory/front50-armory:2023.11.10.21.30.24.master
[46036517a30f7795eb33cf945f5449fdc2362451](https://github.com/armory-io/front50-armory/commit/46036517a30f7795eb33cf945f5449fdc2362451)
[408c34a042760fc135d08bef62d927c8ec5e4502](https://github.com/spinnaker/front50/commit/408c34a042760fc135d08bef62d927c8ec5e4502)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "408c34a042760fc135d08bef62d927c8ec5e4502"
},
"details": {
"image": {
"imageId": "sha256:26bf20d717272d5206527e4b89b55ac3e83273eddfd1983fa8dea4a32233e7e9",
"tag": "2023.11.10.21.30.24.master"
},
"vcs": {
"repo": {
"repoName": …
```

chore(cd): update front50-armory version to 2023.11.10.21.30.24.master

---

stack.yml

* **master**
armory/clouddriver-armory:2023.11.13.19.55.54.master
[50bad7dbe9cfc03db0866de0e3e96c99fc87aa16](https://github.com/armory-io/clouddriver-armory/commit/50bad7dbe9cfc03db0866de0e3e96c99fc87aa16)
[c90e3e3b1b0b617518e1c7786c6e35f4af633f6e](https://github.com/spinnaker/clouddriver/commit/c90e3e3b1b0b617518e1c7786c6e35f4af633f6e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c90e3e3b1b0b617518e1c7786c6e35f4af633f6e"
},
"details": {
"image": {
"imageId": "sha256:019b233eba8bcb9994796bde59c1ee8a18c1fc5652f1c0cd1935960d0c512510",
"tag": "2023.11.13.19.55.54.master"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update clouddriver-armory version to 2023.11.13.19.55.54.master

---

stack.yml

* **master**
armory/deck-armory:2023.11.14.10.41.45.master
[611c9ec066b38a6d95b489d805b17168c4c62a9a](https://github.com/armory-io/deck-armory/commit/611c9ec066b38a6d95b489d805b17168c4c62a9a)
[73dda48caccd969ef562af3f86bc1f17efbdad7f](https://github.com/spinnaker/deck/commit/73dda48caccd969ef562af3f86bc1f17efbdad7f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "73dda48caccd969ef562af3f86bc1f17efbdad7f"
},
"details": {
"image": {
"imageId": "sha256:28069f6e5f605f38dd050ba650659b4455a332d2dd6f63fa9776310583cece66",
"tag": "2023.11.14.10.41.45.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update deck-armory version to 2023.11.14.10.41.45.master

---

stack.yml

* **master**
armory/clouddriver-armory:2023.11.14.12.36.54.master
[2a7f2a800543e8ddd241ae54f42eee75b3377681](https://github.com/armory-io/clouddriver-armory/commit/2a7f2a800543e8ddd241ae54f42eee75b3377681)
[c4d1827f94980d23f5bf7d7bb761ab43f2386717](https://github.com/spinnaker/clouddriver/commit/c4d1827f94980d23f5bf7d7bb761ab43f2386717)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c4d1827f94980d23f5bf7d7bb761ab43f2386717"
},
"details": {
"image": {
"imageId": "sha256:50630404b10396206c16b20824eaf67baaa85e5ccdcbf0f4dcf9e9902aabd037",
"tag": "2023.11.14.12.36.54.master"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update clouddriver-armory version to 2023.11.14.12.36.54.master

---

stack.yml

* **master**
armory/front50-armory:2023.11.20.21.59.08.master
[9486ec7a1a95cb3b3403f566102e62495836b581](https://github.com/armory-io/front50-armory/commit/9486ec7a1a95cb3b3403f566102e62495836b581)
[4b40a26189d6c8d824c207635f0143137cefaeaa](https://github.com/spinnaker/front50/commit/4b40a26189d6c8d824c207635f0143137cefaeaa)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4b40a26189d6c8d824c207635f0143137cefaeaa"
},
"details": {
"image": {
"imageId": "sha256:debf8fdb0b5cb1fe0d30d7fd447a171edd3194bc347dd5cca0090eb5053b0a0c",
"tag": "2023.11.20.21.59.08.master"
},
"vcs": {
"repo": {
"repoName": …
```

chore(cd): update front50-armory version to 2023.11.20.21.59.08.master

---

stack.yml

armory/kayenta-armory:2023.11.21.08.27.32.release-2.30.x
[2981e6d45c0a408b826e9262aec01a1d49cd930c](https://github.com/armory-io/kayenta-armory/commit/2981e6d45c0a408b826e9262aec01a1d49cd930c)
[b5bd22c57e41de48a477eac910058361538cc6b0](https://github.com/spinnaker/kayenta/commit/b5bd22c57e41de48a477eac910058361538cc6b0)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b5bd22c57e41de48a477eac910058361538cc6b0"
},
"details": {
"image": {
"imageId": "sha256:a55c950012f9e6b44e5af972615a6be755a09b0a0f06327dfd87434ab753c1e4",
"tag": "2023.11.21.08.27.32.release-2.30.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update kayenta-armory version to 2023.11.21.08.27.32.release-2.30.x

---

stack.yml

armory/dinghy:2023.11.17.15.02.09.release-2.31.x
[362913af0c5d00eee5ea3b157274cabbef920c43](https://github.com/armory-io/dinghy/commit/362913af0c5d00eee5ea3b157274cabbef920c43)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:cfdb9bb25d8dfa9d64456bb76b62f7b07d60850be3229003ec0e171064a7e6ca",
"tag": "2023.11.17.15.02.09.release-2.31.x"
},
"vcs": {
"repo": {
},
"sha": "362913af0c5d00eee5ea3b157274cabbef920c43"
}
},
},
"details": {
"image": {
"imageId": "sha256:cfdb9bb25d8dfa9d64456bb76b62f7b07d60850be3229003ec0e171064a7e6ca", …
```

chore(cd): update dinghy version to 2023.11.17.15.02.09.release-2.31.x

---

stack.yml

armory/orca-armory:2023.11.21.20.52.52.release-2.31.x
[b1a6fe2247ef18f6239b3ab90b101197c57314c4](https://github.com/armory-io/orca-armory/commit/b1a6fe2247ef18f6239b3ab90b101197c57314c4)
[91de7c3b43df7edb3f7bfd406185b9450a23c3a9](https://github.com/spinnaker/orca/commit/91de7c3b43df7edb3f7bfd406185b9450a23c3a9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "91de7c3b43df7edb3f7bfd406185b9450a23c3a9"
},
"details": {
"image": {
"imageId": "sha256:2acfdccfb07358a91cfab4338bd7c29d08d277975f825966ec7856eb1964b128",
"tag": "2023.11.21.20.52.52.release-2.31.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2023.11.21.20.52.52.release-2.31.x

---

stack.yml

armory/igor-armory:2023.11.22.00.16.21.release-2.31.x
[e94591b4172e7d75ce94db23ebed5deb756af92d](https://github.com/armory-io/igor-armory/commit/e94591b4172e7d75ce94db23ebed5deb756af92d)
[3fb141e655c4e4728f561817dbc54a0306c19094](https://github.com/spinnaker/igor/commit/3fb141e655c4e4728f561817dbc54a0306c19094)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "3fb141e655c4e4728f561817dbc54a0306c19094"
},
"details": {
"image": {
"imageId": "sha256:00b906640788ce2622ef62bd3ccccb7269c3a269a3bcd7190386452f6da2b92b",
"tag": "2023.11.22.00.16.21.release-2.31.x"
},
"vcs": {
"repo": { …
```

chore(cd): update igor-armory version to 2023.11.22.00.16.21.release-2.31.x

---

stack.yml

armory/fiat-armory:2023.11.22.15.42.19.release-2.31.x
[f1079f69f0184aae517680c48283cf9a52c9cf26](https://github.com/armory-io/fiat-armory/commit/f1079f69f0184aae517680c48283cf9a52c9cf26)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:1e692ed07348389f5161b759c6cc3168a9c40175241a67b821934f46fe44d1d5",
"tag": "2023.11.22.15.42.19.release-2.31.x"
},
"vcs": {
"repo": {
},
"sha": "f1079f69f0184aae517680c48283cf9a52c9cf26"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update fiat-armory version to 2023.11.22.15.42.19.release-2.31.x

---

stack.yml

armory/clouddriver-armory:2023.11.22.09.16.59.release-2.31.x
[1db66b13244c3d25b48e767992c5bb7730772271](https://github.com/armory-io/clouddriver-armory/commit/1db66b13244c3d25b48e767992c5bb7730772271)
[66c27aede668dc170016499671731766529ce4aa](https://github.com/spinnaker/clouddriver/commit/66c27aede668dc170016499671731766529ce4aa)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "66c27aede668dc170016499671731766529ce4aa"
},
"details": {
"image": {
"imageId": "sha256:e23d74facc6b9d8e3b6a395bed3bedddd2be0c45849fb037b6937a71d6d5c6ac",
"tag": "2023.11.22.09.16.59.release-2.31.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.11.22.09.16.59.release-2.31.x

---

stack.yml

armory/clouddriver-armory:2023.11.22.09.17.06.release-2.30.x
[864ec55ac074d4a68347cd63f69d1c8dd6eade97](https://github.com/armory-io/clouddriver-armory/commit/864ec55ac074d4a68347cd63f69d1c8dd6eade97)
[ef4bbdc4421ce685a2db4ed956cfd175cb33bb52](https://github.com/spinnaker/clouddriver/commit/ef4bbdc4421ce685a2db4ed956cfd175cb33bb52)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "ef4bbdc4421ce685a2db4ed956cfd175cb33bb52"
},
"details": {
"image": {
"imageId": "sha256:bdef8b7f1f4f4e8d82d8b08a96dd349dce897555d32da07af52f26b0bebb7055",
"tag": "2023.11.22.09.17.06.release-2.30.x"
},
"vcs": …
```

chore(cd): update clouddriver-armory version to 2023.11.22.09.17.06.release-2.30.x

---

stack.yml

armory/deck-armory:2023.11.23.10.42.14.release-2.28.x
[cda38e832ab5bdc02231601e85528613a8d48cf1](https://github.com/armory-io/deck-armory/commit/cda38e832ab5bdc02231601e85528613a8d48cf1)
[0d188f1db9bb3ffff1211d781fc262a7f0e6e5cf](https://github.com/spinnaker/deck/commit/0d188f1db9bb3ffff1211d781fc262a7f0e6e5cf)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0d188f1db9bb3ffff1211d781fc262a7f0e6e5cf"
},
"details": {
"image": {
"imageId": "sha256:c3e993f635bf3041ea0d8b976a1494d3a945d5759b35625bc2119e64d65dafd8",
"tag": "2023.11.23.10.42.14.release-2.28.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2023.11.23.10.42.14.release-2.28.x

---

stack.yml

armory/kayenta-armory:2023.11.23.14.35.34.release-2.31.x
[4a528f19b704cc0f25295daef56d27b78a84a25e](https://github.com/armory-io/kayenta-armory/commit/4a528f19b704cc0f25295daef56d27b78a84a25e)
[6c73ba3c0b2892d7cb3f6777ccfc2db92295c463](https://github.com/spinnaker/kayenta/commit/6c73ba3c0b2892d7cb3f6777ccfc2db92295c463)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "6c73ba3c0b2892d7cb3f6777ccfc2db92295c463"
},
"details": {
"image": {
"imageId": "sha256:1727486d8336141ea45481eb2f1c77daf611a547f51a4315d6bb8c78e03ff5cb",
"tag": "2023.11.23.14.35.34.release-2.31.x"
},
"vcs": {
"repo": {
"orgName": …
```

chore(cd): update kayenta-armory version to 2023.11.23.14.35.34.release-2.31.x

---

stack.yml

* **master**
armory/kayenta-armory:2023.11.23.15.08.44.master
[1402f8522a27c5d271ea42b3e38081c07dae79b3](https://github.com/armory-io/kayenta-armory/commit/1402f8522a27c5d271ea42b3e38081c07dae79b3)
[d1f7ee2e3555a58827ea7ba1b9ba3d8b5ccce830](https://github.com/spinnaker/kayenta/commit/d1f7ee2e3555a58827ea7ba1b9ba3d8b5ccce830)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d1f7ee2e3555a58827ea7ba1b9ba3d8b5ccce830"
},
"details": {
"image": {
"imageId": "sha256:f12178a1188558486be2bc83ee88f1f2640c9e8b52c9987734faf8c5930a4166",
"tag": "2023.11.23.15.08.44.master"
},
"vcs": {
"repo": {
"repoName": …
```

chore(cd): update kayenta-armory version to 2023.11.23.15.08.44.master

---

stack.yml

* **master**
armory/echo-armory:2023.11.21.20.19.33.master
[fcb4ee24520871bd3b6c858aeb89602bf45fa706](https://github.com/armory-io/echo-armory/commit/fcb4ee24520871bd3b6c858aeb89602bf45fa706)
[9b00515c1cf648622f1783817936a9108fe0f971](https://github.com/spinnaker/echo/commit/9b00515c1cf648622f1783817936a9108fe0f971)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9b00515c1cf648622f1783817936a9108fe0f971"
},
"details": {
"image": {
"imageId": "sha256:fde5f503ad350488411fbb3ebe5556e4693e9b54a460e731a6edef692d2ba1d8",
"tag": "2023.11.21.20.19.33.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update echo-armory version to 2023.11.21.20.19.33.master

---

stack.yml

* **master**
armory/rosco-armory:2023.11.14.21.43.30.master
[26eb20dede2b305f70c47c457b2b6a12bda47105](https://github.com/armory-io/rosco-armory/commit/26eb20dede2b305f70c47c457b2b6a12bda47105)
[ea551b9e6340028dd21b816d71a8a7d972269793](https://github.com/spinnaker/rosco/commit/ea551b9e6340028dd21b816d71a8a7d972269793)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "ea551b9e6340028dd21b816d71a8a7d972269793"
},
"details": {
"image": {
"imageId": "sha256:9668d711925c5132150805cad631c066d3cc6b9dd3b34ac909fd5bd738d64956",
"tag": "2023.11.14.21.43.30.master"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2023.11.14.21.43.30.master

---

stack.yml

* **master**
armory/gate-armory:2023.11.21.20.21.59.master
[691dd7e67f03fd33d4426b028026e005e295846e](https://github.com/armory-io/gate-armory/commit/691dd7e67f03fd33d4426b028026e005e295846e)
[23806cc6cddf6213d107b19e5ebfad12ceb751c5](https://github.com/spinnaker/gate/commit/23806cc6cddf6213d107b19e5ebfad12ceb751c5)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "23806cc6cddf6213d107b19e5ebfad12ceb751c5"
},
"details": {
"image": {
"imageId": "sha256:615ccb1e8580847236c86ba3e046674e2707b66067e7e1903540301a8031497d",
"tag": "2023.11.21.20.21.59.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update gate-armory version to 2023.11.21.20.21.59.master

---

stack.yml

* **master**
armory/deck-armory:2023.11.16.22.12.02.master
[fca0736eab714f578c10bd01aa90117a7914c70c](https://github.com/armory-io/deck-armory/commit/fca0736eab714f578c10bd01aa90117a7914c70c)
[73dda48caccd969ef562af3f86bc1f17efbdad7f](https://github.com/spinnaker/deck/commit/73dda48caccd969ef562af3f86bc1f17efbdad7f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "73dda48caccd969ef562af3f86bc1f17efbdad7f"
},
"details": {
"image": {
"imageId": "sha256:039009c3ed78b3b218d2942e5638da6da8cfca8747df2a025bccf006a5ad133e",
"tag": "2023.11.16.22.12.02.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update deck-armory version to 2023.11.16.22.12.02.master

---

stack.yml

* **master**
armory/fiat-armory:2023.11.22.15.34.57.master
[49206f6309cf6b8227835996a9c22909adf571e8](https://github.com/armory-io/fiat-armory/commit/49206f6309cf6b8227835996a9c22909adf571e8)
[3947a1bcc9890046bd82483a2ce58986b6d4906f](https://github.com/spinnaker/fiat/commit/3947a1bcc9890046bd82483a2ce58986b6d4906f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "3947a1bcc9890046bd82483a2ce58986b6d4906f"
},
"details": {
"image": {
"imageId": "sha256:39e12a297541555e2e484f9fadc17d09c5c8912fff83cf5c3102c0c01e7fe346",
"tag": "2023.11.22.15.34.57.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update fiat-armory version to 2023.11.22.15.34.57.master

---

stack.yml

* **master**
armory/front50-armory:2023.11.22.01.15.58.master
[2f40cdb6f8c97d7f9569f73b59d807cfa3413708](https://github.com/armory-io/front50-armory/commit/2f40cdb6f8c97d7f9569f73b59d807cfa3413708)
[04997e25d83d5d1f8901e4b6e35f65c272f9d99d](https://github.com/spinnaker/front50/commit/04997e25d83d5d1f8901e4b6e35f65c272f9d99d)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "04997e25d83d5d1f8901e4b6e35f65c272f9d99d"
},
"details": {
"image": {
"imageId": "sha256:436ba638e027bad208bd081541ebedc73a0d47cf58b6355f6f8f663a8b664c92",
"tag": "2023.11.22.01.15.58.master"
},
"vcs": {
"repo": {
"repoName": …
```

chore(cd): update front50-armory version to 2023.11.22.01.15.58.master

---

stack.yml

* **master**
armory/igor-armory:2023.11.22.00.35.19.master
[03192d56dc648d56f2cd118b37f5966cc2c0de40](https://github.com/armory-io/igor-armory/commit/03192d56dc648d56f2cd118b37f5966cc2c0de40)
[25435d8ab5d547a3c3d039767720e44c03dc62d9](https://github.com/spinnaker/igor/commit/25435d8ab5d547a3c3d039767720e44c03dc62d9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "25435d8ab5d547a3c3d039767720e44c03dc62d9"
},
"details": {
"image": {
"imageId": "sha256:5113a1e58015ef20b76f75387749e987d3bda4d7a385a2f5be457ce7012c4b81",
"tag": "2023.11.22.00.35.19.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update igor-armory version to 2023.11.22.00.35.19.master

---

stack.yml

armory/kayenta-armory:2023.11.23.15.06.30.release-2.27.x
[ee4af9c5f5ecbb76504ebc1aafca1c2485db2f61](https://github.com/armory-io/kayenta-armory/commit/ee4af9c5f5ecbb76504ebc1aafca1c2485db2f61)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:42a785cc13992feb2316d68a50779a11022f5e39f4630b12846671069574259f",
"tag": "2023.11.23.15.06.30.release-2.27.x"
},
"vcs": {
"repo": {
},
"sha": "ee4af9c5f5ecbb76504ebc1aafca1c2485db2f61"
}
},
},
"details": { …
```

chore(cd): update kayenta-armory version to 2023.11.23.15.06.30.release-2.27.x

---

stack.yml

* **master**
armory/fiat-armory:2023.11.28.17.46.23.master
[2df756449f3c3e6e3b91c013898fe052502a1dff](https://github.com/armory-io/fiat-armory/commit/2df756449f3c3e6e3b91c013898fe052502a1dff)
[3947a1bcc9890046bd82483a2ce58986b6d4906f](https://github.com/spinnaker/fiat/commit/3947a1bcc9890046bd82483a2ce58986b6d4906f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "3947a1bcc9890046bd82483a2ce58986b6d4906f"
},
"details": {
"image": {
"imageId": "sha256:25a834054db83fb3877b20ca3e9c00497b952a4d881e44dccae399276305a279",
"tag": "2023.11.28.17.46.23.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update fiat-armory version to 2023.11.28.17.46.23.master

---

stack.yml

* **master**
armory/front50-armory:2023.11.28.17.48.14.master
[ec5d997d6f42217068823d987858c9946334dce7](https://github.com/armory-io/front50-armory/commit/ec5d997d6f42217068823d987858c9946334dce7)
[04997e25d83d5d1f8901e4b6e35f65c272f9d99d](https://github.com/spinnaker/front50/commit/04997e25d83d5d1f8901e4b6e35f65c272f9d99d)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "04997e25d83d5d1f8901e4b6e35f65c272f9d99d"
},
"details": {
"image": {
"imageId": "sha256:3214212306274689993fc776715e7ea657835b0325102b1dabc812ccf6de2dd5",
"tag": "2023.11.28.17.48.14.master"
},
"vcs": {
"repo": {
"repoName": …
```

chore(cd): update front50-armory version to 2023.11.28.17.48.14.master

---

stack.yml

armory/orca-armory:2024.01.23.22.42.42.release-2.32.x
[26f1b78e328c1051db39f535f8a6f13de7ca7f68](https://github.com/armory-io/orca-armory/commit/26f1b78e328c1051db39f535f8a6f13de7ca7f68)
[83c37a309daa24dd1574470ed440c3699df762ef](https://github.com/spinnaker/orca/commit/83c37a309daa24dd1574470ed440c3699df762ef)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "83c37a309daa24dd1574470ed440c3699df762ef"
},
"details": {
"image": {
"imageId": "sha256:3ef7b14c969910b970b776ea1b60c1e3f6ca39bc2be6ce14f83a3e51a8da5d6f",
"tag": "2024.01.23.22.42.42.release-2.32.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2024.01.23.22.42.42.release-2.32.x

---

stack.yml

armory/dinghy:2024.01.23.13.24.09.release-2.32.x
[3a713c33889aa36301dd4fde4061c3d5d3bfa237](https://github.com/armory-io/dinghy/commit/3a713c33889aa36301dd4fde4061c3d5d3bfa237)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:a1d76dccb12fe54ff554a7e867ec0279595ab98b65baf7a1fed2df61fec59558",
"tag": "2024.01.23.13.24.09.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "3a713c33889aa36301dd4fde4061c3d5d3bfa237"
}
},
},
"details": {
"image": {
"imageId": "sha256:a1d76dccb12fe54ff554a7e867ec0279595ab98b65baf7a1fed2df61fec59558", …
```

chore(cd): update dinghy version to 2024.01.23.13.24.09.release-2.32.x

---

stack.yml

armory/front50-armory:2024.01.23.19.45.33.release-2.32.x
[c68b97b642a6d9168d361d74dad373e565850f5d](https://github.com/armory-io/front50-armory/commit/c68b97b642a6d9168d361d74dad373e565850f5d)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:24b400878d930d75ab9ee34cec7b5594aaf44687b1f269162d19014774bf8f9f",
"tag": "2024.01.23.19.45.33.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "c68b97b642a6d9168d361d74dad373e565850f5d"
}
},
},
"details": { …
```

chore(cd): update front50-armory version to 2024.01.23.19.45.33.release-2.32.x

---

stack.yml

armory/deck-armory:2024.01.23.17.56.29.release-2.32.x
[59070649f442e6806a5ef4e7ad5f91e8b2588226](https://github.com/armory-io/deck-armory/commit/59070649f442e6806a5ef4e7ad5f91e8b2588226)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:af92c5d670a5a77924967cd1c029111e968ebceef2d838ba7d57fa37b0ea9c46",
"tag": "2024.01.23.17.56.29.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "59070649f442e6806a5ef4e7ad5f91e8b2588226"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update deck-armory version to 2024.01.23.17.56.29.release-2.32.x

---

stack.yml

armory/rosco-armory:2024.01.24.11.10.07.release-2.32.x
[776c66208dd16ad41defad3d0b6d8bcc3dbba24d](https://github.com/armory-io/rosco-armory/commit/776c66208dd16ad41defad3d0b6d8bcc3dbba24d)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:d224257047045226357b336f9e49190f4fcd1442b153e1923565a3f32cc1b98e",
"tag": "2024.01.24.11.10.07.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "776c66208dd16ad41defad3d0b6d8bcc3dbba24d"
}
},
},
"details": {
"image": { …
```

chore(cd): update rosco-armory version to 2024.01.24.11.10.07.release-2.32.x

---

stack.yml

armory/kayenta-armory:2024.01.24.16.15.06.release-2.32.x
[af68e872b806eb49f4f0071187f998f18f04c3c2](https://github.com/armory-io/kayenta-armory/commit/af68e872b806eb49f4f0071187f998f18f04c3c2)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:2d266b025dfd5501af98a8d44474ff7588929a99e331fe10ab583a86f3e3d345",
"tag": "2024.01.24.16.15.06.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "af68e872b806eb49f4f0071187f998f18f04c3c2"
}
},
},
"details": { …
```

chore(cd): update kayenta-armory version to 2024.01.24.16.15.06.release-2.32.x

---

stack.yml

armory/fiat-armory:2024.01.24.16.14.16.release-2.32.x
[2c0d010ce00d9519b316e15af734a05835df1048](https://github.com/armory-io/fiat-armory/commit/2c0d010ce00d9519b316e15af734a05835df1048)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:622a66a43b630c9de3ec82243d750fcb2765ac189b5becb43c8f751b2b78986d",
"tag": "2024.01.24.16.14.16.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "2c0d010ce00d9519b316e15af734a05835df1048"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update fiat-armory version to 2024.01.24.16.14.16.release-2.32.x

---

stack.yml

armory/gate-armory:2024.01.23.19.44.45.release-2.32.x
[e2feabb1bc987eec8b2afb818d93aa3b7fe982c0](https://github.com/armory-io/gate-armory/commit/e2feabb1bc987eec8b2afb818d93aa3b7fe982c0)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:8507e58f74ee679835242ebba000d5faa6a8d1373160b2366b909537839d5131",
"tag": "2024.01.23.19.44.45.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "e2feabb1bc987eec8b2afb818d93aa3b7fe982c0"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update gate-armory version to 2024.01.23.19.44.45.release-2.32.x

---

stack.yml

armory/deck-armory:2024.01.26.12.34.13.release-2.32.x
[564c0a536cd3df788801b97fb167e16224e2793c](https://github.com/armory-io/deck-armory/commit/564c0a536cd3df788801b97fb167e16224e2793c)
[181384690ff5320669f2ae548cd38bf59cc4b0b3](https://github.com/spinnaker/deck/commit/181384690ff5320669f2ae548cd38bf59cc4b0b3)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "181384690ff5320669f2ae548cd38bf59cc4b0b3"
},
"details": {
"image": {
"imageId": "sha256:47c05cf7f5135363d689c556761baf7b97d3e06cabcb5f59e36e782296a3f584",
"tag": "2024.01.26.12.34.13.release-2.32.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2024.01.26.12.34.13.release-2.32.x

---

stack.yml

* **master**
armory/deck-armory:2024.01.26.20.33.14.master
[51f4c7c31101909f6cf3be265ecd3ee97cd6d9c8](https://github.com/armory-io/deck-armory/commit/51f4c7c31101909f6cf3be265ecd3ee97cd6d9c8)
[32dfea87b69790d1093dac495f98a33fe73c5067](https://github.com/spinnaker/deck/commit/32dfea87b69790d1093dac495f98a33fe73c5067)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "32dfea87b69790d1093dac495f98a33fe73c5067"
},
"details": {
"image": {
"imageId": "sha256:acec1da523eefe57305cf1701b952185434ea83d9a3b6ae9f39b32405970897a",
"tag": "2024.01.26.20.33.14.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update deck-armory version to 2024.01.26.20.33.14.master

---

stack.yml

* **master**
armory/front50-armory:2024.01.23.19.17.19.master
[ca25a8b09287a0eae39e88434fca392b467f67db](https://github.com/armory-io/front50-armory/commit/ca25a8b09287a0eae39e88434fca392b467f67db)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:8e9a2a39872326f028fa575be44041c89ec41f64aebe8fcff3b3cc814e53d913",
"tag": "2024.01.23.19.17.19.master"
},
"vcs": {
"repo": {
},
"sha": "ca25a8b09287a0eae39e88434fca392b467f67db"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update front50-armory version to 2024.01.23.19.17.19.master

---

stack.yml

* **master**
armory/gate-armory:2024.01.23.19.16.38.master
[106618970f2d654c4fb8e279c24d6c20dc5b4dba](https://github.com/armory-io/gate-armory/commit/106618970f2d654c4fb8e279c24d6c20dc5b4dba)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:87c6b85c2003c1a0f777a0efe5b3cb8891d276f84b9014f9746e7bbe0c515b82",
"tag": "2024.01.23.19.16.38.master"
},
"vcs": {
"repo": {
},
"sha": "106618970f2d654c4fb8e279c24d6c20dc5b4dba"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update gate-armory version to 2024.01.23.19.16.38.master

---

stack.yml

* **master**
armory/echo-armory:2024.01.23.19.05.54.master
[150277f85195b58bdcc5e806fecc00ef662c9f2c](https://github.com/armory-io/echo-armory/commit/150277f85195b58bdcc5e806fecc00ef662c9f2c)
[9b00515c1cf648622f1783817936a9108fe0f971](https://github.com/spinnaker/echo/commit/9b00515c1cf648622f1783817936a9108fe0f971)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9b00515c1cf648622f1783817936a9108fe0f971"
},
"details": {
"image": {
"imageId": "sha256:e8b530d71b856183957df7b981bca2a36197cf3c15d2ec296f576fafe050e98e",
"tag": "2024.01.23.19.05.54.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update echo-armory version to 2024.01.23.19.05.54.master

---

stack.yml

armory/deck-armory:2024.01.26.22.07.49.release-2.32.x
[a79682affbf676b47dc20d81ab7de04562686119](https://github.com/armory-io/deck-armory/commit/a79682affbf676b47dc20d81ab7de04562686119)
[181384690ff5320669f2ae548cd38bf59cc4b0b3](https://github.com/spinnaker/deck/commit/181384690ff5320669f2ae548cd38bf59cc4b0b3)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "181384690ff5320669f2ae548cd38bf59cc4b0b3"
},
"details": {
"image": {
"imageId": "sha256:1e88aeb4615b0c5c66e8bdc75dcf231c30b8de0e9513de7b4ad2b3b7611dbbff",
"tag": "2024.01.26.22.07.49.release-2.32.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2024.01.26.22.07.49.release-2.32.x

---

stack.yml

* **master**
armory/gate-armory:2024.02.01.15.19.56.master
[c843322840ae333fe48aa45e624d2eaa5fdde7b1](https://github.com/armory-io/gate-armory/commit/c843322840ae333fe48aa45e624d2eaa5fdde7b1)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:362f846d4c336d7b8f4e1236a26545e2af04c64a30a255c39e065becf9ec8bf7",
"tag": "2024.02.01.15.19.56.master"
},
"vcs": {
"repo": {
},
"sha": "c843322840ae333fe48aa45e624d2eaa5fdde7b1"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update gate-armory version to 2024.02.01.15.19.56.master

---

stack.yml

armory/gate-armory:2024.02.01.15.31.31.release-2.31.x
[f0d8fde54a472050d32c2f6aee44fdd110e7382d](https://github.com/armory-io/gate-armory/commit/f0d8fde54a472050d32c2f6aee44fdd110e7382d)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:b9fbbb1f2c595fb30e6f112137ea6e8a1652a961db0bf04bbe6cec413f258762",
"tag": "2024.02.01.15.31.31.release-2.31.x"
},
"vcs": {
"repo": {
},
"sha": "f0d8fde54a472050d32c2f6aee44fdd110e7382d"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update gate-armory version to 2024.02.01.15.31.31.release-2.31.x

---

stack.yml

* **master**
armory/front50-armory:2024.02.01.16.35.52.master
[cffc024969376e39e3c86595e7d4f00458adfb58](https://github.com/armory-io/front50-armory/commit/cffc024969376e39e3c86595e7d4f00458adfb58)
[7f797b7ca6d50cf025c5bf8ebd07f47f07560f01](https://github.com/spinnaker/front50/commit/7f797b7ca6d50cf025c5bf8ebd07f47f07560f01)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7f797b7ca6d50cf025c5bf8ebd07f47f07560f01"
},
"details": {
"image": {
"imageId": "sha256:279f3fecf03a2855e26b062e09ea1e6da6e8445f4b2d3310bdc6948e555b11d0",
"tag": "2024.02.01.16.35.52.master"
},
"vcs": {
"repo": {
"repoName": …
```

chore(cd): update front50-armory version to 2024.02.01.16.35.52.master

---

stack.yml

armory/rosco-armory:2024.01.24.10.13.05.release-2.31.x
[a8ff067ff32d892f9bf29102d4ac663eeed1b4a0](https://github.com/armory-io/rosco-armory/commit/a8ff067ff32d892f9bf29102d4ac663eeed1b4a0)
[6a866e7c74ce241f5c849978d0a2bafc739cf882](https://github.com/spinnaker/rosco/commit/6a866e7c74ce241f5c849978d0a2bafc739cf882)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "6a866e7c74ce241f5c849978d0a2bafc739cf882"
},
"details": {
"image": {
"imageId": "sha256:eaa7ea882a380e0e95c75fe13056a640a0c9a0f00b0d2f29fd0272572faefda6",
"tag": "2024.01.24.10.13.05.release-2.31.x"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2024.01.24.10.13.05.release-2.31.x

---

stack.yml

* **master**
armory/rosco-armory:2024.01.24.10.00.19.master
[6b4119df0c8a7be5859d63a19d76ea4605f92781](https://github.com/armory-io/rosco-armory/commit/6b4119df0c8a7be5859d63a19d76ea4605f92781)
[ea551b9e6340028dd21b816d71a8a7d972269793](https://github.com/spinnaker/rosco/commit/ea551b9e6340028dd21b816d71a8a7d972269793)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "ea551b9e6340028dd21b816d71a8a7d972269793"
},
"details": {
"image": {
"imageId": "sha256:43af5fbe3697260f195ef28db87591f07139c33df5fa04d9055d60b65a2533e4",
"tag": "2024.01.24.10.00.19.master"
},
"vcs": {
"repo": { …
```

chore(cd): update rosco-armory version to 2024.01.24.10.00.19.master

---

stack.yml

armory/orca-armory:2024.01.31.13.59.36.release-2.32.x
[9b0cbcc0d618fb135d7e9551db5b493ad3def9a3](https://github.com/armory-io/orca-armory/commit/9b0cbcc0d618fb135d7e9551db5b493ad3def9a3)
[83c37a309daa24dd1574470ed440c3699df762ef](https://github.com/spinnaker/orca/commit/83c37a309daa24dd1574470ed440c3699df762ef)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "83c37a309daa24dd1574470ed440c3699df762ef"
},
"details": {
"image": {
"imageId": "sha256:fd608978e4c8d6303595c4c702f3af83ee579c4bf18f8271f7ad0fc695a40e28",
"tag": "2024.01.31.13.59.36.release-2.32.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2024.01.31.13.59.36.release-2.32.x

---

stack.yml

armory/gate-armory:2024.02.01.16.44.24.release-2.32.x
[1f96d4f238c63798cf34e818760ffb25b3a4b009](https://github.com/armory-io/gate-armory/commit/1f96d4f238c63798cf34e818760ffb25b3a4b009)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:43c7af646dafc57f6ecaabdfe4750726f0d8909e581fd607a9af5b7aebeb533d",
"tag": "2024.02.01.16.44.24.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "1f96d4f238c63798cf34e818760ffb25b3a4b009"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update gate-armory version to 2024.02.01.16.44.24.release-2.32.x

---

stack.yml

* **master**
armory/igor-armory:2024.02.02.13.02.07.master
[bd87885fdc4257a76503fcd2c4a35f9fa1dc4438](https://github.com/armory-io/igor-armory/commit/bd87885fdc4257a76503fcd2c4a35f9fa1dc4438)
[957000fe4ecdf1cb963aae5432ce2bc0ebe702b9](https://github.com/spinnaker/igor/commit/957000fe4ecdf1cb963aae5432ce2bc0ebe702b9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "957000fe4ecdf1cb963aae5432ce2bc0ebe702b9"
},
"details": {
"image": {
"imageId": "sha256:96dafed488305c76de7d0b50a0b90be3ee65fcdeb326e565677f94b7e829e781",
"tag": "2024.02.02.13.02.07.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update igor-armory version to 2024.02.02.13.02.07.master

---

stack.yml

armory/orca-armory:2024.02.02.13.11.39.release-2.31.x
[60004db47f9d73ed7e8972f75783d64f2885df35](https://github.com/armory-io/orca-armory/commit/60004db47f9d73ed7e8972f75783d64f2885df35)
[91de7c3b43df7edb3f7bfd406185b9450a23c3a9](https://github.com/spinnaker/orca/commit/91de7c3b43df7edb3f7bfd406185b9450a23c3a9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "91de7c3b43df7edb3f7bfd406185b9450a23c3a9"
},
"details": {
"image": {
"imageId": "sha256:40cf8c516622abd41c4db152be7bb6367b52c5c05a5c80c84a555ec1ae5b3f59",
"tag": "2024.02.02.13.11.39.release-2.31.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2024.02.02.13.11.39.release-2.31.x

---

stack.yml

armory/kayenta-armory:2023.12.02.02.57.12.release-2.31.x
[e5c68b27dabe7675140805485b7bd60758a858f3](https://github.com/armory-io/kayenta-armory/commit/e5c68b27dabe7675140805485b7bd60758a858f3)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:2769833e1bfa5e0cb6814a409aec8d64c0ad1d45deaf20671944b3d762600361",
"tag": "2023.12.02.02.57.12.release-2.31.x"
},
"vcs": {
"repo": {
},
"sha": "e5c68b27dabe7675140805485b7bd60758a858f3"
}
},
},
"details": { …
```

chore(cd): update kayenta-armory version to 2023.12.02.02.57.12.release-2.31.x

---

stack.yml

* **master**
armory/kayenta-armory:2024.02.01.16.58.52.master
[6343b50b0ae0db780ea080d809bbe9d142a22152](https://github.com/armory-io/kayenta-armory/commit/6343b50b0ae0db780ea080d809bbe9d142a22152)
[f0e67c36db734bf6a622356a0719bec00e0e715d](https://github.com/spinnaker/kayenta/commit/f0e67c36db734bf6a622356a0719bec00e0e715d)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f0e67c36db734bf6a622356a0719bec00e0e715d"
},
"details": {
"image": {
"imageId": "sha256:446911a048affbf235aa325fc934af1691290f21873a8259dc458bdde0276948",
"tag": "2024.02.01.16.58.52.master"
},
"vcs": {
"repo": {
"repoName": …
```

chore(cd): update kayenta-armory version to 2024.02.01.16.58.52.master

---

stack.yml

armory/igor-armory:2024.02.02.13.21.05.release-2.31.x
[15c26af7729f7695edb835af225c4b5811ddd8c6](https://github.com/armory-io/igor-armory/commit/15c26af7729f7695edb835af225c4b5811ddd8c6)
[683246643f8389f35704ed03a8a69559b531e714](https://github.com/spinnaker/igor/commit/683246643f8389f35704ed03a8a69559b531e714)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "683246643f8389f35704ed03a8a69559b531e714"
},
"details": {
"image": {
"imageId": "sha256:ebf9c00de2137a74fe7088331ed238db9ebe040e33e3d7f0896a57136a405798",
"tag": "2024.02.02.13.21.05.release-2.31.x"
},
"vcs": {
"repo": { …
```

chore(cd): update igor-armory version to 2024.02.02.13.21.05.release-2.31.x

---

stack.yml

* **master**
armory/fiat-armory:2024.02.02.19.14.51.master
[53c6a03f2f10838bc8d4ddb04f4a34731734f5cc](https://github.com/armory-io/fiat-armory/commit/53c6a03f2f10838bc8d4ddb04f4a34731734f5cc)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:40341be7ca5c330ed7d4b199da38b3124e5d190630ef9e59605033057185b75d",
"tag": "2024.02.02.19.14.51.master"
},
"vcs": {
"repo": {
},
"sha": "53c6a03f2f10838bc8d4ddb04f4a34731734f5cc"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update fiat-armory version to 2024.02.02.19.14.51.master

---

stack.yml

* **master**
armory/deck-armory:2024.02.01.18.12.59.master
[cc9d6af174691523c177477dee58ed87bbc67ed1](https://github.com/armory-io/deck-armory/commit/cc9d6af174691523c177477dee58ed87bbc67ed1)
[59adc51d946eb925283410ce02db33d16bbab3e9](https://github.com/spinnaker/deck/commit/59adc51d946eb925283410ce02db33d16bbab3e9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "59adc51d946eb925283410ce02db33d16bbab3e9"
},
"details": {
"image": {
"imageId": "sha256:0d010c69b63169983d21ed9af7a83528e78100a32136c7e557ae677d472c1002",
"tag": "2024.02.01.18.12.59.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update deck-armory version to 2024.02.01.18.12.59.master

---

stack.yml

* **master**
armory/orca-armory:2024.02.01.18.22.01.master
[eb9f90804f4a23268792421b1770b0ee0a9b2f0c](https://github.com/armory-io/orca-armory/commit/eb9f90804f4a23268792421b1770b0ee0a9b2f0c)
[8c563f52e118153997ac596679d2776414c929bf](https://github.com/spinnaker/orca/commit/8c563f52e118153997ac596679d2776414c929bf)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "8c563f52e118153997ac596679d2776414c929bf"
},
"details": {
"image": {
"imageId": "sha256:68d999c3d43edcb4c8f376507b405ee21c5c298b1307fccd8e001c0559e6fbe7",
"tag": "2024.02.01.18.22.01.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update orca-armory version to 2024.02.01.18.22.01.master

---

stack.yml

* **master**
armory/front50-armory:2024.02.02.19.16.46.master
[11ec99124052309173b9c9f2e458b0270aac1735](https://github.com/armory-io/front50-armory/commit/11ec99124052309173b9c9f2e458b0270aac1735)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:1a9a343728462659827c988c7d08ce67c7f6171fd5f18cc0ad1a226b162f9826",
"tag": "2024.02.02.19.16.46.master"
},
"vcs": {
"repo": {
},
"sha": "11ec99124052309173b9c9f2e458b0270aac1735"
}
},
},
"details": {
"image": {
"imageId": …
```

chore(cd): update front50-armory version to 2024.02.02.19.16.46.master

---

stack.yml

* **master**
armory/front50-armory:2024.02.05.04.31.48.master
[c07051d0cf88a6711d7b502be645e82aaa675de6](https://github.com/armory-io/front50-armory/commit/c07051d0cf88a6711d7b502be645e82aaa675de6)
[1d4a51b9dc13aab4bb4db3ff9480907f851ac4ba](https://github.com/spinnaker/front50/commit/1d4a51b9dc13aab4bb4db3ff9480907f851ac4ba)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1d4a51b9dc13aab4bb4db3ff9480907f851ac4ba"
},
"details": {
"image": {
"imageId": "sha256:8e53a51745b0dddc0b8f67f82fb55b899cc8c5516da3761a5d29bcc36e997505",
"tag": "2024.02.05.04.31.48.master"
},
"vcs": {
"repo": {
"repoName": …
```

chore(cd): update front50-armory version to 2024.02.05.04.31.48.master

---

stack.yml

armory/front50-armory:2024.01.23.15.43.12.release-2.31.x
[592471c8b5b45d0f5012d218f839921b91d6ae5c](https://github.com/armory-io/front50-armory/commit/592471c8b5b45d0f5012d218f839921b91d6ae5c)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:1753e3011a2be0a92669cb578242a874e7b3c96815ee74d1ec66e805cbdd5e7d",
"tag": "2024.01.23.15.43.12.release-2.31.x"
},
"vcs": {
"repo": {
},
"sha": "592471c8b5b45d0f5012d218f839921b91d6ae5c"
}
},
},
"details": { …
```

chore(cd): update front50-armory version to 2024.01.23.15.43.12.release-2.31.x

---

stack.yml

armory/deck-armory:2024.02.06.15.35.43.release-2.32.x
[e7c8c0982afe9a49ab6c3d230f3aaa38e874eb30](https://github.com/armory-io/deck-armory/commit/e7c8c0982afe9a49ab6c3d230f3aaa38e874eb30)
[181384690ff5320669f2ae548cd38bf59cc4b0b3](https://github.com/spinnaker/deck/commit/181384690ff5320669f2ae548cd38bf59cc4b0b3)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "181384690ff5320669f2ae548cd38bf59cc4b0b3"
},
"details": {
"image": {
"imageId": "sha256:a96f2e483e8ef11759d8a0e41f839efb3e5672cc7437ca6d21b0602e3f8791bc",
"tag": "2024.02.06.15.35.43.release-2.32.x"
},
"vcs": {
"repo": { …
```

chore(cd): update deck-armory version to 2024.02.06.15.35.43.release-2.32.x

---

stack.yml

armory/dinghy:2024.02.07.12.49.11.release-2.32.x
[a257cbcab26643a18cdfab24bff3a5e1ef651a27](https://github.com/armory-io/dinghy/commit/a257cbcab26643a18cdfab24bff3a5e1ef651a27)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:cc67ca2431d59307ae626444254c88c63baef1187af1648f89b2641af9681a13",
"tag": "2024.02.07.12.49.11.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "a257cbcab26643a18cdfab24bff3a5e1ef651a27"
}
},
},
"details": {
"image": {
"imageId": "sha256:cc67ca2431d59307ae626444254c88c63baef1187af1648f89b2641af9681a13", …
```

chore(cd): update dinghy version to 2024.02.07.12.49.11.release-2.32.x

---

stack.yml

armory/orca-armory:2024.02.08.15.28.19.release-2.32.x
[a575354cf39559e9784baad086e26f55fb2cb6ac](https://github.com/armory-io/orca-armory/commit/a575354cf39559e9784baad086e26f55fb2cb6ac)
[83c37a309daa24dd1574470ed440c3699df762ef](https://github.com/spinnaker/orca/commit/83c37a309daa24dd1574470ed440c3699df762ef)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "83c37a309daa24dd1574470ed440c3699df762ef"
},
"details": {
"image": {
"imageId": "sha256:2889ee2e882185ebad0d8bbd7cdf54b1abc30461467bf76508ca692c753accc8",
"tag": "2024.02.08.15.28.19.release-2.32.x"
},
"vcs": {
"repo": { …
```

chore(cd): update orca-armory version to 2024.02.08.15.28.19.release-2.32.x

---

stack.yml

* **master**
armory/kayenta-armory:2024.02.06.18.43.35.master
[2097caf716e5851d1af4a2e1a06c264cb8388970](https://github.com/armory-io/kayenta-armory/commit/2097caf716e5851d1af4a2e1a06c264cb8388970)
[c933f7f9f2c786b2216099c4ae50b64c62177dc0](https://github.com/spinnaker/kayenta/commit/c933f7f9f2c786b2216099c4ae50b64c62177dc0)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c933f7f9f2c786b2216099c4ae50b64c62177dc0"
},
"details": {
"image": {
"imageId": "sha256:7c69772d478891846b00aad51820137851fdd8432b1a14b69d9a3da71e827fad",
"tag": "2024.02.06.18.43.35.master"
},
"vcs": {
"repo": {
"repoName": …
```

chore(cd): update kayenta-armory version to 2024.02.06.18.43.35.master

---

stack.yml

* **master**
armory/orca-armory:2024.02.07.21.42.40.master
[d12fe45e1429bfcead32d28c7ec430a98c8d8749](https://github.com/armory-io/orca-armory/commit/d12fe45e1429bfcead32d28c7ec430a98c8d8749)
[39576af7795e6d71ffbb14302b15f2be97409da3](https://github.com/spinnaker/orca/commit/39576af7795e6d71ffbb14302b15f2be97409da3)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "39576af7795e6d71ffbb14302b15f2be97409da3"
},
"details": {
"image": {
"imageId": "sha256:c062a93bd833851c03224923fb0fa2c723b39c6a7cea60e41b470757ece832c2",
"tag": "2024.02.07.21.42.40.master"
},
"vcs": {
"repo": {
"type": …
```

chore(cd): update orca-armory version to 2024.02.07.21.42.40.master
