armory-io/armory-stack

stack.yml
* **master**
armory/rosco-armory:2024.02.07.19.39.51.master
[413a96737f4f209134709ee8278273a0df01639c](https://github.com/armory-io/rosco-armory/commit/413a96737f4f209134709ee8278273a0df01639c)
[9cffd978c50860fdb74bd0d4c7e5ed7b36017b4c](https://github.com/spinnaker/rosco/commit/9cffd978c50860fdb74bd0d4c7e5ed7b36017b4c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9cffd978c50860fdb74bd0d4c7e5ed7b36017b4c"
},
"details": {
"image": {
"imageId": "sha256:d4f0cc246e533033bd524bd443a28401221287de8a52ac97ba9bd7bf259ffcb4",
"tag": "2024.02.07.19.39.51.master"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.02.07.19.39.51.master

stack.yml
* **master**
armory/fiat-armory:2024.02.07.19.45.25.master
[29b91102cef531fc80622dca8d0f260ec6cec9d9](https://github.com/armory-io/fiat-armory/commit/29b91102cef531fc80622dca8d0f260ec6cec9d9)
[82ad305fa6684080006c3df092c1af8ada03186b](https://github.com/spinnaker/fiat/commit/82ad305fa6684080006c3df092c1af8ada03186b)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "82ad305fa6684080006c3df092c1af8ada03186b"
},
"details": {
"image": {
"imageId": "sha256:b8b3f0ce1fff3840cde9a0063e108e9a861924ec117b4ba348473044a8539dc5",
"tag": "2024.02.07.19.45.25.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update fiat-armory version to 2024.02.07.19.45.25.master

stack.yml
* **master**
armory/rosco-armory:2024.02.09.15.56.14.master
[dec0c87e20844b3effbfe6b77096dbc6b5dd6cac](https://github.com/armory-io/rosco-armory/commit/dec0c87e20844b3effbfe6b77096dbc6b5dd6cac)
[c0e6d3b5ff7926ae51dc081628abb99c1c7ea7c5](https://github.com/spinnaker/rosco/commit/c0e6d3b5ff7926ae51dc081628abb99c1c7ea7c5)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c0e6d3b5ff7926ae51dc081628abb99c1c7ea7c5"
},
"details": {
"image": {
"imageId": "sha256:147e25debfbc59b8550da04d19151423f30ce69224bd8bb063e7d92edae7203c",
"tag": "2024.02.09.15.56.14.master"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.02.09.15.56.14.master

stack.yml
armory/echo-armory:2024.02.13.00.35.35.release-2.32.x
[d7483b6acd82b7b7a8053a1ec66aa9897930dbea](https://github.com/armory-io/echo-armory/commit/d7483b6acd82b7b7a8053a1ec66aa9897930dbea)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:7265b739c4198736876c5481198118bfb753373a344bcb98465d9a316b4198a1",
"tag": "2024.02.13.00.35.35.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "d7483b6acd82b7b7a8053a1ec66aa9897930dbea"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update echo-armory version to 2024.02.13.00.35.35.release-2.32.x

stack.yml
armory/orca-armory:2024.02.13.08.55.38.release-2.32.x
[538b577c932e3c67af7db78f28fa3ee0209e934b](https://github.com/armory-io/orca-armory/commit/538b577c932e3c67af7db78f28fa3ee0209e934b)
[83c37a309daa24dd1574470ed440c3699df762ef](https://github.com/spinnaker/orca/commit/83c37a309daa24dd1574470ed440c3699df762ef)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "83c37a309daa24dd1574470ed440c3699df762ef"
},
"details": {
"image": {
"imageId": "sha256:0956f7aa11d44cd310f4d242e69fc797132fcaaecff1c4545851967e6e7b6786",
"tag": "2024.02.13.08.55.38.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2024.02.13.08.55.38.release-2.32.x

stack.yml
armory/front50-armory:2024.01.23.15.42.49.release-2.30.x
[af86fc703f1ef024f0a55979cef77dab373baf92](https://github.com/armory-io/front50-armory/commit/af86fc703f1ef024f0a55979cef77dab373baf92)
[66d8f0096ba1199909acd48d0446cf824cf17a35](https://github.com/spinnaker/front50/commit/66d8f0096ba1199909acd48d0446cf824cf17a35)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "66d8f0096ba1199909acd48d0446cf824cf17a35"
},
"details": {
"image": {
"imageId": "sha256:d069757163428871a1934d6348b04777358d01c53b1e324d93192ed8efafb5af",
"tag": "2024.01.23.15.42.49.release-2.30.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update front50-armory version to 2024.01.23.15.42.49.release-2.30.x

stack.yml
armory/dinghy:2024.02.13.14.18.34.release-2.32.x
[f5b14ffba75721322ada662f2325e80ec86347de](https://github.com/armory-io/dinghy/commit/f5b14ffba75721322ada662f2325e80ec86347de)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:1682e088ca88f91b21aee17a6802dcea89bb77f0845b2658e24bd9781d557875",
"tag": "2024.02.13.14.18.34.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "f5b14ffba75721322ada662f2325e80ec86347de"
}
},
},
"details": {
"image": {
"imageId": "sha256:1682e088ca88f91b21aee17a6802dcea89bb77f0845b2658e24bd9781d557875", …
```
=> chore(cd): update dinghy version to 2024.02.13.14.18.34.release-2.32.x

stack.yml
armory/gate-armory:2024.02.27.08.29.49.release-2.32.x
[f0f75e4457e679578b75cc629a562e29ccaca211](https://github.com/armory-io/gate-armory/commit/f0f75e4457e679578b75cc629a562e29ccaca211)
[edc09af80446a7c6eea3bb935ea54ad35c508122](https://github.com/spinnaker/gate/commit/edc09af80446a7c6eea3bb935ea54ad35c508122)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "edc09af80446a7c6eea3bb935ea54ad35c508122"
},
"details": {
"image": {
"imageId": "sha256:e0be4d89cbf89c1c1450c55d63ea78519d623c93910f627628e14c0a4807e8c8",
"tag": "2024.02.27.08.29.49.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update gate-armory version to 2024.02.27.08.29.49.release-2.32.x

stack.yml
armory/igor-armory:2024.02.27.15.52.13.release-2.32.x
[c55a06f48e48fc15871a07a52db8d592948e26cc](https://github.com/armory-io/igor-armory/commit/c55a06f48e48fc15871a07a52db8d592948e26cc)
[667a68fa066f35a61ede2f2fe5b7d38c21789575](https://github.com/spinnaker/igor/commit/667a68fa066f35a61ede2f2fe5b7d38c21789575)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "667a68fa066f35a61ede2f2fe5b7d38c21789575"
},
"details": {
"image": {
"imageId": "sha256:0a480804b25cacd4473f9edd4b0db058d3270749bb149407a4798d67d02e8223",
"tag": "2024.02.27.15.52.13.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update igor-armory version to 2024.02.27.15.52.13.release-2.32.x

stack.yml
armory/clouddriver-armory:2024.02.27.15.07.53.release-2.32.x
[64b5303b0645b1ffe83fa7f2d4e22ce2f38cd981](https://github.com/armory-io/clouddriver-armory/commit/64b5303b0645b1ffe83fa7f2d4e22ce2f38cd981)
[282958303c530214b8293b67e08ac31c4c550448](https://github.com/spinnaker/clouddriver/commit/282958303c530214b8293b67e08ac31c4c550448)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "282958303c530214b8293b67e08ac31c4c550448"
},
"details": {
"image": {
"imageId": "sha256:e5a7f53e41c8e6d322199ee347f90384c4baf884de512cd6899f3c75493968e6",
"tag": "2024.02.27.15.07.53.release-2.32.x"
},
"vcs": …
```
=> chore(cd): update clouddriver-armory version to 2024.02.27.15.07.53.release-2.32.x

stack.yml
armory/orca-armory:2024.03.01.09.17.06.release-2.32.x
[b36a5eb32c8167067cc5ba536adf52732d46b520](https://github.com/armory-io/orca-armory/commit/b36a5eb32c8167067cc5ba536adf52732d46b520)
[df6e058b13a76ffbe77da85589829d87a3403b0e](https://github.com/spinnaker/orca/commit/df6e058b13a76ffbe77da85589829d87a3403b0e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "df6e058b13a76ffbe77da85589829d87a3403b0e"
},
"details": {
"image": {
"imageId": "sha256:1edec877c5a17347103f2d81d76abce80db175940ae7d95fd53db165605881d8",
"tag": "2024.03.01.09.17.06.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2024.03.01.09.17.06.release-2.32.x

stack.yml
armory/echo-armory:2024.03.01.09.16.27.release-2.32.x
[8132dd28a7461c85a8ade99e867d1db8ca1d57ca](https://github.com/armory-io/echo-armory/commit/8132dd28a7461c85a8ade99e867d1db8ca1d57ca)
[d5ebde4c51246a6f6e1c996d05febde65dbdd7cb](https://github.com/spinnaker/echo/commit/d5ebde4c51246a6f6e1c996d05febde65dbdd7cb)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d5ebde4c51246a6f6e1c996d05febde65dbdd7cb"
},
"details": {
"image": {
"imageId": "sha256:b27f207af09e975dcd5b87b87f8655daf0ec1331cc486bb60e8f90ae215325c1",
"tag": "2024.03.01.09.16.27.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2024.03.01.09.16.27.release-2.32.x

stack.yml
armory/clouddriver-armory:2024.03.01.09.15.46.release-2.32.x
[e3e765a19daa02a3c82fa1c4505d6d3da98d1ac1](https://github.com/armory-io/clouddriver-armory/commit/e3e765a19daa02a3c82fa1c4505d6d3da98d1ac1)
[282958303c530214b8293b67e08ac31c4c550448](https://github.com/spinnaker/clouddriver/commit/282958303c530214b8293b67e08ac31c4c550448)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "282958303c530214b8293b67e08ac31c4c550448"
},
"details": {
"image": {
"imageId": "sha256:0d88568862249b8d28bee29af5e427ef3d77b7d22063f38039dc38923ae19ed0",
"tag": "2024.03.01.09.15.46.release-2.32.x"
},
"vcs": …
```
=> chore(cd): update clouddriver-armory version to 2024.03.01.09.15.46.release-2.32.x

stack.yml
armory/fiat-armory:2024.03.01.11.25.33.release-2.32.x
[804e5f862ed600d42e1acab3b67dc9c282c7cf3a](https://github.com/armory-io/fiat-armory/commit/804e5f862ed600d42e1acab3b67dc9c282c7cf3a)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:47bc7461db0a657675f25a71785d3dac57ada097b62f9c12e97933e4ba1bd49a",
"tag": "2024.03.01.11.25.33.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "804e5f862ed600d42e1acab3b67dc9c282c7cf3a"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update fiat-armory version to 2024.03.01.11.25.33.release-2.32.x

stack.yml
armory/front50-armory:2024.03.01.09.19.04.release-2.32.x
[54cc4a0a9c0a9f8509a6ed1ff35b143c199b70d0](https://github.com/armory-io/front50-armory/commit/54cc4a0a9c0a9f8509a6ed1ff35b143c199b70d0)
[f8d4d344e3858d9c3d45534d34a10e51181ece8e](https://github.com/spinnaker/front50/commit/f8d4d344e3858d9c3d45534d34a10e51181ece8e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f8d4d344e3858d9c3d45534d34a10e51181ece8e"
},
"details": {
"image": {
"imageId": "sha256:ccd26b14dba13ce8e99bbfeaa2f04c1897849b82a2cae26031393dac4eb3cb39",
"tag": "2024.03.01.09.19.04.release-2.32.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update front50-armory version to 2024.03.01.09.19.04.release-2.32.x

stack.yml
armory/igor-armory:2024.03.01.09.18.24.release-2.32.x
[344e258677d460acd4a4a86310d69f3975c846db](https://github.com/armory-io/igor-armory/commit/344e258677d460acd4a4a86310d69f3975c846db)
[667a68fa066f35a61ede2f2fe5b7d38c21789575](https://github.com/spinnaker/igor/commit/667a68fa066f35a61ede2f2fe5b7d38c21789575)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "667a68fa066f35a61ede2f2fe5b7d38c21789575"
},
"details": {
"image": {
"imageId": "sha256:9670af44f14d616cc982354ba140e26eec541f9dd0af9bb9639d2dc4ccc94d38",
"tag": "2024.03.01.09.18.24.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update igor-armory version to 2024.03.01.09.18.24.release-2.32.x

stack.yml
armory/gate-armory:2024.03.01.09.18.12.release-2.32.x
[619047a5a3afc11b367c6b0b3aa36e237288c456](https://github.com/armory-io/gate-armory/commit/619047a5a3afc11b367c6b0b3aa36e237288c456)
[edc09af80446a7c6eea3bb935ea54ad35c508122](https://github.com/spinnaker/gate/commit/edc09af80446a7c6eea3bb935ea54ad35c508122)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "edc09af80446a7c6eea3bb935ea54ad35c508122"
},
"details": {
"image": {
"imageId": "sha256:66ef95c058c4564a5aaf3c2b201253c77c2eb2f657b36f667480ee6d1d7ccb06",
"tag": "2024.03.01.09.18.12.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update gate-armory version to 2024.03.01.09.18.12.release-2.32.x

stack.yml
armory/kayenta-armory:2024.03.01.09.32.15.release-2.32.x
[6a4369342998682c8c35ba1e1144b72f42484c6c](https://github.com/armory-io/kayenta-armory/commit/6a4369342998682c8c35ba1e1144b72f42484c6c)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:3a57ffe44aec59f33489d47f6549462ea70dcde338d3a62f1f31e3ed214bccbf",
"tag": "2024.03.01.09.32.15.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "6a4369342998682c8c35ba1e1144b72f42484c6c"
}
},
},
"details": { …
```
=> chore(cd): update kayenta-armory version to 2024.03.01.09.32.15.release-2.32.x

stack.yml
armory/rosco-armory:2024.03.01.09.22.27.release-2.32.x
[d258548dff17a766c7d0e110ae618ab24f27bb53](https://github.com/armory-io/rosco-armory/commit/d258548dff17a766c7d0e110ae618ab24f27bb53)
[93ae1b49876b734e725cdb2c01e8eae9237ed653](https://github.com/spinnaker/rosco/commit/93ae1b49876b734e725cdb2c01e8eae9237ed653)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "93ae1b49876b734e725cdb2c01e8eae9237ed653"
},
"details": {
"image": {
"imageId": "sha256:222d4fbc63121e12594cfac2e89a9dad604636a5938591828585ffb27640e822",
"tag": "2024.03.01.09.22.27.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.03.01.09.22.27.release-2.32.x

stack.yml
* **master**
armory/front50-armory:2024.03.03.18.00.22.master
[551e96c6ee0002461f45676b3a71506c764fd80a](https://github.com/armory-io/front50-armory/commit/551e96c6ee0002461f45676b3a71506c764fd80a)
[d26a079b04a4163702d1f4f07be6f108edeab513](https://github.com/spinnaker/front50/commit/d26a079b04a4163702d1f4f07be6f108edeab513)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d26a079b04a4163702d1f4f07be6f108edeab513"
},
"details": {
"image": {
"imageId": "sha256:55be183c487d967a6cdf53c4515e90e5bc2aa7f733a7023be6690374d021b5db",
"tag": "2024.03.03.18.00.22.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update front50-armory version to 2024.03.03.18.00.22.master

stack.yml
* **master**
armory/kayenta-armory:2024.02.20.06.52.31.master
[d1d3b924370531f2e417e2ff3bab08a9e16e3905](https://github.com/armory-io/kayenta-armory/commit/d1d3b924370531f2e417e2ff3bab08a9e16e3905)
[8c30e062030f032d2655f04b2dcf6218aa1460c1](https://github.com/spinnaker/kayenta/commit/8c30e062030f032d2655f04b2dcf6218aa1460c1)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "8c30e062030f032d2655f04b2dcf6218aa1460c1"
},
"details": {
"image": {
"imageId": "sha256:298f7137e76fcb6f000bea75574b12a09a23d562398eee4ffba202003c37b6ec",
"tag": "2024.02.20.06.52.31.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update kayenta-armory version to 2024.02.20.06.52.31.master

stack.yml
armory/front50-armory:2024.03.05.10.33.06.release-2.32.x
[9fbcb8b1b60c6074c7154cc22f3455b932119dd8](https://github.com/armory-io/front50-armory/commit/9fbcb8b1b60c6074c7154cc22f3455b932119dd8)
[f8d4d344e3858d9c3d45534d34a10e51181ece8e](https://github.com/spinnaker/front50/commit/f8d4d344e3858d9c3d45534d34a10e51181ece8e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f8d4d344e3858d9c3d45534d34a10e51181ece8e"
},
"details": {
"image": {
"imageId": "sha256:8c49ce4c37854760bdbc4119c011fc30f5a6c82386c166d42b8a275225f7e62a",
"tag": "2024.03.05.10.33.06.release-2.32.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update front50-armory version to 2024.03.05.10.33.06.release-2.32.x

stack.yml
armory/front50-armory:2024.03.05.15.55.17.release-2.32.x
[90972680ae73ef9ec6df43ab4987cfde9fe4416c](https://github.com/armory-io/front50-armory/commit/90972680ae73ef9ec6df43ab4987cfde9fe4416c)
[f8d4d344e3858d9c3d45534d34a10e51181ece8e](https://github.com/spinnaker/front50/commit/f8d4d344e3858d9c3d45534d34a10e51181ece8e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f8d4d344e3858d9c3d45534d34a10e51181ece8e"
},
"details": {
"image": {
"imageId": "sha256:b806b14066949bdaedb46663cb3ccc5503d696454183dd07ec20acb475f44399",
"tag": "2024.03.05.15.55.17.release-2.32.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update front50-armory version to 2024.03.05.15.55.17.release-2.32.x

stack.yml
armory/kayenta-armory:2024.03.08.22.16.33.release-2.32.x
[bccd150fcc8a7cb7df537ec6269bce5d2843c703](https://github.com/armory-io/kayenta-armory/commit/bccd150fcc8a7cb7df537ec6269bce5d2843c703)
[d6f5f1321961c3e2fadb8fe295af152f46003b11](https://github.com/spinnaker/kayenta/commit/d6f5f1321961c3e2fadb8fe295af152f46003b11)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d6f5f1321961c3e2fadb8fe295af152f46003b11"
},
"details": {
"image": {
"imageId": "sha256:3bc9ed35c5fbd08617d73e4bc92aaacc32311312965e24309eb5c73173b1bab5",
"tag": "2024.03.08.22.16.33.release-2.32.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update kayenta-armory version to 2024.03.08.22.16.33.release-2.32.x

stack.yml
armory/front50-armory:2024.03.08.19.35.36.release-2.32.x
[ba318cd2c445f14e5d6c3db87fa1658549385403](https://github.com/armory-io/front50-armory/commit/ba318cd2c445f14e5d6c3db87fa1658549385403)
[9bb418e3069173ca4ad636e6d66665ca096c313c](https://github.com/spinnaker/front50/commit/9bb418e3069173ca4ad636e6d66665ca096c313c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9bb418e3069173ca4ad636e6d66665ca096c313c"
},
"details": {
"image": {
"imageId": "sha256:3e98aa5672359a82b1236c903c957f15512e3b840267eca547fef3065f32d2b6",
"tag": "2024.03.08.19.35.36.release-2.32.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update front50-armory version to 2024.03.08.19.35.36.release-2.32.x

stack.yml
armory/orca-armory:2024.03.08.19.41.39.release-2.32.x
[9d45d87956abd9aad29ef8f9858e602e72d78c3c](https://github.com/armory-io/orca-armory/commit/9d45d87956abd9aad29ef8f9858e602e72d78c3c)
[73d47ccaca8b6d735887e97c3dc4ad1914ff0c78](https://github.com/spinnaker/orca/commit/73d47ccaca8b6d735887e97c3dc4ad1914ff0c78)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "73d47ccaca8b6d735887e97c3dc4ad1914ff0c78"
},
"details": {
"image": {
"imageId": "sha256:23996212989460a97367a647a623eee14b17b797351a42f8cc08ab37e8f16ea7",
"tag": "2024.03.08.19.41.39.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2024.03.08.19.41.39.release-2.32.x

stack.yml
armory/orca-armory:2024.03.11.15.32.23.release-2.31.x
[1ba0274d497782011ab0abed2eee0e1018e865c5](https://github.com/armory-io/orca-armory/commit/1ba0274d497782011ab0abed2eee0e1018e865c5)
[d97e2c4ad7b7cebd67d9a569410df1a44e3e23a2](https://github.com/spinnaker/orca/commit/d97e2c4ad7b7cebd67d9a569410df1a44e3e23a2)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d97e2c4ad7b7cebd67d9a569410df1a44e3e23a2"
},
"details": {
"image": {
"imageId": "sha256:65cda9842fd47a5943d0f63e7362df01f9c4742a5e3cbfda1fd02973b31238a1",
"tag": "2024.03.11.15.32.23.release-2.31.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2024.03.11.15.32.23.release-2.31.x

stack.yml
armory/rosco-armory:2024.02.28.09.06.38.release-2.31.x
[9812503db8271e32cd5d7960db12441fa8a39494](https://github.com/armory-io/rosco-armory/commit/9812503db8271e32cd5d7960db12441fa8a39494)
[6a866e7c74ce241f5c849978d0a2bafc739cf882](https://github.com/spinnaker/rosco/commit/6a866e7c74ce241f5c849978d0a2bafc739cf882)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "6a866e7c74ce241f5c849978d0a2bafc739cf882"
},
"details": {
"image": {
"imageId": "sha256:331287a6d4ad331a27be1b62f045d69bfb6a0c956a5108b03f6eb94777c77384",
"tag": "2024.02.28.09.06.38.release-2.31.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.02.28.09.06.38.release-2.31.x

stack.yml
armory/gate-armory:2024.02.28.09.01.44.release-2.31.x
[abfb0120ca617cb5806c7f2082ab4f8e9d7190b2](https://github.com/armory-io/gate-armory/commit/abfb0120ca617cb5806c7f2082ab4f8e9d7190b2)
[7bc7898bee5c38a200fafbf391126a41dd4aa594](https://github.com/spinnaker/gate/commit/7bc7898bee5c38a200fafbf391126a41dd4aa594)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7bc7898bee5c38a200fafbf391126a41dd4aa594"
},
"details": {
"image": {
"imageId": "sha256:a20662f47e12725a6058cae074ef9b296f14036ac5e2bc63cd20cb936c3a2b1f",
"tag": "2024.02.28.09.01.44.release-2.31.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update gate-armory version to 2024.02.28.09.01.44.release-2.31.x

stack.yml
armory/echo-armory:2024.03.08.22.02.26.release-2.32.x
[9d2abeeea4341e5ba94654925ba6488a9038af3f](https://github.com/armory-io/echo-armory/commit/9d2abeeea4341e5ba94654925ba6488a9038af3f)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:a6f95519b8085ae9f3626507949d9403514016ac6e9e9634e8a594687de69c35",
"tag": "2024.03.08.22.02.26.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "9d2abeeea4341e5ba94654925ba6488a9038af3f"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update echo-armory version to 2024.03.08.22.02.26.release-2.32.x

stack.yml
armory/clouddriver-armory:2024.03.08.20.08.23.release-2.32.x
[b29acea67a40b4145431137ba96454c1d1bf0d73](https://github.com/armory-io/clouddriver-armory/commit/b29acea67a40b4145431137ba96454c1d1bf0d73)
[03342d393ee1079153c5e5966f88a6433ba5328d](https://github.com/spinnaker/clouddriver/commit/03342d393ee1079153c5e5966f88a6433ba5328d)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "03342d393ee1079153c5e5966f88a6433ba5328d"
},
"details": {
"image": {
"imageId": "sha256:c99b266b66959669d60c7b10ad32f38f1d996bdf51514b384fc50a97931d69a4",
"tag": "2024.03.08.20.08.23.release-2.32.x"
},
"vcs": …
```
=> chore(cd): update clouddriver-armory version to 2024.03.08.20.08.23.release-2.32.x

stack.yml
* **master**
armory/front50-armory:2024.03.12.16.44.00.master
[8abd23f4c237c68f95504286a2cbe74c74128284](https://github.com/armory-io/front50-armory/commit/8abd23f4c237c68f95504286a2cbe74c74128284)
[51da7f8287ca1c886d7996d92d6440db5f30c993](https://github.com/spinnaker/front50/commit/51da7f8287ca1c886d7996d92d6440db5f30c993)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "51da7f8287ca1c886d7996d92d6440db5f30c993"
},
"details": {
"image": {
"imageId": "sha256:56c8706a3adc4e856302b1375ac5e53a7ceeefbe487e332d1117561057778805",
"tag": "2024.03.12.16.44.00.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update front50-armory version to 2024.03.12.16.44.00.master

stack.yml
* **master**
armory/rosco-armory:2024.02.23.18.09.58.master
[bd4d971f9cbe98fe1f0db399aef8c91ae5ccb00e](https://github.com/armory-io/rosco-armory/commit/bd4d971f9cbe98fe1f0db399aef8c91ae5ccb00e)
[3e002773d7053ff762d41a70b9cce0941ca219e0](https://github.com/spinnaker/rosco/commit/3e002773d7053ff762d41a70b9cce0941ca219e0)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "3e002773d7053ff762d41a70b9cce0941ca219e0"
},
"details": {
"image": {
"imageId": "sha256:be3e3145ccdb7a5598ee76d95c5e00162e2bc59139e0f9af08ddd67d410d82f2",
"tag": "2024.02.23.18.09.58.master"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.02.23.18.09.58.master

stack.yml
armory/clouddriver-armory:2024.02.28.08.59.37.release-2.31.x
[cb7a25cc5d610afc67346cf25af98082566e38f6](https://github.com/armory-io/clouddriver-armory/commit/cb7a25cc5d610afc67346cf25af98082566e38f6)
[06fa41289e95e6010901f241a176a0445ef38edb](https://github.com/spinnaker/clouddriver/commit/06fa41289e95e6010901f241a176a0445ef38edb)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "06fa41289e95e6010901f241a176a0445ef38edb"
},
"details": {
"image": {
"imageId": "sha256:275eab90ea605ebf1ea4715cfe03791b1ff826cf2237847ce82ea0589ace983d",
"tag": "2024.02.28.08.59.37.release-2.31.x"
},
"vcs": …
```
=> chore(cd): update clouddriver-armory version to 2024.02.28.08.59.37.release-2.31.x

stack.yml
armory/kayenta-armory:2024.02.28.09.16.27.release-2.31.x
[18b22f0e9ca778f354ec5ac8255d0014ba6339ff](https://github.com/armory-io/kayenta-armory/commit/18b22f0e9ca778f354ec5ac8255d0014ba6339ff)
[d5e02906da9f5420e27c63f368e13ff7533355ee](https://github.com/spinnaker/kayenta/commit/d5e02906da9f5420e27c63f368e13ff7533355ee)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d5e02906da9f5420e27c63f368e13ff7533355ee"
},
"details": {
"image": {
"imageId": "sha256:0caff850cba0be5660b89deba8716c965a34435b993982e5583bcc1d2148a242",
"tag": "2024.02.28.09.16.27.release-2.31.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update kayenta-armory version to 2024.02.28.09.16.27.release-2.31.x

stack.yml
armory/dinghy:2024.02.13.15.49.20.release-2.31.x
[1bbb649f71d128d167229d72a1c94aa480f99684](https://github.com/armory-io/dinghy/commit/1bbb649f71d128d167229d72a1c94aa480f99684)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:75837a4ec89addd3a21aad877942ba9261217b2425c52e9d3b6a3b62d619fa55",
"tag": "2024.02.13.15.49.20.release-2.31.x"
},
"vcs": {
"repo": {
},
"sha": "1bbb649f71d128d167229d72a1c94aa480f99684"
}
},
},
"details": {
"image": {
"imageId": "sha256:75837a4ec89addd3a21aad877942ba9261217b2425c52e9d3b6a3b62d619fa55", …
```
=> chore(cd): update dinghy version to 2024.02.13.15.49.20.release-2.31.x

stack.yml
armory/front50-armory:2024.03.05.15.43.15.release-2.31.x
[13814c48944265261af52c3929a4b96fc6c45add](https://github.com/armory-io/front50-armory/commit/13814c48944265261af52c3929a4b96fc6c45add)
[f0494570576de5aa33d969fdd7fad93dee2479cc](https://github.com/spinnaker/front50/commit/f0494570576de5aa33d969fdd7fad93dee2479cc)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f0494570576de5aa33d969fdd7fad93dee2479cc"
},
"details": {
"image": {
"imageId": "sha256:63f0bb148303bef8bd73df571266df7be6c2c156cbd4f88eba86a23efb1f4c9e",
"tag": "2024.03.05.15.43.15.release-2.31.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update front50-armory version to 2024.03.05.15.43.15.release-2.31.x

stack.yml
armory/igor-armory:2024.03.14.16.03.54.release-2.31.x
[a66db7a9037a4ddec4e131ec0b0bb137956a9395](https://github.com/armory-io/igor-armory/commit/a66db7a9037a4ddec4e131ec0b0bb137956a9395)
[b57c06a4620974e0b65a5356eccd41907d99543c](https://github.com/spinnaker/igor/commit/b57c06a4620974e0b65a5356eccd41907d99543c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b57c06a4620974e0b65a5356eccd41907d99543c"
},
"details": {
"image": {
"imageId": "sha256:a23af50b5815b706be7930a220752bc19b59f10aac5628cc12181ec050562fe3",
"tag": "2024.03.14.16.03.54.release-2.31.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update igor-armory version to 2024.03.14.16.03.54.release-2.31.x

stack.yml
armory/echo-armory:2024.03.14.16.13.42.release-2.31.x
[abefa81c6eac597a0db45e33ebaebd464cfdc5df](https://github.com/armory-io/echo-armory/commit/abefa81c6eac597a0db45e33ebaebd464cfdc5df)
[1486874368400b85578b5ea11aa9acc84f4e5838](https://github.com/spinnaker/echo/commit/1486874368400b85578b5ea11aa9acc84f4e5838)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1486874368400b85578b5ea11aa9acc84f4e5838"
},
"details": {
"image": {
"imageId": "sha256:3665a0f60066dc0d47bc1ed62360878d28e2b3db959e8419660e8d86d080b205",
"tag": "2024.03.14.16.13.42.release-2.31.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2024.03.14.16.13.42.release-2.31.x

stack.yml
armory/orca-armory:2024.03.14.16.52.46.release-2.31.x
[e46aab32af0ec1031eb216fc3fa2cf00f957aea0](https://github.com/armory-io/orca-armory/commit/e46aab32af0ec1031eb216fc3fa2cf00f957aea0)
[ff02beab839a1635492c4ecc40657a90e84dad24](https://github.com/spinnaker/orca/commit/ff02beab839a1635492c4ecc40657a90e84dad24)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "ff02beab839a1635492c4ecc40657a90e84dad24"
},
"details": {
"image": {
"imageId": "sha256:e6b2d36a4da04b316062234c247a32854cbc55fa205638bf4db5e17d0bb4f2f9",
"tag": "2024.03.14.16.52.46.release-2.31.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2024.03.14.16.52.46.release-2.31.x

stack.yml
* **master**
armory/gate-armory:2024.03.19.15.17.41.master
[dd7d54c1c7eecfe043ac58b6c1e237284d0e6479](https://github.com/armory-io/gate-armory/commit/dd7d54c1c7eecfe043ac58b6c1e237284d0e6479)
[23806cc6cddf6213d107b19e5ebfad12ceb751c5](https://github.com/spinnaker/gate/commit/23806cc6cddf6213d107b19e5ebfad12ceb751c5)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "23806cc6cddf6213d107b19e5ebfad12ceb751c5"
},
"details": {
"image": {
"imageId": "sha256:1651a6a36422faa432b7691bc9cac29d6fe06b924e5cf7dff393b14490fd08aa",
"tag": "2024.03.19.15.17.41.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update gate-armory version to 2024.03.19.15.17.41.master

stack.yml
* **master**
armory/echo-armory:2024.03.19.15.19.00.master
[3eebe4c750ae12d8b0e42cbc7ecff4fb3fe6322b](https://github.com/armory-io/echo-armory/commit/3eebe4c750ae12d8b0e42cbc7ecff4fb3fe6322b)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:e8b801105e02baa2dd8dfc758183de02c4bb5eeb9aa15384eb39efbc4677d350",
"tag": "2024.03.19.15.19.00.master"
},
"vcs": {
"repo": {
},
"sha": "3eebe4c750ae12d8b0e42cbc7ecff4fb3fe6322b"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update echo-armory version to 2024.03.19.15.19.00.master

stack.yml
* **master**
armory/orca-armory:2024.03.19.15.16.26.master
[89dbd605c6d2f140db002370a5ed860612966b0b](https://github.com/armory-io/orca-armory/commit/89dbd605c6d2f140db002370a5ed860612966b0b)
[5444774f8c4c28ca6676bc23c29fb8c4f8f6489b](https://github.com/spinnaker/orca/commit/5444774f8c4c28ca6676bc23c29fb8c4f8f6489b)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5444774f8c4c28ca6676bc23c29fb8c4f8f6489b"
},
"details": {
"image": {
"imageId": "sha256:8e9448456a36e885370a70d5c4bc8553ddd913cd22c7b47e4da2024d8f4cf452",
"tag": "2024.03.19.15.16.26.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update orca-armory version to 2024.03.19.15.16.26.master

stack.yml
* **master**
armory/clouddriver-armory:2024.03.20.09.57.30.master
[eaf1f64f6ee12320f34a9c54dd18eeb8470ef39b](https://github.com/armory-io/clouddriver-armory/commit/eaf1f64f6ee12320f34a9c54dd18eeb8470ef39b)
[53396d00657983f2c65a47e865580ecf85c8bb87](https://github.com/spinnaker/clouddriver/commit/53396d00657983f2c65a47e865580ecf85c8bb87)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "53396d00657983f2c65a47e865580ecf85c8bb87"
},
"details": {
"image": {
"imageId": "sha256:fffc8ca38835efd64c16e61c2f9054eb21eea0375961c09cb3b0763546a48ecf",
"tag": "2024.03.20.09.57.30.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.03.20.09.57.30.master

stack.yml
* **master**
armory/front50-armory:2024.03.19.15.18.07.master
[f98044d0e1241f7b9806eff3e06017b777964c67](https://github.com/armory-io/front50-armory/commit/f98044d0e1241f7b9806eff3e06017b777964c67)
[9c838ea4835fb2953b462791db56029a53614b3c](https://github.com/spinnaker/front50/commit/9c838ea4835fb2953b462791db56029a53614b3c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9c838ea4835fb2953b462791db56029a53614b3c"
},
"details": {
"image": {
"imageId": "sha256:31dd4186bd8acffee0bbaa6c5aef3d420ffe26691dd37e34ae86fe7b8ccf30b7",
"tag": "2024.03.19.15.18.07.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update front50-armory version to 2024.03.19.15.18.07.master

stack.yml
* **master**
armory/fiat-armory:2024.03.19.15.18.48.master
[6def41a1bb8f3e15d552b6b65e63d4bcff7f9a8e](https://github.com/armory-io/fiat-armory/commit/6def41a1bb8f3e15d552b6b65e63d4bcff7f9a8e)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:be9a4b12d41f178257496213a1e37850504e0940f40bf732c248d8d4af7261fb",
"tag": "2024.03.19.15.18.48.master"
},
"vcs": {
"repo": {
},
"sha": "6def41a1bb8f3e15d552b6b65e63d4bcff7f9a8e"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update fiat-armory version to 2024.03.19.15.18.48.master

stack.yml
* **master**
armory/kayenta-armory:2024.03.19.15.17.08.master
[05a4a71db8f4572c959f5626e2a7a53c1b4c9c6d](https://github.com/armory-io/kayenta-armory/commit/05a4a71db8f4572c959f5626e2a7a53c1b4c9c6d)
[8c30e062030f032d2655f04b2dcf6218aa1460c1](https://github.com/spinnaker/kayenta/commit/8c30e062030f032d2655f04b2dcf6218aa1460c1)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "8c30e062030f032d2655f04b2dcf6218aa1460c1"
},
"details": {
"image": {
"imageId": "sha256:e1184b2079038fc6deea0bae12667b62bf636d938c261a27d0d7f821aac2012c",
"tag": "2024.03.19.15.17.08.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update kayenta-armory version to 2024.03.19.15.17.08.master

stack.yml
* **master**
armory/rosco-armory:2024.03.19.15.16.07.master
[0e7c0378ecf64ad17fb8b1923360d360a8111051](https://github.com/armory-io/rosco-armory/commit/0e7c0378ecf64ad17fb8b1923360d360a8111051)
[3e002773d7053ff762d41a70b9cce0941ca219e0](https://github.com/spinnaker/rosco/commit/3e002773d7053ff762d41a70b9cce0941ca219e0)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "3e002773d7053ff762d41a70b9cce0941ca219e0"
},
"details": {
"image": {
"imageId": "sha256:af4c51f4d053099501caea98e5cd7839971a47aa95e45eec63fe60aeac507163",
"tag": "2024.03.19.15.16.07.master"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.03.19.15.16.07.master

stack.yml
armory/gate-armory:2024.03.25.22.27.15.release-2.32.x
[c6654ca6e316eef474c59296120d3f9f34eb0bdf](https://github.com/armory-io/gate-armory/commit/c6654ca6e316eef474c59296120d3f9f34eb0bdf)
[17f68c4c985e16bc9dadf90ab604eae015e38604](https://github.com/spinnaker/gate/commit/17f68c4c985e16bc9dadf90ab604eae015e38604)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "17f68c4c985e16bc9dadf90ab604eae015e38604"
},
"details": {
"image": {
"imageId": "sha256:48a0e2fec4bc3ca2feb3d0c8426b4f23cf3418781e0ab299dd93319a8373adc2",
"tag": "2024.03.25.22.27.15.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update gate-armory version to 2024.03.25.22.27.15.release-2.32.x

stack.yml
armory/orca-armory:2024.03.26.22.38.57.release-2.32.x
[c51e8891acbccccd2e8ee7e050edfdb42be60cd2](https://github.com/armory-io/orca-armory/commit/c51e8891acbccccd2e8ee7e050edfdb42be60cd2)
[30454a20251f719a7271f63498a3098bd4b91fdc](https://github.com/spinnaker/orca/commit/30454a20251f719a7271f63498a3098bd4b91fdc)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "30454a20251f719a7271f63498a3098bd4b91fdc"
},
"details": {
"image": {
"imageId": "sha256:9551a31c37248a24cc72bfe32e9274228d8772d65b6a297ed08e3ddc9e2fea3c",
"tag": "2024.03.26.22.38.57.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2024.03.26.22.38.57.release-2.32.x

stack.yml
armory/orca-armory:2024.03.26.22.38.38.release-2.31.x
[346b1118377066499cd4c720df949aa5e14aba55](https://github.com/armory-io/orca-armory/commit/346b1118377066499cd4c720df949aa5e14aba55)
[453900260e7a3977ee759ac67a8d42bb16445710](https://github.com/spinnaker/orca/commit/453900260e7a3977ee759ac67a8d42bb16445710)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "453900260e7a3977ee759ac67a8d42bb16445710"
},
"details": {
"image": {
"imageId": "sha256:5a1769c03eae616dbfc6c0af43a15b2daacc63e2ceaa77830f6df11bfc83ac93",
"tag": "2024.03.26.22.38.38.release-2.31.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2024.03.26.22.38.38.release-2.31.x

stack.yml
* **master**
armory/orca-armory:2024.03.29.11.09.47.master
[6ce9d75d3539aefd61cabb6934533ac9c1f143f0](https://github.com/armory-io/orca-armory/commit/6ce9d75d3539aefd61cabb6934533ac9c1f143f0)
[886e2b1e19f0e5adfc01c53406bd14a7ffff9af9](https://github.com/spinnaker/orca/commit/886e2b1e19f0e5adfc01c53406bd14a7ffff9af9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "886e2b1e19f0e5adfc01c53406bd14a7ffff9af9"
},
"details": {
"image": {
"imageId": "sha256:ca974c3467d8095ad80e06cadf5f03904877c7161907103fe66ff61ec6e357b0",
"tag": "2024.03.29.11.09.47.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update orca-armory version to 2024.03.29.11.09.47.master

stack.yml
* **master**
armory/gate-armory:2024.03.29.11.09.16.master
[c7e18e6826f30f897428e194291dc1fd48f15329](https://github.com/armory-io/gate-armory/commit/c7e18e6826f30f897428e194291dc1fd48f15329)
[23806cc6cddf6213d107b19e5ebfad12ceb751c5](https://github.com/spinnaker/gate/commit/23806cc6cddf6213d107b19e5ebfad12ceb751c5)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "23806cc6cddf6213d107b19e5ebfad12ceb751c5"
},
"details": {
"image": {
"imageId": "sha256:d625b3ddb8a1f102dcd0d43455d94ba505094d35b53c98810a30ae53e91e1241",
"tag": "2024.03.29.11.09.16.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update gate-armory version to 2024.03.29.11.09.16.master

stack.yml
* **master**
armory/front50-armory:2024.03.29.11.08.49.master
[ae95a744f1c816485496a5ca199f8422997e0172](https://github.com/armory-io/front50-armory/commit/ae95a744f1c816485496a5ca199f8422997e0172)
[e5c739cb176a924183689ad139061ce7e2e12c66](https://github.com/spinnaker/front50/commit/e5c739cb176a924183689ad139061ce7e2e12c66)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e5c739cb176a924183689ad139061ce7e2e12c66"
},
"details": {
"image": {
"imageId": "sha256:c29937e4d512f51c9e5496aa0247fda5be535f3781c19f192905f1b45b0d3a89",
"tag": "2024.03.29.11.08.49.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update front50-armory version to 2024.03.29.11.08.49.master

stack.yml
* **master**
armory/kayenta-armory:2024.03.22.13.45.16.master
[03110bb2b550d90f5aecca30a0c80e23ca1ff731](https://github.com/armory-io/kayenta-armory/commit/03110bb2b550d90f5aecca30a0c80e23ca1ff731)
[22b1bf154024d9ae5ebfd9bf2d90648813a3d662](https://github.com/spinnaker/kayenta/commit/22b1bf154024d9ae5ebfd9bf2d90648813a3d662)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "22b1bf154024d9ae5ebfd9bf2d90648813a3d662"
},
"details": {
"image": {
"imageId": "sha256:e80df2d055a86b025fbe02bd1d3adcc33873882ca35c7b404849af8cef20587f",
"tag": "2024.03.22.13.45.16.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update kayenta-armory version to 2024.03.22.13.45.16.master

stack.yml
* **master**
armory/igor-armory:2024.03.29.11.09.33.master
[4146dcf5f3ee60f640024012e9815b6488c10c69](https://github.com/armory-io/igor-armory/commit/4146dcf5f3ee60f640024012e9815b6488c10c69)
[3e0789ec2a93a743fb2579eeebdd3645d870352f](https://github.com/spinnaker/igor/commit/3e0789ec2a93a743fb2579eeebdd3645d870352f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "3e0789ec2a93a743fb2579eeebdd3645d870352f"
},
"details": {
"image": {
"imageId": "sha256:2b81d94d0d7c232392a0e383287f3824c4548429c13debba8a02408c0eff6bfe",
"tag": "2024.03.29.11.09.33.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update igor-armory version to 2024.03.29.11.09.33.master

stack.yml
* **master**
armory/rosco-armory:2024.03.27.13.57.39.master
[f77de7992c63839b7ba03bb65cfeca5068203b35](https://github.com/armory-io/rosco-armory/commit/f77de7992c63839b7ba03bb65cfeca5068203b35)
[f16c1f8a3084ef64591433380d561206f68a21d2](https://github.com/spinnaker/rosco/commit/f16c1f8a3084ef64591433380d561206f68a21d2)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f16c1f8a3084ef64591433380d561206f68a21d2"
},
"details": {
"image": {
"imageId": "sha256:b817fd3092ec040968d9c4d3cbdd6d88c6a319e68dd5a9ecd19ef86863902430",
"tag": "2024.03.27.13.57.39.master"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.03.27.13.57.39.master

stack.yml
* **master**
armory/fiat-armory:2024.03.29.11.09.46.master
[7deb85a1197c5bbf01842c8c7aa1b89329a7a04a](https://github.com/armory-io/fiat-armory/commit/7deb85a1197c5bbf01842c8c7aa1b89329a7a04a)
[8b130e52b44a2e26fba515bbdb1e505dd3953939](https://github.com/spinnaker/fiat/commit/8b130e52b44a2e26fba515bbdb1e505dd3953939)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "8b130e52b44a2e26fba515bbdb1e505dd3953939"
},
"details": {
"image": {
"imageId": "sha256:23619efa689fce9dd928e61f2891edc73b133e8b5438480facfdca1740e8dce5",
"tag": "2024.03.29.11.09.46.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update fiat-armory version to 2024.03.29.11.09.46.master

stack.yml
* **master**
armory/igor-armory:2024.04.01.04.46.05.master
[3a38c33246c0e7d10a9ea009bc3ea4baa1aec0d7](https://github.com/armory-io/igor-armory/commit/3a38c33246c0e7d10a9ea009bc3ea4baa1aec0d7)
[27215736c89d7a08c6c4f51deea783b63fbf799b](https://github.com/spinnaker/igor/commit/27215736c89d7a08c6c4f51deea783b63fbf799b)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "27215736c89d7a08c6c4f51deea783b63fbf799b"
},
"details": {
"image": {
"imageId": "sha256:8108e17f144fee59c5ada5815f13767a72d00fec47a214f73217748883bd831e",
"tag": "2024.04.01.04.46.05.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update igor-armory version to 2024.04.01.04.46.05.master

stack.yml
* **master**
armory/echo-armory:2024.03.29.22.18.26.master
[628f4a4edf39dfc4dfecef2bc74edafd8b7025e5](https://github.com/armory-io/echo-armory/commit/628f4a4edf39dfc4dfecef2bc74edafd8b7025e5)
[da37acb549071f3a791e04495e2cbde9b4c7463a](https://github.com/spinnaker/echo/commit/da37acb549071f3a791e04495e2cbde9b4c7463a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "da37acb549071f3a791e04495e2cbde9b4c7463a"
},
"details": {
"image": {
"imageId": "sha256:ccd97d2f64a9077d26e55024ebfac277062d69747a2eb8c58299eecaecabe19c",
"tag": "2024.03.29.22.18.26.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2024.03.29.22.18.26.master

stack.yml
* **master**
armory/fiat-armory:2024.04.01.17.19.29.master
[ad501b5fc1b9c7fcab988662c52f9d55c92fce54](https://github.com/armory-io/fiat-armory/commit/ad501b5fc1b9c7fcab988662c52f9d55c92fce54)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:f028d7da09f873fd9b732017a1242d069113aa0f3a8650df40d999b94fe5519a",
"tag": "2024.04.01.17.19.29.master"
},
"vcs": {
"repo": {
},
"sha": "ad501b5fc1b9c7fcab988662c52f9d55c92fce54"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update fiat-armory version to 2024.04.01.17.19.29.master

stack.yml
* **master**
armory/clouddriver-armory:2024.04.01.21.37.49.master
[da933e85726935b90359dc70d7a31461d7ec772d](https://github.com/armory-io/clouddriver-armory/commit/da933e85726935b90359dc70d7a31461d7ec772d)
[6f24dfcd84af94ea5e00080af03afd7c613177e7](https://github.com/spinnaker/clouddriver/commit/6f24dfcd84af94ea5e00080af03afd7c613177e7)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "6f24dfcd84af94ea5e00080af03afd7c613177e7"
},
"details": {
"image": {
"imageId": "sha256:937a4fdcefd38e0d058b4d650ffff5d30464674aa8b83582a188b226e690c265",
"tag": "2024.04.01.21.37.49.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.04.01.21.37.49.master

stack.yml
* **master**
armory/echo-armory:2024.04.01.18.28.33.master
[42b9968e823969accd5f5cf45476505aaafecc43](https://github.com/armory-io/echo-armory/commit/42b9968e823969accd5f5cf45476505aaafecc43)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:ad39228ee1ae7dd976a5909b89519f69038eab385c7524b0cc863072d599be6f",
"tag": "2024.04.01.18.28.33.master"
},
"vcs": {
"repo": {
},
"sha": "42b9968e823969accd5f5cf45476505aaafecc43"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update echo-armory version to 2024.04.01.18.28.33.master

stack.yml
* **master**
armory/deck-armory:2024.04.01.18.37.22.master
[044da359e57344286fef98d9430b60874d3b323e](https://github.com/armory-io/deck-armory/commit/044da359e57344286fef98d9430b60874d3b323e)
[484716bf9575fbef76a8a7f3f82bf72072aea6d2](https://github.com/spinnaker/deck/commit/484716bf9575fbef76a8a7f3f82bf72072aea6d2)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "484716bf9575fbef76a8a7f3f82bf72072aea6d2"
},
"details": {
"image": {
"imageId": "sha256:02e0d579904d46a5e00d006989563f14b380f5788fcd0bc601137313095f43a2",
"tag": "2024.04.01.18.37.22.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update deck-armory version to 2024.04.01.18.37.22.master

stack.yml
* **master**
armory/front50-armory:2024.04.01.18.25.17.master
[3b0f7c18ff3f0f84fb03a66c08b9c26cdd32d1a9](https://github.com/armory-io/front50-armory/commit/3b0f7c18ff3f0f84fb03a66c08b9c26cdd32d1a9)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:6bb99ba270a669c14665fa580525ca4d603cb7d72d1266a4487822cd38ee9eb6",
"tag": "2024.04.01.18.25.17.master"
},
"vcs": {
"repo": {
},
"sha": "3b0f7c18ff3f0f84fb03a66c08b9c26cdd32d1a9"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update front50-armory version to 2024.04.01.18.25.17.master

stack.yml
* **master**
armory/kayenta-armory:2024.04.01.18.40.49.master
[8b0ba90eee2960723d9a8a56f28bac95eccf657c](https://github.com/armory-io/kayenta-armory/commit/8b0ba90eee2960723d9a8a56f28bac95eccf657c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:63d052f3ecb41b184ea83c71fd5d8eeef54573edcda3c56b383a5713e66fde0f",
"tag": "2024.04.01.18.40.49.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update kayenta-armory version to 2024.04.01.18.40.49.master

stack.yml
armory/fiat-armory:2024.04.03.10.25.13.release-2.32.x
[5e1839ef81812c439fb37b411bd3b381131c8c40](https://github.com/armory-io/fiat-armory/commit/5e1839ef81812c439fb37b411bd3b381131c8c40)
[1ba9526d339abecddbf12accfdd4ef9d1d25ce75](https://github.com/spinnaker/fiat/commit/1ba9526d339abecddbf12accfdd4ef9d1d25ce75)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1ba9526d339abecddbf12accfdd4ef9d1d25ce75"
},
"details": {
"image": {
"imageId": "sha256:d248e362de4935daea299e848d779b6a0199e8b8a4f5bca80227a228d7019f8a",
"tag": "2024.04.03.10.25.13.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update fiat-armory version to 2024.04.03.10.25.13.release-2.32.x

stack.yml
armory/orca-armory:2024.04.04.10.23.05.release-2.32.x
[cc38ef77b2b4fe6e8ecc3c0e179908df8ab5f08c](https://github.com/armory-io/orca-armory/commit/cc38ef77b2b4fe6e8ecc3c0e179908df8ab5f08c)
[30454a20251f719a7271f63498a3098bd4b91fdc](https://github.com/spinnaker/orca/commit/30454a20251f719a7271f63498a3098bd4b91fdc)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "30454a20251f719a7271f63498a3098bd4b91fdc"
},
"details": {
"image": {
"imageId": "sha256:2b871e25fff24c36153153d052e7627d6ba36602d6fc1748459c121f1b1df185",
"tag": "2024.04.04.10.23.05.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2024.04.04.10.23.05.release-2.32.x

stack.yml
* **master**
armory/fiat-armory:2024.04.06.04.39.28.master
[3fe8405b2064f313ef2b7fbfb003f78e8f851d71](https://github.com/armory-io/fiat-armory/commit/3fe8405b2064f313ef2b7fbfb003f78e8f851d71)
[507d4a27dbfcc0cb69d6416db19dee9f3893b397](https://github.com/spinnaker/fiat/commit/507d4a27dbfcc0cb69d6416db19dee9f3893b397)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "507d4a27dbfcc0cb69d6416db19dee9f3893b397"
},
"details": {
"image": {
"imageId": "sha256:0b4da6c49f25dd3b17139e863ba60e5156e94222266d1eea4bacaa38cf840e29",
"tag": "2024.04.06.04.39.28.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update fiat-armory version to 2024.04.06.04.39.28.master

stack.yml
* **master**
armory/rosco-armory:2024.04.06.04.39.02.master
[884aef61e8ee68dab68e72a728bbc6b042c6bb72](https://github.com/armory-io/rosco-armory/commit/884aef61e8ee68dab68e72a728bbc6b042c6bb72)
[456a2f7efae552c355905cbc2b2763374947a558](https://github.com/spinnaker/rosco/commit/456a2f7efae552c355905cbc2b2763374947a558)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "456a2f7efae552c355905cbc2b2763374947a558"
},
"details": {
"image": {
"imageId": "sha256:2622e5f244cece2fe67600cbee2afc36125a9bccaabfdd2527d80a80ff9d78f4",
"tag": "2024.04.06.04.39.02.master"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.04.06.04.39.02.master

stack.yml
* **master**
armory/echo-armory:2024.04.06.04.47.01.master
[d792a9fde3f547bc717d146f268d1529aec35224](https://github.com/armory-io/echo-armory/commit/d792a9fde3f547bc717d146f268d1529aec35224)
[d229f2e0399389d5c6b63c176ddbc1617ef6b079](https://github.com/spinnaker/echo/commit/d229f2e0399389d5c6b63c176ddbc1617ef6b079)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d229f2e0399389d5c6b63c176ddbc1617ef6b079"
},
"details": {
"image": {
"imageId": "sha256:686772ed2af33f49fc24f853813177dcb266f7353b605fc8ca5639a793e57cab",
"tag": "2024.04.06.04.47.01.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2024.04.06.04.47.01.master

stack.yml
* **master**
armory/front50-armory:2024.04.07.23.24.05.master
[dd0cac07bd4ad22b9616acdd86dad961a704bc93](https://github.com/armory-io/front50-armory/commit/dd0cac07bd4ad22b9616acdd86dad961a704bc93)
[f99f3baeec6bd8c1b721003e8cc7d235f27127d5](https://github.com/spinnaker/front50/commit/f99f3baeec6bd8c1b721003e8cc7d235f27127d5)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f99f3baeec6bd8c1b721003e8cc7d235f27127d5"
},
"details": {
"image": {
"imageId": "sha256:052c782864940b5b983c90db8109f9277b544c3e1162fdf9bbe02b4d79d872d5",
"tag": "2024.04.07.23.24.05.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update front50-armory version to 2024.04.07.23.24.05.master

stack.yml
* **master**
armory/orca-armory:2024.04.15.17.20.52.master
[05be8ac1cb69b2b51f2cec83758b821d88c70800](https://github.com/armory-io/orca-armory/commit/05be8ac1cb69b2b51f2cec83758b821d88c70800)
[a27e88a0a30156b5b000c5eb763b4a796be7763a](https://github.com/spinnaker/orca/commit/a27e88a0a30156b5b000c5eb763b4a796be7763a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a27e88a0a30156b5b000c5eb763b4a796be7763a"
},
"details": {
"image": {
"imageId": "sha256:36cfe0bd912d9db4179b2d1864cf7e0029a3e0095ee32a70b76db762c7576840",
"tag": "2024.04.15.17.20.52.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update orca-armory version to 2024.04.15.17.20.52.master

stack.yml
* **master**
armory/deck-armory:2024.04.15.19.47.53.master
[b8f6d09833a3ccb926495459824b64eaa31a5ce8](https://github.com/armory-io/deck-armory/commit/b8f6d09833a3ccb926495459824b64eaa31a5ce8)
[a7c6ec6aa0beecf04eff618f7b9b2635d01f860f](https://github.com/spinnaker/deck/commit/a7c6ec6aa0beecf04eff618f7b9b2635d01f860f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a7c6ec6aa0beecf04eff618f7b9b2635d01f860f"
},
"details": {
"image": {
"imageId": "sha256:95693375ef8eae47fde6a12ecd0d022899554d815224e6b3bdd00fd1e5a0df9d",
"tag": "2024.04.15.19.47.53.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update deck-armory version to 2024.04.15.19.47.53.master

stack.yml
* **master**
armory/orca-armory:2024.04.15.20.25.36.master
[6b25a07a6e8e2da34d7156b5916d4a9413ea94b1](https://github.com/armory-io/orca-armory/commit/6b25a07a6e8e2da34d7156b5916d4a9413ea94b1)
[a27e88a0a30156b5b000c5eb763b4a796be7763a](https://github.com/spinnaker/orca/commit/a27e88a0a30156b5b000c5eb763b4a796be7763a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a27e88a0a30156b5b000c5eb763b4a796be7763a"
},
"details": {
"image": {
"imageId": "sha256:f0be64cf656fcbce099300dd24599f40d8c4d5806b50f2c1a152cf23f2902dc1",
"tag": "2024.04.15.20.25.36.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update orca-armory version to 2024.04.15.20.25.36.master

stack.yml
armory/orca-armory:2024.04.15.22.46.06.release-2.32.x
[aa898e512f93921b8786ea790bfe1cb5abc12f2b](https://github.com/armory-io/orca-armory/commit/aa898e512f93921b8786ea790bfe1cb5abc12f2b)
[c64ed7f42d6235a29ae5d850aec0d752da26094e](https://github.com/spinnaker/orca/commit/c64ed7f42d6235a29ae5d850aec0d752da26094e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c64ed7f42d6235a29ae5d850aec0d752da26094e"
},
"details": {
"image": {
"imageId": "sha256:b0d1197d75af4d3a1df4497e27fb5340e2214b11faaa8b68941e23e9cece68c5",
"tag": "2024.04.15.22.46.06.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2024.04.15.22.46.06.release-2.32.x

stack.yml
* **master**
armory/clouddriver-armory:2024.04.15.21.20.33.master
[15ddf1972fa2341ece5e748eef488c4747a74369](https://github.com/armory-io/clouddriver-armory/commit/15ddf1972fa2341ece5e748eef488c4747a74369)
[90495edd27a415175fa9e14c9000ef61ccd8fbfb](https://github.com/spinnaker/clouddriver/commit/90495edd27a415175fa9e14c9000ef61ccd8fbfb)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "90495edd27a415175fa9e14c9000ef61ccd8fbfb"
},
"details": {
"image": {
"imageId": "sha256:a0dafec05e9379fe76088a20b35659e0a49100ea80e021fcc5c13d37a88b5cc5",
"tag": "2024.04.15.21.20.33.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.04.15.21.20.33.master

stack.yml
* **master**
armory/deck-armory:2024.04.16.21.12.53.master
[539612d8c54f8fa226a0127be3a43dcb121f545d](https://github.com/armory-io/deck-armory/commit/539612d8c54f8fa226a0127be3a43dcb121f545d)
[420c291dab26a813dce7498c10a18010a05db1c7](https://github.com/spinnaker/deck/commit/420c291dab26a813dce7498c10a18010a05db1c7)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "420c291dab26a813dce7498c10a18010a05db1c7"
},
"details": {
"image": {
"imageId": "sha256:8a52df1ae9b54111f804825da9e2bbc4e598549059c7d24e5eb40a5a2ab6d6dd",
"tag": "2024.04.16.21.12.53.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update deck-armory version to 2024.04.16.21.12.53.master

stack.yml
* **master**
armory/orca-armory:2024.04.16.22.51.13.master
[67b0e2cef94525dd7943b97a629c97dee6e2309d](https://github.com/armory-io/orca-armory/commit/67b0e2cef94525dd7943b97a629c97dee6e2309d)
[90a383264fd3fdba7f6a0f487366cee9e744bc73](https://github.com/spinnaker/orca/commit/90a383264fd3fdba7f6a0f487366cee9e744bc73)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "90a383264fd3fdba7f6a0f487366cee9e744bc73"
},
"details": {
"image": {
"imageId": "sha256:af53783ab7102901a7ebf35a9eb23515c7e65a600f22e611eddc0649e99a3363",
"tag": "2024.04.16.22.51.13.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update orca-armory version to 2024.04.16.22.51.13.master

stack.yml
armory/deck-armory:2024.04.16.23.48.23.release-2.32.x
[0877ee7c3d723de92b0ea626fa8d1f8bdc0724d5](https://github.com/armory-io/deck-armory/commit/0877ee7c3d723de92b0ea626fa8d1f8bdc0724d5)
[f100273c1e74b9a8654701378e22c9f5da648ad3](https://github.com/spinnaker/deck/commit/f100273c1e74b9a8654701378e22c9f5da648ad3)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f100273c1e74b9a8654701378e22c9f5da648ad3"
},
"details": {
"image": {
"imageId": "sha256:2e8db69103acee8bcb0c715d610a1bd2a56a1db94da390ccfd175de476ba893e",
"tag": "2024.04.16.23.48.23.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2024.04.16.23.48.23.release-2.32.x

stack.yml
* **master**
armory/clouddriver-armory:2024.04.17.00.56.35.master
[f45abd91335c0deb1079e5345e84f7b25aac416d](https://github.com/armory-io/clouddriver-armory/commit/f45abd91335c0deb1079e5345e84f7b25aac416d)
[4d786f788b0128866d223fe4ee754a9f4e658aff](https://github.com/spinnaker/clouddriver/commit/4d786f788b0128866d223fe4ee754a9f4e658aff)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4d786f788b0128866d223fe4ee754a9f4e658aff"
},
"details": {
"image": {
"imageId": "sha256:4dcfbc499bb49e78a56c0b0945b9e0dd7436d9f4cc043df5776128240e08c023",
"tag": "2024.04.17.00.56.35.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.04.17.00.56.35.master

stack.yml
* **master**
armory/front50-armory:2024.04.16.22.51.44.master
[8222f293d0a58de75778ca9fc3617c404d9cc0c3](https://github.com/armory-io/front50-armory/commit/8222f293d0a58de75778ca9fc3617c404d9cc0c3)
[035a626c08bf7926960dd91b7228d5019190d276](https://github.com/spinnaker/front50/commit/035a626c08bf7926960dd91b7228d5019190d276)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "035a626c08bf7926960dd91b7228d5019190d276"
},
"details": {
"image": {
"imageId": "sha256:494015293f5c1230d5b97810cec8338d0c977b3050790a534d6a2d38fa5fb840",
"tag": "2024.04.16.22.51.44.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update front50-armory version to 2024.04.16.22.51.44.master

stack.yml
* **master**
armory/echo-armory:2024.04.16.22.53.22.master
[121bbc6e4778664c696686c58aac981bc86b3f5f](https://github.com/armory-io/echo-armory/commit/121bbc6e4778664c696686c58aac981bc86b3f5f)
[faad6555cd3d65a9dccd32dd110aead79a8f3751](https://github.com/spinnaker/echo/commit/faad6555cd3d65a9dccd32dd110aead79a8f3751)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "faad6555cd3d65a9dccd32dd110aead79a8f3751"
},
"details": {
"image": {
"imageId": "sha256:bd01d9ba33e58f7a599a526677406ff3436ac2c2ce06dce923bffa114c4b7cc2",
"tag": "2024.04.16.22.53.22.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2024.04.16.22.53.22.master

stack.yml
* **master**
armory/igor-armory:2024.04.16.22.52.10.master
[2038dfa51d93f3708ef7da39b43d8d2dc8b0028b](https://github.com/armory-io/igor-armory/commit/2038dfa51d93f3708ef7da39b43d8d2dc8b0028b)
[0dd07621d0004a91ba012060366c297fd8da8817](https://github.com/spinnaker/igor/commit/0dd07621d0004a91ba012060366c297fd8da8817)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0dd07621d0004a91ba012060366c297fd8da8817"
},
"details": {
"image": {
"imageId": "sha256:c4d4bb2a01e13ce65d1ba66b512c4cf1b0d1775bdb5850bf07ec4f93e6a6ea37",
"tag": "2024.04.16.22.52.10.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update igor-armory version to 2024.04.16.22.52.10.master

stack.yml
* **master**
armory/clouddriver-armory:2024.04.17.22.44.50.master
[bcd305eef3037f066c001af8dc9e09442dae86d8](https://github.com/armory-io/clouddriver-armory/commit/bcd305eef3037f066c001af8dc9e09442dae86d8)
[d471a2a2e085603c8f0ac99a9babf12b509c3b46](https://github.com/spinnaker/clouddriver/commit/d471a2a2e085603c8f0ac99a9babf12b509c3b46)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d471a2a2e085603c8f0ac99a9babf12b509c3b46"
},
"details": {
"image": {
"imageId": "sha256:831d0c95225d97324b25dc10763c2e1161c0668d0c96e0d7a7363c2fc76f80dd",
"tag": "2024.04.17.22.44.50.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.04.17.22.44.50.master

stack.yml
* **master**
armory/echo-armory:2024.04.17.17.39.15.master
[d12f4822b5f99fdab2d151c5bdc351f609ce1f5a](https://github.com/armory-io/echo-armory/commit/d12f4822b5f99fdab2d151c5bdc351f609ce1f5a)
[73925aaf37b86ae94c42a160149309e1c6f2d69e](https://github.com/spinnaker/echo/commit/73925aaf37b86ae94c42a160149309e1c6f2d69e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "73925aaf37b86ae94c42a160149309e1c6f2d69e"
},
"details": {
"image": {
"imageId": "sha256:a32ba1dcc8a962fe3f867ce01903ef19a2054dde978851c58310cd6e34693111",
"tag": "2024.04.17.17.39.15.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2024.04.17.17.39.15.master

stack.yml
* **master**
armory/orca-armory:2024.04.17.17.39.41.master
[1abf11775472408b2fac979d5f89f0ef5eb3809f](https://github.com/armory-io/orca-armory/commit/1abf11775472408b2fac979d5f89f0ef5eb3809f)
[90a383264fd3fdba7f6a0f487366cee9e744bc73](https://github.com/spinnaker/orca/commit/90a383264fd3fdba7f6a0f487366cee9e744bc73)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "90a383264fd3fdba7f6a0f487366cee9e744bc73"
},
"details": {
"image": {
"imageId": "sha256:3f0c46635c89fb16af780b6f855b369d580596449150b79b73cc67891df6cd26",
"tag": "2024.04.17.17.39.41.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update orca-armory version to 2024.04.17.17.39.41.master

stack.yml
* **master**
armory/orca-armory:2024.04.18.16.39.37.master
[24f2b63546a5b03d2b7ec8eb14185476710d1f61](https://github.com/armory-io/orca-armory/commit/24f2b63546a5b03d2b7ec8eb14185476710d1f61)
[83aa47f31f880192ee6ed69c65f262df2e62263a](https://github.com/spinnaker/orca/commit/83aa47f31f880192ee6ed69c65f262df2e62263a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "83aa47f31f880192ee6ed69c65f262df2e62263a"
},
"details": {
"image": {
"imageId": "sha256:d0c6f2aad63f00d8e63fdead9a93734003eb3c4a5b810e95d83756f3e96a9f17",
"tag": "2024.04.18.16.39.37.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update orca-armory version to 2024.04.18.16.39.37.master

stack.yml
* **master**
armory/rosco-armory:2024.04.18.17.06.50.master
[a0a9f67fa7186c3c02b9f66724e7f9eeb83bee02](https://github.com/armory-io/rosco-armory/commit/a0a9f67fa7186c3c02b9f66724e7f9eeb83bee02)
[35d07359b372e8acf212b500518e77cf43ae840c](https://github.com/spinnaker/rosco/commit/35d07359b372e8acf212b500518e77cf43ae840c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "35d07359b372e8acf212b500518e77cf43ae840c"
},
"details": {
"image": {
"imageId": "sha256:300a1f167825cc992256e6519d9c00578d75d81ae982097c88474a513607edfd",
"tag": "2024.04.18.17.06.50.master"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.04.18.17.06.50.master

stack.yml
* **master**
armory/front50-armory:2024.04.19.02.53.12.master
[20bf9f59bcb4e45b35e4b0157f029726efc872e5](https://github.com/armory-io/front50-armory/commit/20bf9f59bcb4e45b35e4b0157f029726efc872e5)
[f413f5c9e4882e3ba62d9314ab82ee4f727e1ed7](https://github.com/spinnaker/front50/commit/f413f5c9e4882e3ba62d9314ab82ee4f727e1ed7)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f413f5c9e4882e3ba62d9314ab82ee4f727e1ed7"
},
"details": {
"image": {
"imageId": "sha256:11e5aec5b0929d40bfbe06f929e0e7807cee6c78e23a7844ded3a75ae9ae1fcf",
"tag": "2024.04.19.02.53.12.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update front50-armory version to 2024.04.19.02.53.12.master

stack.yml
* **master**
armory/clouddriver-armory:2024.04.19.15.19.47.master
[a15d2a1e2f5f65ada7156b124f59f65dd66795e9](https://github.com/armory-io/clouddriver-armory/commit/a15d2a1e2f5f65ada7156b124f59f65dd66795e9)
[db8897c38b5e676574cd6101df6d84514aa84a5d](https://github.com/spinnaker/clouddriver/commit/db8897c38b5e676574cd6101df6d84514aa84a5d)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "db8897c38b5e676574cd6101df6d84514aa84a5d"
},
"details": {
"image": {
"imageId": "sha256:72668a7a710501b278a7f18ae3ecb806aa419e2c8e2d6194d28ed436331b8c20",
"tag": "2024.04.19.15.19.47.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.04.19.15.19.47.master

stack.yml
* **master**
armory/deck-armory:2024.04.25.08.32.11.master
[3ef57cbf57aa81a7465fb4c4dda3d97a7c5ad312](https://github.com/armory-io/deck-armory/commit/3ef57cbf57aa81a7465fb4c4dda3d97a7c5ad312)
[4e1635d6026c6fbcb5912de1859c45038fd1258a](https://github.com/spinnaker/deck/commit/4e1635d6026c6fbcb5912de1859c45038fd1258a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4e1635d6026c6fbcb5912de1859c45038fd1258a"
},
"details": {
"image": {
"imageId": "sha256:e59a52fd785784077e44bb90924abcb8f1bdc4b190798887e4b8888a05deb00c",
"tag": "2024.04.25.08.32.11.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update deck-armory version to 2024.04.25.08.32.11.master

stack.yml
* **master**
armory/orca-armory:2024.04.24.18.59.56.master
[3ed9db117bccc2e179a6bdd1bfc55f75304d2873](https://github.com/armory-io/orca-armory/commit/3ed9db117bccc2e179a6bdd1bfc55f75304d2873)
[d2f50242637207491ba9fdcc40eaf02c3255c447](https://github.com/spinnaker/orca/commit/d2f50242637207491ba9fdcc40eaf02c3255c447)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d2f50242637207491ba9fdcc40eaf02c3255c447"
},
"details": {
"image": {
"imageId": "sha256:242e72b86ddde82f81e0ceb5e5899de87f92a55bdc57399474ebdbb15efbd51e",
"tag": "2024.04.24.18.59.56.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update orca-armory version to 2024.04.24.18.59.56.master

stack.yml
armory/deck-armory:2024.04.25.14.25.43.release-2.32.x
[13f331421b292db61f14392e6932880aa5c49f25](https://github.com/armory-io/deck-armory/commit/13f331421b292db61f14392e6932880aa5c49f25)
[abd95bdbf0d9817c2c13880051cd73339c22ae58](https://github.com/spinnaker/deck/commit/abd95bdbf0d9817c2c13880051cd73339c22ae58)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "abd95bdbf0d9817c2c13880051cd73339c22ae58"
},
"details": {
"image": {
"imageId": "sha256:fc2ea7910b880e9c2d746d74400bfb562e9375d3d2a66e0b9188103f326f4065",
"tag": "2024.04.25.14.25.43.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2024.04.25.14.25.43.release-2.32.x

stack.yml
* **master**
armory/deck-armory:2024.04.25.14.06.43.master
[b5e2d5071c11099d79552615620b25cfc48ef959](https://github.com/armory-io/deck-armory/commit/b5e2d5071c11099d79552615620b25cfc48ef959)
[93bab656555fabd539e186587a40dd8a0358dbd9](https://github.com/spinnaker/deck/commit/93bab656555fabd539e186587a40dd8a0358dbd9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "93bab656555fabd539e186587a40dd8a0358dbd9"
},
"details": {
"image": {
"imageId": "sha256:474a90ef4f3d051c0b4fa41c75ecc7f34923a87edeb9f1b5c3feb8c94258802f",
"tag": "2024.04.25.14.06.43.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update deck-armory version to 2024.04.25.14.06.43.master

stack.yml
* **master**
armory/orca-armory:2024.04.25.14.07.34.master
[fcdae100792bd0b34bdff60cdde00837f9156f09](https://github.com/armory-io/orca-armory/commit/fcdae100792bd0b34bdff60cdde00837f9156f09)
[d2f50242637207491ba9fdcc40eaf02c3255c447](https://github.com/spinnaker/orca/commit/d2f50242637207491ba9fdcc40eaf02c3255c447)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d2f50242637207491ba9fdcc40eaf02c3255c447"
},
"details": {
"image": {
"imageId": "sha256:bd71414321cfabf0c18bddf850bfdf2b6ebb2ae5d796d0518ba28f78bfac6346",
"tag": "2024.04.25.14.07.34.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update orca-armory version to 2024.04.25.14.07.34.master

stack.yml
* **master**
armory/clouddriver-armory:2024.04.27.01.31.37.master
[e5b318ccdd63eb32091bda58685d5cda3d2fbd28](https://github.com/armory-io/clouddriver-armory/commit/e5b318ccdd63eb32091bda58685d5cda3d2fbd28)
[734f10d67b1cb082d48aa0ebd147399874f2fc32](https://github.com/spinnaker/clouddriver/commit/734f10d67b1cb082d48aa0ebd147399874f2fc32)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "734f10d67b1cb082d48aa0ebd147399874f2fc32"
},
"details": {
"image": {
"imageId": "sha256:f4d50d5486722c98c5cc27ba16ad2077300aa0fed400b129fdbfe221252903d7",
"tag": "2024.04.27.01.31.37.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.04.27.01.31.37.master

stack.yml
* **master**
armory/fiat-armory:2024.04.27.01.58.42.master
[404c358ad17997e3e866266d5b0713e35e234c30](https://github.com/armory-io/fiat-armory/commit/404c358ad17997e3e866266d5b0713e35e234c30)
[5c90023372ef8aca64adf4d0dbb614e350ac8f29](https://github.com/spinnaker/fiat/commit/5c90023372ef8aca64adf4d0dbb614e350ac8f29)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5c90023372ef8aca64adf4d0dbb614e350ac8f29"
},
"details": {
"image": {
"imageId": "sha256:4eb799f187ffa8ea31de43cf871b108548575140e69c6007f7e25373893d074e",
"tag": "2024.04.27.01.58.42.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update fiat-armory version to 2024.04.27.01.58.42.master

stack.yml
* **master**
armory/orca-armory:2024.04.29.16.46.45.master
[ee6bff6721570e1d418a0a2d95270dcc304c6230](https://github.com/armory-io/orca-armory/commit/ee6bff6721570e1d418a0a2d95270dcc304c6230)
[a1b32d7398eb9b1ff610d7f3afd980b51f6cf7b1](https://github.com/spinnaker/orca/commit/a1b32d7398eb9b1ff610d7f3afd980b51f6cf7b1)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a1b32d7398eb9b1ff610d7f3afd980b51f6cf7b1"
},
"details": {
"image": {
"imageId": "sha256:8e4ede1d901b01a5f0aa31e19666abaa1eb63da395b724a2cec26e716a3c1504",
"tag": "2024.04.29.16.46.45.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update orca-armory version to 2024.04.29.16.46.45.master

stack.yml
* **master**
armory/clouddriver-armory:2024.04.28.04.14.06.master
[4c4c312005378af5b8e6731fe1ce3554f6764fc9](https://github.com/armory-io/clouddriver-armory/commit/4c4c312005378af5b8e6731fe1ce3554f6764fc9)
[7eeef26d50f82c6363525f092d516a3ebc8e501a](https://github.com/spinnaker/clouddriver/commit/7eeef26d50f82c6363525f092d516a3ebc8e501a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7eeef26d50f82c6363525f092d516a3ebc8e501a"
},
"details": {
"image": {
"imageId": "sha256:29e4812cbb6a72171530ef06ccbcb8f6d67689b6d5c891ca0ce95c8d526ea0ef",
"tag": "2024.04.28.04.14.06.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.04.28.04.14.06.master

stack.yml
* **master**
armory/igor-armory:2024.04.27.02.43.09.master
[4915086d5abdddd5e505c6f53179736f3d0d577f](https://github.com/armory-io/igor-armory/commit/4915086d5abdddd5e505c6f53179736f3d0d577f)
[da14a3aee2c49405ffc58f021bbf755b7519d4eb](https://github.com/spinnaker/igor/commit/da14a3aee2c49405ffc58f021bbf755b7519d4eb)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "da14a3aee2c49405ffc58f021bbf755b7519d4eb"
},
"details": {
"image": {
"imageId": "sha256:188e49a7453d5e2536542141073505a7887436e9faf72a98b548593339e506c9",
"tag": "2024.04.27.02.43.09.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update igor-armory version to 2024.04.27.02.43.09.master

stack.yml
* **master**
armory/orca-armory:2024.04.29.19.34.54.master
[e26dc4f2c78388ccf9b0e9c7683a1ce2a6e92db3](https://github.com/armory-io/orca-armory/commit/e26dc4f2c78388ccf9b0e9c7683a1ce2a6e92db3)
[bc76db00f3996ce21cde44b0c46af6cb0cae77fb](https://github.com/spinnaker/orca/commit/bc76db00f3996ce21cde44b0c46af6cb0cae77fb)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "bc76db00f3996ce21cde44b0c46af6cb0cae77fb"
},
"details": {
"image": {
"imageId": "sha256:dec86f1cf0d219ea7d04ec2922e42a34e41126736f3140ef20f3dd9e953b7d5d",
"tag": "2024.04.29.19.34.54.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update orca-armory version to 2024.04.29.19.34.54.master

stack.yml
* **master**
armory/clouddriver-armory:2024.04.29.20.39.40.master
[dd072d5361f9e0158adde96665af686fcbb49f03](https://github.com/armory-io/clouddriver-armory/commit/dd072d5361f9e0158adde96665af686fcbb49f03)
[291a87258ebbac1961db6a3201bf164702948b8f](https://github.com/spinnaker/clouddriver/commit/291a87258ebbac1961db6a3201bf164702948b8f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "291a87258ebbac1961db6a3201bf164702948b8f"
},
"details": {
"image": {
"imageId": "sha256:01dbb31f0c51ea3b01c36ac55d6789793a90d37db847ecd9b1fdf030200e2588",
"tag": "2024.04.29.20.39.40.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.04.29.20.39.40.master

stack.yml
* **master**
armory/front50-armory:2024.04.29.15.57.45.master
[228c933975ef6e263914eaee3de183afc44c8e3c](https://github.com/armory-io/front50-armory/commit/228c933975ef6e263914eaee3de183afc44c8e3c)
[55ad3aa7ebb70acf00e3e5b8ec6b37f25b2191ab](https://github.com/spinnaker/front50/commit/55ad3aa7ebb70acf00e3e5b8ec6b37f25b2191ab)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "55ad3aa7ebb70acf00e3e5b8ec6b37f25b2191ab"
},
"details": {
"image": {
"imageId": "sha256:a16b64064140d940a4ea8f1b78ea9445c481347108ed844dfb9dfa24d818fe50",
"tag": "2024.04.29.15.57.45.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update front50-armory version to 2024.04.29.15.57.45.master

stack.yml
armory/orca-armory:2024.04.30.15.43.48.release-2.34.x
[b3bb72e7a8f893ad42d7a68a75af31058437aeb6](https://github.com/armory-io/orca-armory/commit/b3bb72e7a8f893ad42d7a68a75af31058437aeb6)
[bc76db00f3996ce21cde44b0c46af6cb0cae77fb](https://github.com/spinnaker/orca/commit/bc76db00f3996ce21cde44b0c46af6cb0cae77fb)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "bc76db00f3996ce21cde44b0c46af6cb0cae77fb"
},
"details": {
"image": {
"imageId": "sha256:0b2e7be8af91319782ef5bf9adfbce2c349d4f849b427e9a91a58de61f1a47f6",
"tag": "2024.04.30.15.43.48.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2024.04.30.15.43.48.release-2.34.x

stack.yml
armory/dinghy:2024.02.13.13.25.37.release-2.34.x
[947343831b2325deda8421ed9a55564fcb86b7b6](https://github.com/armory-io/dinghy/commit/947343831b2325deda8421ed9a55564fcb86b7b6)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:11d4ee7ad5c1d9356968d236ca7e8733e733aade05615400467381a725214894",
"tag": "2024.02.13.13.25.37.release-2.34.x"
},
"vcs": {
"repo": {
},
"sha": "947343831b2325deda8421ed9a55564fcb86b7b6"
}
},
},
"details": {
"image": {
"imageId": "sha256:11d4ee7ad5c1d9356968d236ca7e8733e733aade05615400467381a725214894", …
```
=> chore(cd): update dinghy version to 2024.02.13.13.25.37.release-2.34.x

stack.yml
armory/kayenta-armory:2024.04.01.18.40.49.release-2.34.x
[8b0ba90eee2960723d9a8a56f28bac95eccf657c](https://github.com/armory-io/kayenta-armory/commit/8b0ba90eee2960723d9a8a56f28bac95eccf657c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:3ea398072589ffe905056cf3513b69bcc190ca2c39f1f9c900559488392d2c9c",
"tag": "2024.04.01.18.40.49.release-2.34.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update kayenta-armory version to 2024.04.01.18.40.49.release-2.34.x

stack.yml
armory/igor-armory:2024.04.30.15.42.25.release-2.34.x
[1de5256b1ed6e71a9523921a3ff5db1f1d7e006b](https://github.com/armory-io/igor-armory/commit/1de5256b1ed6e71a9523921a3ff5db1f1d7e006b)
[da14a3aee2c49405ffc58f021bbf755b7519d4eb](https://github.com/spinnaker/igor/commit/da14a3aee2c49405ffc58f021bbf755b7519d4eb)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "da14a3aee2c49405ffc58f021bbf755b7519d4eb"
},
"details": {
"image": {
"imageId": "sha256:e0f5e298e3224588c4d89c1197e9ad143dcb05a2f783893b05911e39bc2def89",
"tag": "2024.04.30.15.42.25.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update igor-armory version to 2024.04.30.15.42.25.release-2.34.x

stack.yml
armory/deck-armory:2024.04.25.14.06.43.release-2.34.x
[b5e2d5071c11099d79552615620b25cfc48ef959](https://github.com/armory-io/deck-armory/commit/b5e2d5071c11099d79552615620b25cfc48ef959)
[93bab656555fabd539e186587a40dd8a0358dbd9](https://github.com/spinnaker/deck/commit/93bab656555fabd539e186587a40dd8a0358dbd9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "93bab656555fabd539e186587a40dd8a0358dbd9"
},
"details": {
"image": {
"imageId": "sha256:1e999eb0633f97885a3d945411d3f0c04361bc7d5b5f1dbf7a7607f3b263a3d6",
"tag": "2024.04.25.14.06.43.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2024.04.25.14.06.43.release-2.34.x

stack.yml
armory/clouddriver-armory:2024.04.30.15.42.31.release-2.34.x
[dff329cb4459102ce710ac6a0c82799996be68d4](https://github.com/armory-io/clouddriver-armory/commit/dff329cb4459102ce710ac6a0c82799996be68d4)
[291a87258ebbac1961db6a3201bf164702948b8f](https://github.com/spinnaker/clouddriver/commit/291a87258ebbac1961db6a3201bf164702948b8f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "291a87258ebbac1961db6a3201bf164702948b8f"
},
"details": {
"image": {
"imageId": "sha256:1a068ded46ec3c49d99aa82a063a0c060af170b2b9b2acf9f78a6ace57aa6e2c",
"tag": "2024.04.30.15.42.31.release-2.34.x"
},
"vcs": …
```
=> chore(cd): update clouddriver-armory version to 2024.04.30.15.42.31.release-2.34.x

stack.yml
armory/front50-armory:2024.04.30.15.42.18.release-2.34.x
[168acfe5a762eb7923a3b8e162d61f44015e5132](https://github.com/armory-io/front50-armory/commit/168acfe5a762eb7923a3b8e162d61f44015e5132)
[55ad3aa7ebb70acf00e3e5b8ec6b37f25b2191ab](https://github.com/spinnaker/front50/commit/55ad3aa7ebb70acf00e3e5b8ec6b37f25b2191ab)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "55ad3aa7ebb70acf00e3e5b8ec6b37f25b2191ab"
},
"details": {
"image": {
"imageId": "sha256:87777c24543f119a5b4f2242cb4824112973902b97ba206524e8f250292871e5",
"tag": "2024.04.30.15.42.18.release-2.34.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update front50-armory version to 2024.04.30.15.42.18.release-2.34.x

stack.yml
armory/echo-armory:2024.04.30.15.43.00.release-2.34.x
[b878dc4324c2425da5e1ff0db457ed5fe06e31b0](https://github.com/armory-io/echo-armory/commit/b878dc4324c2425da5e1ff0db457ed5fe06e31b0)
[78c7d3e6cf1081fa358b38a735b1de04705e3d3f](https://github.com/spinnaker/echo/commit/78c7d3e6cf1081fa358b38a735b1de04705e3d3f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "78c7d3e6cf1081fa358b38a735b1de04705e3d3f"
},
"details": {
"image": {
"imageId": "sha256:8d0a8fcb188cd0291ddb02fc8e4f78a96122de7c75fadec3572552cc29a32841",
"tag": "2024.04.30.15.43.00.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2024.04.30.15.43.00.release-2.34.x

stack.yml
armory/rosco-armory:2024.04.30.15.44.24.release-2.34.x
[a1d6e37b46b32193af9be79ba2a9998f60308dd3](https://github.com/armory-io/rosco-armory/commit/a1d6e37b46b32193af9be79ba2a9998f60308dd3)
[35d07359b372e8acf212b500518e77cf43ae840c](https://github.com/spinnaker/rosco/commit/35d07359b372e8acf212b500518e77cf43ae840c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "35d07359b372e8acf212b500518e77cf43ae840c"
},
"details": {
"image": {
"imageId": "sha256:83bd6c958ef87ef730fdc9fef0e7a6b64b95a19cb37da1b82fa83f963d40ccc0",
"tag": "2024.04.30.15.44.24.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.04.30.15.44.24.release-2.34.x

stack.yml
* **master**
armory/clouddriver-armory:2024.05.01.13.03.25.master
[b53a11fee42377c188e0c0e266a575f15e86808d](https://github.com/armory-io/clouddriver-armory/commit/b53a11fee42377c188e0c0e266a575f15e86808d)
[28599eb1ecc935cbabb65b32c2dc0e9ffde13a12](https://github.com/spinnaker/clouddriver/commit/28599eb1ecc935cbabb65b32c2dc0e9ffde13a12)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "28599eb1ecc935cbabb65b32c2dc0e9ffde13a12"
},
"details": {
"image": {
"imageId": "sha256:4d725a9309433b114b2b8916d3ca4f1d5aab763d4b51a81ca57583e07e2b427d",
"tag": "2024.05.01.13.03.25.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.05.01.13.03.25.master

stack.yml
armory/gate-armory:2024.04.30.15.46.50.release-2.34.x
[33f4fa2608142d054e3f7fba4a6a07e63eb1d00c](https://github.com/armory-io/gate-armory/commit/33f4fa2608142d054e3f7fba4a6a07e63eb1d00c)
[23806cc6cddf6213d107b19e5ebfad12ceb751c5](https://github.com/spinnaker/gate/commit/23806cc6cddf6213d107b19e5ebfad12ceb751c5)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "23806cc6cddf6213d107b19e5ebfad12ceb751c5"
},
"details": {
"image": {
"imageId": "sha256:1330915b7e9b4bfff4e6cae6ff83b9214f7f0dfed8eae47ff4ee79f2ed234e1b",
"tag": "2024.04.30.15.46.50.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update gate-armory version to 2024.04.30.15.46.50.release-2.34.x

stack.yml
armory/fiat-armory:2024.04.30.15.43.57.release-2.34.x
[38f716da21c92b0e64d769e41b4b40e929d356ae](https://github.com/armory-io/fiat-armory/commit/38f716da21c92b0e64d769e41b4b40e929d356ae)
[5c90023372ef8aca64adf4d0dbb614e350ac8f29](https://github.com/spinnaker/fiat/commit/5c90023372ef8aca64adf4d0dbb614e350ac8f29)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5c90023372ef8aca64adf4d0dbb614e350ac8f29"
},
"details": {
"image": {
"imageId": "sha256:cbff7fd2eef251b9c9a7c1a14b9bb938d0bdd710ba6320f0947f2b8a88ce98db",
"tag": "2024.04.30.15.43.57.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update fiat-armory version to 2024.04.30.15.43.57.release-2.34.x

stack.yml
* **master**
armory/orca-armory:2024.05.01.16.15.03.master
[5013368f9cc980b8af7f63230a33bacbd1614412](https://github.com/armory-io/orca-armory/commit/5013368f9cc980b8af7f63230a33bacbd1614412)
[88114eb396d2b9454e7e8d472417b0e94b2c403b](https://github.com/spinnaker/orca/commit/88114eb396d2b9454e7e8d472417b0e94b2c403b)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "88114eb396d2b9454e7e8d472417b0e94b2c403b"
},
"details": {
"image": {
"imageId": "sha256:0f961acb9e06630a49a777df1060d90b0fb9cefdeeb9f06d77aba34e4b80c36c",
"tag": "2024.05.01.16.15.03.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update orca-armory version to 2024.05.01.16.15.03.master

stack.yml
* **master**
armory/clouddriver-armory:2024.05.02.04.37.25.master
[46288753c3bdceb092fe2659b1d969c9dcd75f68](https://github.com/armory-io/clouddriver-armory/commit/46288753c3bdceb092fe2659b1d969c9dcd75f68)
[9ea2224ef03033d99535678a4aa176a3f574574f](https://github.com/spinnaker/clouddriver/commit/9ea2224ef03033d99535678a4aa176a3f574574f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9ea2224ef03033d99535678a4aa176a3f574574f"
},
"details": {
"image": {
"imageId": "sha256:4da8191d054603ec04939997ed9fbf734eb8a947cfd7e83c5937e154c1b396fb",
"tag": "2024.05.02.04.37.25.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.05.02.04.37.25.master

stack.yml
* **master**
armory/fiat-armory:2024.05.01.21.08.39.master
[f52575e60d91aa351771e1e595c60a626764d5da](https://github.com/armory-io/fiat-armory/commit/f52575e60d91aa351771e1e595c60a626764d5da)
[69fdb4c2076323e1587ee7436833aeb5d6193096](https://github.com/spinnaker/fiat/commit/69fdb4c2076323e1587ee7436833aeb5d6193096)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "69fdb4c2076323e1587ee7436833aeb5d6193096"
},
"details": {
"image": {
"imageId": "sha256:2dca8d6ea52bdc274a7cae5b33d7736aa1d0c994326ea3f590ad28ced77ca474",
"tag": "2024.05.01.21.08.39.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update fiat-armory version to 2024.05.01.21.08.39.master

stack.yml
armory/clouddriver-armory:2024.05.07.00.28.50.release-2.32.x
[7d9e31043c8baa81afb59a2a30aee2235b7e90ab](https://github.com/armory-io/clouddriver-armory/commit/7d9e31043c8baa81afb59a2a30aee2235b7e90ab)
[a3f4a638f2f79fba5a72818a1882f573aa675ad8](https://github.com/spinnaker/clouddriver/commit/a3f4a638f2f79fba5a72818a1882f573aa675ad8)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a3f4a638f2f79fba5a72818a1882f573aa675ad8"
},
"details": {
"image": {
"imageId": "sha256:74fb9d94f6b6a9f546c477456b3100026b3789337839425ed893eff07bf3eaa3",
"tag": "2024.05.07.00.28.50.release-2.32.x"
},
"vcs": …
```
=> chore(cd): update clouddriver-armory version to 2024.05.07.00.28.50.release-2.32.x

stack.yml
* **master**
armory/deck-armory:2024.05.07.08.02.53.master
[c84c7395d8df919adc885f8c2f562bbb35dcf803](https://github.com/armory-io/deck-armory/commit/c84c7395d8df919adc885f8c2f562bbb35dcf803)
[5fa1e96b90c7398338d67ef7a7337ee3628591bd](https://github.com/spinnaker/deck/commit/5fa1e96b90c7398338d67ef7a7337ee3628591bd)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5fa1e96b90c7398338d67ef7a7337ee3628591bd"
},
"details": {
"image": {
"imageId": "sha256:04ca7f17f303b70f11aa76e6be8142eb07ba31bf851ba2fabec428867a7add19",
"tag": "2024.05.07.08.02.53.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update deck-armory version to 2024.05.07.08.02.53.master

stack.yml
* **master**
armory/orca-armory:2024.05.07.02.53.48.master
[8ae99fa6fbbceee4f9a7750e142305071ad0ce4b](https://github.com/armory-io/orca-armory/commit/8ae99fa6fbbceee4f9a7750e142305071ad0ce4b)
[b360ad58820b1021fc982ed7443729e4c5e0d6ee](https://github.com/spinnaker/orca/commit/b360ad58820b1021fc982ed7443729e4c5e0d6ee)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b360ad58820b1021fc982ed7443729e4c5e0d6ee"
},
"details": {
"image": {
"imageId": "sha256:9683c76d88466536ad89a1f68d18a62279e62aef050c51381b084d709ab1e082",
"tag": "2024.05.07.02.53.48.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update orca-armory version to 2024.05.07.02.53.48.master

stack.yml
armory/deck-armory:2024.05.07.17.21.36.release-2.32.x
[ae348ea3facfd841e722a65d9a31d6799cb36004](https://github.com/armory-io/deck-armory/commit/ae348ea3facfd841e722a65d9a31d6799cb36004)
[f24d29283cd3e5be926cdd72f36b7b4a18fb2f32](https://github.com/spinnaker/deck/commit/f24d29283cd3e5be926cdd72f36b7b4a18fb2f32)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f24d29283cd3e5be926cdd72f36b7b4a18fb2f32"
},
"details": {
"image": {
"imageId": "sha256:ee7ff6c5e0229f9bfd7b60aa135b849572316f2b1665bb90e58e5444e9894133",
"tag": "2024.05.07.17.21.36.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2024.05.07.17.21.36.release-2.32.x

stack.yml
armory/clouddriver-armory:2024.05.07.00.27.34.release-2.34.x
[fdc3fba9c430b97322755c9bcf746172a5555caf](https://github.com/armory-io/clouddriver-armory/commit/fdc3fba9c430b97322755c9bcf746172a5555caf)
[20fd2c8998d8bb69f3319ec9ae3f848fbddb9b6f](https://github.com/spinnaker/clouddriver/commit/20fd2c8998d8bb69f3319ec9ae3f848fbddb9b6f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "20fd2c8998d8bb69f3319ec9ae3f848fbddb9b6f"
},
"details": {
"image": {
"imageId": "sha256:a8e43ac2f8971d1031367f917ab77ee0e855edb6121afeb6e96d9e0ccd8df80c",
"tag": "2024.05.07.00.27.34.release-2.34.x"
},
"vcs": …
```
=> chore(cd): update clouddriver-armory version to 2024.05.07.00.27.34.release-2.34.x

stack.yml
armory/orca-armory:2024.05.07.00.30.50.release-2.32.x
[a1d218042cd26832f9fa352051d0a9ba8d2150dd](https://github.com/armory-io/orca-armory/commit/a1d218042cd26832f9fa352051d0a9ba8d2150dd)
[25bb54cb01257ee13c92512ad54ad3b8886cf23c](https://github.com/spinnaker/orca/commit/25bb54cb01257ee13c92512ad54ad3b8886cf23c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "25bb54cb01257ee13c92512ad54ad3b8886cf23c"
},
"details": {
"image": {
"imageId": "sha256:34eb922a3dff992e5fd50d2c30bc154c506c911fd59187907638313292911f6b",
"tag": "2024.05.07.00.30.50.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2024.05.07.00.30.50.release-2.32.x

stack.yml
* **master**
armory/igor-armory:2024.05.08.17.15.08.master
[9cc981e963d7e367cb9651a086acdc6c1cc838bc](https://github.com/armory-io/igor-armory/commit/9cc981e963d7e367cb9651a086acdc6c1cc838bc)
[73354d5654aad569171a74b56116559487418e1a](https://github.com/spinnaker/igor/commit/73354d5654aad569171a74b56116559487418e1a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "73354d5654aad569171a74b56116559487418e1a"
},
"details": {
"image": {
"imageId": "sha256:ced4b642d62e09f4904aa74367dab68c43ee7c565237501300a1cce4fc9d0c62",
"tag": "2024.05.08.17.15.08.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update igor-armory version to 2024.05.08.17.15.08.master

stack.yml
* **master**
armory/orca-armory:2024.05.09.12.02.27.master
[ed758685195b81419450032de82059fcec97fe8b](https://github.com/armory-io/orca-armory/commit/ed758685195b81419450032de82059fcec97fe8b)
[b2dba5935bfdb3674961d97ae776fd8eaa90318f](https://github.com/spinnaker/orca/commit/b2dba5935bfdb3674961d97ae776fd8eaa90318f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b2dba5935bfdb3674961d97ae776fd8eaa90318f"
},
"details": {
"image": {
"imageId": "sha256:0551ac9c37748cad8f6802ae4ab7bf0d57ea165f65290dc29f17547b2f946659",
"tag": "2024.05.09.12.02.27.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update orca-armory version to 2024.05.09.12.02.27.master

stack.yml
armory/deck-armory:2024.05.09.18.28.31.release-2.32.x
[8c772d3699dc50861b32fff120ce567ba4aec776](https://github.com/armory-io/deck-armory/commit/8c772d3699dc50861b32fff120ce567ba4aec776)
[7d8ba66217d880412fab9031d804db916d5ad922](https://github.com/spinnaker/deck/commit/7d8ba66217d880412fab9031d804db916d5ad922)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7d8ba66217d880412fab9031d804db916d5ad922"
},
"details": {
"image": {
"imageId": "sha256:0889deb2a66bc0e111d107cc3875867032dac91dd80a71917861383364635592",
"tag": "2024.05.09.18.28.31.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2024.05.09.18.28.31.release-2.32.x

stack.yml
armory/deck-armory:2024.05.09.18.36.20.release-2.34.x
[34e6ed3392d12fa91f9818d07b4c5b8e9e186130](https://github.com/armory-io/deck-armory/commit/34e6ed3392d12fa91f9818d07b4c5b8e9e186130)
[e322eb530493934177f08d5335404a870c1e761a](https://github.com/spinnaker/deck/commit/e322eb530493934177f08d5335404a870c1e761a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e322eb530493934177f08d5335404a870c1e761a"
},
"details": {
"image": {
"imageId": "sha256:315c054f65233c0b22c59f8710ba37d235da34cbf1f2ec863ac2206d65defdd4",
"tag": "2024.05.09.18.36.20.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2024.05.09.18.36.20.release-2.34.x

stack.yml
armory/orca-armory:2024.05.09.18.13.00.release-2.32.x
[ddbe104b0a3e32406c3bac38ea2b8c0c04605825](https://github.com/armory-io/orca-armory/commit/ddbe104b0a3e32406c3bac38ea2b8c0c04605825)
[50e4457550de95615c0703000b0d788f04186c53](https://github.com/spinnaker/orca/commit/50e4457550de95615c0703000b0d788f04186c53)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "50e4457550de95615c0703000b0d788f04186c53"
},
"details": {
"image": {
"imageId": "sha256:885fdbd7d2f43baf5466cc2f8ea19c2ad5ab1bacc38a50ad771cd25d7e75f8f3",
"tag": "2024.05.09.18.13.00.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2024.05.09.18.13.00.release-2.32.x

stack.yml
armory/deck-armory:2024.05.10.15.58.52.release-2.32.x
[8020acb5708bce7dc3b334d4cbedeebb6e0fdfc7](https://github.com/armory-io/deck-armory/commit/8020acb5708bce7dc3b334d4cbedeebb6e0fdfc7)
[988e42cf1f229561341ed0b9fe3c2ff1ac9915e3](https://github.com/spinnaker/deck/commit/988e42cf1f229561341ed0b9fe3c2ff1ac9915e3)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "988e42cf1f229561341ed0b9fe3c2ff1ac9915e3"
},
"details": {
"image": {
"imageId": "sha256:f256afe39f121450f56d720e6f54aca059dfa99eb2e40bac5251da2562e1a8a1",
"tag": "2024.05.10.15.58.52.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2024.05.10.15.58.52.release-2.32.x

stack.yml
armory/deck-armory:2024.05.10.17.04.36.release-2.34.x
[6608d0e2ce96e8955676e3cadf39af23e9b3be06](https://github.com/armory-io/deck-armory/commit/6608d0e2ce96e8955676e3cadf39af23e9b3be06)
[7924b110567e810e82bc11cb8216f1e5f468f383](https://github.com/spinnaker/deck/commit/7924b110567e810e82bc11cb8216f1e5f468f383)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7924b110567e810e82bc11cb8216f1e5f468f383"
},
"details": {
"image": {
"imageId": "sha256:7c1163d6d267b77bb37bbf5f99888041455bcb31f3136891b18588d40042bfbc",
"tag": "2024.05.10.17.04.36.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2024.05.10.17.04.36.release-2.34.x

stack.yml
* **master**
armory/orca-armory:2024.05.10.18.49.03.master
[ad6acffb04df4bd9dfd7c2e17c00c0efe43ff9eb](https://github.com/armory-io/orca-armory/commit/ad6acffb04df4bd9dfd7c2e17c00c0efe43ff9eb)
[b1285942f2a43491a055f16b68b05ddc786f9b8d](https://github.com/spinnaker/orca/commit/b1285942f2a43491a055f16b68b05ddc786f9b8d)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b1285942f2a43491a055f16b68b05ddc786f9b8d"
},
"details": {
"image": {
"imageId": "sha256:613cc5b5bf2f26eaf46f789023923d60daa6f1b9447ef8c07c43d69337e4a91d",
"tag": "2024.05.10.18.49.03.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update orca-armory version to 2024.05.10.18.49.03.master

stack.yml
* **master**
armory/deck-armory:2024.05.10.15.07.11.master
[4d2ffe5dc36c85e177dd2cb29da1c4a70d2250f2](https://github.com/armory-io/deck-armory/commit/4d2ffe5dc36c85e177dd2cb29da1c4a70d2250f2)
[9237f7890e5f02f5369bc91984de98b18591ef9e](https://github.com/spinnaker/deck/commit/9237f7890e5f02f5369bc91984de98b18591ef9e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9237f7890e5f02f5369bc91984de98b18591ef9e"
},
"details": {
"image": {
"imageId": "sha256:dc89905047b1f1b20bbe6a7b6cbfe96a02015e31e2461efbc7deaec4d2f5a086",
"tag": "2024.05.10.15.07.11.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update deck-armory version to 2024.05.10.15.07.11.master

stack.yml
* **master**
armory/front50-armory:2024.05.10.18.40.34.master
[44741da3e83c9bbd72f97b67c1454bc12dc94de8](https://github.com/armory-io/front50-armory/commit/44741da3e83c9bbd72f97b67c1454bc12dc94de8)
[a7081ef38e76a557c56879849ce092dc6f58d5f9](https://github.com/spinnaker/front50/commit/a7081ef38e76a557c56879849ce092dc6f58d5f9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a7081ef38e76a557c56879849ce092dc6f58d5f9"
},
"details": {
"image": {
"imageId": "sha256:0e59593b88b5c05b40825460d1c028d0749b2f7cca2e54c730db2a204122fc18",
"tag": "2024.05.10.18.40.34.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update front50-armory version to 2024.05.10.18.40.34.master

stack.yml
* **master**
armory/rosco-armory:2024.05.10.18.42.22.master
[ad0603de8d776a3e5069e0ad58db023b87dac2fd](https://github.com/armory-io/rosco-armory/commit/ad0603de8d776a3e5069e0ad58db023b87dac2fd)
[1b00ab83a597f28f4446f070675b7343bb4dd83f](https://github.com/spinnaker/rosco/commit/1b00ab83a597f28f4446f070675b7343bb4dd83f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1b00ab83a597f28f4446f070675b7343bb4dd83f"
},
"details": {
"image": {
"imageId": "sha256:32e24ba2a36c714d08c3e8fa85c2dc58e8f69770d050b227f100ae9eee190457",
"tag": "2024.05.10.18.42.22.master"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.05.10.18.42.22.master

stack.yml
* **master**
armory/echo-armory:2024.05.10.18.43.06.master
[7362b878d1369fcff73983378dd025745fd6633f](https://github.com/armory-io/echo-armory/commit/7362b878d1369fcff73983378dd025745fd6633f)
[8d6488ed8a3a86165c3cdafa747c7461a357e326](https://github.com/spinnaker/echo/commit/8d6488ed8a3a86165c3cdafa747c7461a357e326)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "8d6488ed8a3a86165c3cdafa747c7461a357e326"
},
"details": {
"image": {
"imageId": "sha256:4b97d4d008e47cf264e511e0570958ec5fd1a1b001384e4da38725a4a096b7d0",
"tag": "2024.05.10.18.43.06.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2024.05.10.18.43.06.master

stack.yml
* **master**
armory/clouddriver-armory:2024.05.10.19.22.13.master
[a1e7508940a029f5fa14f72927eae6e377b0ac56](https://github.com/armory-io/clouddriver-armory/commit/a1e7508940a029f5fa14f72927eae6e377b0ac56)
[52ee86b3ecce4ff55bf12f374580c5e2e434a769](https://github.com/spinnaker/clouddriver/commit/52ee86b3ecce4ff55bf12f374580c5e2e434a769)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "52ee86b3ecce4ff55bf12f374580c5e2e434a769"
},
"details": {
"image": {
"imageId": "sha256:83b5334ff856edcd95238edc24d867105744880811100b9f9cd40dbae4cb91ac",
"tag": "2024.05.10.19.22.13.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.05.10.19.22.13.master

stack.yml
* **master**
armory/fiat-armory:2024.05.10.18.42.55.master
[405d1c0629935c6ef15e3022d200b00942568246](https://github.com/armory-io/fiat-armory/commit/405d1c0629935c6ef15e3022d200b00942568246)
[68f3b322693df04f45d2a82e883694a8466d4009](https://github.com/spinnaker/fiat/commit/68f3b322693df04f45d2a82e883694a8466d4009)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "68f3b322693df04f45d2a82e883694a8466d4009"
},
"details": {
"image": {
"imageId": "sha256:f6e559a13f222d36be5bca2153355bf4962de906e2ad09c02a8dc8670919d1c9",
"tag": "2024.05.10.18.42.55.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update fiat-armory version to 2024.05.10.18.42.55.master

stack.yml
* **master**
armory/deck-armory:2024.05.12.14.06.01.master
[113a7685c7a1ec797390f6078ebcaba116cd7de8](https://github.com/armory-io/deck-armory/commit/113a7685c7a1ec797390f6078ebcaba116cd7de8)
[082a084908e13888d640e88a5bd6e1571479de14](https://github.com/spinnaker/deck/commit/082a084908e13888d640e88a5bd6e1571479de14)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "082a084908e13888d640e88a5bd6e1571479de14"
},
"details": {
"image": {
"imageId": "sha256:2f904f671b524c26bb0311063cd1fdeb50a351cae30234a282363cccc17ddc8b",
"tag": "2024.05.12.14.06.01.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update deck-armory version to 2024.05.12.14.06.01.master

stack.yml
* **master**
armory/deck-armory:2024.05.13.12.58.40.master
[22ada2c3eb42d85ddf4cdb6aecdf80bdd476690e](https://github.com/armory-io/deck-armory/commit/22ada2c3eb42d85ddf4cdb6aecdf80bdd476690e)
[443408e7f6404b10d195b146f2f68fe926c2413a](https://github.com/spinnaker/deck/commit/443408e7f6404b10d195b146f2f68fe926c2413a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "443408e7f6404b10d195b146f2f68fe926c2413a"
},
"details": {
"image": {
"imageId": "sha256:a9a90b9a630094f7c98f442a5d4ca1d1d0f61e474ff64a32183e487546875ac8",
"tag": "2024.05.13.12.58.40.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update deck-armory version to 2024.05.13.12.58.40.master

stack.yml
armory/deck-armory:2024.05.13.18.40.06.release-2.32.x
[19096fa607fabd0fd8865b18739eab577b4b7a9b](https://github.com/armory-io/deck-armory/commit/19096fa607fabd0fd8865b18739eab577b4b7a9b)
[0cb78bc43e854bcf70421ab16351d639de98da92](https://github.com/spinnaker/deck/commit/0cb78bc43e854bcf70421ab16351d639de98da92)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0cb78bc43e854bcf70421ab16351d639de98da92"
},
"details": {
"image": {
"imageId": "sha256:858d25ff494545530cf00003f5af6f99292f6ee0500bb2320d7e0103f149aacc",
"tag": "2024.05.13.18.40.06.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2024.05.13.18.40.06.release-2.32.x

stack.yml
* **master**
armory/clouddriver-armory:2024.05.15.14.17.45.master
[b0c29ce31b78dc6d0212c59d2b71c141357f41c6](https://github.com/armory-io/clouddriver-armory/commit/b0c29ce31b78dc6d0212c59d2b71c141357f41c6)
[c9bba669c24d1dd5d2e6d17a58fa4bd99aa20881](https://github.com/spinnaker/clouddriver/commit/c9bba669c24d1dd5d2e6d17a58fa4bd99aa20881)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c9bba669c24d1dd5d2e6d17a58fa4bd99aa20881"
},
"details": {
"image": {
"imageId": "sha256:9e7bccb5f7f8240744ecc29df59fecb886f0d434017050291c0912c6576ef6fa",
"tag": "2024.05.15.14.17.45.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.05.15.14.17.45.master

stack.yml
* **master**
armory/terraformer:2024.05.16.06.04.28.master
[2120b93755c3da2b94c4f053c6d5fbb0c2ea97e1](https://github.com/armory-io/terraformer/commit/2120b93755c3da2b94c4f053c6d5fbb0c2ea97e1)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:356f4cef68cbdc301051628924ba402b0b82332d1e9ca2d98afdeda40ed5af6d",
"tag": "2024.05.16.06.04.28.master"
},
"vcs": {
"repo": {
},
"sha": "2120b93755c3da2b94c4f053c6d5fbb0c2ea97e1"
}
},
},
"details": {
"image": {
"imageId": "sha256:356f4cef68cbdc301051628924ba402b0b82332d1e9ca2d98afdeda40ed5af6d", …
```
=> chore(cd): update terraformer version to 2024.05.16.06.04.28.master

stack.yml
armory/clouddriver-armory:2024.05.15.15.11.59.release-2.34.x
[e01932096487864963680a2b04118f5dbd53a5d4](https://github.com/armory-io/clouddriver-armory/commit/e01932096487864963680a2b04118f5dbd53a5d4)
[f8bfe2468ebf4edb191011edcf92816a708fdb55](https://github.com/spinnaker/clouddriver/commit/f8bfe2468ebf4edb191011edcf92816a708fdb55)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f8bfe2468ebf4edb191011edcf92816a708fdb55"
},
"details": {
"image": {
"imageId": "sha256:16a1cd76e9a55b1efd95fb262b9c3d64ddbaac68dea646bb22b8baec75876906",
"tag": "2024.05.15.15.11.59.release-2.34.x"
},
"vcs": …
```
=> chore(cd): update clouddriver-armory version to 2024.05.15.15.11.59.release-2.34.x

stack.yml
* **master**
armory/front50-armory:2024.05.16.18.17.28.master
[25412617c2452e5f9c0956bf26ab3b75e6118e6b](https://github.com/armory-io/front50-armory/commit/25412617c2452e5f9c0956bf26ab3b75e6118e6b)
[d292d195317a5a13f50ef656677a1531960ae34e](https://github.com/spinnaker/front50/commit/d292d195317a5a13f50ef656677a1531960ae34e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d292d195317a5a13f50ef656677a1531960ae34e"
},
"details": {
"image": {
"imageId": "sha256:c064dd47f63b07ce2423015e6a487bbf01d9285160f8030c332b980e72360b80",
"tag": "2024.05.16.18.17.28.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update front50-armory version to 2024.05.16.18.17.28.master

stack.yml
* **master**
armory/clouddriver-armory:2024.05.16.18.17.38.master
[aabadc7ae546bcbd888ccaada8a5102d60564f38](https://github.com/armory-io/clouddriver-armory/commit/aabadc7ae546bcbd888ccaada8a5102d60564f38)
[f8b8f1edc095ed63699e618b8efb4d330f7d3c37](https://github.com/spinnaker/clouddriver/commit/f8b8f1edc095ed63699e618b8efb4d330f7d3c37)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f8b8f1edc095ed63699e618b8efb4d330f7d3c37"
},
"details": {
"image": {
"imageId": "sha256:89e6914cd3806c22ee7b7c1b7ab9c847c599f02951a63740eb0af3306486a0b4",
"tag": "2024.05.16.18.17.38.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.05.16.18.17.38.master

stack.yml
* **master**
armory/igor-armory:2024.05.10.18.39.48.master
[635027645e85d6b82154c67da846dddb4a1a207c](https://github.com/armory-io/igor-armory/commit/635027645e85d6b82154c67da846dddb4a1a207c)
[89c84193c420f3912cee1aeb7d47d76d2558c9d5](https://github.com/spinnaker/igor/commit/89c84193c420f3912cee1aeb7d47d76d2558c9d5)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "89c84193c420f3912cee1aeb7d47d76d2558c9d5"
},
"details": {
"image": {
"imageId": "sha256:16d0b4535d99d942f1f3440e97f72b9c4eb7db181359ef5609bc83be4d4f95db",
"tag": "2024.05.10.18.39.48.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update igor-armory version to 2024.05.10.18.39.48.master

stack.yml
armory/rosco-armory:2024.06.03.10.40.07.release-2.34.x
[55e81f44714e69123daaa25e8b50a255ddf369b0](https://github.com/armory-io/rosco-armory/commit/55e81f44714e69123daaa25e8b50a255ddf369b0)
[626849fb20ae9840db5ae722dab1b12a48ba9584](https://github.com/spinnaker/rosco/commit/626849fb20ae9840db5ae722dab1b12a48ba9584)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "626849fb20ae9840db5ae722dab1b12a48ba9584"
},
"details": {
"image": {
"imageId": "sha256:e2c77b9b817286ccf8bc9d8ee7fb274ed39a681b91a6afe2d5e597a18c2a8693",
"tag": "2024.06.03.10.40.07.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.06.03.10.40.07.release-2.34.x

stack.yml
armory/clouddriver-armory:2024.06.05.17.35.01.release-2.32.x
[83a6e894c30f802cc73312a9984f28a21cc04b09](https://github.com/armory-io/clouddriver-armory/commit/83a6e894c30f802cc73312a9984f28a21cc04b09)
[7a8e6e8b3876215f84737ea10a8bf9f349dbfb85](https://github.com/spinnaker/clouddriver/commit/7a8e6e8b3876215f84737ea10a8bf9f349dbfb85)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7a8e6e8b3876215f84737ea10a8bf9f349dbfb85"
},
"details": {
"image": {
"imageId": "sha256:011c4ed0365b70705e74c2dad12e6800b7307a91dabdef8c5bc09da31f32ecea",
"tag": "2024.06.05.17.35.01.release-2.32.x"
},
"vcs": …
```
=> chore(cd): update clouddriver-armory version to 2024.06.05.17.35.01.release-2.32.x

stack.yml
* **master**
armory/clouddriver-armory:2024.06.05.18.01.29.master
[65280cc708f05526c34eeba2ccb48dbea49c5121](https://github.com/armory-io/clouddriver-armory/commit/65280cc708f05526c34eeba2ccb48dbea49c5121)
[b00e07f7c99b5f0ff7f549386ffa34df1b60eb4e](https://github.com/spinnaker/clouddriver/commit/b00e07f7c99b5f0ff7f549386ffa34df1b60eb4e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b00e07f7c99b5f0ff7f549386ffa34df1b60eb4e"
},
"details": {
"image": {
"imageId": "sha256:bc7d661c313fe2aed30d69115a92954636edba552ca29ec211649caa0640ca54",
"tag": "2024.06.05.18.01.29.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.06.05.18.01.29.master

stack.yml
* **master**
armory/echo-armory:2024.06.06.14.23.10.master
[3a1841ac1801eed6ed1c278cb59c4925cfa86625](https://github.com/armory-io/echo-armory/commit/3a1841ac1801eed6ed1c278cb59c4925cfa86625)
[8d6488ed8a3a86165c3cdafa747c7461a357e326](https://github.com/spinnaker/echo/commit/8d6488ed8a3a86165c3cdafa747c7461a357e326)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "8d6488ed8a3a86165c3cdafa747c7461a357e326"
},
"details": {
"image": {
"imageId": "sha256:6b9d91ecc9e803155bdedf7c42fb0fb40e1bb48a85199e9d3ee0d9b5660b4353",
"tag": "2024.06.06.14.23.10.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2024.06.06.14.23.10.master

stack.yml
* **master**
armory/front50-armory:2024.06.06.14.21.20.master
[30f7f447ae7a344d759f308664be2c45c3587c76](https://github.com/armory-io/front50-armory/commit/30f7f447ae7a344d759f308664be2c45c3587c76)
[8edaf0b5b4e796d8b0eb14852d80c3af6cc2ab17](https://github.com/spinnaker/front50/commit/8edaf0b5b4e796d8b0eb14852d80c3af6cc2ab17)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "8edaf0b5b4e796d8b0eb14852d80c3af6cc2ab17"
},
"details": {
"image": {
"imageId": "sha256:17db5bd752020604fd2acaf1e573b71917566c103479f7c794fa04ba522539a1",
"tag": "2024.06.06.14.21.20.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update front50-armory version to 2024.06.06.14.21.20.master

stack.yml
* **master**
armory/fiat-armory:2024.06.06.14.16.35.master
[fed73da8c482d93734e1e9c72b045215551aef1e](https://github.com/armory-io/fiat-armory/commit/fed73da8c482d93734e1e9c72b045215551aef1e)
[65f80ddfb2c3e01bc0f4b05a6bf2b8684fd22e08](https://github.com/spinnaker/fiat/commit/65f80ddfb2c3e01bc0f4b05a6bf2b8684fd22e08)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "65f80ddfb2c3e01bc0f4b05a6bf2b8684fd22e08"
},
"details": {
"image": {
"imageId": "sha256:d6cbe8fe15d2fb2db86ea3d597b8d049127540788e12046746e5ccaf45484510",
"tag": "2024.06.06.14.16.35.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update fiat-armory version to 2024.06.06.14.16.35.master

stack.yml
* **master**
armory/rosco-armory:2024.06.06.14.14.52.master
[9ce8adc442d222be191347a27dbf9b182a816ab4](https://github.com/armory-io/rosco-armory/commit/9ce8adc442d222be191347a27dbf9b182a816ab4)
[1b5b47d7a820df68b47deeeba451490bf854e8f8](https://github.com/spinnaker/rosco/commit/1b5b47d7a820df68b47deeeba451490bf854e8f8)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1b5b47d7a820df68b47deeeba451490bf854e8f8"
},
"details": {
"image": {
"imageId": "sha256:3ad3b46f691f9b371a1dc224fe42d40b3cc94c8da5cdc09a8c808e59f641ec74",
"tag": "2024.06.06.14.14.52.master"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.06.06.14.14.52.master

stack.yml
* **master**
armory/igor-armory:2024.06.06.14.23.14.master
[55fa6b26de8215fa50ee6c88bac1ff14b850afcd](https://github.com/armory-io/igor-armory/commit/55fa6b26de8215fa50ee6c88bac1ff14b850afcd)
[ef8189f122ff8af6a5203301b4cc03cd80f44dfc](https://github.com/spinnaker/igor/commit/ef8189f122ff8af6a5203301b4cc03cd80f44dfc)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "ef8189f122ff8af6a5203301b4cc03cd80f44dfc"
},
"details": {
"image": {
"imageId": "sha256:c0204ed07f9c6929c96740299926ea7b2db2dae94c81960c8367b3ce15b141b7",
"tag": "2024.06.06.14.23.14.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update igor-armory version to 2024.06.06.14.23.14.master

stack.yml
* **master**
armory/igor-armory:2024.06.07.06.00.42.master
[12f38784b07eae35dfe4857c35dc8232078a7f65](https://github.com/armory-io/igor-armory/commit/12f38784b07eae35dfe4857c35dc8232078a7f65)
[c0c71919279d3fa6f172224fbb138c56f7dc97e4](https://github.com/spinnaker/igor/commit/c0c71919279d3fa6f172224fbb138c56f7dc97e4)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c0c71919279d3fa6f172224fbb138c56f7dc97e4"
},
"details": {
"image": {
"imageId": "sha256:37bf666b934528b8d8b63f5f4577ce14453af1ceb5921f71574990b247c5e083",
"tag": "2024.06.07.06.00.42.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update igor-armory version to 2024.06.07.06.00.42.master

stack.yml
* **master**
armory/front50-armory:2024.06.07.06.07.53.master
[30c7f4cb8dbd9fd60889f9226b272e7ca219efa6](https://github.com/armory-io/front50-armory/commit/30c7f4cb8dbd9fd60889f9226b272e7ca219efa6)
[05d172c14d53ca560b2044c88698d49d4a425cb3](https://github.com/spinnaker/front50/commit/05d172c14d53ca560b2044c88698d49d4a425cb3)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "05d172c14d53ca560b2044c88698d49d4a425cb3"
},
"details": {
"image": {
"imageId": "sha256:c55272c08d29ac37e2b26867661aca7ebf7f3bfc3c8a86a6619606d59674d01f",
"tag": "2024.06.07.06.07.53.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update front50-armory version to 2024.06.07.06.07.53.master

stack.yml
* **master**
armory/fiat-armory:2024.06.07.06.09.18.master
[38402ba44956a0d16f16ba98744f23e30042d43b](https://github.com/armory-io/fiat-armory/commit/38402ba44956a0d16f16ba98744f23e30042d43b)
[65f80ddfb2c3e01bc0f4b05a6bf2b8684fd22e08](https://github.com/spinnaker/fiat/commit/65f80ddfb2c3e01bc0f4b05a6bf2b8684fd22e08)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "65f80ddfb2c3e01bc0f4b05a6bf2b8684fd22e08"
},
"details": {
"image": {
"imageId": "sha256:205daa5a83d368a6ce191561f950b1403a7bfb70bd8fcb28a263baea27b2ba84",
"tag": "2024.06.07.06.09.18.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update fiat-armory version to 2024.06.07.06.09.18.master

stack.yml
* **master**
armory/rosco-armory:2024.06.07.06.08.28.master
[b383119bc52836f5816ebdd1fe210e175e4e8bb3](https://github.com/armory-io/rosco-armory/commit/b383119bc52836f5816ebdd1fe210e175e4e8bb3)
[b731839a8222e3a495e096a39c0f01e29eec085a](https://github.com/spinnaker/rosco/commit/b731839a8222e3a495e096a39c0f01e29eec085a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "b731839a8222e3a495e096a39c0f01e29eec085a"
},
"details": {
"image": {
"imageId": "sha256:1d8af565233e5691e7f9a44518586563655dd65dd57a461692ce5e6cbf563891",
"tag": "2024.06.07.06.08.28.master"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.06.07.06.08.28.master

stack.yml
* **master**
armory/echo-armory:2024.06.07.06.17.13.master
[b2160eda62f46b394571963a9396b138aea750cf](https://github.com/armory-io/echo-armory/commit/b2160eda62f46b394571963a9396b138aea750cf)
[9d31dccaa24bfd7202bd90a0f2001a13032cea4d](https://github.com/spinnaker/echo/commit/9d31dccaa24bfd7202bd90a0f2001a13032cea4d)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9d31dccaa24bfd7202bd90a0f2001a13032cea4d"
},
"details": {
"image": {
"imageId": "sha256:201232c1711b6bc8cfc5555559f212dcf0af85d410abfc8cfd38e6b498c3832b",
"tag": "2024.06.07.06.17.13.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2024.06.07.06.17.13.master

stack.yml
* **master**
armory/clouddriver-armory:2024.06.07.07.02.05.master
[383577c119d9e7ea031f54dba909aa0890696b8c](https://github.com/armory-io/clouddriver-armory/commit/383577c119d9e7ea031f54dba909aa0890696b8c)
[1645ecf6960e057f35ea6e22aed851952085c0d3](https://github.com/spinnaker/clouddriver/commit/1645ecf6960e057f35ea6e22aed851952085c0d3)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1645ecf6960e057f35ea6e22aed851952085c0d3"
},
"details": {
"image": {
"imageId": "sha256:c416e71ac2ffe761e3360b19bc426fe1eaa635aaedfc0ddd9a4613d644c9735d",
"tag": "2024.06.07.07.02.05.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.06.07.07.02.05.master

stack.yml
* **master**
armory/clouddriver-armory:2024.06.07.15.30.59.master
[473684bcd8e54cc97b63873278e592ef34f76a48](https://github.com/armory-io/clouddriver-armory/commit/473684bcd8e54cc97b63873278e592ef34f76a48)
[ad1a8efc214264276e3a22d30af179b825145cab](https://github.com/spinnaker/clouddriver/commit/ad1a8efc214264276e3a22d30af179b825145cab)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "ad1a8efc214264276e3a22d30af179b825145cab"
},
"details": {
"image": {
"imageId": "sha256:9a2f4d49a7e50d1ca202d1267220848131adfc20c1a29d19d8f90b5ff95b1674",
"tag": "2024.06.07.15.30.59.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.06.07.15.30.59.master

stack.yml
* **master**
armory/orca-armory:2024.06.07.06.25.29.master
[6e0af4aef592f6ddf517023627d723a61e082d38](https://github.com/armory-io/orca-armory/commit/6e0af4aef592f6ddf517023627d723a61e082d38)
[7564826e1a8be04ffcfea1f58f5aabcdc20c31b7](https://github.com/spinnaker/orca/commit/7564826e1a8be04ffcfea1f58f5aabcdc20c31b7)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7564826e1a8be04ffcfea1f58f5aabcdc20c31b7"
},
"details": {
"image": {
"imageId": "sha256:434bdf1fd37a56f86df161682c1bbecb4087fae0ac148c8c229d6b245db81d8e",
"tag": "2024.06.07.06.25.29.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update orca-armory version to 2024.06.07.06.25.29.master

stack.yml
* **master**
armory/deck-armory:2024.06.10.15.03.31.master
[b2421088347997c216c8762f64abbe212f77b67d](https://github.com/armory-io/deck-armory/commit/b2421088347997c216c8762f64abbe212f77b67d)
[1f6d2c1a69bfae5fd8b6bb9f5fbf0b7fb86930d3](https://github.com/spinnaker/deck/commit/1f6d2c1a69bfae5fd8b6bb9f5fbf0b7fb86930d3)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1f6d2c1a69bfae5fd8b6bb9f5fbf0b7fb86930d3"
},
"details": {
"image": {
"imageId": "sha256:d8a9ee094993745ba6ea24edae92f5ebc1616de8b81f79506cd8d87e12cd55f3",
"tag": "2024.06.10.15.03.31.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update deck-armory version to 2024.06.10.15.03.31.master

stack.yml
armory/deck-armory:2024.06.10.15.44.58.release-2.34.x
[63cd2960432f7921cecefc634bc5b187473832fe](https://github.com/armory-io/deck-armory/commit/63cd2960432f7921cecefc634bc5b187473832fe)
[af6fa4260cbee3320a28549446e87454456a51dd](https://github.com/spinnaker/deck/commit/af6fa4260cbee3320a28549446e87454456a51dd)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "af6fa4260cbee3320a28549446e87454456a51dd"
},
"details": {
"image": {
"imageId": "sha256:64b47b7eae2aaa10723a106a36061bc80535f07908e4e4d2739b5c353741dae3",
"tag": "2024.06.10.15.44.58.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2024.06.10.15.44.58.release-2.34.x

stack.yml
armory/deck-armory:2024.06.10.15.45.07.release-2.32.x
[db3aa36e8971fbb6669858f666c9799092e091f6](https://github.com/armory-io/deck-armory/commit/db3aa36e8971fbb6669858f666c9799092e091f6)
[3daea6a6edde8279da82882a4cc706b31d55f5f0](https://github.com/spinnaker/deck/commit/3daea6a6edde8279da82882a4cc706b31d55f5f0)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "3daea6a6edde8279da82882a4cc706b31d55f5f0"
},
"details": {
"image": {
"imageId": "sha256:df848eef601f987f99bc7acc807d65755128a38f40f8f94340f9a52c0e97e4ab",
"tag": "2024.06.10.15.45.07.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2024.06.10.15.45.07.release-2.32.x

stack.yml
* **master**
armory/orca-armory:2024.06.10.16.57.10.master
[20e2b63e0c7c3ff45028d45cac17ba66a8e45764](https://github.com/armory-io/orca-armory/commit/20e2b63e0c7c3ff45028d45cac17ba66a8e45764)
[e110e65b6bcd04df2497f88525b76517946e08bb](https://github.com/spinnaker/orca/commit/e110e65b6bcd04df2497f88525b76517946e08bb)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e110e65b6bcd04df2497f88525b76517946e08bb"
},
"details": {
"image": {
"imageId": "sha256:b9c725b28659ee59a3b306a6234eada9de09183c41bd82d7f7cc603dd8e5592b",
"tag": "2024.06.10.16.57.10.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update orca-armory version to 2024.06.10.16.57.10.master

stack.yml
* **master**
armory/fiat-armory:2024.06.12.14.54.24.master
[e4e61c6d345fc973e8719421c634ae485c903e8e](https://github.com/armory-io/fiat-armory/commit/e4e61c6d345fc973e8719421c634ae485c903e8e)
[4ea6ebb3497ea62979dfd972c6a50fe9ff26b2f5](https://github.com/spinnaker/fiat/commit/4ea6ebb3497ea62979dfd972c6a50fe9ff26b2f5)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4ea6ebb3497ea62979dfd972c6a50fe9ff26b2f5"
},
"details": {
"image": {
"imageId": "sha256:8a55b60cc343754bfcd52ae6f628dac7a708625c920c8e841d6a383fd814b7ec",
"tag": "2024.06.12.14.54.24.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update fiat-armory version to 2024.06.12.14.54.24.master

stack.yml
* **master**
armory/front50-armory:2024.06.12.14.53.06.master
[8f2b944938f19b1e43d0448e28bb46ec01c12b9b](https://github.com/armory-io/front50-armory/commit/8f2b944938f19b1e43d0448e28bb46ec01c12b9b)
[89d520f72f2c8803d7a7099b0dac50443cd88337](https://github.com/spinnaker/front50/commit/89d520f72f2c8803d7a7099b0dac50443cd88337)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "89d520f72f2c8803d7a7099b0dac50443cd88337"
},
"details": {
"image": {
"imageId": "sha256:a8cc8aaa70e68107ecc42d1180bf50fc3adb92429678659096db80846c1ec8e2",
"tag": "2024.06.12.14.53.06.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update front50-armory version to 2024.06.12.14.53.06.master

stack.yml
armory/orca-armory:2024.06.10.16.44.03.release-2.32.x
[a89a8ec34243b9c5de64eaabe6b7d3395a6d5524](https://github.com/armory-io/orca-armory/commit/a89a8ec34243b9c5de64eaabe6b7d3395a6d5524)
[3f8965d032be8fe5cf8a8afa4668c9a81e6bfbe4](https://github.com/spinnaker/orca/commit/3f8965d032be8fe5cf8a8afa4668c9a81e6bfbe4)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "3f8965d032be8fe5cf8a8afa4668c9a81e6bfbe4"
},
"details": {
"image": {
"imageId": "sha256:d9926613cc46668270933c1908f741db9eb99663b678a73c8a30cbbc9f41f6ae",
"tag": "2024.06.10.16.44.03.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2024.06.10.16.44.03.release-2.32.x

stack.yml
armory/front50-armory:2024.06.11.18.35.10.release-2.32.x
[0f22731b93b51f48fc823728db69b86783679314](https://github.com/armory-io/front50-armory/commit/0f22731b93b51f48fc823728db69b86783679314)
[1371f26e6172450896c07f8015583c30b80e4769](https://github.com/spinnaker/front50/commit/1371f26e6172450896c07f8015583c30b80e4769)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1371f26e6172450896c07f8015583c30b80e4769"
},
"details": {
"image": {
"imageId": "sha256:7c88701ce8b97f03cf6b57f5be861ffc12c21c3ff815c494d6e987e296a8c1be",
"tag": "2024.06.11.18.35.10.release-2.32.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update front50-armory version to 2024.06.11.18.35.10.release-2.32.x

stack.yml
armory/orca-armory:2024.06.12.02.32.32.release-2.34.x
[c31f9adc1739c5c7b11ffb11a18e6efa27041c07](https://github.com/armory-io/orca-armory/commit/c31f9adc1739c5c7b11ffb11a18e6efa27041c07)
[0c322572071a67397dc01d387e5cbbd729d38d94](https://github.com/spinnaker/orca/commit/0c322572071a67397dc01d387e5cbbd729d38d94)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0c322572071a67397dc01d387e5cbbd729d38d94"
},
"details": {
"image": {
"imageId": "sha256:65ff51b8da12c1f21a66960cbf6a4592dc7c7ca16c2b8cc6369ee0eaa67d3645",
"tag": "2024.06.12.02.32.32.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2024.06.12.02.32.32.release-2.34.x

stack.yml
armory/front50-armory:2024.06.19.09.50.14.release-2.34.x
[e1f5c4d2993ba0329516961b21d3e1c7d4ac83e3](https://github.com/armory-io/front50-armory/commit/e1f5c4d2993ba0329516961b21d3e1c7d4ac83e3)
[f8c86dc36f174f04cdfbe8ae686174df655e4c0a](https://github.com/spinnaker/front50/commit/f8c86dc36f174f04cdfbe8ae686174df655e4c0a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f8c86dc36f174f04cdfbe8ae686174df655e4c0a"
},
"details": {
"image": {
"imageId": "sha256:d97eea89fa1059260a7069ab1f4abb90da900f766ec6a988f4d1ae050a8b8fb2",
"tag": "2024.06.19.09.50.14.release-2.34.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update front50-armory version to 2024.06.19.09.50.14.release-2.34.x

stack.yml
armory/clouddriver-armory:2024.06.11.20.00.33.release-2.34.x
[06659caf1ccf667affc2b3f835a8829990e97849](https://github.com/armory-io/clouddriver-armory/commit/06659caf1ccf667affc2b3f835a8829990e97849)
[4d1782ebadb5e938e919a82282cab1bff60f34d8](https://github.com/spinnaker/clouddriver/commit/4d1782ebadb5e938e919a82282cab1bff60f34d8)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4d1782ebadb5e938e919a82282cab1bff60f34d8"
},
"details": {
"image": {
"imageId": "sha256:522668663cf8990d563c8753a12e4e5fc2cdd758de70ac558d65ab8d29ac4a5e",
"tag": "2024.06.11.20.00.33.release-2.34.x"
},
"vcs": …
```
=> chore(cd): update clouddriver-armory version to 2024.06.11.20.00.33.release-2.34.x

stack.yml
* **master**
armory/igor-armory:2024.06.12.14.53.14.master
[831a8e8e06e29728e23ff90662566b442b7d8399](https://github.com/armory-io/igor-armory/commit/831a8e8e06e29728e23ff90662566b442b7d8399)
[a56c420e7387a67bb43380dc8ad011403517f205](https://github.com/spinnaker/igor/commit/a56c420e7387a67bb43380dc8ad011403517f205)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a56c420e7387a67bb43380dc8ad011403517f205"
},
"details": {
"image": {
"imageId": "sha256:4e33378df1cdca37922c06153346da94538e67850483a1799f6552e315bb667d",
"tag": "2024.06.12.14.53.14.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update igor-armory version to 2024.06.12.14.53.14.master

stack.yml
* **master**
armory/echo-armory:2024.06.12.15.10.08.master
[56b4f9b2b622903ab77af768587463cbcfd730b8](https://github.com/armory-io/echo-armory/commit/56b4f9b2b622903ab77af768587463cbcfd730b8)
[9bcd1fec28692137dba3d197a164eb3e46989acc](https://github.com/spinnaker/echo/commit/9bcd1fec28692137dba3d197a164eb3e46989acc)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9bcd1fec28692137dba3d197a164eb3e46989acc"
},
"details": {
"image": {
"imageId": "sha256:13b1d221427a6904c6cba839b891907e7c6096be0673ad43ee812944af6e5c3b",
"tag": "2024.06.12.15.10.08.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2024.06.12.15.10.08.master

stack.yml
* **master**
armory/clouddriver-armory:2024.06.12.15.36.29.master
[682efbce5995ec5baee986b03376f9be5a323ed6](https://github.com/armory-io/clouddriver-armory/commit/682efbce5995ec5baee986b03376f9be5a323ed6)
[4dd79ca1871c5f16a25f1feb583da962fd097650](https://github.com/spinnaker/clouddriver/commit/4dd79ca1871c5f16a25f1feb583da962fd097650)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4dd79ca1871c5f16a25f1feb583da962fd097650"
},
"details": {
"image": {
"imageId": "sha256:7346ec893a20b4d920e06d28328e4a1bc7b303d7e2291fc142c458e2d33e2d16",
"tag": "2024.06.12.15.36.29.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.06.12.15.36.29.master

stack.yml
* **master**
armory/rosco-armory:2024.06.12.14.53.47.master
[01f66493db72145d721d9e408e9fa886d56fdef9](https://github.com/armory-io/rosco-armory/commit/01f66493db72145d721d9e408e9fa886d56fdef9)
[00c1b33e0459db7555c7f0332867f23681f01215](https://github.com/spinnaker/rosco/commit/00c1b33e0459db7555c7f0332867f23681f01215)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "00c1b33e0459db7555c7f0332867f23681f01215"
},
"details": {
"image": {
"imageId": "sha256:ca4f2ce16888368f8a6933d669d8465c19dffd1176e719506864fd3beca2d016",
"tag": "2024.06.12.14.53.47.master"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.06.12.14.53.47.master

stack.yml
* **master**
armory/echo-armory:2024.06.27.15.18.05.master
[6a84b04a3304e15557a2863967ddb8f07cde3cb6](https://github.com/armory-io/echo-armory/commit/6a84b04a3304e15557a2863967ddb8f07cde3cb6)
[9bcd1fec28692137dba3d197a164eb3e46989acc](https://github.com/spinnaker/echo/commit/9bcd1fec28692137dba3d197a164eb3e46989acc)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9bcd1fec28692137dba3d197a164eb3e46989acc"
},
"details": {
"image": {
"imageId": "sha256:d3713e7fae3e5b7472d4f2687a5d28fbac3514f30f7c77dce99c8bcccbd5a3a6",
"tag": "2024.06.27.15.18.05.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2024.06.27.15.18.05.master

stack.yml
* **master**
armory/igor-armory:2024.06.27.15.19.18.master
[763107041881ec88dbba9230f9a70e133d2623f7](https://github.com/armory-io/igor-armory/commit/763107041881ec88dbba9230f9a70e133d2623f7)
[a56c420e7387a67bb43380dc8ad011403517f205](https://github.com/spinnaker/igor/commit/a56c420e7387a67bb43380dc8ad011403517f205)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a56c420e7387a67bb43380dc8ad011403517f205"
},
"details": {
"image": {
"imageId": "sha256:ea668faa6bba3a2745626e858f8772cf679d77c194e940c5524df98923ee8628",
"tag": "2024.06.27.15.19.18.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update igor-armory version to 2024.06.27.15.19.18.master

stack.yml
* **master**
armory/clouddriver-armory:2024.06.27.15.05.14.master
[a883c883b53188731aadf1726fb6b070aa5c0988](https://github.com/armory-io/clouddriver-armory/commit/a883c883b53188731aadf1726fb6b070aa5c0988)
[4dd79ca1871c5f16a25f1feb583da962fd097650](https://github.com/spinnaker/clouddriver/commit/4dd79ca1871c5f16a25f1feb583da962fd097650)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4dd79ca1871c5f16a25f1feb583da962fd097650"
},
"details": {
"image": {
"imageId": "sha256:59f672da9c8999b5f5cea35b6cbba52272b13f0a4e7540ca4435cc5ba6868f48",
"tag": "2024.06.27.15.05.14.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.06.27.15.05.14.master

stack.yml
* **master**
armory/fiat-armory:2024.06.27.15.04.02.master
[e0f8ee024bbdedd62778929b57bc11748169d374](https://github.com/armory-io/fiat-armory/commit/e0f8ee024bbdedd62778929b57bc11748169d374)
[cec1223fde38d18399e37f5cb5cb56047b0a332b](https://github.com/spinnaker/fiat/commit/cec1223fde38d18399e37f5cb5cb56047b0a332b)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "cec1223fde38d18399e37f5cb5cb56047b0a332b"
},
"details": {
"image": {
"imageId": "sha256:12ec6e5bec994544ffee6a9a20a87b5275e053a1f13776a4dc221aafae7b8f76",
"tag": "2024.06.27.15.04.02.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update fiat-armory version to 2024.06.27.15.04.02.master

stack.yml
* **master**
armory/kayenta-armory:2024.06.27.17.40.50.master
[79ba072de6c99a907fa39bcf2f18721aab12682b](https://github.com/armory-io/kayenta-armory/commit/79ba072de6c99a907fa39bcf2f18721aab12682b)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:9345c1d50afb1191a7086a6f9e1ac3a52759358039815fa805415977d6f6442e",
"tag": "2024.06.27.17.40.50.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update kayenta-armory version to 2024.06.27.17.40.50.master

stack.yml
* **master**
armory/gate-armory:2024.06.27.15.19.04.master
[e9935adf4d8de1de7bf4aeafa05e6d2a91b256f6](https://github.com/armory-io/gate-armory/commit/e9935adf4d8de1de7bf4aeafa05e6d2a91b256f6)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:70f536a0b21160487629cdae0335402ef282254d27a20a5c81ee31133c3a9cbd",
"tag": "2024.06.27.15.19.04.master"
},
"vcs": {
"repo": {
},
"sha": "e9935adf4d8de1de7bf4aeafa05e6d2a91b256f6"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update gate-armory version to 2024.06.27.15.19.04.master

stack.yml
armory/clouddriver-armory:2024.06.28.08.16.48.release-2.34.x
[94c77a6b398a40993e6fba92e5692393d8f22564](https://github.com/armory-io/clouddriver-armory/commit/94c77a6b398a40993e6fba92e5692393d8f22564)
[f3d9bcfe549e571b0ff4f655c23e9c2a3133c8db](https://github.com/spinnaker/clouddriver/commit/f3d9bcfe549e571b0ff4f655c23e9c2a3133c8db)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f3d9bcfe549e571b0ff4f655c23e9c2a3133c8db"
},
"details": {
"image": {
"imageId": "sha256:36bfd831c4aa0b45ba688a15e9ba75a34929810028293427919a099acd48eacc",
"tag": "2024.06.28.08.16.48.release-2.34.x"
},
"vcs": …
```
=> chore(cd): update clouddriver-armory version to 2024.06.28.08.16.48.release-2.34.x

stack.yml
armory/kayenta-armory:2024.06.28.07.56.57.release-2.34.x
[df1ff1e1024951c84f5d214dce342eb3338e97c9](https://github.com/armory-io/kayenta-armory/commit/df1ff1e1024951c84f5d214dce342eb3338e97c9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:14d1f3a94467f0b33c2c878b66d1df0eb21754380b9dda8b724f39f877178f03",
"tag": "2024.06.28.07.56.57.release-2.34.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update kayenta-armory version to 2024.06.28.07.56.57.release-2.34.x

stack.yml
* **master**
armory/kayenta-armory:2024.06.28.08.16.24.master
[6391e078b1d78b574b1454c89f9739e4d5cf20c3](https://github.com/armory-io/kayenta-armory/commit/6391e078b1d78b574b1454c89f9739e4d5cf20c3)
[29d1bf1a44557c7b76c0d06a50ebe1fa0cf9c1aa](https://github.com/spinnaker/kayenta/commit/29d1bf1a44557c7b76c0d06a50ebe1fa0cf9c1aa)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "29d1bf1a44557c7b76c0d06a50ebe1fa0cf9c1aa"
},
"details": {
"image": {
"imageId": "sha256:1c60de88e1ff2f0fd90039159b3573f299d659a191548fb22b5dc523838bdd86",
"tag": "2024.06.28.08.16.24.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update kayenta-armory version to 2024.06.28.08.16.24.master

stack.yml
* **master**
armory/rosco-armory:2024.06.27.15.19.39.master
[abdbad68a612110f566288e12f8fddb1be369b07](https://github.com/armory-io/rosco-armory/commit/abdbad68a612110f566288e12f8fddb1be369b07)
[00c1b33e0459db7555c7f0332867f23681f01215](https://github.com/spinnaker/rosco/commit/00c1b33e0459db7555c7f0332867f23681f01215)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "00c1b33e0459db7555c7f0332867f23681f01215"
},
"details": {
"image": {
"imageId": "sha256:87159bfd7b38fb15d29a4204d7fe737c2d6728975efcf8e29793e82d8297d38e",
"tag": "2024.06.27.15.19.39.master"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.06.27.15.19.39.master

stack.yml
* **master**
armory/front50-armory:2024.06.27.15.18.32.master
[787f0e93159774442bd3fbf1c86571bf58c143de](https://github.com/armory-io/front50-armory/commit/787f0e93159774442bd3fbf1c86571bf58c143de)
[89d520f72f2c8803d7a7099b0dac50443cd88337](https://github.com/spinnaker/front50/commit/89d520f72f2c8803d7a7099b0dac50443cd88337)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "89d520f72f2c8803d7a7099b0dac50443cd88337"
},
"details": {
"image": {
"imageId": "sha256:08c6369a41621cd1b845541fc4b0504bce8981d82238dc4b9aeb38ebed498635",
"tag": "2024.06.27.15.18.32.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update front50-armory version to 2024.06.27.15.18.32.master

stack.yml
* **master**
armory/clouddriver-armory:2024.06.28.08.12.57.master
[9871187e87e5342703f5c27c7f50862f0ef0bb00](https://github.com/armory-io/clouddriver-armory/commit/9871187e87e5342703f5c27c7f50862f0ef0bb00)
[f12a0439f2da58ab80fc037451b5011e516d513d](https://github.com/spinnaker/clouddriver/commit/f12a0439f2da58ab80fc037451b5011e516d513d)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f12a0439f2da58ab80fc037451b5011e516d513d"
},
"details": {
"image": {
"imageId": "sha256:9ed1c21fd3a5bb5df287345a51b99006b8f317beff3d64b390014d1fbd05281e",
"tag": "2024.06.28.08.12.57.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.06.28.08.12.57.master

stack.yml
armory/fiat-armory:2024.06.28.14.26.54.release-2.34.x
[e8be593635189433704d0a7945fa1335c24ac896](https://github.com/armory-io/fiat-armory/commit/e8be593635189433704d0a7945fa1335c24ac896)
[5c90023372ef8aca64adf4d0dbb614e350ac8f29](https://github.com/spinnaker/fiat/commit/5c90023372ef8aca64adf4d0dbb614e350ac8f29)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5c90023372ef8aca64adf4d0dbb614e350ac8f29"
},
"details": {
"image": {
"imageId": "sha256:d676e84b5dd0c5c3d15bf23c3874fee076a1d9ab54ce1cb8b1a3ef854ef9f5ed",
"tag": "2024.06.28.14.26.54.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update fiat-armory version to 2024.06.28.14.26.54.release-2.34.x

stack.yml
armory/orca-armory:2024.06.28.14.26.26.release-2.34.x
[7e470413d4bbc4d25c1ac9c787f27d7a5261aafd](https://github.com/armory-io/orca-armory/commit/7e470413d4bbc4d25c1ac9c787f27d7a5261aafd)
[0c322572071a67397dc01d387e5cbbd729d38d94](https://github.com/spinnaker/orca/commit/0c322572071a67397dc01d387e5cbbd729d38d94)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0c322572071a67397dc01d387e5cbbd729d38d94"
},
"details": {
"image": {
"imageId": "sha256:311defc34303f0eda5201c2656c68a0443eb36e7a8721ac22295f147cf827ab5",
"tag": "2024.06.28.14.26.26.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2024.06.28.14.26.26.release-2.34.x

stack.yml
armory/front50-armory:2024.06.28.14.27.51.release-2.34.x
[cce826e7cc2203970da4ebd37ccd9a91d9b39790](https://github.com/armory-io/front50-armory/commit/cce826e7cc2203970da4ebd37ccd9a91d9b39790)
[f8c86dc36f174f04cdfbe8ae686174df655e4c0a](https://github.com/spinnaker/front50/commit/f8c86dc36f174f04cdfbe8ae686174df655e4c0a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f8c86dc36f174f04cdfbe8ae686174df655e4c0a"
},
"details": {
"image": {
"imageId": "sha256:04bbe2d80af7a7644e694965a45c320b94833dc6aabfc29c21bd47f787eb58c3",
"tag": "2024.06.28.14.27.51.release-2.34.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update front50-armory version to 2024.06.28.14.27.51.release-2.34.x

stack.yml
armory/gate-armory:2024.06.28.14.28.45.release-2.34.x
[d193f203e8d9f1121f4a1bfcb5785b7828be6085](https://github.com/armory-io/gate-armory/commit/d193f203e8d9f1121f4a1bfcb5785b7828be6085)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:d6afac7de1973c2fb64cb1b569700ea4a67d12e7798522e1752a44d44bf2e10d",
"tag": "2024.06.28.14.28.45.release-2.34.x"
},
"vcs": {
"repo": {
},
"sha": "d193f203e8d9f1121f4a1bfcb5785b7828be6085"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update gate-armory version to 2024.06.28.14.28.45.release-2.34.x

stack.yml
armory/rosco-armory:2024.06.28.14.28.26.release-2.34.x
[3fbb0163c59a444cdf0ba8067b7569c666ee5c39](https://github.com/armory-io/rosco-armory/commit/3fbb0163c59a444cdf0ba8067b7569c666ee5c39)
[626849fb20ae9840db5ae722dab1b12a48ba9584](https://github.com/spinnaker/rosco/commit/626849fb20ae9840db5ae722dab1b12a48ba9584)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "626849fb20ae9840db5ae722dab1b12a48ba9584"
},
"details": {
"image": {
"imageId": "sha256:6bbe879125958880815fd7fd4cd221c1fc621cc73db3187d41b0f93de8716a93",
"tag": "2024.06.28.14.28.26.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.06.28.14.28.26.release-2.34.x

stack.yml
armory/kayenta-armory:2024.07.01.13.04.22.release-2.34.x
[840e7e93fbc83c7704895307fe057b84d14776f2](https://github.com/armory-io/kayenta-armory/commit/840e7e93fbc83c7704895307fe057b84d14776f2)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:b011845f81bb8f5b0562d1e8f0eb7604fd1461e16f72127853719d3bdec56e19",
"tag": "2024.07.01.13.04.22.release-2.34.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update kayenta-armory version to 2024.07.01.13.04.22.release-2.34.x

stack.yml
* **master**
armory/gate-armory:2024.07.01.14.40.26.master
[15c386fc223b48828bd44eadc58a635f4ecc6200](https://github.com/armory-io/gate-armory/commit/15c386fc223b48828bd44eadc58a635f4ecc6200)
[606f252a131521f3abb1ead818d7ccf36a5a1823](https://github.com/spinnaker/gate/commit/606f252a131521f3abb1ead818d7ccf36a5a1823)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "606f252a131521f3abb1ead818d7ccf36a5a1823"
},
"details": {
"image": {
"imageId": "sha256:f330191f591b57d96d28331e9ba68556ec02b96008137ec35b2bcda55c94b321",
"tag": "2024.07.01.14.40.26.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update gate-armory version to 2024.07.01.14.40.26.master

stack.yml
* **master**
armory/deck-armory:2024.07.01.13.05.46.master
[cfa8950ca4cd082218d7b1a2d35ffda7b0f923e0](https://github.com/armory-io/deck-armory/commit/cfa8950ca4cd082218d7b1a2d35ffda7b0f923e0)
[0551bb17cf12e2ad5fe49a3c4ddec13c55c085ed](https://github.com/spinnaker/deck/commit/0551bb17cf12e2ad5fe49a3c4ddec13c55c085ed)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0551bb17cf12e2ad5fe49a3c4ddec13c55c085ed"
},
"details": {
"image": {
"imageId": "sha256:1aa7df13337a28a4e6024972d79a5ee683d8c499ab1fc4553b1371f667fe5dd1",
"tag": "2024.07.01.13.05.46.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update deck-armory version to 2024.07.01.13.05.46.master

stack.yml
* **master**
armory/dinghy:2024.07.01.14.13.27.master
[50041173d1a043493409059e7fa5d7a1a80fb553](https://github.com/armory-io/dinghy/commit/50041173d1a043493409059e7fa5d7a1a80fb553)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:8b53358ede272f3397c47620446561aca3ae20eb20ad31aa81f24feb4bb36558",
"tag": "2024.07.01.14.13.27.master"
},
"vcs": {
"repo": {
},
"sha": "50041173d1a043493409059e7fa5d7a1a80fb553"
}
},
},
"details": {
"image": {
"imageId": "sha256:8b53358ede272f3397c47620446561aca3ae20eb20ad31aa81f24feb4bb36558", …
```
=> chore(cd): update dinghy version to 2024.07.01.14.13.27.master

stack.yml
* **master**
armory/rosco-armory:2024.07.01.18.43.16.master
[1ccb5181f0cc4c9c0d8fb15d212ee7860406b562](https://github.com/armory-io/rosco-armory/commit/1ccb5181f0cc4c9c0d8fb15d212ee7860406b562)
[12b0d5bec5c9aea6dbd20bcf91eebb5e81ac3db1](https://github.com/spinnaker/rosco/commit/12b0d5bec5c9aea6dbd20bcf91eebb5e81ac3db1)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "12b0d5bec5c9aea6dbd20bcf91eebb5e81ac3db1"
},
"details": {
"image": {
"imageId": "sha256:5ffcf62044cf897223fefe0f17e9f47fcc136e89392df7e15a8ad773b9df9e90",
"tag": "2024.07.01.18.43.16.master"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.07.01.18.43.16.master

stack.yml
* **master**
armory/rosco-armory:2024.07.02.07.41.25.master
[9067c82adb26c4e91c8aa3a77557ca2f1821319c](https://github.com/armory-io/rosco-armory/commit/9067c82adb26c4e91c8aa3a77557ca2f1821319c)
[422b75bae12ce183523ad7ce413150789bd7fc5c](https://github.com/spinnaker/rosco/commit/422b75bae12ce183523ad7ce413150789bd7fc5c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "422b75bae12ce183523ad7ce413150789bd7fc5c"
},
"details": {
"image": {
"imageId": "sha256:65c45a45aba1d66d1a39fcf1a3c89e8d94d78d50e88cb7b6f34794cca40c4efd",
"tag": "2024.07.02.07.41.25.master"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.07.02.07.41.25.master

stack.yml
* **master**
armory/echo-armory:2024.07.02.07.40.38.master
[428579fbea9ca0542f128a616661c55432974cd8](https://github.com/armory-io/echo-armory/commit/428579fbea9ca0542f128a616661c55432974cd8)
[9bcd1fec28692137dba3d197a164eb3e46989acc](https://github.com/spinnaker/echo/commit/9bcd1fec28692137dba3d197a164eb3e46989acc)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9bcd1fec28692137dba3d197a164eb3e46989acc"
},
"details": {
"image": {
"imageId": "sha256:a56755eb4d1e8e39b157e5cb71eefa474357634554912c548f8ce636e7541b90",
"tag": "2024.07.02.07.40.38.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2024.07.02.07.40.38.master

stack.yml
* **master**
armory/gate-armory:2024.07.02.07.40.56.master
[fd4aaebed31a4280567c155b66858906d00765b2](https://github.com/armory-io/gate-armory/commit/fd4aaebed31a4280567c155b66858906d00765b2)
[606f252a131521f3abb1ead818d7ccf36a5a1823](https://github.com/spinnaker/gate/commit/606f252a131521f3abb1ead818d7ccf36a5a1823)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "606f252a131521f3abb1ead818d7ccf36a5a1823"
},
"details": {
"image": {
"imageId": "sha256:1feb0cfc6630a09b6ff962ad3250f7c445d9a8737bf2559c3f4d618b01e3d5d4",
"tag": "2024.07.02.07.40.56.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update gate-armory version to 2024.07.02.07.40.56.master

stack.yml
armory/rosco-armory:2024.07.02.10.31.01.release-2.34.x
[23db1000615781164ae3042eed3ef8cf298d7da4](https://github.com/armory-io/rosco-armory/commit/23db1000615781164ae3042eed3ef8cf298d7da4)
[626849fb20ae9840db5ae722dab1b12a48ba9584](https://github.com/spinnaker/rosco/commit/626849fb20ae9840db5ae722dab1b12a48ba9584)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "626849fb20ae9840db5ae722dab1b12a48ba9584"
},
"details": {
"image": {
"imageId": "sha256:6adbc51dd6ce1557770d752ba08ff5d4cf79db29083c358555506f1a91f4b35c",
"tag": "2024.07.02.10.31.01.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.07.02.10.31.01.release-2.34.x

stack.yml
* **master**
armory/fiat-armory:2024.07.03.07.31.05.master
[93b542fc6e7f905ee8ca1db5334636642a109bde](https://github.com/armory-io/fiat-armory/commit/93b542fc6e7f905ee8ca1db5334636642a109bde)
[253380a726674b69b6c9a45fdff5457289ce1489](https://github.com/spinnaker/fiat/commit/253380a726674b69b6c9a45fdff5457289ce1489)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "253380a726674b69b6c9a45fdff5457289ce1489"
},
"details": {
"image": {
"imageId": "sha256:8d3bfea17b665b362aaa238889dd639e93926382b455297c17f0cd560619ee4f",
"tag": "2024.07.03.07.31.05.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update fiat-armory version to 2024.07.03.07.31.05.master

stack.yml
* **master**
armory/clouddriver-armory:2024.07.03.07.31.13.master
[6a36c815d29cafcc284736c1077e2ededc0508eb](https://github.com/armory-io/clouddriver-armory/commit/6a36c815d29cafcc284736c1077e2ededc0508eb)
[ad43bd15d2aa281276a0f8afe8820809b1699722](https://github.com/spinnaker/clouddriver/commit/ad43bd15d2aa281276a0f8afe8820809b1699722)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "ad43bd15d2aa281276a0f8afe8820809b1699722"
},
"details": {
"image": {
"imageId": "sha256:c4049952eb38e67e325197391725916e1978ff99f556e8bff010e7daa4c24db5",
"tag": "2024.07.03.07.31.13.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.07.03.07.31.13.master

stack.yml
* **master**
armory/echo-armory:2024.07.03.07.31.21.master
[80fcbdbf4bfca5f6410713657cef3f82e123f887](https://github.com/armory-io/echo-armory/commit/80fcbdbf4bfca5f6410713657cef3f82e123f887)
[d97ff355df8f2978bbc906c069309ddcd1ebb590](https://github.com/spinnaker/echo/commit/d97ff355df8f2978bbc906c069309ddcd1ebb590)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d97ff355df8f2978bbc906c069309ddcd1ebb590"
},
"details": {
"image": {
"imageId": "sha256:833632ca29d2c25d7274d6765eb7a397c216a9ce0055f54032c4ceb35d6e48a1",
"tag": "2024.07.03.07.31.21.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2024.07.03.07.31.21.master

stack.yml
* **master**
armory/front50-armory:2024.07.03.07.31.28.master
[70c2052ea523416b231dab860e4884f763aaa069](https://github.com/armory-io/front50-armory/commit/70c2052ea523416b231dab860e4884f763aaa069)
[27ea5f9d5cc2628a6d80f0bb23c32e1599f0769c](https://github.com/spinnaker/front50/commit/27ea5f9d5cc2628a6d80f0bb23c32e1599f0769c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "27ea5f9d5cc2628a6d80f0bb23c32e1599f0769c"
},
"details": {
"image": {
"imageId": "sha256:2d6ad043316dc93b59e549d35a9e5fc3254a1a6b023a549156335086a025215b",
"tag": "2024.07.03.07.31.28.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update front50-armory version to 2024.07.03.07.31.28.master

stack.yml
* **master**
armory/igor-armory:2024.07.03.07.31.43.master
[41719ac3c3c68bd31a82bb8cd5e9a98b69d6bdd5](https://github.com/armory-io/igor-armory/commit/41719ac3c3c68bd31a82bb8cd5e9a98b69d6bdd5)
[22c5255beb2ba06bc333c0c81c64ff9af038319b](https://github.com/spinnaker/igor/commit/22c5255beb2ba06bc333c0c81c64ff9af038319b)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "22c5255beb2ba06bc333c0c81c64ff9af038319b"
},
"details": {
"image": {
"imageId": "sha256:0e89e543abfe522ff7376a9c413525a91799c9eef3fba8a25e48ba8bcbea0adf",
"tag": "2024.07.03.07.31.43.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update igor-armory version to 2024.07.03.07.31.43.master

stack.yml
* **master**
armory/rosco-armory:2024.07.03.07.31.54.master
[c88341cb78229ab98dd955d61c3c9123d60e25c4](https://github.com/armory-io/rosco-armory/commit/c88341cb78229ab98dd955d61c3c9123d60e25c4)
[801973e0b81d7db5f4a864415b9bdf66122fd32a](https://github.com/spinnaker/rosco/commit/801973e0b81d7db5f4a864415b9bdf66122fd32a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "801973e0b81d7db5f4a864415b9bdf66122fd32a"
},
"details": {
"image": {
"imageId": "sha256:e426653b19315f64dd544715bf8bafcbec90f995d05992394635676200731ba4",
"tag": "2024.07.03.07.31.54.master"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.07.03.07.31.54.master

stack.yml
* **master**
armory/kayenta-armory:2024.07.04.08.11.30.master
[555a345c9f2847d4ac0e2bf9eed9cc2c6ec991e7](https://github.com/armory-io/kayenta-armory/commit/555a345c9f2847d4ac0e2bf9eed9cc2c6ec991e7)
[0681788314822ec6201777614a745eefe2545692](https://github.com/spinnaker/kayenta/commit/0681788314822ec6201777614a745eefe2545692)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0681788314822ec6201777614a745eefe2545692"
},
"details": {
"image": {
"imageId": "sha256:a8bca07817efac2935f1d6420194f896932c5b7decdcf7dd9cf31324b501f15a",
"tag": "2024.07.04.08.11.30.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update kayenta-armory version to 2024.07.04.08.11.30.master

stack.yml
* **master**
armory/deck-armory:2024.07.09.23.35.02.master
[021c3852b16aa6535ef07930f5a52753200302d7](https://github.com/armory-io/deck-armory/commit/021c3852b16aa6535ef07930f5a52753200302d7)
[ec9f1e7c5102a849eae7f7e6ff24cbb88df98269](https://github.com/spinnaker/deck/commit/ec9f1e7c5102a849eae7f7e6ff24cbb88df98269)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "ec9f1e7c5102a849eae7f7e6ff24cbb88df98269"
},
"details": {
"image": {
"imageId": "sha256:f7ac9709c068fa3942873666f5cc4475081844d943b28e4fbed7d5a435e11d8f",
"tag": "2024.07.09.23.35.02.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update deck-armory version to 2024.07.09.23.35.02.master

stack.yml
* **master**
armory/clouddriver-armory:2024.07.10.00.10.14.master
[2e3bd386ed4cda644c5f5acd380cd130897fb71c](https://github.com/armory-io/clouddriver-armory/commit/2e3bd386ed4cda644c5f5acd380cd130897fb71c)
[dc19c3c0b795cc5ae0dc1f3f6a1a889c0460a6b1](https://github.com/spinnaker/clouddriver/commit/dc19c3c0b795cc5ae0dc1f3f6a1a889c0460a6b1)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "dc19c3c0b795cc5ae0dc1f3f6a1a889c0460a6b1"
},
"details": {
"image": {
"imageId": "sha256:ecec5e83f13d68e66729d31e98291d8e7a3421f55ac103251d22d20c30065c72",
"tag": "2024.07.10.00.10.14.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.07.10.00.10.14.master

stack.yml
* **master**
armory/echo-armory:2024.07.09.16.35.39.master
[ecab631778dd1b8d7c2916f7c1f43e7b3bd2ee6a](https://github.com/armory-io/echo-armory/commit/ecab631778dd1b8d7c2916f7c1f43e7b3bd2ee6a)
[d97ff355df8f2978bbc906c069309ddcd1ebb590](https://github.com/spinnaker/echo/commit/d97ff355df8f2978bbc906c069309ddcd1ebb590)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d97ff355df8f2978bbc906c069309ddcd1ebb590"
},
"details": {
"image": {
"imageId": "sha256:79d7aa2d01163a8024c242fd2844fe6679b672adfcc63dcd33c7f8dfa5d55c14",
"tag": "2024.07.09.16.35.39.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2024.07.09.16.35.39.master

stack.yml
armory/dinghy:2024.07.09.20.13.40.release-2.34.x
[fbba492fb3d6c116d75f9ca959f6b5d84ab473a6](https://github.com/armory-io/dinghy/commit/fbba492fb3d6c116d75f9ca959f6b5d84ab473a6)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:ae5fefacf7a49dc51125443ac73b66afadcc8bdf1bb772252a897471e1546460",
"tag": "2024.07.09.20.13.40.release-2.34.x"
},
"vcs": {
"repo": {
},
"sha": "fbba492fb3d6c116d75f9ca959f6b5d84ab473a6"
}
},
},
"details": {
"image": {
"imageId": "sha256:ae5fefacf7a49dc51125443ac73b66afadcc8bdf1bb772252a897471e1546460", …
```
=> chore(cd): update dinghy version to 2024.07.09.20.13.40.release-2.34.x

stack.yml
* **master**
armory/orca-armory:2024.07.11.06.38.07.master
[dc7d894db4d1c1dbd618cae361509f77daa241df](https://github.com/armory-io/orca-armory/commit/dc7d894db4d1c1dbd618cae361509f77daa241df)
[efc0f2a840d81f73ace519a2f0bb652f5e7addf3](https://github.com/spinnaker/orca/commit/efc0f2a840d81f73ace519a2f0bb652f5e7addf3)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "efc0f2a840d81f73ace519a2f0bb652f5e7addf3"
},
"details": {
"image": {
"imageId": "sha256:ab42acb090d6e4122d1b2952f2da2e358332264c7199af0480903204c1e210e5",
"tag": "2024.07.11.06.38.07.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update orca-armory version to 2024.07.11.06.38.07.master

stack.yml
armory/orca-armory:2024.07.17.09.36.19.release-2.34.x
[b52430340a82dd536d4e6d13c5b9b44962452ff2](https://github.com/armory-io/orca-armory/commit/b52430340a82dd536d4e6d13c5b9b44962452ff2)
[69084612ddd9f074c5ef1b2b5e008d4a3f59bb11](https://github.com/spinnaker/orca/commit/69084612ddd9f074c5ef1b2b5e008d4a3f59bb11)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "69084612ddd9f074c5ef1b2b5e008d4a3f59bb11"
},
"details": {
"image": {
"imageId": "sha256:870dca84f7d5c01694bd8b2f8dc8074a92f945ab4e6db2009529392a7a2780c7",
"tag": "2024.07.17.09.36.19.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2024.07.17.09.36.19.release-2.34.x

stack.yml
* **master**
armory/orca-armory:2024.07.17.09.49.39.master
[def643bb584dd98439c5b3b23a9b02c96bc234bb](https://github.com/armory-io/orca-armory/commit/def643bb584dd98439c5b3b23a9b02c96bc234bb)
[f28f2955c601246429c5e1eb2d4bd6d8fca84225](https://github.com/spinnaker/orca/commit/f28f2955c601246429c5e1eb2d4bd6d8fca84225)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f28f2955c601246429c5e1eb2d4bd6d8fca84225"
},
"details": {
"image": {
"imageId": "sha256:eac5fd89f79bcebe8de9b0d0d0405e1b6bba9ef579af59575ca3c776700ea1a2",
"tag": "2024.07.17.09.49.39.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update orca-armory version to 2024.07.17.09.49.39.master

stack.yml
* **master**
armory/clouddriver-armory:2024.07.16.21.21.59.master
[c7540c52d738ca606fb88fe77c04d7e9589534c3](https://github.com/armory-io/clouddriver-armory/commit/c7540c52d738ca606fb88fe77c04d7e9589534c3)
[a71e9bd94f04872027bdd418f35e71ff0d5bbbf9](https://github.com/spinnaker/clouddriver/commit/a71e9bd94f04872027bdd418f35e71ff0d5bbbf9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a71e9bd94f04872027bdd418f35e71ff0d5bbbf9"
},
"details": {
"image": {
"imageId": "sha256:4419838a45881dc93e522a225742b5d07e517516833b42db3c3252f27e01ff5b",
"tag": "2024.07.16.21.21.59.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.07.16.21.21.59.master

stack.yml
* **master**
armory/echo-armory:2024.07.11.21.53.40.master
[35ad987cdbc8bc8f9ac025a48b6bfa27ebed94ec](https://github.com/armory-io/echo-armory/commit/35ad987cdbc8bc8f9ac025a48b6bfa27ebed94ec)
[01ada0ca93bb03669a8bea94414fd44771eb7290](https://github.com/spinnaker/echo/commit/01ada0ca93bb03669a8bea94414fd44771eb7290)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "01ada0ca93bb03669a8bea94414fd44771eb7290"
},
"details": {
"image": {
"imageId": "sha256:4748286f20a2974a122d52a880b9d663dc29457c1d0cf0265a0b9d2bbb6ba0fb",
"tag": "2024.07.11.21.53.40.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2024.07.11.21.53.40.master

stack.yml
* **master**
armory/gate-armory:2024.07.12.18.00.49.master
[92a71fe4570c3fa4e79ae08bd307f867c43b6db6](https://github.com/armory-io/gate-armory/commit/92a71fe4570c3fa4e79ae08bd307f867c43b6db6)
[ae6eddce91999bb17da5613cbb5ba16d13a647af](https://github.com/spinnaker/gate/commit/ae6eddce91999bb17da5613cbb5ba16d13a647af)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "ae6eddce91999bb17da5613cbb5ba16d13a647af"
},
"details": {
"image": {
"imageId": "sha256:51e29dc5447832a34732397af1144625e6007b3390197e22e44541142def02c8",
"tag": "2024.07.12.18.00.49.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update gate-armory version to 2024.07.12.18.00.49.master

stack.yml
* **master**
armory/gate-armory:2024.07.17.16.56.52.master
[c331f47a3010d206ce3a4234c94671f20789fd82](https://github.com/armory-io/gate-armory/commit/c331f47a3010d206ce3a4234c94671f20789fd82)
[ae6eddce91999bb17da5613cbb5ba16d13a647af](https://github.com/spinnaker/gate/commit/ae6eddce91999bb17da5613cbb5ba16d13a647af)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "ae6eddce91999bb17da5613cbb5ba16d13a647af"
},
"details": {
"image": {
"imageId": "sha256:22a0f65a079b658edcc343dc205a27637a637de11cb74bc201bc05f4041b3cd7",
"tag": "2024.07.17.16.56.52.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update gate-armory version to 2024.07.17.16.56.52.master

stack.yml
* **master**
armory/front50-armory:2024.07.17.18.23.35.master
[db0939e48e6ba5e25d940ca57cd01c5fda444f46](https://github.com/armory-io/front50-armory/commit/db0939e48e6ba5e25d940ca57cd01c5fda444f46)
[c8c6d4bea47f9639147a84ea1c0355ecca2205b8](https://github.com/spinnaker/front50/commit/c8c6d4bea47f9639147a84ea1c0355ecca2205b8)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c8c6d4bea47f9639147a84ea1c0355ecca2205b8"
},
"details": {
"image": {
"imageId": "sha256:bc03c69f60c946bdd2e988e8fc8aa057a5f7ef6d2382aef92c0d3ece2ced9b6f",
"tag": "2024.07.17.18.23.35.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update front50-armory version to 2024.07.17.18.23.35.master

stack.yml
* **master**
armory/clouddriver-armory:2024.07.17.17.41.54.master
[1d4bbe658d2a4284dec7fe1ca0d949d1f80e9d11](https://github.com/armory-io/clouddriver-armory/commit/1d4bbe658d2a4284dec7fe1ca0d949d1f80e9d11)
[a5fc30d55d354d3cff929a67f2ad2cd028055920](https://github.com/spinnaker/clouddriver/commit/a5fc30d55d354d3cff929a67f2ad2cd028055920)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a5fc30d55d354d3cff929a67f2ad2cd028055920"
},
"details": {
"image": {
"imageId": "sha256:87d8592b620404f8acff99cf00981adbd0ee2db65dfb3b797896221ed29ef059",
"tag": "2024.07.17.17.41.54.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.07.17.17.41.54.master

stack.yml
* **master**
armory/igor-armory:2024.07.17.18.30.57.master
[4cdb1bc21c2fcb3bae28e25747e04e8a574e69e8](https://github.com/armory-io/igor-armory/commit/4cdb1bc21c2fcb3bae28e25747e04e8a574e69e8)
[65b1cc83fd9ec9cfac23d83335133e7afe4dc7bb](https://github.com/spinnaker/igor/commit/65b1cc83fd9ec9cfac23d83335133e7afe4dc7bb)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "65b1cc83fd9ec9cfac23d83335133e7afe4dc7bb"
},
"details": {
"image": {
"imageId": "sha256:fa3068ca1fe3b659bcb580c5fb9d7b8978c0b896d82263ccc884ea8a3f0a53e1",
"tag": "2024.07.17.18.30.57.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update igor-armory version to 2024.07.17.18.30.57.master

stack.yml
* **master**
armory/gate-armory:2024.07.17.18.28.05.master
[a7f2668ab64779406f6d69d173421fcc2067692e](https://github.com/armory-io/gate-armory/commit/a7f2668ab64779406f6d69d173421fcc2067692e)
[d80e264db66c97abbee23581271e8b5e52bc95e0](https://github.com/spinnaker/gate/commit/d80e264db66c97abbee23581271e8b5e52bc95e0)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d80e264db66c97abbee23581271e8b5e52bc95e0"
},
"details": {
"image": {
"imageId": "sha256:ee02e0ec69ef9006b33d72acee6cabe4ced232b1e605e10b7944189b5f77e144",
"tag": "2024.07.17.18.28.05.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update gate-armory version to 2024.07.17.18.28.05.master

stack.yml
* **master**
armory/echo-armory:2024.07.18.11.25.17.master
[ee04979353c1cdc26275144778e01b27ca1d43fc](https://github.com/armory-io/echo-armory/commit/ee04979353c1cdc26275144778e01b27ca1d43fc)
[e84263ec6ac1c2b8f140231fcab3fcc2719260bf](https://github.com/spinnaker/echo/commit/e84263ec6ac1c2b8f140231fcab3fcc2719260bf)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e84263ec6ac1c2b8f140231fcab3fcc2719260bf"
},
"details": {
"image": {
"imageId": "sha256:fa91bdcc7f322ca70df2758d42ea3c7c717223430588fe061e1516d87110b147",
"tag": "2024.07.18.11.25.17.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2024.07.18.11.25.17.master

stack.yml
* **master**
armory/echo-armory:2024.07.19.14.16.23.master
[d6626dcfd85cab785a9e5229b7fbf205f676c2a5](https://github.com/armory-io/echo-armory/commit/d6626dcfd85cab785a9e5229b7fbf205f676c2a5)
[41b334aa811fe3eef0a9cd62237664fd4bbe97bb](https://github.com/spinnaker/echo/commit/41b334aa811fe3eef0a9cd62237664fd4bbe97bb)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "41b334aa811fe3eef0a9cd62237664fd4bbe97bb"
},
"details": {
"image": {
"imageId": "sha256:546d5cf61b6d0f645df7cb5f5ec838bb99f694c665c62db3de06cc15c2d4a716",
"tag": "2024.07.19.14.16.23.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2024.07.19.14.16.23.master

stack.yml
* **master**
armory/terraformer:2024.07.19.17.05.08.master
[9756bee07eaabbb25b54812996314c22554ec1c0](https://github.com/armory-io/terraformer/commit/9756bee07eaabbb25b54812996314c22554ec1c0)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:3c7b5dbc87c297f9e1d61b74fc4f295146d34bdaf8e74970b846963c7ad8d1c3",
"tag": "2024.07.19.17.05.08.master"
},
"vcs": {
"repo": {
},
"sha": "9756bee07eaabbb25b54812996314c22554ec1c0"
}
},
},
"details": {
"image": {
"imageId": "sha256:3c7b5dbc87c297f9e1d61b74fc4f295146d34bdaf8e74970b846963c7ad8d1c3", …
```
=> chore(cd): update terraformer version to 2024.07.19.17.05.08.master

stack.yml
* **master**
armory/front50-armory:2024.07.23.03.06.51.master
[99aa00fb6d4c26a3b771704c835f0b93921f0da2](https://github.com/armory-io/front50-armory/commit/99aa00fb6d4c26a3b771704c835f0b93921f0da2)
[edfe564228de84efbe805705453440e096799802](https://github.com/spinnaker/front50/commit/edfe564228de84efbe805705453440e096799802)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "edfe564228de84efbe805705453440e096799802"
},
"details": {
"image": {
"imageId": "sha256:330ea2699fbb899da16e662e81a3b727fefe289e46cd62cc2c2faf350de66e4f",
"tag": "2024.07.23.03.06.51.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update front50-armory version to 2024.07.23.03.06.51.master

stack.yml
* **master**
armory/echo-armory:2024.07.30.19.01.51.master
[e0e16553752e35905e5b3fa7781e8458bbeb5ac5](https://github.com/armory-io/echo-armory/commit/e0e16553752e35905e5b3fa7781e8458bbeb5ac5)
[4767363942b4f043f0d89c3ea8364c830b7eeaba](https://github.com/spinnaker/echo/commit/4767363942b4f043f0d89c3ea8364c830b7eeaba)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4767363942b4f043f0d89c3ea8364c830b7eeaba"
},
"details": {
"image": {
"imageId": "sha256:96a5b1150f255e6c7cbc6c52e267f5ef9239cb8f31239758576e6cad70797d6f",
"tag": "2024.07.30.19.01.51.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2024.07.30.19.01.51.master

stack.yml
* **master**
armory/igor-armory:2024.07.30.18.59.35.master
[61083f802adc25604eb0e08c0b0e997523716a92](https://github.com/armory-io/igor-armory/commit/61083f802adc25604eb0e08c0b0e997523716a92)
[e7cb75baba61490995257f206e57c1496b76fd79](https://github.com/spinnaker/igor/commit/e7cb75baba61490995257f206e57c1496b76fd79)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e7cb75baba61490995257f206e57c1496b76fd79"
},
"details": {
"image": {
"imageId": "sha256:c6101ceb606da64280d4382327196332a7aeaea4ced55b6329d424051ef36d05",
"tag": "2024.07.30.18.59.35.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update igor-armory version to 2024.07.30.18.59.35.master

stack.yml
* **master**
armory/deck-armory:2024.08.01.18.15.53.master
[576052d6f753979473fde6981d6d93991e0f0ce4](https://github.com/armory-io/deck-armory/commit/576052d6f753979473fde6981d6d93991e0f0ce4)
[52a9601c726c6e1bb5e53ba539034648325634c7](https://github.com/spinnaker/deck/commit/52a9601c726c6e1bb5e53ba539034648325634c7)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "52a9601c726c6e1bb5e53ba539034648325634c7"
},
"details": {
"image": {
"imageId": "sha256:a71dc8440545f53ffe1c3c58c063ce2192062f2093927ce4afe2f27feeece364",
"tag": "2024.08.01.18.15.53.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update deck-armory version to 2024.08.01.18.15.53.master

stack.yml
* **master**
armory/front50-armory:2024.07.30.18.59.46.master
[f0aec15e142e5b93d1a4a461e84370ddf317b887](https://github.com/armory-io/front50-armory/commit/f0aec15e142e5b93d1a4a461e84370ddf317b887)
[dde80079a7d05656448d63e946aeeb55f131f65f](https://github.com/spinnaker/front50/commit/dde80079a7d05656448d63e946aeeb55f131f65f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "dde80079a7d05656448d63e946aeeb55f131f65f"
},
"details": {
"image": {
"imageId": "sha256:e94c778e91a01fcd4006c6ad2a0679df88c625157e754981460229c6706dfdd6",
"tag": "2024.07.30.18.59.46.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update front50-armory version to 2024.07.30.18.59.46.master

stack.yml
* **master**
armory/gate-armory:2024.07.31.16.36.18.master
[3d553f1d962a4cfc62189118269e2f21234b1d2a](https://github.com/armory-io/gate-armory/commit/3d553f1d962a4cfc62189118269e2f21234b1d2a)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:a359856afe916eb254a8d48a24daf5d40067011f56d96501ac1c740af7a29d62",
"tag": "2024.07.31.16.36.18.master"
},
"vcs": {
"repo": {
},
"sha": "3d553f1d962a4cfc62189118269e2f21234b1d2a"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update gate-armory version to 2024.07.31.16.36.18.master

stack.yml
armory/igor-armory:2024.08.26.12.06.51.release-2.32.x
[c4e429724d83aae802796cda7c5d9b39ce6efba1](https://github.com/armory-io/igor-armory/commit/c4e429724d83aae802796cda7c5d9b39ce6efba1)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:c4abda205695da3f2d6c1c65aa33a13e966413369257000e3ac2bd69073e6296",
"tag": "2024.08.26.12.06.51.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "c4e429724d83aae802796cda7c5d9b39ce6efba1"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update igor-armory version to 2024.08.26.12.06.51.release-2.32.x

stack.yml
armory/deck-armory:2024.08.08.19.36.58.release-2.32.x
[9f22fea76ec0ce4ad425a09fd5793372d077f243](https://github.com/armory-io/deck-armory/commit/9f22fea76ec0ce4ad425a09fd5793372d077f243)
[bd7a13d2f8d940e36b74197ad324fff072c0e990](https://github.com/spinnaker/deck/commit/bd7a13d2f8d940e36b74197ad324fff072c0e990)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "bd7a13d2f8d940e36b74197ad324fff072c0e990"
},
"details": {
"image": {
"imageId": "sha256:1a7cb90f04255f2e134390db73b14258c5af444e93976634f4d48c4a65b1d343",
"tag": "2024.08.08.19.36.58.release-2.32.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2024.08.08.19.36.58.release-2.32.x

stack.yml
armory/echo-armory:2024.08.26.10.56.51.release-2.32.x
[e376d0eb3f19fd3027820bb013b0fbf9fee98e55](https://github.com/armory-io/echo-armory/commit/e376d0eb3f19fd3027820bb013b0fbf9fee98e55)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:cd2c51a88f7399587b104a58af824304c1f5b1faccdf424d9658460ed363cd73",
"tag": "2024.08.26.10.56.51.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "e376d0eb3f19fd3027820bb013b0fbf9fee98e55"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update echo-armory version to 2024.08.26.10.56.51.release-2.32.x

stack.yml
armory/gate-armory:2024.08.26.11.53.09.release-2.32.x
[9a3705729990d170a142b297d2df150fac71bf0f](https://github.com/armory-io/gate-armory/commit/9a3705729990d170a142b297d2df150fac71bf0f)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:ff50a30edb661f5458591e4ddef494ac7eeb6495a700ae4cf388ae7f7fd8602d",
"tag": "2024.08.26.11.53.09.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "9a3705729990d170a142b297d2df150fac71bf0f"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update gate-armory version to 2024.08.26.11.53.09.release-2.32.x

stack.yml
armory/fiat-armory:2024.08.26.11.04.40.release-2.32.x
[b674ce72dc02d7e39008bfbf2a551b3d1cc9544e](https://github.com/armory-io/fiat-armory/commit/b674ce72dc02d7e39008bfbf2a551b3d1cc9544e)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:f3c394901db92183f135896d02857b0323c0b50b7353e8510f8db85ad8b8c25e",
"tag": "2024.08.26.11.04.40.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "b674ce72dc02d7e39008bfbf2a551b3d1cc9544e"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update fiat-armory version to 2024.08.26.11.04.40.release-2.32.x

stack.yml
armory/orca-armory:2024.08.27.09.47.29.release-2.32.x
[9feaae8ddcf27315da951b4a51ffc7f0c4d4ffe6](https://github.com/armory-io/orca-armory/commit/9feaae8ddcf27315da951b4a51ffc7f0c4d4ffe6)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:0b06eb1bfcb5ad719bdffe3e9ed840490e9163ab1546b8aa6263233563298182",
"tag": "2024.08.27.09.47.29.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "9feaae8ddcf27315da951b4a51ffc7f0c4d4ffe6"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update orca-armory version to 2024.08.27.09.47.29.release-2.32.x

stack.yml
armory/front50-armory:2024.08.23.16.29.53.release-2.34.x
[eb8691d3c549c86ba3547b0710828b9f37c62f38](https://github.com/armory-io/front50-armory/commit/eb8691d3c549c86ba3547b0710828b9f37c62f38)
[27526ee8add36981b823e27ccddc07901142211b](https://github.com/spinnaker/front50/commit/27526ee8add36981b823e27ccddc07901142211b)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "27526ee8add36981b823e27ccddc07901142211b"
},
"details": {
"image": {
"imageId": "sha256:fc3113c052cd8f8f82ab2778594dd2006705b972cc4fbff4601fe51768b4f06b",
"tag": "2024.08.23.16.29.53.release-2.34.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update front50-armory version to 2024.08.23.16.29.53.release-2.34.x

stack.yml
armory/fiat-armory:2024.08.17.00.10.41.release-2.34.x
[df367d6ed0185b61abcea1e943109503a4b7928b](https://github.com/armory-io/fiat-armory/commit/df367d6ed0185b61abcea1e943109503a4b7928b)
[e144e4d22322a452fc289f50f35b5e82aaf3f33b](https://github.com/spinnaker/fiat/commit/e144e4d22322a452fc289f50f35b5e82aaf3f33b)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e144e4d22322a452fc289f50f35b5e82aaf3f33b"
},
"details": {
"image": {
"imageId": "sha256:b13665070b8fe9f0e37a76987bf2a579bd03781d77c73a735a81eeb0d12cc0b7",
"tag": "2024.08.17.00.10.41.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update fiat-armory version to 2024.08.17.00.10.41.release-2.34.x

stack.yml
armory/rosco-armory:2024.08.17.00.15.24.release-2.34.x
[f0e9fdb04e392820324f5edb72c0ff46b5307701](https://github.com/armory-io/rosco-armory/commit/f0e9fdb04e392820324f5edb72c0ff46b5307701)
[8adc69835b436a30e6c56aec562a8d86b43f93c9](https://github.com/spinnaker/rosco/commit/8adc69835b436a30e6c56aec562a8d86b43f93c9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "8adc69835b436a30e6c56aec562a8d86b43f93c9"
},
"details": {
"image": {
"imageId": "sha256:f24a5d364008a398903d57cec000c57080ddf5fd6538fad0ed9b559d522e378d",
"tag": "2024.08.17.00.15.24.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.08.17.00.15.24.release-2.34.x

stack.yml
* **master**
armory/echo-armory:2024.08.13.08.31.18.master
[6db8090d156ddf882228db5ceaab99098a144331](https://github.com/armory-io/echo-armory/commit/6db8090d156ddf882228db5ceaab99098a144331)
[de49e97a1516469bdbcd5dc5a92473f93b4d51f2](https://github.com/spinnaker/echo/commit/de49e97a1516469bdbcd5dc5a92473f93b4d51f2)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "de49e97a1516469bdbcd5dc5a92473f93b4d51f2"
},
"details": {
"image": {
"imageId": "sha256:cd9817b548f46c39101d18f4c80fda2d56be97cc6d19cc2b77547df6441879a0",
"tag": "2024.08.13.08.31.18.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2024.08.13.08.31.18.master

stack.yml
armory/deck-armory:2024.08.08.19.37.13.release-2.34.x
[4e15526f16000326035436c57783415b5e5c1d72](https://github.com/armory-io/deck-armory/commit/4e15526f16000326035436c57783415b5e5c1d72)
[7126789353fe5cb111d5aa9abc8bad5cb81413f4](https://github.com/spinnaker/deck/commit/7126789353fe5cb111d5aa9abc8bad5cb81413f4)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7126789353fe5cb111d5aa9abc8bad5cb81413f4"
},
"details": {
"image": {
"imageId": "sha256:5a19d63f8086601928cd9a73c09bdaa4cace609e3424817115841b81e13f445b",
"tag": "2024.08.08.19.37.13.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2024.08.08.19.37.13.release-2.34.x

stack.yml
* **master**
armory/igor-armory:2024.08.13.08.29.02.master
[65e00075f9686ee328806d7ea18e865d16ef7591](https://github.com/armory-io/igor-armory/commit/65e00075f9686ee328806d7ea18e865d16ef7591)
[d1e6fd1f52affedf3a2d963c2ecf99c2d209b97c](https://github.com/spinnaker/igor/commit/d1e6fd1f52affedf3a2d963c2ecf99c2d209b97c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d1e6fd1f52affedf3a2d963c2ecf99c2d209b97c"
},
"details": {
"image": {
"imageId": "sha256:0e95055e5da77e8b4921583066d9f050c537cfad35e71c89a9b73afd9ba0f40e",
"tag": "2024.08.13.08.29.02.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update igor-armory version to 2024.08.13.08.29.02.master

stack.yml
armory/gate-armory:2024.08.17.03.44.12.release-2.34.x
[f54a45abcf7a622e4233e471723c2b54d3972c5d](https://github.com/armory-io/gate-armory/commit/f54a45abcf7a622e4233e471723c2b54d3972c5d)
[0ee70bb6f83f447d910aecf17b8d431a05606722](https://github.com/spinnaker/gate/commit/0ee70bb6f83f447d910aecf17b8d431a05606722)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0ee70bb6f83f447d910aecf17b8d431a05606722"
},
"details": {
"image": {
"imageId": "sha256:b36d04d49632cf2d09070d034ed777331d5e1602611c5107d200c50fe358c263",
"tag": "2024.08.17.03.44.12.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update gate-armory version to 2024.08.17.03.44.12.release-2.34.x

stack.yml
* **master**
armory/deck-armory:2024.08.21.12.12.52.master
[908007967dd4e8b96f0ab63e16f894c5fd1b7a3f](https://github.com/armory-io/deck-armory/commit/908007967dd4e8b96f0ab63e16f894c5fd1b7a3f)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:19e8add3523f7123926e4261f1992a50e1b946ce54fc6b0c21c0f7755ce6edc0",
"tag": "2024.08.21.12.12.52.master"
},
"vcs": {
"repo": {
},
"sha": "908007967dd4e8b96f0ab63e16f894c5fd1b7a3f"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update deck-armory version to 2024.08.21.12.12.52.master

stack.yml
armory/echo-armory:2024.08.21.11.09.00.release-2.34.x
[391b1f4924679a0ce23c216d4b0d8bc4cfdd9ed5](https://github.com/armory-io/echo-armory/commit/391b1f4924679a0ce23c216d4b0d8bc4cfdd9ed5)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:82a27b9c28a10d2a9e8356da8cc856f7300631779c7ff35e4bea909b9da96598",
"tag": "2024.08.21.11.09.00.release-2.34.x"
},
"vcs": {
"repo": {
},
"sha": "391b1f4924679a0ce23c216d4b0d8bc4cfdd9ed5"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update echo-armory version to 2024.08.21.11.09.00.release-2.34.x

stack.yml
armory/orca-armory:2024.08.17.03.50.04.release-2.34.x
[9385c93a4ce4f30a5484989b0b9913b6cd7e24d6](https://github.com/armory-io/orca-armory/commit/9385c93a4ce4f30a5484989b0b9913b6cd7e24d6)
[0de6415a4cceb25b6f807879c8500442c58930a1](https://github.com/spinnaker/orca/commit/0de6415a4cceb25b6f807879c8500442c58930a1)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0de6415a4cceb25b6f807879c8500442c58930a1"
},
"details": {
"image": {
"imageId": "sha256:8762860f27108224f7eb76a8abe4bdbb688859568878dbc6f4843c0ecb5c31e2",
"tag": "2024.08.17.03.50.04.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2024.08.17.03.50.04.release-2.34.x

stack.yml
* **master**
armory/orca-armory:2024.08.28.15.59.45.master
[5f2a306c7e321075ef0254f9bdf557a8d8b77c5c](https://github.com/armory-io/orca-armory/commit/5f2a306c7e321075ef0254f9bdf557a8d8b77c5c)
[eb61f0e25330b2c2a34d543e63e59f6be95de859](https://github.com/spinnaker/orca/commit/eb61f0e25330b2c2a34d543e63e59f6be95de859)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "eb61f0e25330b2c2a34d543e63e59f6be95de859"
},
"details": {
"image": {
"imageId": "sha256:4b1d5cb430f7d4e01840f2e8377c59d1c4a5ac8629af17342463f881f25cf3b7",
"tag": "2024.08.28.15.59.45.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update orca-armory version to 2024.08.28.15.59.45.master

stack.yml
* **master**
armory/gate-armory:2024.08.23.20.02.41.master
[92e8190cdbbb17b2a8175fd3869ee441a838aafd](https://github.com/armory-io/gate-armory/commit/92e8190cdbbb17b2a8175fd3869ee441a838aafd)
[47f666f9b5afbe2549064968a64baad8d6d6feb1](https://github.com/spinnaker/gate/commit/47f666f9b5afbe2549064968a64baad8d6d6feb1)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "47f666f9b5afbe2549064968a64baad8d6d6feb1"
},
"details": {
"image": {
"imageId": "sha256:9ab0f6bd86b694f6605bf7f2918aa222aeb800ef14ed2158ce68b0163e748acc",
"tag": "2024.08.23.20.02.41.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update gate-armory version to 2024.08.23.20.02.41.master

stack.yml
* **master**
armory/kayenta-armory:2024.08.13.23.49.45.master
[cd8c133cdc7f9e682ac135069abfb5e859fb81e1](https://github.com/armory-io/kayenta-armory/commit/cd8c133cdc7f9e682ac135069abfb5e859fb81e1)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:f224a59f5982e0a2438a237d254a885119e96b07d3fe712dcb9bc77152a713e7",
"tag": "2024.08.13.23.49.45.master"
},
"vcs": {
"repo": {
},
"sha": "cd8c133cdc7f9e682ac135069abfb5e859fb81e1"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update kayenta-armory version to 2024.08.13.23.49.45.master

stack.yml
armory/igor-armory:2024.08.17.03.28.10.release-2.34.x
[0ddc88fc33b097ca8d822e91591218c2216dbbc2](https://github.com/armory-io/igor-armory/commit/0ddc88fc33b097ca8d822e91591218c2216dbbc2)
[f30dce4da0b339379b805276702ea3c67c461df2](https://github.com/spinnaker/igor/commit/f30dce4da0b339379b805276702ea3c67c461df2)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f30dce4da0b339379b805276702ea3c67c461df2"
},
"details": {
"image": {
"imageId": "sha256:db07233988e3c84fefd981ec5f99e56fbd51d497dc5cc95fcde8685b248c4197",
"tag": "2024.08.17.03.28.10.release-2.34.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update igor-armory version to 2024.08.17.03.28.10.release-2.34.x

stack.yml
armory/kayenta-armory:2024.08.17.06.20.01.release-2.34.x
[b8983452be0897fc98a6c47d84f8689a9e0e623b](https://github.com/armory-io/kayenta-armory/commit/b8983452be0897fc98a6c47d84f8689a9e0e623b)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:d61b354064932e75ede580f9af4aba4c6560cfbdda1cd2629e805973d3bde688",
"tag": "2024.08.17.06.20.01.release-2.34.x"
},
"vcs": {
"repo": {
},
"sha": "b8983452be0897fc98a6c47d84f8689a9e0e623b"
}
},
},
"details": { …
```
=> chore(cd): update kayenta-armory version to 2024.08.17.06.20.01.release-2.34.x

stack.yml
* **master**
armory/fiat-armory:2024.08.26.10.09.17.master
[879caa8edb293a713991aff56e5e95d0019895fe](https://github.com/armory-io/fiat-armory/commit/879caa8edb293a713991aff56e5e95d0019895fe)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:fe665cd386a269be0886eab48546dce2019cae454474e38c0bad280fe7102099",
"tag": "2024.08.26.10.09.17.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update fiat-armory version to 2024.08.26.10.09.17.master

stack.yml
* **master**
armory/rosco-armory:2024.08.26.15.52.14.master
[9980810bd0d9f684acf01e931d197473dc136c58](https://github.com/armory-io/rosco-armory/commit/9980810bd0d9f684acf01e931d197473dc136c58)
[28269adcb859848dd261a48c6290a428c8c97af8](https://github.com/spinnaker/rosco/commit/28269adcb859848dd261a48c6290a428c8c97af8)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "28269adcb859848dd261a48c6290a428c8c97af8"
},
"details": {
"image": {
"imageId": "sha256:dab335beeec927bb64d91e55bff1ed598b75322a1a4f364e832bd56f8f8556d3",
"tag": "2024.08.26.15.52.14.master"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.08.26.15.52.14.master

stack.yml
* **master**
armory/gate-armory:2024.08.30.14.51.28.master
[f6e4b56226f3fe28bb8552644de59287c4573d26](https://github.com/armory-io/gate-armory/commit/f6e4b56226f3fe28bb8552644de59287c4573d26)
[f745fcc762d3d98c6ba27157f914cf70bb5e8766](https://github.com/spinnaker/gate/commit/f745fcc762d3d98c6ba27157f914cf70bb5e8766)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f745fcc762d3d98c6ba27157f914cf70bb5e8766"
},
"details": {
"image": {
"imageId": "sha256:2daa10f426874c0ec1677b4636163d081b5aa8ab1c57224282d5d7234faf6989",
"tag": "2024.08.30.14.51.28.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update gate-armory version to 2024.08.30.14.51.28.master

stack.yml
armory/kayenta-armory:2024.08.27.07.29.25.release-2.32.x
[1d0be49daf965910063c3ee611da1453b4fc5a2a](https://github.com/armory-io/kayenta-armory/commit/1d0be49daf965910063c3ee611da1453b4fc5a2a)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:3de7399843ecb480582896c52eeb53319730d1991e48f61e27c83a95a9e038c2",
"tag": "2024.08.27.07.29.25.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "1d0be49daf965910063c3ee611da1453b4fc5a2a"
}
},
},
"details": { …
```
=> chore(cd): update kayenta-armory version to 2024.08.27.07.29.25.release-2.32.x

stack.yml
armory/rosco-armory:2024.09.03.15.04.20.release-2.32.x
[42bd6d8abb90f78bed7e276b6c4be89890855335](https://github.com/armory-io/rosco-armory/commit/42bd6d8abb90f78bed7e276b6c4be89890855335)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:6a475553c5cab3ed47b03dff1c4fb9a3f9dd4599a393cb85245589247fc006e8",
"tag": "2024.09.03.15.04.20.release-2.32.x"
},
"vcs": {
"repo": {
},
"sha": "42bd6d8abb90f78bed7e276b6c4be89890855335"
}
},
},
"details": {
"image": { …
```
=> chore(cd): update rosco-armory version to 2024.09.03.15.04.20.release-2.32.x

stack.yml
armory/rosco-armory:2024.09.03.14.24.41.release-2.35.x
[65073cbfbd4d6118bde0ebd2475e6e457b0f9267](https://github.com/armory-io/rosco-armory/commit/65073cbfbd4d6118bde0ebd2475e6e457b0f9267)
[28269adcb859848dd261a48c6290a428c8c97af8](https://github.com/spinnaker/rosco/commit/28269adcb859848dd261a48c6290a428c8c97af8)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "28269adcb859848dd261a48c6290a428c8c97af8"
},
"details": {
"image": {
"imageId": "sha256:26cd0d589d7ce677149fa5311a7b53783fe0fd45d715476ab81e5fc68db6d2ef",
"tag": "2024.09.03.14.24.41.release-2.35.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.09.03.14.24.41.release-2.35.x

stack.yml
armory/deck-armory:2024.08.21.12.12.52.release-2.35.x
[908007967dd4e8b96f0ab63e16f894c5fd1b7a3f](https://github.com/armory-io/deck-armory/commit/908007967dd4e8b96f0ab63e16f894c5fd1b7a3f)
[32f0e3d23093308ab426e0dd92efc8f3909f3509](https://github.com/spinnaker/deck/commit/32f0e3d23093308ab426e0dd92efc8f3909f3509)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "32f0e3d23093308ab426e0dd92efc8f3909f3509"
},
"details": {
"image": {
"imageId": "sha256:7c09c27e4d680ef3c3d0c0059a9339a9176cfce9b4001e86743a88e53a072dbb",
"tag": "2024.08.21.12.12.52.release-2.35.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2024.08.21.12.12.52.release-2.35.x

stack.yml
armory/kayenta-armory:2024.09.03.14.41.59.release-2.35.x
[e08abc568b0248f3f698bde375e582f053d59032](https://github.com/armory-io/kayenta-armory/commit/e08abc568b0248f3f698bde375e582f053d59032)
[7eb6d0bc75b4499d8580fc3e65c74f0012fb3439](https://github.com/spinnaker/kayenta/commit/7eb6d0bc75b4499d8580fc3e65c74f0012fb3439)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7eb6d0bc75b4499d8580fc3e65c74f0012fb3439"
},
"details": {
"image": {
"imageId": "sha256:e510c21c066fc59810070cc75db09b6830d267e6257ae1f030be22dca57eec5e",
"tag": "2024.09.03.14.41.59.release-2.35.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update kayenta-armory version to 2024.09.03.14.41.59.release-2.35.x

stack.yml
armory/dinghy:2024.07.01.14.13.27.release-2.35.x
[50041173d1a043493409059e7fa5d7a1a80fb553](https://github.com/armory-io/dinghy/commit/50041173d1a043493409059e7fa5d7a1a80fb553)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:d89895b250277e1f2d56e20b977d7059d57075320a633d554cc1d2a0a0330d2c",
"tag": "2024.07.01.14.13.27.release-2.35.x"
},
"vcs": {
"repo": {
},
"sha": "50041173d1a043493409059e7fa5d7a1a80fb553"
}
},
},
"details": {
"image": {
"imageId": "sha256:d89895b250277e1f2d56e20b977d7059d57075320a633d554cc1d2a0a0330d2c", …
```
=> chore(cd): update dinghy version to 2024.07.01.14.13.27.release-2.35.x

stack.yml
armory/igor-armory:2024.09.03.14.28.51.release-2.35.x
[a0c90450c2d2a5e7219f6efc33d39c4c16e2244d](https://github.com/armory-io/igor-armory/commit/a0c90450c2d2a5e7219f6efc33d39c4c16e2244d)
[d1e6fd1f52affedf3a2d963c2ecf99c2d209b97c](https://github.com/spinnaker/igor/commit/d1e6fd1f52affedf3a2d963c2ecf99c2d209b97c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d1e6fd1f52affedf3a2d963c2ecf99c2d209b97c"
},
"details": {
"image": {
"imageId": "sha256:5e803ffe515cadf28467e6e4b2ed46559f481991f5145bda5ee304d3f7049183",
"tag": "2024.09.03.14.28.51.release-2.35.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update igor-armory version to 2024.09.03.14.28.51.release-2.35.x

stack.yml
armory/front50-armory:2024.09.03.14.24.20.release-2.35.x
[2dac49c31cbeb8a30a9c801a1a020877cceaf84b](https://github.com/armory-io/front50-armory/commit/2dac49c31cbeb8a30a9c801a1a020877cceaf84b)
[2f828b74065412ba5423f4ef4b00735158bda0f5](https://github.com/spinnaker/front50/commit/2f828b74065412ba5423f4ef4b00735158bda0f5)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "2f828b74065412ba5423f4ef4b00735158bda0f5"
},
"details": {
"image": {
"imageId": "sha256:6b6c7cb9af060d0f67b5305a60777c55dd3b3c9c82e992d12d354ffbbe9513a4",
"tag": "2024.09.03.14.24.20.release-2.35.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update front50-armory version to 2024.09.03.14.24.20.release-2.35.x

stack.yml
armory/gate-armory:2024.09.03.14.26.06.release-2.35.x
[f6cbf0584c891895dd2afcfe94d3dbbecd7b0ce5](https://github.com/armory-io/gate-armory/commit/f6cbf0584c891895dd2afcfe94d3dbbecd7b0ce5)
[7373cfe3578b53b19fa7807e0fd1c0c3984ae45e](https://github.com/spinnaker/gate/commit/7373cfe3578b53b19fa7807e0fd1c0c3984ae45e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7373cfe3578b53b19fa7807e0fd1c0c3984ae45e"
},
"details": {
"image": {
"imageId": "sha256:1fb9a677f7d6796d5bb631ee5f93d76edf5e62643a07b947bdc71c24c122db0f",
"tag": "2024.09.03.14.26.06.release-2.35.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update gate-armory version to 2024.09.03.14.26.06.release-2.35.x

stack.yml
armory/orca-armory:2024.09.03.14.24.56.release-2.35.x
[50db0c48e945757be138f2b5671e569eaad480e0](https://github.com/armory-io/orca-armory/commit/50db0c48e945757be138f2b5671e569eaad480e0)
[eb61f0e25330b2c2a34d543e63e59f6be95de859](https://github.com/spinnaker/orca/commit/eb61f0e25330b2c2a34d543e63e59f6be95de859)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "eb61f0e25330b2c2a34d543e63e59f6be95de859"
},
"details": {
"image": {
"imageId": "sha256:c59edde1bd0c3b34f32e1a933989fce88b0b259fa57c9bf0c27897df8d4802d8",
"tag": "2024.09.03.14.24.56.release-2.35.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2024.09.03.14.24.56.release-2.35.x

stack.yml
armory/clouddriver-armory:2024.09.03.14.24.09.release-2.35.x
[ad6ec3b371c3c5c003247578920a06f68d8e9763](https://github.com/armory-io/clouddriver-armory/commit/ad6ec3b371c3c5c003247578920a06f68d8e9763)
[0226100a95b16e1176a296198b1f892c4514e4d6](https://github.com/spinnaker/clouddriver/commit/0226100a95b16e1176a296198b1f892c4514e4d6)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0226100a95b16e1176a296198b1f892c4514e4d6"
},
"details": {
"image": {
"imageId": "sha256:586cee91c950f769ce26493018cc93b448d87615216f5f986aad3739d002bf22",
"tag": "2024.09.03.14.24.09.release-2.35.x"
},
"vcs": …
```
=> chore(cd): update clouddriver-armory version to 2024.09.03.14.24.09.release-2.35.x

stack.yml
armory/fiat-armory:2024.09.03.14.25.08.release-2.35.x
[3e9f8d7828bc6543e0ffe9b38dc57a8469196406](https://github.com/armory-io/fiat-armory/commit/3e9f8d7828bc6543e0ffe9b38dc57a8469196406)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:b4154ff79403c1597402fa87b7473b682e459f9cfd87f62ac8a2fb804fad922f",
"tag": "2024.09.03.14.25.08.release-2.35.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update fiat-armory version to 2024.09.03.14.25.08.release-2.35.x

stack.yml
armory/echo-armory:2024.09.03.14.30.21.release-2.35.x
[f6cac55f5a31e60efdb1241fca2944fabb29f4cd](https://github.com/armory-io/echo-armory/commit/f6cac55f5a31e60efdb1241fca2944fabb29f4cd)
[83a181c36b0a3220d106a4b98a1cbc715b0f964a](https://github.com/spinnaker/echo/commit/83a181c36b0a3220d106a4b98a1cbc715b0f964a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "83a181c36b0a3220d106a4b98a1cbc715b0f964a"
},
"details": {
"image": {
"imageId": "sha256:c98603081f1459f4d27b3b8669c1a2a96cc5ae48baf0e9b8c93020e79148c699",
"tag": "2024.09.03.14.30.21.release-2.35.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2024.09.03.14.30.21.release-2.35.x

stack.yml
* **master**
armory/deck-armory:2024.09.12.18.58.46.master
[2cb91ee66d8284ec9ea04ddcc31597bc4164057d](https://github.com/armory-io/deck-armory/commit/2cb91ee66d8284ec9ea04ddcc31597bc4164057d)
[08b95dfbce3c47b57031f12d004df56b1c4944e8](https://github.com/spinnaker/deck/commit/08b95dfbce3c47b57031f12d004df56b1c4944e8)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "08b95dfbce3c47b57031f12d004df56b1c4944e8"
},
"details": {
"image": {
"imageId": "sha256:670f2b841d11a2927e3403249aaed230cb432645fc31681d5e7b32d8a781eccb",
"tag": "2024.09.12.18.58.46.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update deck-armory version to 2024.09.12.18.58.46.master

stack.yml
* **master**
armory/gate-armory:2024.09.12.20.12.23.master
[7fa7e758bb3fc6ec4ca089416ce5925c510c9382](https://github.com/armory-io/gate-armory/commit/7fa7e758bb3fc6ec4ca089416ce5925c510c9382)
[bd9b2817b23b466c9840bdd5263b5bc18a7de140](https://github.com/spinnaker/gate/commit/bd9b2817b23b466c9840bdd5263b5bc18a7de140)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "bd9b2817b23b466c9840bdd5263b5bc18a7de140"
},
"details": {
"image": {
"imageId": "sha256:ed95e83540059f765e24e41fef8e846a9c26eb22213d3d85d7eda1580d78ab7b",
"tag": "2024.09.12.20.12.23.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update gate-armory version to 2024.09.12.20.12.23.master

stack.yml
* **master**
armory/gate-armory:2024.09.12.23.27.35.master
[b3e7f121afe75ae272e8c8c3ab47727820040759](https://github.com/armory-io/gate-armory/commit/b3e7f121afe75ae272e8c8c3ab47727820040759)
[81b25aa7cb647ee0c9c2aac0fa23755b71037a72](https://github.com/spinnaker/gate/commit/81b25aa7cb647ee0c9c2aac0fa23755b71037a72)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "81b25aa7cb647ee0c9c2aac0fa23755b71037a72"
},
"details": {
"image": {
"imageId": "sha256:8751da14d8cf60daf2b3e22b93be1d360fe19021982bd922a4de49f2720c9f43",
"tag": "2024.09.12.23.27.35.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update gate-armory version to 2024.09.12.23.27.35.master

stack.yml
armory/deck-armory:2024.09.11.17.27.32.release-2.35.x
[b04971d387e1a0664f536427976c0d64733044b5](https://github.com/armory-io/deck-armory/commit/b04971d387e1a0664f536427976c0d64733044b5)
[d2e3a0c4e4d54cb4b539d032783343939165e1fa](https://github.com/spinnaker/deck/commit/d2e3a0c4e4d54cb4b539d032783343939165e1fa)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d2e3a0c4e4d54cb4b539d032783343939165e1fa"
},
"details": {
"image": {
"imageId": "sha256:c9bcd9f22d82aee0d9efa4fe3cdb97053fbb8ed6bc7ad1b23736857c177dd3e4",
"tag": "2024.09.11.17.27.32.release-2.35.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2024.09.11.17.27.32.release-2.35.x

stack.yml
* **master**
armory/gate-armory:2024.09.19.19.19.59.master
[0e86b4ec67e1d44367c6f8418e43050bb861094e](https://github.com/armory-io/gate-armory/commit/0e86b4ec67e1d44367c6f8418e43050bb861094e)
[79dc08e63646c2bd70e39d63f489197913dfbc82](https://github.com/spinnaker/gate/commit/79dc08e63646c2bd70e39d63f489197913dfbc82)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "79dc08e63646c2bd70e39d63f489197913dfbc82"
},
"details": {
"image": {
"imageId": "sha256:2bcf73512affabcbdf99880c544d57889c2540a29d179812c0df72d34720f622",
"tag": "2024.09.19.19.19.59.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update gate-armory version to 2024.09.19.19.19.59.master

stack.yml
* **master**
armory/clouddriver-armory:2024.09.24.14.35.26.master
[f32307d7e632c72ce03aa7ae9b1048e32bf7bb5c](https://github.com/armory-io/clouddriver-armory/commit/f32307d7e632c72ce03aa7ae9b1048e32bf7bb5c)
[031bf1d289769f587f446d61e2fad1c3f8d1aca6](https://github.com/spinnaker/clouddriver/commit/031bf1d289769f587f446d61e2fad1c3f8d1aca6)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "031bf1d289769f587f446d61e2fad1c3f8d1aca6"
},
"details": {
"image": {
"imageId": "sha256:acdd739ce703fb4e7254573cb78f0723f44ec96048ce5f0f1dd98bfb726c9c9b",
"tag": "2024.09.24.14.35.26.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2024.09.24.14.35.26.master

stack.yml
* **master**
armory/front50-armory:2024.09.25.17.08.32.master
[381150e3c0581ec75186f22e8c97086225cbb8bf](https://github.com/armory-io/front50-armory/commit/381150e3c0581ec75186f22e8c97086225cbb8bf)
[ca32115cf1950db2a276d672cbc0ec4fa9c38c06](https://github.com/spinnaker/front50/commit/ca32115cf1950db2a276d672cbc0ec4fa9c38c06)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "ca32115cf1950db2a276d672cbc0ec4fa9c38c06"
},
"details": {
"image": {
"imageId": "sha256:b50aabbe4bf0db81269288b3b64a4fac09cba782c180c9200b4a53b97057ffc1",
"tag": "2024.09.25.17.08.32.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update front50-armory version to 2024.09.25.17.08.32.master

stack.yml
* **master**
armory/echo-armory:2024.09.26.21.05.16.master
[2f1441b2648e9ca204f7d9727eed547faab072a6](https://github.com/armory-io/echo-armory/commit/2f1441b2648e9ca204f7d9727eed547faab072a6)
[7f83d98f3b2885d18b2035ff0ad71886c05eb873](https://github.com/spinnaker/echo/commit/7f83d98f3b2885d18b2035ff0ad71886c05eb873)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7f83d98f3b2885d18b2035ff0ad71886c05eb873"
},
"details": {
"image": {
"imageId": "sha256:e6b24d231149e558ac013d22847dfa0e82c00a48e80ab8051fe29fcfbf9afb86",
"tag": "2024.09.26.21.05.16.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2024.09.26.21.05.16.master

stack.yml
* **master**
armory/orca-armory:2024.09.25.20.10.06.master
[c0466ea7c8156fd3b839ff0744c3de3c5b0788b7](https://github.com/armory-io/orca-armory/commit/c0466ea7c8156fd3b839ff0744c3de3c5b0788b7)
[ae249528097447da3f340f8b24bf0f465769e924](https://github.com/spinnaker/orca/commit/ae249528097447da3f340f8b24bf0f465769e924)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "ae249528097447da3f340f8b24bf0f465769e924"
},
"details": {
"image": {
"imageId": "sha256:4d9e22cb619c18e224ad18432f09f3c6b94580de3ffafa59ca28dbccc553d665",
"tag": "2024.09.25.20.10.06.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update orca-armory version to 2024.09.25.20.10.06.master

stack.yml
armory/echo-armory:2024.11.04.22.50.35.release-2.35.x
[1bb22da7c0c104b25b56271ff3e4016fd0ceda22](https://github.com/armory-io/echo-armory/commit/1bb22da7c0c104b25b56271ff3e4016fd0ceda22)
[83a181c36b0a3220d106a4b98a1cbc715b0f964a](https://github.com/spinnaker/echo/commit/83a181c36b0a3220d106a4b98a1cbc715b0f964a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "83a181c36b0a3220d106a4b98a1cbc715b0f964a"
},
"details": {
"image": {
"imageId": "sha256:9840b81e91160ff9867ada4202ed076f8df6a9bb3fa773840236c097587e50c3",
"tag": "2024.11.04.22.50.35.release-2.35.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2024.11.04.22.50.35.release-2.35.x

stack.yml
armory/igor-armory:2024.11.04.21.27.28.release-2.35.x
[56f0c75e06b79f2e3029b0b0da323a2d6c0dff6f](https://github.com/armory-io/igor-armory/commit/56f0c75e06b79f2e3029b0b0da323a2d6c0dff6f)
[d1e6fd1f52affedf3a2d963c2ecf99c2d209b97c](https://github.com/spinnaker/igor/commit/d1e6fd1f52affedf3a2d963c2ecf99c2d209b97c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d1e6fd1f52affedf3a2d963c2ecf99c2d209b97c"
},
"details": {
"image": {
"imageId": "sha256:13181bed3c9c588dff19d94491cccd9a967a8169e014db48c53839b917bf379f",
"tag": "2024.11.04.21.27.28.release-2.35.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update igor-armory version to 2024.11.04.21.27.28.release-2.35.x

stack.yml
armory/orca-armory:2024.11.04.21.40.24.release-2.35.x
[007b767579a0b983049ae5da7960d8b286462e94](https://github.com/armory-io/orca-armory/commit/007b767579a0b983049ae5da7960d8b286462e94)
[eb61f0e25330b2c2a34d543e63e59f6be95de859](https://github.com/spinnaker/orca/commit/eb61f0e25330b2c2a34d543e63e59f6be95de859)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "eb61f0e25330b2c2a34d543e63e59f6be95de859"
},
"details": {
"image": {
"imageId": "sha256:0fe3891aac61aa9c4e1ddab56abde9a7ef8fb6ff5bbb9c6595e1d46cbb631d32",
"tag": "2024.11.04.21.40.24.release-2.35.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2024.11.04.21.40.24.release-2.35.x

stack.yml
armory/clouddriver-armory:2024.11.04.21.46.18.release-2.35.x
[61870a298437653ac15a109e0e2a4e13dfdb61ca](https://github.com/armory-io/clouddriver-armory/commit/61870a298437653ac15a109e0e2a4e13dfdb61ca)
[c83c7c03c629c507e4dd6b6d8eb4488a7367a1ac](https://github.com/spinnaker/clouddriver/commit/c83c7c03c629c507e4dd6b6d8eb4488a7367a1ac)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c83c7c03c629c507e4dd6b6d8eb4488a7367a1ac"
},
"details": {
"image": {
"imageId": "sha256:8e72352fec959c44322d6ce031e68371456ed07bb02da081fd5af84d7bb042af",
"tag": "2024.11.04.21.46.18.release-2.35.x"
},
"vcs": …
```
=> chore(cd): update clouddriver-armory version to 2024.11.04.21.46.18.release-2.35.x

stack.yml
armory/rosco-armory:2024.11.04.21.56.58.release-2.35.x
[8e22b77b251ee3083cddfa6cdc11e8eaec2dfdb0](https://github.com/armory-io/rosco-armory/commit/8e22b77b251ee3083cddfa6cdc11e8eaec2dfdb0)
[28269adcb859848dd261a48c6290a428c8c97af8](https://github.com/spinnaker/rosco/commit/28269adcb859848dd261a48c6290a428c8c97af8)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "28269adcb859848dd261a48c6290a428c8c97af8"
},
"details": {
"image": {
"imageId": "sha256:8d44db9f514fd481da29ac4484929fb2652c2cc6dd61b1ac7f13d94ade02c530",
"tag": "2024.11.04.21.56.58.release-2.35.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.11.04.21.56.58.release-2.35.x

stack.yml
armory/kayenta-armory:2024.11.04.22.00.40.release-2.35.x
[ac4b20926966e3b984c9b46ae241c5a12e0dddc2](https://github.com/armory-io/kayenta-armory/commit/ac4b20926966e3b984c9b46ae241c5a12e0dddc2)
[7eb6d0bc75b4499d8580fc3e65c74f0012fb3439](https://github.com/spinnaker/kayenta/commit/7eb6d0bc75b4499d8580fc3e65c74f0012fb3439)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7eb6d0bc75b4499d8580fc3e65c74f0012fb3439"
},
"details": {
"image": {
"imageId": "sha256:e9d060273b37614c1d4acdd3ae3f6371391145a18e3f0f3eef9e112381367619",
"tag": "2024.11.04.22.00.40.release-2.35.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update kayenta-armory version to 2024.11.04.22.00.40.release-2.35.x

stack.yml
armory/front50-armory:2024.11.04.22.29.54.release-2.35.x
[900b169d3cea95992d781e22939bb5fa1224a75d](https://github.com/armory-io/front50-armory/commit/900b169d3cea95992d781e22939bb5fa1224a75d)
[210501bfd07eea0275ed06cb724fec6d615573c9](https://github.com/spinnaker/front50/commit/210501bfd07eea0275ed06cb724fec6d615573c9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "210501bfd07eea0275ed06cb724fec6d615573c9"
},
"details": {
"image": {
"imageId": "sha256:9899193b5f99c682c3bee3bd9ae0820c7a4202f32dd5018cc936781c2eee4cef",
"tag": "2024.11.04.22.29.54.release-2.35.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update front50-armory version to 2024.11.04.22.29.54.release-2.35.x

stack.yml
armory/gate-armory:2024.11.04.22.29.31.release-2.35.x
[af49faafbd341109028335630f25c46e9077bc1f](https://github.com/armory-io/gate-armory/commit/af49faafbd341109028335630f25c46e9077bc1f)
[7373cfe3578b53b19fa7807e0fd1c0c3984ae45e](https://github.com/spinnaker/gate/commit/7373cfe3578b53b19fa7807e0fd1c0c3984ae45e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "7373cfe3578b53b19fa7807e0fd1c0c3984ae45e"
},
"details": {
"image": {
"imageId": "sha256:80735d678e9fc801f5198c5ba994d12385edd1b45a6db1af8796c1c92ce42c2a",
"tag": "2024.11.04.22.29.31.release-2.35.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update gate-armory version to 2024.11.04.22.29.31.release-2.35.x

stack.yml
* **master**
armory/echo-armory:2024.11.06.17.51.29.master
[010fe336969f7e55292fce4c2fca4e02033970b9](https://github.com/armory-io/echo-armory/commit/010fe336969f7e55292fce4c2fca4e02033970b9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:067575077b7e653c122984cdb4beba2dccb0e36058f67a4437c3524e0857521d",
"tag": "2024.11.06.17.51.29.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2024.11.06.17.51.29.master

stack.yml
armory/igor-armory:2024.11.26.04.38.15.release-2.36.x
[d28f7260388d131de8a9a36cdbc52d3b8d0d0498](https://github.com/armory-io/igor-armory/commit/d28f7260388d131de8a9a36cdbc52d3b8d0d0498)
[d1e6fd1f52affedf3a2d963c2ecf99c2d209b97c](https://github.com/spinnaker/igor/commit/d1e6fd1f52affedf3a2d963c2ecf99c2d209b97c)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "d1e6fd1f52affedf3a2d963c2ecf99c2d209b97c"
},
"details": {
"image": {
"imageId": "sha256:7219f5c8c7bf11f82821287675025447ccc4d0e0022b861738cdadd9a60eb520",
"tag": "2024.11.26.04.38.15.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update igor-armory version to 2024.11.26.04.38.15.release-2.36.x

stack.yml
armory/fiat-armory:2024.08.26.10.09.17.release-2.36.x
[879caa8edb293a713991aff56e5e95d0019895fe](https://github.com/armory-io/fiat-armory/commit/879caa8edb293a713991aff56e5e95d0019895fe)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:994d7d33cb5926c36b876f32ad7d9e4eee2ada24c67fc81f6303b26716aa925b",
"tag": "2024.08.26.10.09.17.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update fiat-armory version to 2024.08.26.10.09.17.release-2.36.x

stack.yml
armory/dinghy:2024.07.01.14.13.27.release-2.36.x
[50041173d1a043493409059e7fa5d7a1a80fb553](https://github.com/armory-io/dinghy/commit/50041173d1a043493409059e7fa5d7a1a80fb553)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:104826ba8040648b789c00dd6e0a322696be0fc1bc8379ef11f4a08897aa4562",
"tag": "2024.07.01.14.13.27.release-2.36.x"
},
"vcs": {
"repo": {
},
"sha": "50041173d1a043493409059e7fa5d7a1a80fb553"
}
},
},
"details": {
"image": {
"imageId": "sha256:104826ba8040648b789c00dd6e0a322696be0fc1bc8379ef11f4a08897aa4562", …
```
=> chore(cd): update dinghy version to 2024.07.01.14.13.27.release-2.36.x

stack.yml
armory/deck-armory:2024.11.26.04.37.36.release-2.36.x
[384f4d4922031162974496e287e265091551bbb4](https://github.com/armory-io/deck-armory/commit/384f4d4922031162974496e287e265091551bbb4)
[08b95dfbce3c47b57031f12d004df56b1c4944e8](https://github.com/spinnaker/deck/commit/08b95dfbce3c47b57031f12d004df56b1c4944e8)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "08b95dfbce3c47b57031f12d004df56b1c4944e8"
},
"details": {
"image": {
"imageId": "sha256:e7a80369d02bb0e4f3adfbf6a477a67c35f8b093f20cdb9c73e7fc19d50caad5",
"tag": "2024.11.26.04.37.36.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2024.11.26.04.37.36.release-2.36.x

stack.yml
armory/kayenta-armory:2024.11.26.16.27.18.release-2.36.x
[6f3282cc34552b14e053d0d34397d176814fe46c](https://github.com/armory-io/kayenta-armory/commit/6f3282cc34552b14e053d0d34397d176814fe46c)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:56ca000216c1ac8c51e22aad54ca163722ed5796ed95bca350cadbb5a8f1026c",
"tag": "2024.11.26.16.27.18.release-2.36.x"
},
"vcs": {
"repo": {
},
"sha": "6f3282cc34552b14e053d0d34397d176814fe46c"
}
},
},
"details": { …
```
=> chore(cd): update kayenta-armory version to 2024.11.26.16.27.18.release-2.36.x

stack.yml
armory/front50-armory:2024.11.26.04.37.54.release-2.36.x
[1daf85e251e2994278f06eb8f3c7df1d92595df2](https://github.com/armory-io/front50-armory/commit/1daf85e251e2994278f06eb8f3c7df1d92595df2)
[ca32115cf1950db2a276d672cbc0ec4fa9c38c06](https://github.com/spinnaker/front50/commit/ca32115cf1950db2a276d672cbc0ec4fa9c38c06)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "ca32115cf1950db2a276d672cbc0ec4fa9c38c06"
},
"details": {
"image": {
"imageId": "sha256:df9e1a1d8f4255f4565ba9c00cf86ef7b627a7498dd6926e3845c9b6f8be96de",
"tag": "2024.11.26.04.37.54.release-2.36.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update front50-armory version to 2024.11.26.04.37.54.release-2.36.x

stack.yml
armory/clouddriver-armory:2024.11.26.04.37.18.release-2.36.x
[1a304707906cbb57f4ee1bb9931f798881a72926](https://github.com/armory-io/clouddriver-armory/commit/1a304707906cbb57f4ee1bb9931f798881a72926)
[e8a3775c2dc2b0373443a6648d8875430b703199](https://github.com/spinnaker/clouddriver/commit/e8a3775c2dc2b0373443a6648d8875430b703199)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e8a3775c2dc2b0373443a6648d8875430b703199"
},
"details": {
"image": {
"imageId": "sha256:6d13abe616d3ebee5f9e97deb83d447b614bccf0d393c84afdf9186191686712",
"tag": "2024.11.26.04.37.18.release-2.36.x"
},
"vcs": …
```
=> chore(cd): update clouddriver-armory version to 2024.11.26.04.37.18.release-2.36.x

stack.yml
armory/orca-armory:2024.11.26.18.05.37.release-2.36.x
[1684f5e9488abfed6843a340becbd1263787ddd5](https://github.com/armory-io/orca-armory/commit/1684f5e9488abfed6843a340becbd1263787ddd5)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:38490231e04c08c1d71058c5e99f72fbdbceffea9e35faa13a8a4c204a52046b",
"tag": "2024.11.26.18.05.37.release-2.36.x"
},
"vcs": {
"repo": {
},
"sha": "1684f5e9488abfed6843a340becbd1263787ddd5"
}
},
},
"details": {
"image": {
"imageId": …
```
=> chore(cd): update orca-armory version to 2024.11.26.18.05.37.release-2.36.x

stack.yml
armory/rosco-armory:2024.12.02.09.04.29.release-2.36.x
[012ab0799a64a3ed61951888cebb04688bedc40b](https://github.com/armory-io/rosco-armory/commit/012ab0799a64a3ed61951888cebb04688bedc40b)
[28269adcb859848dd261a48c6290a428c8c97af8](https://github.com/spinnaker/rosco/commit/28269adcb859848dd261a48c6290a428c8c97af8)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "28269adcb859848dd261a48c6290a428c8c97af8"
},
"details": {
"image": {
"imageId": "sha256:c74c840f824ebe484fdaa037c2d7a36db1f8b5c11b149264c2c2d6165a24c156",
"tag": "2024.12.02.09.04.29.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.12.02.09.04.29.release-2.36.x

stack.yml
armory/orca-armory:2024.12.13.15.33.09.release-2.35.x
[9e94501096394c824bbfca5be5707d0d2c5f1713](https://github.com/armory-io/orca-armory/commit/9e94501096394c824bbfca5be5707d0d2c5f1713)
[f7c2dd3f5e0f5c714c0243d5884c6fd221b8b280](https://github.com/spinnaker/orca/commit/f7c2dd3f5e0f5c714c0243d5884c6fd221b8b280)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f7c2dd3f5e0f5c714c0243d5884c6fd221b8b280"
},
"details": {
"image": {
"imageId": "sha256:0b03211b6a9fe9879b53b07348951068dc028d811edcff65d5214c7ca8df1ced",
"tag": "2024.12.13.15.33.09.release-2.35.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2024.12.13.15.33.09.release-2.35.x

stack.yml
armory/clouddriver-armory:2024.12.13.19.52.45.release-2.35.x
[a256c81616326e55b654692f924fc950744d7b6c](https://github.com/armory-io/clouddriver-armory/commit/a256c81616326e55b654692f924fc950744d7b6c)
[fb1850b9607a081def5b6e76abacbb4ea312d99e](https://github.com/spinnaker/clouddriver/commit/fb1850b9607a081def5b6e76abacbb4ea312d99e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "fb1850b9607a081def5b6e76abacbb4ea312d99e"
},
"details": {
"image": {
"imageId": "sha256:860b796b816c3dcd3e33361ddc9ca4ffac580df3af6e99491c24ada5e4b136e6",
"tag": "2024.12.13.19.52.45.release-2.35.x"
},
"vcs": …
```
=> chore(cd): update clouddriver-armory version to 2024.12.13.19.52.45.release-2.35.x

stack.yml
armory/rosco-armory:2024.12.23.16.57.23.release-2.35.x
[9259f32ee4c6beb1bf1da32c0161590ecf3de800](https://github.com/armory-io/rosco-armory/commit/9259f32ee4c6beb1bf1da32c0161590ecf3de800)
[59a8c79d04a03fe218a8217a74c24da79a46b7b2](https://github.com/spinnaker/rosco/commit/59a8c79d04a03fe218a8217a74c24da79a46b7b2)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "59a8c79d04a03fe218a8217a74c24da79a46b7b2"
},
"details": {
"image": {
"imageId": "sha256:8d3c2966eb1a2c5c6d05902cc37794adbb9414ab12fbe0a9703290255972eab8",
"tag": "2024.12.23.16.57.23.release-2.35.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.12.23.16.57.23.release-2.35.x

stack.yml
armory/echo-armory:2024.12.23.21.40.50.release-2.35.x
[6117e5941dda2f2faa52639cba5e8449b0a64d0c](https://github.com/armory-io/echo-armory/commit/6117e5941dda2f2faa52639cba5e8449b0a64d0c)
[83a181c36b0a3220d106a4b98a1cbc715b0f964a](https://github.com/spinnaker/echo/commit/83a181c36b0a3220d106a4b98a1cbc715b0f964a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "83a181c36b0a3220d106a4b98a1cbc715b0f964a"
},
"details": {
"image": {
"imageId": "sha256:a7b8b16bacecd04d71479967380e283a20192d5ac73bdfb99ff3ad0d6419bd4b",
"tag": "2024.12.23.21.40.50.release-2.35.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2024.12.23.21.40.50.release-2.35.x

stack.yml
armory/clouddriver-armory:2024.12.13.19.56.56.release-2.36.x
[4cdace1410e84e73c4ea9ac48f9c7a895e3b9976](https://github.com/armory-io/clouddriver-armory/commit/4cdace1410e84e73c4ea9ac48f9c7a895e3b9976)
[966f4e8afaafdd22f7540f176b483f0c19e01edf](https://github.com/spinnaker/clouddriver/commit/966f4e8afaafdd22f7540f176b483f0c19e01edf)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "966f4e8afaafdd22f7540f176b483f0c19e01edf"
},
"details": {
"image": {
"imageId": "sha256:83f0dcf94eb7a0a8e4d2ac59597ecc6a84fc5cdd8e77d99104f1f0dac3fede54",
"tag": "2024.12.13.19.56.56.release-2.36.x"
},
"vcs": …
```
=> chore(cd): update clouddriver-armory version to 2024.12.13.19.56.56.release-2.36.x

stack.yml
armory/orca-armory:2024.12.11.16.10.23.release-2.36.x
[33a22bbfae7101c184c67a4e5c851846b0d62ea3](https://github.com/armory-io/orca-armory/commit/33a22bbfae7101c184c67a4e5c851846b0d62ea3)
[87141f21883f410b86f3a602d9331955d3cfeaff](https://github.com/spinnaker/orca/commit/87141f21883f410b86f3a602d9331955d3cfeaff)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "87141f21883f410b86f3a602d9331955d3cfeaff"
},
"details": {
"image": {
"imageId": "sha256:14e2d51c798bb2f3fca4d919c2d49fda73d974dfa5037a67b314949d217016c4",
"tag": "2024.12.11.16.10.23.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2024.12.11.16.10.23.release-2.36.x

stack.yml
armory/orca-armory:2024.12.24.08.08.44.release-2.36.x
[4878c7cf57648f50b67ee28c96a3895271869543](https://github.com/armory-io/orca-armory/commit/4878c7cf57648f50b67ee28c96a3895271869543)
[87141f21883f410b86f3a602d9331955d3cfeaff](https://github.com/spinnaker/orca/commit/87141f21883f410b86f3a602d9331955d3cfeaff)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "87141f21883f410b86f3a602d9331955d3cfeaff"
},
"details": {
"image": {
"imageId": "sha256:dc2672f9ad01342ae4a2bca2ddf2719832d4a259678cc68151fcb00410b2a908",
"tag": "2024.12.24.08.08.44.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2024.12.24.08.08.44.release-2.36.x

stack.yml
armory/rosco-armory:2024.12.26.16.24.38.release-2.36.x
[32a0a65248c02a34f2c811afd5d02928abe26eeb](https://github.com/armory-io/rosco-armory/commit/32a0a65248c02a34f2c811afd5d02928abe26eeb)
[eccbf4d9bc9b6ea0c6804d4720ed6025a55cbbb0](https://github.com/spinnaker/rosco/commit/eccbf4d9bc9b6ea0c6804d4720ed6025a55cbbb0)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "eccbf4d9bc9b6ea0c6804d4720ed6025a55cbbb0"
},
"details": {
"image": {
"imageId": "sha256:0447b5148ae66d0d72d51cba651b8df23a17167b4aa4462f568952594e8ed5d2",
"tag": "2024.12.26.16.24.38.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2024.12.26.16.24.38.release-2.36.x

stack.yml
armory/clouddriver-armory:2025.01.03.20.58.36.release-2.35.x
[f0e7a7470b06b6a8a007f1494bc1d97ea6d4a52c](https://github.com/armory-io/clouddriver-armory/commit/f0e7a7470b06b6a8a007f1494bc1d97ea6d4a52c)
[9c064d10e3efcb70bce2e895acf8bce78fdb77e5](https://github.com/spinnaker/clouddriver/commit/9c064d10e3efcb70bce2e895acf8bce78fdb77e5)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9c064d10e3efcb70bce2e895acf8bce78fdb77e5"
},
"details": {
"image": {
"imageId": "sha256:ef1696779eb6ed1918841fefc7b2b2edcc44ff3556aa73bd7aa3b1c7856aafa0",
"tag": "2025.01.03.20.58.36.release-2.35.x"
},
"vcs": …
```
=> chore(cd): update clouddriver-armory version to 2025.01.03.20.58.36.release-2.35.x

stack.yml
armory/kayenta-armory:2025.01.23.21.26.00.release-2.35.x
[8c63692f834f965848a6f238035d0fb01fbc2834](https://github.com/armory-io/kayenta-armory/commit/8c63692f834f965848a6f238035d0fb01fbc2834)
[17c02a482ba7efb3aa5dce8f424e7b2e38c006a2](https://github.com/spinnaker/kayenta/commit/17c02a482ba7efb3aa5dce8f424e7b2e38c006a2)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "17c02a482ba7efb3aa5dce8f424e7b2e38c006a2"
},
"details": {
"image": {
"imageId": "sha256:1201fd19c083c3f1dda251565dccee6ddd57e370adb027cff4d3ab4afb7f3cc7",
"tag": "2025.01.23.21.26.00.release-2.35.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update kayenta-armory version to 2025.01.23.21.26.00.release-2.35.x

stack.yml
* **master**
armory/deck-armory:2025.01.28.05.44.06.master
[789bc9a938027d7d5d7da5441a1949839fba9414](https://github.com/armory-io/deck-armory/commit/789bc9a938027d7d5d7da5441a1949839fba9414)
[824e0e548c082b7d6e168047b7df38b10ec6f308](https://github.com/spinnaker/deck/commit/824e0e548c082b7d6e168047b7df38b10ec6f308)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "824e0e548c082b7d6e168047b7df38b10ec6f308"
},
"details": {
"image": {
"imageId": "sha256:e66a9633ea37d094cbc1f04809f8c9343c84c556c96d5750504a65ea2d9f4ff1",
"tag": "2025.01.28.05.44.06.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update deck-armory version to 2025.01.28.05.44.06.master

stack.yml
armory/front50-armory:2025.01.28.17.34.16.release-2.36.x
[9e2606c2d386d00b18b76104564b6467ea2010d3](https://github.com/armory-io/front50-armory/commit/9e2606c2d386d00b18b76104564b6467ea2010d3)
[33a9989434cd99e4a84f6f41e970d559b24396f7](https://github.com/spinnaker/front50/commit/33a9989434cd99e4a84f6f41e970d559b24396f7)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "33a9989434cd99e4a84f6f41e970d559b24396f7"
},
"details": {
"image": {
"imageId": "sha256:eb343100947dc1a06ad69f72ff739ae81f4fd92afe3b7c333387524ac09d7663",
"tag": "2025.01.28.17.34.16.release-2.36.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update front50-armory version to 2025.01.28.17.34.16.release-2.36.x

stack.yml
armory/rosco-armory:2025.01.28.17.35.23.release-2.36.x
[80f1885bcd93da023fdb858d563cc24ccadce276](https://github.com/armory-io/rosco-armory/commit/80f1885bcd93da023fdb858d563cc24ccadce276)
[469879dc8b7c49ff705a2c9e8df0498e9bdd8731](https://github.com/spinnaker/rosco/commit/469879dc8b7c49ff705a2c9e8df0498e9bdd8731)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "469879dc8b7c49ff705a2c9e8df0498e9bdd8731"
},
"details": {
"image": {
"imageId": "sha256:f86d1cb7d6de0cd0375af968d1d9b622155273490e746a61d123d8ef0281b7fa",
"tag": "2025.01.28.17.35.23.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2025.01.28.17.35.23.release-2.36.x

stack.yml
armory/deck-armory:2025.01.21.17.32.41.release-2.36.x
[d3b08fe8100caf2c95a4b332ec459bd33e4b8c6c](https://github.com/armory-io/deck-armory/commit/d3b08fe8100caf2c95a4b332ec459bd33e4b8c6c)
[5dde11ff6554ed1f43644bb1f94e9deab2d4c685](https://github.com/spinnaker/deck/commit/5dde11ff6554ed1f43644bb1f94e9deab2d4c685)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5dde11ff6554ed1f43644bb1f94e9deab2d4c685"
},
"details": {
"image": {
"imageId": "sha256:e4c34eef844c82ed7986138c30b4be91803ccc6d6ed4d9545ec9bd6f594e47a6",
"tag": "2025.01.21.17.32.41.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2025.01.21.17.32.41.release-2.36.x

stack.yml
armory/orca-armory:2025.01.28.17.37.57.release-2.36.x
[2f0d9a64a89bc00114c04ea40fe971801f3e5877](https://github.com/armory-io/orca-armory/commit/2f0d9a64a89bc00114c04ea40fe971801f3e5877)
[6228405f6a2bbdad48fd89f6179ed8dd85cd4911](https://github.com/spinnaker/orca/commit/6228405f6a2bbdad48fd89f6179ed8dd85cd4911)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "6228405f6a2bbdad48fd89f6179ed8dd85cd4911"
},
"details": {
"image": {
"imageId": "sha256:f1dd22b0b36a8754a297c213525350eb65bb22c2f37335c076adc76c8b38844d",
"tag": "2025.01.28.17.37.57.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2025.01.28.17.37.57.release-2.36.x

stack.yml
armory/igor-armory:2025.01.28.17.34.58.release-2.36.x
[c5540e0bfe83bb87fa8896c7c7924113c17453b4](https://github.com/armory-io/igor-armory/commit/c5540e0bfe83bb87fa8896c7c7924113c17453b4)
[2f3de993735c4fe0aab076e9a7f366f023f4ee24](https://github.com/spinnaker/igor/commit/2f3de993735c4fe0aab076e9a7f366f023f4ee24)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "2f3de993735c4fe0aab076e9a7f366f023f4ee24"
},
"details": {
"image": {
"imageId": "sha256:cc1e65dbc51ca8108811b9a31c2dd4d5171f1f23f61785811291d21ea1563fa2",
"tag": "2025.01.28.17.34.58.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update igor-armory version to 2025.01.28.17.34.58.release-2.36.x

stack.yml
armory/kayenta-armory:2025.01.29.17.30.22.release-2.36.x
[1dab7bb6f4156bdf7f15ef74722139e07ceb4581](https://github.com/armory-io/kayenta-armory/commit/1dab7bb6f4156bdf7f15ef74722139e07ceb4581)
[41525f2b62a8fed98f2b09317a5e8474f4cc3101](https://github.com/spinnaker/kayenta/commit/41525f2b62a8fed98f2b09317a5e8474f4cc3101)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "41525f2b62a8fed98f2b09317a5e8474f4cc3101"
},
"details": {
"image": {
"imageId": "sha256:45cf48a8205e72385de84fe5c9c0e5f2358564ae3d645f984b2c7db7c511cf39",
"tag": "2025.01.29.17.30.22.release-2.36.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update kayenta-armory version to 2025.01.29.17.30.22.release-2.36.x

stack.yml
=> chore(cd): update clouddriver-armory version to 2025.01.28.17.36.23.release-2.36.x

stack.yml
armory/deck-armory:2025.01.29.23.53.48.release-2.36.x
[da852d30ae5d29448b8546c3a55e799ef08bec8a](https://github.com/armory-io/deck-armory/commit/da852d30ae5d29448b8546c3a55e799ef08bec8a)
[5dde11ff6554ed1f43644bb1f94e9deab2d4c685](https://github.com/spinnaker/deck/commit/5dde11ff6554ed1f43644bb1f94e9deab2d4c685)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5dde11ff6554ed1f43644bb1f94e9deab2d4c685"
},
"details": {
"image": {
"imageId": "sha256:951c2791a2868909a825ae9af69ee958d09a4b4d3e8c51b08af6898402146797",
"tag": "2025.01.29.23.53.48.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2025.01.29.23.53.48.release-2.36.x

stack.yml
armory/clouddriver-armory:2025.01.30.00.03.22.release-2.36.x
[e52a253da499f54ea951d46472ee20ada1326d1a](https://github.com/armory-io/clouddriver-armory/commit/e52a253da499f54ea951d46472ee20ada1326d1a)
[e75980164bb54751387435dc847e64ce3f78c848](https://github.com/spinnaker/clouddriver/commit/e75980164bb54751387435dc847e64ce3f78c848)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "e75980164bb54751387435dc847e64ce3f78c848"
},
"details": {
"image": {
"imageId": "sha256:84c18e1723cdda8fc51075332ba06a1111022dcd7c70b034fdf8709c3d4036f4",
"tag": "2025.01.30.00.03.22.release-2.36.x"
},
"vcs": …
```
=> chore(cd): update clouddriver-armory version to 2025.01.30.00.03.22.release-2.36.x

stack.yml
armory/orca-armory:2025.02.05.11.14.21.release-2.36.x
[9fa8bf04e3b5882c0b03d0309684ef0cd00a64c0](https://github.com/armory-io/orca-armory/commit/9fa8bf04e3b5882c0b03d0309684ef0cd00a64c0)
[ae249528097447da3f340f8b24bf0f465769e924](https://github.com/spinnaker/orca/commit/ae249528097447da3f340f8b24bf0f465769e924)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "ae249528097447da3f340f8b24bf0f465769e924"
},
"details": {
"image": {
"imageId": "sha256:b5107c80e7824c45a534a3c85453dd19edd90148d31a9d45c4ba5ea4de238c9d",
"tag": "2025.02.05.11.14.21.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2025.02.05.11.14.21.release-2.36.x

stack.yml
* **master**
armory/deck-armory:2025.02.20.11.40.38.master
[933645a43b616d15e81522620fbb7cc6494643f3](https://github.com/armory-io/deck-armory/commit/933645a43b616d15e81522620fbb7cc6494643f3)
[824e0e548c082b7d6e168047b7df38b10ec6f308](https://github.com/spinnaker/deck/commit/824e0e548c082b7d6e168047b7df38b10ec6f308)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "824e0e548c082b7d6e168047b7df38b10ec6f308"
},
"details": {
"image": {
"imageId": "sha256:2d18287c695752fd0309d3aa2f5fefabb475b852bfc353b16e35437185aa7b27",
"tag": "2025.02.20.11.40.38.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update deck-armory version to 2025.02.20.11.40.38.master

stack.yml
armory/deck-armory:2025.02.20.11.48.39.release-2.36.x
[1c97b782e123ee219673c245878aeb59e87b0a06](https://github.com/armory-io/deck-armory/commit/1c97b782e123ee219673c245878aeb59e87b0a06)
[5dde11ff6554ed1f43644bb1f94e9deab2d4c685](https://github.com/spinnaker/deck/commit/5dde11ff6554ed1f43644bb1f94e9deab2d4c685)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5dde11ff6554ed1f43644bb1f94e9deab2d4c685"
},
"details": {
"image": {
"imageId": "sha256:2661ebd91bafcb5ef7673ba183a930da919d73c0c30601a2dfa49fa388d89122",
"tag": "2025.02.20.11.48.39.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2025.02.20.11.48.39.release-2.36.x

stack.yml
* **master**
armory/orca-armory:2024.11.04.21.19.43.master
[0da30a53ef7e998e3ba618b2651643af74595ceb](https://github.com/armory-io/orca-armory/commit/0da30a53ef7e998e3ba618b2651643af74595ceb)
[0284e7537af855159da2511aae2e0f89d8910342](https://github.com/spinnaker/orca/commit/0284e7537af855159da2511aae2e0f89d8910342)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0284e7537af855159da2511aae2e0f89d8910342"
},
"details": {
"image": {
"imageId": "sha256:eb5701e00ff21ad1ec1ab9df3cee1e8718897a7f6f6e052da0e217b460e5e24e",
"tag": "2024.11.04.21.19.43.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update orca-armory version to 2024.11.04.21.19.43.master

stack.yml
* **master**
armory/kayenta-armory:2024.11.29.14.34.48.master
[969b28c48eb03cd2548057fd1bb82fb7d7eaae27](https://github.com/armory-io/kayenta-armory/commit/969b28c48eb03cd2548057fd1bb82fb7d7eaae27)
[09c5b291b712eecf184da2aa1bb1e004da2ce25f](https://github.com/spinnaker/kayenta/commit/09c5b291b712eecf184da2aa1bb1e004da2ce25f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "09c5b291b712eecf184da2aa1bb1e004da2ce25f"
},
"details": {
"image": {
"imageId": "sha256:423677bd8e9f1023393ed7ff008f5318ee5c2c60a7e5e6f5bef353564f8e77f1",
"tag": "2024.11.29.14.34.48.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update kayenta-armory version to 2024.11.29.14.34.48.master

stack.yml
* **master**
armory/echo-armory:2024.11.29.14.34.38.master
[6f5f7d6ad135db39926c17ce5cb34ecc99c17ddf](https://github.com/armory-io/echo-armory/commit/6f5f7d6ad135db39926c17ce5cb34ecc99c17ddf)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:2a4d74fbbfed9d49e1cacd69db17a519c22f0cfb96cb89f70c79cd7641a7e131",
"tag": "2024.11.29.14.34.38.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2024.11.29.14.34.38.master

stack.yml
* **master**
armory/echo-armory:2025.02.28.09.42.56.master
[b002839fa13bc611fc0f72ed9bf6ff68d6871e74](https://github.com/armory-io/echo-armory/commit/b002839fa13bc611fc0f72ed9bf6ff68d6871e74)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:5a27b044149c87206aea8e23318b666a93d84af2124dc9eddf72cbb1a446edec",
"tag": "2025.02.28.09.42.56.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2025.02.28.09.42.56.master

stack.yml
armory/echo-armory:2025.02.28.09.49.33.release-2.36.x
[a8af3ad0d363fc585d1b4599a3f5a73d8f6cdcc5](https://github.com/armory-io/echo-armory/commit/a8af3ad0d363fc585d1b4599a3f5a73d8f6cdcc5)
[4a009d6a31b722157ae94dc35dafd1a9997682ab](https://github.com/spinnaker/echo/commit/4a009d6a31b722157ae94dc35dafd1a9997682ab)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4a009d6a31b722157ae94dc35dafd1a9997682ab"
},
"details": {
"image": {
"imageId": "sha256:1c3992f6cbfd723b87b70e7f446ee422d8232b3cf78c035240faa82baa85b061",
"tag": "2025.02.28.09.49.33.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2025.02.28.09.49.33.release-2.36.x

stack.yml
* **master**
armory/fiat-armory:2024.11.04.21.28.57.master
[674b176e253525a6a5b2f6e68f8cb6d16536f7b0](https://github.com/armory-io/fiat-armory/commit/674b176e253525a6a5b2f6e68f8cb6d16536f7b0)
[91e6a139ab8cbd31fc199c4cc134c3b54df72588](https://github.com/spinnaker/fiat/commit/91e6a139ab8cbd31fc199c4cc134c3b54df72588)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "91e6a139ab8cbd31fc199c4cc134c3b54df72588"
},
"details": {
"image": {
"imageId": "sha256:b504af23bf5d2fbf4bb5a9dd3b3f95939dbe1b67973450d4a320f9ed5eb11ec7",
"tag": "2024.11.04.21.28.57.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update fiat-armory version to 2024.11.04.21.28.57.master

stack.yml
* **master**
armory/dinghy:2024.11.29.14.34.02.master
[2b5ff974df833db39742b42caccc4f474245f9d9](https://github.com/armory-io/dinghy/commit/2b5ff974df833db39742b42caccc4f474245f9d9)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:1050789837dfafca8124c78f2214b3267b04487500c29921b2e9be2befe72ff1",
"tag": "2024.11.29.14.34.02.master"
},
"vcs": {
"repo": {
},
"sha": "2b5ff974df833db39742b42caccc4f474245f9d9"
}
},
},
"details": {
"image": {
"imageId": "sha256:1050789837dfafca8124c78f2214b3267b04487500c29921b2e9be2befe72ff1", …
```
=> chore(cd): update dinghy version to 2024.11.29.14.34.02.master

stack.yml
* **master**
armory/clouddriver-armory:2025.03.25.09.33.17.master
[5af850fc472efed90bc790f0b9db08962d4c56e7](https://github.com/armory-io/clouddriver-armory/commit/5af850fc472efed90bc790f0b9db08962d4c56e7)
[6a65adfda0842648a3773ca8745fbeff606b2be6](https://github.com/spinnaker/clouddriver/commit/6a65adfda0842648a3773ca8745fbeff606b2be6)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "6a65adfda0842648a3773ca8745fbeff606b2be6"
},
"details": {
"image": {
"imageId": "sha256:f306ed7761167e7f1c39a9432a572071def0e910407bf1e8f4c61c61f25c2c6f",
"tag": "2025.03.25.09.33.17.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2025.03.25.09.33.17.master

stack.yml
* **master**
armory/fiat-armory:2025.03.25.10.00.56.master
[325b64cdb4f3d674f248cc26fee4b2107403247e](https://github.com/armory-io/fiat-armory/commit/325b64cdb4f3d674f248cc26fee4b2107403247e)
[91e6a139ab8cbd31fc199c4cc134c3b54df72588](https://github.com/spinnaker/fiat/commit/91e6a139ab8cbd31fc199c4cc134c3b54df72588)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "91e6a139ab8cbd31fc199c4cc134c3b54df72588"
},
"details": {
"image": {
"imageId": "sha256:478132856d603af6f534077807420fef51d6e656e5d3bb10bec2c92941b0f570",
"tag": "2025.03.25.10.00.56.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update fiat-armory version to 2025.03.25.10.00.56.master

stack.yml
* **master**
armory/gate-armory:2025.03.19.20.33.45.master
[65057ac75be63b9ee202abebe686c670f4b51545](https://github.com/armory-io/gate-armory/commit/65057ac75be63b9ee202abebe686c670f4b51545)
[f4b8602641142ef4953c96a68509ed51bdd2875b](https://github.com/spinnaker/gate/commit/f4b8602641142ef4953c96a68509ed51bdd2875b)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "f4b8602641142ef4953c96a68509ed51bdd2875b"
},
"details": {
"image": {
"imageId": "sha256:8f3677cc13eea2e6783aa9cbf254ccff37674617456ecc3b92b6c607ddb91876",
"tag": "2025.03.19.20.33.45.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update gate-armory version to 2025.03.19.20.33.45.master

stack.yml
* **master**
armory/rosco-armory:2025.03.19.20.35.00.master
[fc4ce32c48c0f2595af9620cfd44577707fecc1c](https://github.com/armory-io/rosco-armory/commit/fc4ce32c48c0f2595af9620cfd44577707fecc1c)
[3e497d06ccb109c3b496ce8c570295c6970d18ae](https://github.com/spinnaker/rosco/commit/3e497d06ccb109c3b496ce8c570295c6970d18ae)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "3e497d06ccb109c3b496ce8c570295c6970d18ae"
},
"details": {
"image": {
"imageId": "sha256:484592cc8936eed89daf7f2a5d8c269ce5a5c83d2c8e87bb417ac1eec9a40567",
"tag": "2025.03.19.20.35.00.master"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2025.03.19.20.35.00.master

stack.yml
armory/orca-armory:2025.03.24.11.36.30.release-2.37.x
[f38dba8b579ca0b18e283f6347d95dbd04ee1960](https://github.com/armory-io/orca-armory/commit/f38dba8b579ca0b18e283f6347d95dbd04ee1960)
[1f8d42e9a0121e3b44d61085b0aa0807ceab39d0](https://github.com/spinnaker/orca/commit/1f8d42e9a0121e3b44d61085b0aa0807ceab39d0)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1f8d42e9a0121e3b44d61085b0aa0807ceab39d0"
},
"details": {
"image": {
"imageId": "sha256:3963319c14af19810cff7309bad554101ba37ecb0f6d3e58302911ce2427f4fa",
"tag": "2025.03.24.11.36.30.release-2.37.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2025.03.24.11.36.30.release-2.37.x

stack.yml
armory/clouddriver-armory:2025.03.24.11.26.53.release-2.37.x
[b2cfe143b1bfadee1e8bb2545522bfc9c8a9bdbe](https://github.com/armory-io/clouddriver-armory/commit/b2cfe143b1bfadee1e8bb2545522bfc9c8a9bdbe)
[a34c27597b285ac6713a30ecfde994fdcd54aa88](https://github.com/spinnaker/clouddriver/commit/a34c27597b285ac6713a30ecfde994fdcd54aa88)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "a34c27597b285ac6713a30ecfde994fdcd54aa88"
},
"details": {
"image": {
"imageId": "sha256:dbe4b0688cd1f874ba49d5478ee29a079fe396e3239b9e9d078b959659953925",
"tag": "2025.03.24.11.26.53.release-2.37.x"
},
"vcs": …
```
=> chore(cd): update clouddriver-armory version to 2025.03.24.11.26.53.release-2.37.x

stack.yml
armory/igor-armory:2025.03.24.11.46.33.release-2.37.x
[f805609fc0dc8dd168a0c9d8559fe180789b05e2](https://github.com/armory-io/igor-armory/commit/f805609fc0dc8dd168a0c9d8559fe180789b05e2)
[9a2ad8b59039fa033b9786ae7c20598891d1f532](https://github.com/spinnaker/igor/commit/9a2ad8b59039fa033b9786ae7c20598891d1f532)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "9a2ad8b59039fa033b9786ae7c20598891d1f532"
},
"details": {
"image": {
"imageId": "sha256:1f3ec21fe746cab652920db5b9b1ae6fba6411ea8c84836db6f6a7eaf23d1b74",
"tag": "2025.03.24.11.46.33.release-2.37.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update igor-armory version to 2025.03.24.11.46.33.release-2.37.x

stack.yml
armory/deck-armory:2025.03.25.22.05.20.release-2.36.x
[924d705dc5df1aabce76470e5722b39c67e1694d](https://github.com/armory-io/deck-armory/commit/924d705dc5df1aabce76470e5722b39c67e1694d)
[1b8f60af8ea993eec4909e8110cbe42d966420a1](https://github.com/spinnaker/deck/commit/1b8f60af8ea993eec4909e8110cbe42d966420a1)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1b8f60af8ea993eec4909e8110cbe42d966420a1"
},
"details": {
"image": {
"imageId": "sha256:794ed4d8891f5c875dded13ec273cedae51157bcec9c9555ed7deac2f97d4ecd",
"tag": "2025.03.25.22.05.20.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2025.03.25.22.05.20.release-2.36.x

stack.yml
armory/clouddriver-armory:2025.03.24.18.27.10.release-2.36.x
[f19d08cb4b70c698ddb80c099e0b63c71b4ada07](https://github.com/armory-io/clouddriver-armory/commit/f19d08cb4b70c698ddb80c099e0b63c71b4ada07)
[482dda727dffbba2b9259b97638851a66b806d42](https://github.com/spinnaker/clouddriver/commit/482dda727dffbba2b9259b97638851a66b806d42)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "482dda727dffbba2b9259b97638851a66b806d42"
},
"details": {
"image": {
"imageId": "sha256:3851c399956717aa66ecb5858bf73cc7732e61b5204c2d76156b873938b1ed3c",
"tag": "2025.03.24.18.27.10.release-2.36.x"
},
"vcs": …
```
=> chore(cd): update clouddriver-armory version to 2025.03.24.18.27.10.release-2.36.x

stack.yml
armory/rosco-armory:2025.03.24.13.50.18.release-2.37.x
[fb5d83c0a74e88b2f58e38fbf973230e47b99f22](https://github.com/armory-io/rosco-armory/commit/fb5d83c0a74e88b2f58e38fbf973230e47b99f22)
Event Payload
```
{
"service": {
"details": {
"image": {
"imageId": "sha256:c253bbc6de99cca17d0e3d67963305f64314b86473e1591a496056cefaca330e",
"tag": "2025.03.24.13.50.18.release-2.37.x"
},
"vcs": {
"repo": {
},
"sha": "fb5d83c0a74e88b2f58e38fbf973230e47b99f22"
}
},
},
"details": {
"image": { …
```
=> chore(cd): update rosco-armory version to 2025.03.24.13.50.18.release-2.37.x

stack.yml
armory/fiat-armory:2025.03.25.10.12.53.release-2.37.x
[35919f05a96ce258b7e3eced8cca85ff24d29df6](https://github.com/armory-io/fiat-armory/commit/35919f05a96ce258b7e3eced8cca85ff24d29df6)
[91e6a139ab8cbd31fc199c4cc134c3b54df72588](https://github.com/spinnaker/fiat/commit/91e6a139ab8cbd31fc199c4cc134c3b54df72588)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "91e6a139ab8cbd31fc199c4cc134c3b54df72588"
},
"details": {
"image": {
"imageId": "sha256:cc0e23cfd38d90491bebbfb0c010753ead5fe170d50f98b0ec97fb5c03992bfd",
"tag": "2025.03.25.10.12.53.release-2.37.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update fiat-armory version to 2025.03.25.10.12.53.release-2.37.x

stack.yml
* **master**
armory/kayenta-armory:2025.03.19.20.34.30.master
[69eb07d60fc1d7198ee7dd3a6581a6a46b48f56e](https://github.com/armory-io/kayenta-armory/commit/69eb07d60fc1d7198ee7dd3a6581a6a46b48f56e)
[09c5b291b712eecf184da2aa1bb1e004da2ce25f](https://github.com/spinnaker/kayenta/commit/09c5b291b712eecf184da2aa1bb1e004da2ce25f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "09c5b291b712eecf184da2aa1bb1e004da2ce25f"
},
"details": {
"image": {
"imageId": "sha256:30242dea02fb791fbf68a36eda77172020d642e44776a372802c7666515a51f5",
"tag": "2025.03.19.20.34.30.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update kayenta-armory version to 2025.03.19.20.34.30.master

stack.yml
armory/deck-armory:2025.03.25.10.09.39.release-2.37.x
[40134fa0271df6c14e08b8a43fbf95e4aea59c06](https://github.com/armory-io/deck-armory/commit/40134fa0271df6c14e08b8a43fbf95e4aea59c06)
[824e0e548c082b7d6e168047b7df38b10ec6f308](https://github.com/spinnaker/deck/commit/824e0e548c082b7d6e168047b7df38b10ec6f308)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "824e0e548c082b7d6e168047b7df38b10ec6f308"
},
"details": {
"image": {
"imageId": "sha256:0624b041a43774871ab0b30f2601ad7ead6037eda60c139c0717178498602bd4",
"tag": "2025.03.25.10.09.39.release-2.37.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2025.03.25.10.09.39.release-2.37.x

stack.yml
armory/deck-armory:2025.04.02.16.55.14.release-2.36.x
[4222c053922c03ec4427381dc2ccaed253b695e9](https://github.com/armory-io/deck-armory/commit/4222c053922c03ec4427381dc2ccaed253b695e9)
[1b8f60af8ea993eec4909e8110cbe42d966420a1](https://github.com/spinnaker/deck/commit/1b8f60af8ea993eec4909e8110cbe42d966420a1)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1b8f60af8ea993eec4909e8110cbe42d966420a1"
},
"details": {
"image": {
"imageId": "sha256:3a42c241aebd72e36d0b5f39c094eaaa1721fe7a99c377c43a7ccbed04ed7802",
"tag": "2025.04.02.16.55.14.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2025.04.02.16.55.14.release-2.36.x

stack.yml
* **master**
armory/front50-armory:2025.04.02.19.37.58.master
[73a5b90ce634176438a32f589874feec7d5ca54b](https://github.com/armory-io/front50-armory/commit/73a5b90ce634176438a32f589874feec7d5ca54b)
[84137d73ecc6b8132545fcdfec7006a9f40df7a8](https://github.com/spinnaker/front50/commit/84137d73ecc6b8132545fcdfec7006a9f40df7a8)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "84137d73ecc6b8132545fcdfec7006a9f40df7a8"
},
"details": {
"image": {
"imageId": "sha256:05adedd09fbed34f97aca57b4a683048f06ceafe2e4ae27d79d4323e5a63ef03",
"tag": "2025.04.02.19.37.58.master"
},
"vcs": {
"repo": {
"repoName": …
```
=> chore(cd): update front50-armory version to 2025.04.02.19.37.58.master

stack.yml
* **master**
armory/echo-armory:2025.04.03.17.48.34.master
[a574bd1ff547ebd1f2c9526800b106f8c5094c5a](https://github.com/armory-io/echo-armory/commit/a574bd1ff547ebd1f2c9526800b106f8c5094c5a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
},
"details": {
"image": {
"imageId": "sha256:152b49e457575f7899f5015f45c0328a680d74f11a8e78477ea1b92e58d7dd58",
"tag": "2025.04.03.17.48.34.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2025.04.03.17.48.34.master

stack.yml
armory/kayenta-armory:2025.03.24.13.50.41.release-2.37.x
[3bdfb9a7c78f5578cdf4e2d8e9df94b625b30b3d](https://github.com/armory-io/kayenta-armory/commit/3bdfb9a7c78f5578cdf4e2d8e9df94b625b30b3d)
[09c5b291b712eecf184da2aa1bb1e004da2ce25f](https://github.com/spinnaker/kayenta/commit/09c5b291b712eecf184da2aa1bb1e004da2ce25f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "09c5b291b712eecf184da2aa1bb1e004da2ce25f"
},
"details": {
"image": {
"imageId": "sha256:a66ab9b0767baa44389876d62aaadbb7e125c97e2f6fd892b17a4e32e333cae1",
"tag": "2025.03.24.13.50.41.release-2.37.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update kayenta-armory version to 2025.03.24.13.50.41.release-2.37.x

stack.yml
* **master**
armory/echo-armory:2025.04.04.07.59.03.master
[4b4ea6de02b3697b83f404b5060b287f82fb5441](https://github.com/armory-io/echo-armory/commit/4b4ea6de02b3697b83f404b5060b287f82fb5441)
[db1889af0393439a98d7e71a1a34dac7459f31c2](https://github.com/spinnaker/echo/commit/db1889af0393439a98d7e71a1a34dac7459f31c2)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "db1889af0393439a98d7e71a1a34dac7459f31c2"
},
"details": {
"image": {
"imageId": "sha256:86de13f2c3c93299e6417b86af735c10751fa0d25d8d32a2aa06d695a973433d",
"tag": "2025.04.04.07.59.03.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2025.04.04.07.59.03.master

stack.yml
armory/echo-armory:2025.04.04.08.23.21.release-2.37.x
[cc98a59bcd860c66ed61869ae69c9b77eab8573c](https://github.com/armory-io/echo-armory/commit/cc98a59bcd860c66ed61869ae69c9b77eab8573c)
[0685f7a88a4c6751e0e8c239af40f97fc2022012](https://github.com/spinnaker/echo/commit/0685f7a88a4c6751e0e8c239af40f97fc2022012)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0685f7a88a4c6751e0e8c239af40f97fc2022012"
},
"details": {
"image": {
"imageId": "sha256:8534f57b4e24e75f2031b646160d8f499cb7653074c4f8d9a0ecb7c61fb24c35",
"tag": "2025.04.04.08.23.21.release-2.37.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2025.04.04.08.23.21.release-2.37.x

stack.yml
armory/clouddriver-armory:2025.04.11.16.42.33.release-2.36.x
[98d36d67fcd9eecc71fbbcc10e581c4f3ee005d1](https://github.com/armory-io/clouddriver-armory/commit/98d36d67fcd9eecc71fbbcc10e581c4f3ee005d1)
[c8c9d4c894772cbce2df093d470a718881afd9aa](https://github.com/spinnaker/clouddriver/commit/c8c9d4c894772cbce2df093d470a718881afd9aa)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c8c9d4c894772cbce2df093d470a718881afd9aa"
},
"details": {
"image": {
"imageId": "sha256:5b4bacb9bf9de20df60c55c9ee6fe5e92ffd5e9bb075600eb8d3b9279ee25b17",
"tag": "2025.04.11.16.42.33.release-2.36.x"
},
"vcs": …
```
=> chore(cd): update clouddriver-armory version to 2025.04.11.16.42.33.release-2.36.x

stack.yml
armory/deck-armory:2025.04.22.14.55.39.release-2.37.x
[8bcd06f91b2d618f71196c14b299209ead832348](https://github.com/armory-io/deck-armory/commit/8bcd06f91b2d618f71196c14b299209ead832348)
[4b1789d7ccc509007b550da87b187fb546c21fef](https://github.com/spinnaker/deck/commit/4b1789d7ccc509007b550da87b187fb546c21fef)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "4b1789d7ccc509007b550da87b187fb546c21fef"
},
"details": {
"image": {
"imageId": "sha256:526c3742b371160cb1451920b55500c47b7748aa5b5048a5889df99237d18007",
"tag": "2025.04.22.14.55.39.release-2.37.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2025.04.22.14.55.39.release-2.37.x

stack.yml
* **master**
armory/deck-armory:2025.04.22.14.55.27.master
[4704b5664a12e4d6b264022429b94896bdda99d8](https://github.com/armory-io/deck-armory/commit/4704b5664a12e4d6b264022429b94896bdda99d8)
[3f2418ea6d1ecf61b7e9d38e8c90d74ff7619ef6](https://github.com/spinnaker/deck/commit/3f2418ea6d1ecf61b7e9d38e8c90d74ff7619ef6)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "3f2418ea6d1ecf61b7e9d38e8c90d74ff7619ef6"
},
"details": {
"image": {
"imageId": "sha256:696ab9b9120aa290c42d8264156c383170023a502b89e80e0b4d8d792a2f1ab3",
"tag": "2025.04.22.14.55.27.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update deck-armory version to 2025.04.22.14.55.27.master

stack.yml
armory/orca-armory:2025.04.23.07.44.35.release-2.37.x
[015a2acc51c6dbe39c9395defbd65ebf6e4ec855](https://github.com/armory-io/orca-armory/commit/015a2acc51c6dbe39c9395defbd65ebf6e4ec855)
[38b4af39981fe1d024aade6cf15bc66f2901f611](https://github.com/spinnaker/orca/commit/38b4af39981fe1d024aade6cf15bc66f2901f611)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "38b4af39981fe1d024aade6cf15bc66f2901f611"
},
"details": {
"image": {
"imageId": "sha256:0d3e10bb56cad615399600302e09b04063926e9e9c28dba208b30c309f4e1d17",
"tag": "2025.04.23.07.44.35.release-2.37.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2025.04.23.07.44.35.release-2.37.x

stack.yml
* **master**
armory/orca-armory:2025.04.23.07.44.24.master
[58f1f9dfb914a1f34d55542e275780de52f222ad](https://github.com/armory-io/orca-armory/commit/58f1f9dfb914a1f34d55542e275780de52f222ad)
[2fdb327a9f67345c4919e1503ff5119fa3c31caf](https://github.com/spinnaker/orca/commit/2fdb327a9f67345c4919e1503ff5119fa3c31caf)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "2fdb327a9f67345c4919e1503ff5119fa3c31caf"
},
"details": {
"image": {
"imageId": "sha256:7fb6f2bd7db6bf4401ca9498bb2d300fa1532c4f2d05b3fa6005f3c46dc9baf0",
"tag": "2025.04.23.07.44.24.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update orca-armory version to 2025.04.23.07.44.24.master

stack.yml
armory/deck-armory:2025.04.23.07.43.15.release-2.36.x
[e9fdcdf36257ffbbe1b5460d7e3496f8b457c8f9](https://github.com/armory-io/deck-armory/commit/e9fdcdf36257ffbbe1b5460d7e3496f8b457c8f9)
[127fa906205ad4ca835eb38502ab07d02b8974d9](https://github.com/spinnaker/deck/commit/127fa906205ad4ca835eb38502ab07d02b8974d9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "127fa906205ad4ca835eb38502ab07d02b8974d9"
},
"details": {
"image": {
"imageId": "sha256:1742dca17eabd9549184b3cd7c4bb399184bc2cd0f97e3a666fe635ec6646cab",
"tag": "2025.04.23.07.43.15.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2025.04.23.07.43.15.release-2.36.x

stack.yml
armory/fiat-armory:2025.04.23.07.46.49.release-2.37.x
[98c778ad3363cfa71ee63915d9f63ad5634fbbc7](https://github.com/armory-io/fiat-armory/commit/98c778ad3363cfa71ee63915d9f63ad5634fbbc7)
[489b9b273999d71cc5aeb90512b35dcd90837fe9](https://github.com/spinnaker/fiat/commit/489b9b273999d71cc5aeb90512b35dcd90837fe9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "489b9b273999d71cc5aeb90512b35dcd90837fe9"
},
"details": {
"image": {
"imageId": "sha256:adbb8d217211fe2ea7d427773ef6ba69f1497332d577898469762acd036cfb10",
"tag": "2025.04.23.07.46.49.release-2.37.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update fiat-armory version to 2025.04.23.07.46.49.release-2.37.x

stack.yml
* **master**
armory/fiat-armory:2025.04.23.07.46.40.master
[8016f6b9e3b3619d63ce47b93930c32f16d86d85](https://github.com/armory-io/fiat-armory/commit/8016f6b9e3b3619d63ce47b93930c32f16d86d85)
[1c7fb38cd9bb3c3ea6c81d364612ca7abaadfe6a](https://github.com/spinnaker/fiat/commit/1c7fb38cd9bb3c3ea6c81d364612ca7abaadfe6a)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "1c7fb38cd9bb3c3ea6c81d364612ca7abaadfe6a"
},
"details": {
"image": {
"imageId": "sha256:11d776f24a3d5d783d859e51fbb3dd3fdc750289cd56791e2e273bfd7a28a3bc",
"tag": "2025.04.23.07.46.40.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update fiat-armory version to 2025.04.23.07.46.40.master

stack.yml
armory/kayenta-armory:2025.04.23.07.48.09.release-2.37.x
[400ecafba05803fd840a0340e1fc77c1fe335fb7](https://github.com/armory-io/kayenta-armory/commit/400ecafba05803fd840a0340e1fc77c1fe335fb7)
[343b06ec6b241ce86c7e23c3b21da5816b8559c1](https://github.com/spinnaker/kayenta/commit/343b06ec6b241ce86c7e23c3b21da5816b8559c1)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "343b06ec6b241ce86c7e23c3b21da5816b8559c1"
},
"details": {
"image": {
"imageId": "sha256:0ba2e2dcbbf2fac1e7600b0246f1844346744987b631d386ad83565877e13e6b",
"tag": "2025.04.23.07.48.09.release-2.37.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update kayenta-armory version to 2025.04.23.07.48.09.release-2.37.x

stack.yml
* **master**
armory/deck-armory:2025.04.23.07.43.29.master
[56a634ca15e25622e4821bed1d9d6ec3347239d6](https://github.com/armory-io/deck-armory/commit/56a634ca15e25622e4821bed1d9d6ec3347239d6)
[3f2418ea6d1ecf61b7e9d38e8c90d74ff7619ef6](https://github.com/spinnaker/deck/commit/3f2418ea6d1ecf61b7e9d38e8c90d74ff7619ef6)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "3f2418ea6d1ecf61b7e9d38e8c90d74ff7619ef6"
},
"details": {
"image": {
"imageId": "sha256:49aa18630cd4a2d717e796ba9532b884bc314b53009b3aee7174f481ae28d199",
"tag": "2025.04.23.07.43.29.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update deck-armory version to 2025.04.23.07.43.29.master

stack.yml
* **master**
armory/rosco-armory:2025.04.23.07.48.40.master
[a78a3e9512164b0612c7e2a65e54b36c64636b4f](https://github.com/armory-io/rosco-armory/commit/a78a3e9512164b0612c7e2a65e54b36c64636b4f)
[0ae53eb04d872050841dd813d993d7e5c38ea50f](https://github.com/spinnaker/rosco/commit/0ae53eb04d872050841dd813d993d7e5c38ea50f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "0ae53eb04d872050841dd813d993d7e5c38ea50f"
},
"details": {
"image": {
"imageId": "sha256:2aa178925bb2c1abf3d9f4555e3296df90767b21fde9c60ae27000ebdabcc0aa",
"tag": "2025.04.23.07.48.40.master"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2025.04.23.07.48.40.master

stack.yml
* **master**
armory/echo-armory:2025.04.25.13.52.43.master
[b90d53eab425ede23465f5f91629aeb589a21746](https://github.com/armory-io/echo-armory/commit/b90d53eab425ede23465f5f91629aeb589a21746)
[c0a7c9ed571493e273b7c83bad9f031442b71dac](https://github.com/spinnaker/echo/commit/c0a7c9ed571493e273b7c83bad9f031442b71dac)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c0a7c9ed571493e273b7c83bad9f031442b71dac"
},
"details": {
"image": {
"imageId": "sha256:df2d2d43583f5895d61e04c655e956f233dc7af678002bd658c1d089448b6650",
"tag": "2025.04.25.13.52.43.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2025.04.25.13.52.43.master

stack.yml
* **master**
armory/clouddriver-armory:2025.04.23.07.44.02.master
[16adca86ee19211b3251fa86fc32da0a82c0b141](https://github.com/armory-io/clouddriver-armory/commit/16adca86ee19211b3251fa86fc32da0a82c0b141)
[5e0ce2abb37cce236e4fb65b5f1ffa4ee781346e](https://github.com/spinnaker/clouddriver/commit/5e0ce2abb37cce236e4fb65b5f1ffa4ee781346e)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5e0ce2abb37cce236e4fb65b5f1ffa4ee781346e"
},
"details": {
"image": {
"imageId": "sha256:53c8c982685cd6a80c135bffd77194626c5ddbe36bdc8a06125c7ad894862910",
"tag": "2025.04.23.07.44.02.master"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update clouddriver-armory version to 2025.04.23.07.44.02.master

stack.yml
armory/echo-armory:2025.04.25.08.55.24.release-2.37.x
[b47906dfcdeb314eacc5257d9793b96183910e18](https://github.com/armory-io/echo-armory/commit/b47906dfcdeb314eacc5257d9793b96183910e18)
[21721cb9dcf73fddcb594a3432467da52b7891ed](https://github.com/spinnaker/echo/commit/21721cb9dcf73fddcb594a3432467da52b7891ed)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "21721cb9dcf73fddcb594a3432467da52b7891ed"
},
"details": {
"image": {
"imageId": "sha256:f3205bd1ec6643e637fe6646ce48d4bc258bf21e6b580aee6084c4752b17453c",
"tag": "2025.04.25.08.55.24.release-2.37.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2025.04.25.08.55.24.release-2.37.x

stack.yml
armory/echo-armory:2025.04.30.00.35.20.release-2.37.x
[f0663a57bc1680225b6a5d872364accca20a6503](https://github.com/armory-io/echo-armory/commit/f0663a57bc1680225b6a5d872364accca20a6503)
[284f95504ec5465189957601d8de8ca07b6dcd52](https://github.com/spinnaker/echo/commit/284f95504ec5465189957601d8de8ca07b6dcd52)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "284f95504ec5465189957601d8de8ca07b6dcd52"
},
"details": {
"image": {
"imageId": "sha256:f194dac106c2053283a1bb554696d6e1ba2e6415d033766e0abb717363e10416",
"tag": "2025.04.30.00.35.20.release-2.37.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update echo-armory version to 2025.04.30.00.35.20.release-2.37.x

stack.yml
* **master**
armory/echo-armory:2025.04.30.00.41.42.master
[f1350e8764aeb273bdf916c9221007ab1b4a49fa](https://github.com/armory-io/echo-armory/commit/f1350e8764aeb273bdf916c9221007ab1b4a49fa)
[989e20b5b72fa0ff85956119ba0051cfe1433274](https://github.com/spinnaker/echo/commit/989e20b5b72fa0ff85956119ba0051cfe1433274)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "989e20b5b72fa0ff85956119ba0051cfe1433274"
},
"details": {
"image": {
"imageId": "sha256:1a84fdaaa3be0034f272fc44ac5b52cc81f505a4f3441b8634fcaa98a632995e",
"tag": "2025.04.30.00.41.42.master"
},
"vcs": {
"repo": {
"type": …
```
=> chore(cd): update echo-armory version to 2025.04.30.00.41.42.master

stack.yml
armory/gate-armory:2025.05.20.16.59.50.release-2.36.x
[aa16fc5e9edc704b9aa51ee94408f7a7b0a88b5f](https://github.com/armory-io/gate-armory/commit/aa16fc5e9edc704b9aa51ee94408f7a7b0a88b5f)
[ff320db127a507bd106ccb72b8961ed9eb90f719](https://github.com/spinnaker/gate/commit/ff320db127a507bd106ccb72b8961ed9eb90f719)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "ff320db127a507bd106ccb72b8961ed9eb90f719"
},
"details": {
"image": {
"imageId": "sha256:5948072d5fa8d7bfbd05eab0cf6749b262c6f9dff7423d5ece01b2984d48fc6a",
"tag": "2025.05.20.16.59.50.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update gate-armory version to 2025.05.20.16.59.50.release-2.36.x

stack.yml
armory/igor-armory:2025.05.20.16.57.23.release-2.36.x
[333fed771c8b802b0f0894c5432c93e803a55c87](https://github.com/armory-io/igor-armory/commit/333fed771c8b802b0f0894c5432c93e803a55c87)
[992af5a9eb2a023a734fb2e44a6c5f4295e235c4](https://github.com/spinnaker/igor/commit/992af5a9eb2a023a734fb2e44a6c5f4295e235c4)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "992af5a9eb2a023a734fb2e44a6c5f4295e235c4"
},
"details": {
"image": {
"imageId": "sha256:566a1a2274d54d91bef2f860cd6ec36e3cc8b045c9649aebf543ecd391b092af",
"tag": "2025.05.20.16.57.23.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update igor-armory version to 2025.05.20.16.57.23.release-2.36.x

stack.yml
armory/fiat-armory:2025.05.20.16.58.56.release-2.36.x
[700380bf8a38b8b28234c1e1fde6726e2328cb21](https://github.com/armory-io/fiat-armory/commit/700380bf8a38b8b28234c1e1fde6726e2328cb21)
[6c46d68517b6e8ae1c92bdf4279fcad0106a0807](https://github.com/spinnaker/fiat/commit/6c46d68517b6e8ae1c92bdf4279fcad0106a0807)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "6c46d68517b6e8ae1c92bdf4279fcad0106a0807"
},
"details": {
"image": {
"imageId": "sha256:849129b6043f98eed047a93bb2e5c2205099a709c711e729a842045efdc2537f",
"tag": "2025.05.20.16.58.56.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update fiat-armory version to 2025.05.20.16.58.56.release-2.36.x

stack.yml
armory/front50-armory:2025.05.20.19.05.47.release-2.36.x
[196c8b8a750b79864dc21e58b91a81dd4e87ca0c](https://github.com/armory-io/front50-armory/commit/196c8b8a750b79864dc21e58b91a81dd4e87ca0c)
[3325d3cd364842342b3fb04c8fd349eb9ca31fb9](https://github.com/spinnaker/front50/commit/3325d3cd364842342b3fb04c8fd349eb9ca31fb9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "3325d3cd364842342b3fb04c8fd349eb9ca31fb9"
},
"details": {
"image": {
"imageId": "sha256:cc90cfa3150046abb8e74599c22912126c4f2e0adfcbf667c1fb2899e1693fa7",
"tag": "2025.05.20.19.05.47.release-2.36.x"
},
"vcs": {
"repo": {
"orgName": …
```
=> chore(cd): update front50-armory version to 2025.05.20.19.05.47.release-2.36.x

stack.yml
armory/igor-armory:2025.05.20.20.19.43.release-2.36.x
[768ebcbaf7422eed06c016ba9bc556e39fcea568](https://github.com/armory-io/igor-armory/commit/768ebcbaf7422eed06c016ba9bc556e39fcea568)
[c23e997baf53834878a7e7a170031cc6cea2bda9](https://github.com/spinnaker/igor/commit/c23e997baf53834878a7e7a170031cc6cea2bda9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "c23e997baf53834878a7e7a170031cc6cea2bda9"
},
"details": {
"image": {
"imageId": "sha256:ea0765dab2b26d127a292c5f3a1ef9842c50def8737bbf1100f44cb69602e5a1",
"tag": "2025.05.20.20.19.43.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update igor-armory version to 2025.05.20.20.19.43.release-2.36.x

stack.yml
armory/orca-armory:2025.05.22.11.16.52.release-2.36.x
[45004d9f91ff5419d158855f5b404ec4e733f61a](https://github.com/armory-io/orca-armory/commit/45004d9f91ff5419d158855f5b404ec4e733f61a)
[5f3b9f44cf13bbc1fd098e3f6fff4bc19c7712ec](https://github.com/spinnaker/orca/commit/5f3b9f44cf13bbc1fd098e3f6fff4bc19c7712ec)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "5f3b9f44cf13bbc1fd098e3f6fff4bc19c7712ec"
},
"details": {
"image": {
"imageId": "sha256:6a890235186a3a204bb2bd0bf2921e052ce51bd2aa17dff90e7ed88abdb2a9bb",
"tag": "2025.05.22.11.16.52.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update orca-armory version to 2025.05.22.11.16.52.release-2.36.x

stack.yml
armory/gate-armory:2025.05.20.19.10.38.release-2.36.x
[f64ccc189c6ea7cf3d90bb18881c258c10f0f540](https://github.com/armory-io/gate-armory/commit/f64ccc189c6ea7cf3d90bb18881c258c10f0f540)
[938d70ebbeb52e9160f0f557bd422e726dd2896f](https://github.com/spinnaker/gate/commit/938d70ebbeb52e9160f0f557bd422e726dd2896f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "938d70ebbeb52e9160f0f557bd422e726dd2896f"
},
"details": {
"image": {
"imageId": "sha256:635c5f153ad4e226fdae8fef368c9b593aabc10c31ff121005da252daafd1076",
"tag": "2025.05.20.19.10.38.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update gate-armory version to 2025.05.20.19.10.38.release-2.36.x

stack.yml
armory/rosco-armory:2025.05.20.16.58.33.release-2.36.x
[c518db1ed737092ed90cf68b54048465946382a1](https://github.com/armory-io/rosco-armory/commit/c518db1ed737092ed90cf68b54048465946382a1)
[dbaeacd4fc4fb3f6b9ec3d1c4ed0bd0f4655cb0d](https://github.com/spinnaker/rosco/commit/dbaeacd4fc4fb3f6b9ec3d1c4ed0bd0f4655cb0d)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "dbaeacd4fc4fb3f6b9ec3d1c4ed0bd0f4655cb0d"
},
"details": {
"image": {
"imageId": "sha256:0eda77c0dae0ed6698a11b96d3465f28b7b7ac6d5ebe8f33f0992f470be5509c",
"tag": "2025.05.20.16.58.33.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2025.05.20.16.58.33.release-2.36.x

stack.yml
armory/deck-armory:2025.08.11.11.19.24.release-2.36.x
[457642493d0650cde80672a68a0cf957b417ac43](https://github.com/armory-io/deck-armory/commit/457642493d0650cde80672a68a0cf957b417ac43)
[127fa906205ad4ca835eb38502ab07d02b8974d9](https://github.com/spinnaker/deck/commit/127fa906205ad4ca835eb38502ab07d02b8974d9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "127fa906205ad4ca835eb38502ab07d02b8974d9"
},
"details": {
"image": {
"imageId": "sha256:87382de8d9bf2e9068a4e942353cc857e9504849d5363dbd1e4a57b96bf6da05",
"tag": "2025.08.11.11.19.24.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2025.08.11.11.19.24.release-2.36.x

stack.yml
armory/rosco-armory:2025.08.11.12.13.22.release-2.36.x
[8e35f1c3560b3b8f7de6fc4a35718b4aee98a47c](https://github.com/armory-io/rosco-armory/commit/8e35f1c3560b3b8f7de6fc4a35718b4aee98a47c)
[dbaeacd4fc4fb3f6b9ec3d1c4ed0bd0f4655cb0d](https://github.com/spinnaker/rosco/commit/dbaeacd4fc4fb3f6b9ec3d1c4ed0bd0f4655cb0d)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "dbaeacd4fc4fb3f6b9ec3d1c4ed0bd0f4655cb0d"
},
"details": {
"image": {
"imageId": "sha256:1a7eafacf778c1f80c78b89ac72ef12f554de04d10a71b6cde3dd5f99944ee60",
"tag": "2025.08.11.12.13.22.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update rosco-armory version to 2025.08.11.12.13.22.release-2.36.x

stack.yml
armory/gate-armory:2025.08.11.11.49.11.release-2.36.x
[4008ca9592054ea4cb100231dffe13dd8f819367](https://github.com/armory-io/gate-armory/commit/4008ca9592054ea4cb100231dffe13dd8f819367)
[938d70ebbeb52e9160f0f557bd422e726dd2896f](https://github.com/spinnaker/gate/commit/938d70ebbeb52e9160f0f557bd422e726dd2896f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "938d70ebbeb52e9160f0f557bd422e726dd2896f"
},
"details": {
"image": {
"imageId": "sha256:caea65aa351e333108319862349c0e336ce60fda22b4e5c6b90483c2c0b8968d",
"tag": "2025.08.11.11.49.11.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update gate-armory version to 2025.08.11.11.49.11.release-2.36.x

stack.yml
armory/deck-armory:2025.08.12.10.42.32.release-2.36.x
[7a9eab2a2a9c29455d2be8b7655e1495937ba1a4](https://github.com/armory-io/deck-armory/commit/7a9eab2a2a9c29455d2be8b7655e1495937ba1a4)
[127fa906205ad4ca835eb38502ab07d02b8974d9](https://github.com/spinnaker/deck/commit/127fa906205ad4ca835eb38502ab07d02b8974d9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "127fa906205ad4ca835eb38502ab07d02b8974d9"
},
"details": {
"image": {
"imageId": "sha256:dd79af513f70522ce3b7b90745c9f1b1d4788f451a4cc27315a10b7d28a2176c",
"tag": "2025.08.12.10.42.32.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2025.08.12.10.42.32.release-2.36.x

stack.yml
* **master**
armory/rosco-armory:2025.08.12.19.05.27.main
[a05dbe199c17c34031530e976a5a5dd2a86cb4ee](https://github.com/armory-io/armory-extensions/commit/a05dbe199c17c34031530e976a5a5dd2a86cb4ee)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": ""
},
"details": {
"image": {
"imageId": "",
"tag": "2025.08.12.19.05.27.main"
},
"vcs": {
"repo": {
},
"sha": "a05dbe199c17c34031530e976a5a5dd2a86cb4ee"
}
},
},
"baseVcs": {
"repo": {
"repoName": …
```
=> chore(cd): update rosco-armory version to 2025.08.12.19.05.27.main

stack.yml
* **master**
armory/terraformer:2025.08.12.19.05.27.main
[a05dbe199c17c34031530e976a5a5dd2a86cb4ee](https://github.com/armory-io/armory-extensions/commit/a05dbe199c17c34031530e976a5a5dd2a86cb4ee)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": ""
},
"details": {
"baseService": "terraformer",
"image": {
"imageId": "",
"tag": "2025.08.12.19.05.27.main"
},
"vcs": {
"repo": {
},
"sha": "a05dbe199c17c34031530e976a5a5dd2a86cb4ee"
}
},
},
"baseVcs": {
"repo": {
"repoName": …
```
=> chore(cd): update terraformer version to 2025.08.12.19.05.27.main

stack.yml
* **master**
armory/kayenta-armory:2025.08.12.19.05.27.main
[a05dbe199c17c34031530e976a5a5dd2a86cb4ee](https://github.com/armory-io/armory-extensions/commit/a05dbe199c17c34031530e976a5a5dd2a86cb4ee)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": ""
},
"details": {
"image": {
"imageId": "",
"tag": "2025.08.12.19.05.27.main"
},
"vcs": {
"repo": {
},
"sha": "a05dbe199c17c34031530e976a5a5dd2a86cb4ee"
}
},
},
"baseVcs": {
"repo": { …
```
=> chore(cd): update kayenta-armory version to 2025.08.12.19.05.27.main

stack.yml
* **master**
armory/dinghy:2025.08.12.19.05.27.main
[a05dbe199c17c34031530e976a5a5dd2a86cb4ee](https://github.com/armory-io/armory-extensions/commit/a05dbe199c17c34031530e976a5a5dd2a86cb4ee)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": ""
},
"details": {
"baseService": "dinghy",
"image": {
"imageId": "",
"tag": "2025.08.12.19.05.27.main"
},
"vcs": {
"repo": {
},
"sha": "a05dbe199c17c34031530e976a5a5dd2a86cb4ee"
}
},
},
"baseVcs": {
"repo": {
"type": …
```
=> chore(cd): update dinghy version to 2025.08.12.19.05.27.main

stack.yml
* **master**
armory/fiat-armory:2025.08.13.13.42.13.main
[17d570ed5ef5bd8f377f86f437a3ccdb84e3d29d](https://github.com/armory-io/armory-extensions/commit/17d570ed5ef5bd8f377f86f437a3ccdb84e3d29d)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": ""
},
"details": {
"image": {
"imageId": "sha256:94b12ec1fad453d6767ff95cff21ed80914055a1ad4e89fa5856723cfda19838",
"tag": "2025.08.13.13.42.13.main"
},
"vcs": {
"repo": {
},
"sha": "17d570ed5ef5bd8f377f86f437a3ccdb84e3d29d"
}
},
}, …
```
=> chore(cd): update fiat-armory version to 2025.08.13.13.42.13.main

stack.yml
* **master**
armory/fiat-armory:2025.08.19.16.20.23.main
[7e19e1e4abcb465ac5b963a8dc91309f4fcbb65b](https://github.com/armory-io/armory-extensions/commit/7e19e1e4abcb465ac5b963a8dc91309f4fcbb65b)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": ""
},
"details": {
"image": {
"imageId": "sha256:f6740acaa62c9fb645f514d6045fa8b198fa6d70f3cfa54440670bbeabfee7bb",
"tag": "2025.08.19.16.20.23.main"
},
"vcs": {
"repo": {
},
"sha": "7e19e1e4abcb465ac5b963a8dc91309f4fcbb65b"
}
},
}, …
```
=> chore(cd): update fiat-armory version to 2025.08.19.16.20.23.main

stack.yml
* **master**
armory/dinghy:2025.08.18.09.36.46.main
[a2a71f090d7298312f3841d6dd531622743adfb6](https://github.com/armory-io/armory-extensions/commit/a2a71f090d7298312f3841d6dd531622743adfb6)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": ""
},
"details": {
"baseService": "dinghy",
"image": {
"imageId": "sha256:3c51a81da601e16787c9ec28031fdd32e236d3fb4dba279eb64ca1743e7a3fb0",
"tag": "2025.08.18.09.36.46.main"
},
"vcs": {
"repo": {
},
"sha": "a2a71f090d7298312f3841d6dd531622743adfb6"
}
},
}, …
```
=> chore(cd): update dinghy version to 2025.08.18.09.36.46.main

stack.yml
* **master**
armory/dinghy:2025.08.20.02.33.17.main
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": ""
},
"details": {
"baseService": "dinghy",
"image": {
"imageId": "sha256:75dac23547f399112b46a1a3ee7feb65e50b66386c1931f18e52ffc695afed43",
},
"vcs": {
"repo": {
},
}
},
}, …
```
=> chore(cd): update dinghy version to 2025.08.20.02.33.17.main

stack.yml
* **master**
armory/gate-armory:2025.08.20.02.33.17.main
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": ""
},
"details": {
"image": {
"imageId": "sha256:a1ffc404dc2063cd2492d4dd701f71592b53f4c3b6eaaf30ec3c9463c8e90ff4",
},
"vcs": {
"repo": {
},
}
},
}, …
```
=> chore(cd): update gate-armory version to 2025.08.20.02.33.17.main

stack.yml
* **master**
armory/kayenta-armory:2025.08.20.02.33.17.main
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": ""
},
"details": {
"image": {
"imageId": "sha256:323736468e687650db061bd3c6da0b809a1d3aab6cd9b1f83c06290f53eb93de",
},
"vcs": {
"repo": {
},
}
},
}, …
```
=> chore(cd): update kayenta-armory version to 2025.08.20.02.33.17.main

stack.yml
* **master**
armory/rosco-armory:2025.08.20.02.33.17.main
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": ""
},
"details": {
"image": {
"imageId": "sha256:38b3ba944186f38dda54684178df93ad1900c36b016be01fac5c8134a80fdd7e",
},
"vcs": {
"repo": {
},
}
},
}, …
```
=> chore(cd): update rosco-armory version to 2025.08.20.02.33.17.main

stack.yml
* **master**
armory/deck-armory:2025.08.20.02.33.17.main
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": ""
},
"details": {
"image": {
"imageId": "sha256:3c940a6c3fabcc43be24e1144f6b20c3cddeaffddf288fced0b0af8b1afacd0e",
},
"vcs": {
"repo": {
},
}
},
}, …
```
=> chore(cd): update deck-armory version to 2025.08.20.02.33.17.main

stack.yml
armory/deck-armory:2025.08.22.16.19.04.release-2.36.x
[6ded262395bef930767412386ff799217f21b6ce](https://github.com/armory-io/deck-armory/commit/6ded262395bef930767412386ff799217f21b6ce)
[127fa906205ad4ca835eb38502ab07d02b8974d9](https://github.com/spinnaker/deck/commit/127fa906205ad4ca835eb38502ab07d02b8974d9)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "127fa906205ad4ca835eb38502ab07d02b8974d9"
},
"details": {
"image": {
"imageId": "sha256:56b0ccf8208bb948ff562ca53eac4bcfbbb580cc76f7539932d2bf3c81c587ac",
"tag": "2025.08.22.16.19.04.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update deck-armory version to 2025.08.22.16.19.04.release-2.36.x

stack.yml
armory/gate-armory:2025.09.16.15.13.28.release-2.36.x
[7cad31c006f10d4549bd666c76dbd85bd8286921](https://github.com/armory-io/gate-armory/commit/7cad31c006f10d4549bd666c76dbd85bd8286921)
[938d70ebbeb52e9160f0f557bd422e726dd2896f](https://github.com/spinnaker/gate/commit/938d70ebbeb52e9160f0f557bd422e726dd2896f)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": "938d70ebbeb52e9160f0f557bd422e726dd2896f"
},
"details": {
"image": {
"imageId": "sha256:5f5a705e6ae978b7c4e3fcbaa6423c828dbcedce4cd7139b9dd675afd8fb8b58",
"tag": "2025.09.16.15.13.28.release-2.36.x"
},
"vcs": {
"repo": { …
```
=> chore(cd): update gate-armory version to 2025.09.16.15.13.28.release-2.36.x

stack.yml
armory/gate-armory:2025.09.18.16.38.26.release-2.38.x
[dc41b0e377d7d5ae57819844754a9ac7958a872b](https://github.com/armory-io/armory-extensions/commit/dc41b0e377d7d5ae57819844754a9ac7958a872b)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": ""
},
"details": {
"image": {
"imageId": "sha256:872bd5a1d1782a0d161da3a557f5ef07e7ead8254f0f7cdf873f59ee50a2d5f4",
"tag": "2025.09.18.16.38.26.release-2.38.x"
},
"vcs": {
"repo": {
},
"sha": "dc41b0e377d7d5ae57819844754a9ac7958a872b"
}
}, …
```
=> chore(cd): update gate-armory version to 2025.09.18.16.38.26.release-2.38.x

stack.yml
armory/igor-armory:2025.09.18.16.38.26.release-2.38.x
[dc41b0e377d7d5ae57819844754a9ac7958a872b](https://github.com/armory-io/armory-extensions/commit/dc41b0e377d7d5ae57819844754a9ac7958a872b)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": ""
},
"details": {
"image": {
"imageId": "sha256:c4cfc2a5dccee81b7acb48ae1eacbcdf702239094e0b2ebb76eb627b2336d241",
"tag": "2025.09.18.16.38.26.release-2.38.x"
},
"vcs": {
"repo": {
},
"sha": "dc41b0e377d7d5ae57819844754a9ac7958a872b"
}
}, …
```
=> chore(cd): update igor-armory version to 2025.09.18.16.38.26.release-2.38.x

stack.yml
armory/rosco-armory:2025.09.18.16.38.26.release-2.38.x
[dc41b0e377d7d5ae57819844754a9ac7958a872b](https://github.com/armory-io/armory-extensions/commit/dc41b0e377d7d5ae57819844754a9ac7958a872b)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": ""
},
"details": {
"image": {
"imageId": "sha256:0f36738ad07c97377d29a2187ce9ffd209e939835f92417cd1f6dc1646362f37",
"tag": "2025.09.18.16.38.26.release-2.38.x"
},
"vcs": {
"repo": {
},
"sha": "dc41b0e377d7d5ae57819844754a9ac7958a872b"
} …
```
=> chore(cd): update rosco-armory version to 2025.09.18.16.38.26.release-2.38.x

stack.yml
armory/deck-armory:2025.09.24.11.46.24.release-2.38.x
[ecb4f105b01162bd2a10e6ef63bf1a568e4a4b31](https://github.com/armory-io/armory-extensions/commit/ecb4f105b01162bd2a10e6ef63bf1a568e4a4b31)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": ""
},
"details": {
"image": {
"imageId": "sha256:9a858420ff7a368e9b0b66c2d0d35e81f8c78cefa63404c8df4c686dd6a1e13f",
"tag": "2025.09.24.11.46.24.release-2.38.x"
},
"vcs": {
"repo": {
},
"sha": "ecb4f105b01162bd2a10e6ef63bf1a568e4a4b31"
}
}, …
```
=> chore(cd): update deck-armory version to 2025.09.24.11.46.24.release-2.38.x

stack.yml
armory/orca-armory:2025.09.24.11.46.24.release-2.38.x
[ecb4f105b01162bd2a10e6ef63bf1a568e4a4b31](https://github.com/armory-io/armory-extensions/commit/ecb4f105b01162bd2a10e6ef63bf1a568e4a4b31)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": ""
},
"details": {
"image": {
"imageId": "sha256:4000be48b99bbeb2616baedece6815d30bf4ee885ba0c716ff0669fc72297d4b",
"tag": "2025.09.24.11.46.24.release-2.38.x"
},
"vcs": {
"repo": {
},
"sha": "ecb4f105b01162bd2a10e6ef63bf1a568e4a4b31"
}
}, …
```
=> chore(cd): update orca-armory version to 2025.09.24.11.46.24.release-2.38.x

stack.yml
armory/kayenta-armory:2025.09.24.11.46.24.release-2.38.x
[ecb4f105b01162bd2a10e6ef63bf1a568e4a4b31](https://github.com/armory-io/armory-extensions/commit/ecb4f105b01162bd2a10e6ef63bf1a568e4a4b31)
Event Payload
```
{
"service": {
"baseVcs": {
"repo": {
},
"sha": ""
},
"details": {
"image": {
"imageId": "sha256:532e9e43db123e043f86272939dbccfea96f958005cdce5e3c2a109206007a52",
"tag": "2025.09.24.11.46.24.release-2.38.x"
},
"vcs": {
"repo": {
},
"sha": …
```
=> chore(cd): update kayenta-armory version to 2025.09.24.11.46.24.release-2.38.x
